# -*- coding: utf-8 -*-
import os, re; E=os.environ
p='OPTION_A_INSTRUMENT_SELECTION_RULE_DRAFT_V27_20260907.md'; s=open(p, encoding='utf-8').read()
def rp(pat, new):
    global s; m=re.search(pat, s); assert m, pat[:80]; s=s.replace(m.group(0), new, 1)
def sub(old, new):
    global s; assert old in s, old[:80]; s=s.replace(old, new, 1)
sub('DRAFT V27 — STAGED CANDIDATE (NOT GATED, NOT ADOPTED, NOT APPROVED)','DRAFT V28 — STAGED CANDIDATE (NOT GATED, NOT ADOPTED, NOT APPROVED)')
sub('V27 of 2026-09-07 is V26 after its complete-package review',
 "V28 of 2026-09-07 is V27 after its complete-package review (agy SIGNABLE; codex NOT-SIGNABLE, no fatal — `V27_REVIEW_OUTCOME_20260907.md`), with codex's V27-1/2/3 answered FAIL-FIRST (`TRACK8_FAIL_FIRST_RECEIPT_20260907.md`: 7 tests failing against byte-copies of the V27 modules, classified per test — 3 behavioural, 2 missing-interface, 1 complete-path, 1 text; run 1b executing the V27 functions: a same-id contradiction with an undeterminable head called UNAVAILABLE, a differently encoded same-id copy beside a verbatim one called AUTHENTIC, a wrong-repository event under HTTP 503 called UNAVAILABLE; run 1c executing the V27 driver: an undeterminable witness delivery called IDENTITY-WITNESS-COMMIT; 7 passing after). BLANC'S ORDER OF 02:06 KST (`BLANC_ORDER_V27_CONTRADICTIONS_NOT_LIMITS.md`): V27-1 and V27-2 were CONTRADICTIONS between the stated contract and the implemented path — REPAIRED, not disclosed; the categories are kept apart in §3c and in `LIMITS_VS_CONTRADICTIONS_20260907.md`. (V27-1) PRECEDENCE, stated as three rules and tested: locally decidable input mismatches (not a PushEvent, wrong repository, positive non-delivery) are decided BEFORE any retrieval (`local_precheck`); a same-id contradiction is decided BEFORE the undetermined-delivery return and BEFORE the verbatim-presence shortcut; the same-commit arm is scoped to the pinned protected ref and evaluated only when the retained event is absent (when it is present, another delivering push is an ordering question — NOT-EARLIEST); no other precedence exception exists. (V27-2) TRI-STATE THROUGH EVERY STAGE: the driver's witness-commit precheck and the validator's open-event stage (`validate_continuation_v8`) use `delivery` — UNDETERMINED is RETRY-EVENTS-UNAVAILABLE / EVIDENCE-UNAVAILABLE (offline mode, which has no retry vocabulary, names it IDENTITY-WITNESS-COMMIT-UNDETERMINED), positive non-delivery is EVENT-INCONSISTENT / OPEN-EVENT-INCONSISTENT-INPUT, and a git process-launch exception is UNDETERMINED. (V27-3) driver v12's lineage table re-verified row by row against each retained driver's own import line (v10 composed on provenance_designs_v6, not v7), the helper docstrings corrected where they described current code (historical paragraphs kept and marked), the inspection header names the modules it executes, the design document's row 9b says INCONSISTENT-INPUT, §9 no longer calls the V22 inspection an inspection of this candidate, and the suite count is taken from the executed logs (20 suites). V27 of 2026-09-07 was V26 after its complete-package review")
sub('History: V16–V21 were refused at gates and V22–V26 at complete-package reviews (each by codex; agy passed all eleven);','History: V16–V21 were refused at gates and V22–V27 at complete-package reviews (each by codex; agy passed all twelve);')
rp(r"DRIVER: `run_configurations_v11\.py`, SHA-256 `[0-9a-f]{64}` \(V27 STAGED:", f"DRIVER: `run_configurations_v12.py`, SHA-256 `{E['RC12']}` (V28 STAGED: `run_configurations_v11.py` — reviewed at V27, retained — plus composed mode on `provenance_designs_v8` (locally decidable mismatches before any retrieval; same-id contradictions before any retry; tri-state delivery through the witness-commit precheck — RETRY-EVENTS-UNAVAILABLE / EVENT-INCONSISTENT in composed mode, IDENTITY-WITNESS-COMMIT-UNDETERMINED / IDENTITY-WITNESS-COMMIT offline — and through the open-event stage); V27 STAGED was:")
rp(r"fixture `test_run_configurations_v11\.py` `[0-9a-f]{64}`, 23 tests", f"fixture `test_run_configurations_v12.py` `{E['TRC12']}`, 23 tests")
sub('the track-2 v7 helpers called INSIDE `load_identity` on the production call path','the track-2 v8 helpers called INSIDE `load_identity` on the production call path')
rp(r"`build_corpus_identity_v27\.py`, SHA-256 `[0-9a-f]{64}` \(V27 STAGED:", f"`build_corpus_identity_v28.py`, SHA-256 `{E['B28']}` (V28 STAGED: on provenance_designs_v8; fixture `test_build_corpus_identity_v28.py` `{E['TB28']}`, 8 tests; V27 was:")
rp(r"`_optionA_dev/beacon_v2/beacon_record_drand_v27\.py` `[0-9a-f]{64}` \(V27:", f"`_optionA_dev/beacon_v2/beacon_record_drand_v28.py` `{E['BD28']}` (V28: on provenance_designs_v8; v27 retained; V27:")
rp(r"exercised by `test_beacon_record_drand_v27\.py` \(`[0-9a-f]{64}`, 7 tests", f"exercised by `test_beacon_record_drand_v28.py` (`{E['TBD28']}`, 7 tests")
rp(r"`coherent_attacks_v27\.py` \(`[0-9a-f]{64}`; rows 9m–9u = codex's V24 N2/N3, V25 P1/P2 and V26-1/2 cases; earlier scripts retained as pinned", f"`coherent_attacks_v28.py` (`{E['ATT28']}`; rows 9m–9u = codex's V24 N2/N3, V25 P1/P2 and V26-1/2 cases, re-executed on driver v12 / provenance v8 — `V28_CANDIDATE_ATTACK_INSPECTION_20260907.md`, same verdict in every row as V27; earlier scripts retained as pinned")
rp(r"`track2/provenance_designs_v7\.py` \(`[0-9a-f]{64}`; UNADOPTED; v7 = v6 \+ the stated contradiction predicate, tri-state delivery and named input-mismatch outcomes; fixture `track7/test_track7_fail_first\.py` `([0-9a-f]{64})`, 4 tests fail-first; text tests `track7/test_track7_text_v27\.py` `([0-9a-f]{64})` \(written against THIS text; 1 test\)",
   f"`track2/provenance_designs_v8.py` (`{E['P8']}`; UNADOPTED; v8 = v7 + the three precedence rules with `local_precheck` before retrieval, the tri-state open-event stage of `validate_continuation_v8`, and UNDETERMINED for a git process-launch exception; fixture `track8/test_track8_fail_first.py` `{E['T8']}`, 7 tests fail-first (3 behavioural, 2 missing-interface, 1 complete-path through driver v12, 1 text); text tests `track8/test_track8_text_v28.py` `{E['T8T']}` (written against THIS text; 1 test), the retained V27-specific `track7/test_track7_text_v27.py` `\\2` (written against V27, run against V27 only), v7 (`track2/provenance_designs_v7.py`, fixture `track7/test_track7_fail_first.py` `\\1`, 4 tests) retained; v7 = v6 + the stated contradiction predicate, tri-state delivery and named input-mismatch outcomes")
rp(r"`run_configurations_v11\.py` \(`[0-9a-f]{64}`\) refuses to load an identity unless", f"`run_configurations_v12.py` (`{E['RC12']}`) refuses to load an identity unless")
rp(r"The builder `build_corpus_identity_v27\.py` \(`[0-9a-f]{64}`\)", f"The builder `build_corpus_identity_v28.py` (`{E['B28']}`)")
sub("**3c. V27 — WHAT THE AMENDMENT COSTS, WHAT IS PRESERVED, HOW THE ORDER STAYS VISIBLE, AND WHAT IS STILL OPEN.** ",
 "**3c. V28 — WHAT THE AMENDMENT COSTS, WHAT IS PRESERVED, HOW THE ORDER STAYS VISIBLE, AND WHAT IS STILL OPEN.** TWO CATEGORIES, KEPT APART (Blanc 02:06 KST; register `LIMITS_VS_CONTRADICTIONS_20260907.md`). DISCLOSED LIMITS — a precommitment may carry these and reviewers confirm their disclosure: L-OFF, the OFFLINE candidate (PRODUCTION default) accepts counter-cases 1, 2 and A (a coherently forged approval event, a history rebuilt before the freeze, a rebuilt history published as its own first commit) — only the UNADOPTED composed mode refuses them; L-COV, THE COVENANT below (published history and ordered publications are authenticated, not when operations occurred nor the completeness of unpublished observations/decisions; the seed is unchanged; a late approval stays disqualifying; independent decision evidence is NOT implemented); L-RCPT, the fabricated-first-receipt step of Option A′ (moot under Option C, the recommended no-receipt path); L-INH, the inherited V15 trust in the object lists and pool/exclusion digests (verify_split UNADOPTED, off); L-AVAIL, GitHub's event window (300 events / 30 days) and the stateless RETRY dispositions (an inconsistent identity can stay pending; loss closes the approval under the rule). REPAIRED CONTRADICTIONS — the text said one thing and the code did another; each was repaired fail-first in the candidate that followed its review, never disclosed as a limit: V27-1 (precedence) and V27-2 (tri-state propagation) in THIS candidate (`TRACK8_FAIL_FIRST_RECEIPT_20260907.md`), the earlier ones in tracks 1–7. UNREPAIRED CONTRADICTIONS: none known; anything a reviewer finds of that kind goes to this column and is repaired, never to the first. ")
# (the §3c sentence names `validate_continuation_v3` for the ls-remote step — historical and still true of v3, whose stage v8 wraps; left as is)
n1=s.count('beacon_record_drand_v27'); s=s.replace('beacon_record_drand_v27','beacon_record_drand_v28'); n2=s.count('build_corpus_identity_v27'); s=s.replace('build_corpus_identity_v27','build_corpus_identity_v28'); print('token replacements: beacon', n1, 'builder', n2)
sub("driver v11 23 + V15 driver 17 + history_v2 4 + witness v4 3 + builder v27 8 + V15 builder 4 + verdict v27 7 + verifier v2 4 + track 1 10 + track 2 v2 8 + track 2 v1 2 + track 3 10 + track 4 7 + track 5 6 + track 6 5 + track 6 text (V26-specific) 1 + track 7 4 + track 7 text (V27-specific) 1 = 124 tests",
    "driver v12 23 + V15 driver 17 + history_v2 4 + witness v4 3 + builder v28 8 + V15 builder 4 + verdict v28 7 + verifier v2 4 + track 1 10 + track 2 v2 8 + track 2 v1 2 + track 3 10 + track 4 7 + track 5 6 + track 6 5 + track 6 text (V26-specific) 1 + track 7 4 + track 7 text (V27-specific) 1 + track 8 7 + track 8 text (V28-specific) 1 = 132 tests")
sub("the track-5 label test against the V25 text, the V26-specific text test against the V26 text, and only the version-agnostic tests (tracks 1/3/4, the track-6 sweep) plus the V27-specific test against THIS text",
    "the track-5 label test against the V25 text, the V26-specific text test against the V26 text, the V27-specific text test against the V27 text, and only the version-agnostic tests (tracks 1/3/4, the track-6 sweep, the track-8 V27-3 assertions) plus the V28-specific test against THIS text")
sub("124 tests across the seventeen suites named in §3c;","132 tests across the 20 suites named in §3c;")
sub("Re-run `coherent_attacks_v27.py` and add counter-cases of your own.","Re-run `coherent_attacks_v28.py` and add counter-cases of your own.")
sub("## 9. Questions for the seats at the V27 complete-package review (STAGED candidate; nothing adopted)","## 9. Questions for the seats at the V28 complete-package review (STAGED candidate; nothing adopted)")
sub("(V27, if ordered; V16–V26's counted)","(V28, if ordered; V16–V27's counted)")
sub("`V22_CANDIDATE_ATTACK_INSPECTION_20260906.md` (codex's coherent attacks against THIS candidate — two still pass and are DISCLOSED as open boundaries)","`V22_CANDIDATE_ATTACK_INSPECTION_20260906.md` (codex's coherent attacks against the V22 candidate, historical; the inspection of THIS candidate is `V28_CANDIDATE_ATTACK_INSPECTION_20260907.md` — offline, counter-cases 1, 2 and A still load and are DISCLOSED LIMITS, column one of §3c)")
for bad in ("3c. V27", "seventeen suites", "THIS candidate — two still pass", "run_configurations_v11.py`, SHA-256", "provenance_designs_v7.py` (`8c20"): assert bad not in s, bad
open('OPTION_A_INSTRUMENT_SELECTION_RULE_DRAFT_V28_20260907.md','w',encoding='utf-8').write(s); print("V28 text written")
