# -*- coding: utf-8 -*-
import os, re; E=os.environ
p='OPTION_A_INSTRUMENT_SELECTION_RULE_DRAFT_V26_20260907.md'; s=open(p, encoding='utf-8').read()
def rp(pat, new):
    global s; m=re.search(pat, s); assert m, pat[:70]; s=s.replace(m.group(0), new, 1)
s=s.replace('DRAFT V26 — STAGED CANDIDATE (NOT GATED, NOT ADOPTED, NOT APPROVED)','DRAFT V27 — STAGED CANDIDATE (NOT GATED, NOT ADOPTED, NOT APPROVED)')
s=s.replace('V26 of 2026-09-07 is V25 after its complete-package review','V27 of 2026-09-07 is V26 after its complete-package review (agy SIGNABLE; codex NOT-SIGNABLE, no fatal — `V26_REVIEW_OUTCOME_20260907.md`), with codex\'s V26-1/2/3 answered FAIL-FIRST (`TRACK7_FAIL_FIRST_RECEIPT_20260907.md`: 4 tests failing against byte-copies of the V26 modules, classified per test; run 1b executing the V26 functions — a same-event contradiction called INCOMPLETE, missing git objects called FORGED; 4 passing after): (V26-1) the CONTRADICTION PREDICATE is stated — a live event with the same event id, or delivering the same commit, whose canonical bytes differ (a difference only in `before` or `head` counts) is FORGED, terminal; (V26-2) DELIVERY IS TRI-STATE — DELIVERED / NOT-DELIVERED / UNDETERMINED; UNDETERMINED (a git object missing locally, a failed git command) is UNAVAILABLE, a retry, never forgery; a retained event that positively does not deliver the commit or names the wrong repository is INCONSISTENT-INPUT; a verbatim-present but not-earliest event is NOT-EARLIEST; EVIDENCE-EXPIRED is a loss, not a retry, at every stage; (V26-3) the remnants swept, and driver v11 states its lineage in a table instead of the over-renamed historical lines of v10; the text tests are attributed (`TEXT_TEST_ATTRIBUTION_20260907.md`): the V26-specific test is retained as pinned and a V27-specific test is added. V26 of 2026-09-07 was V25 after its complete-package review')
s=s.replace('History: V16–V21 were refused at gates and V22–V25 at complete-package reviews (each by codex; agy passed all ten);','History: V16–V21 were refused at gates and V22–V26 at complete-package reviews (each by codex; agy passed all eleven);')
rp(r"DRIVER: `run_configurations_v10\.py`, SHA-256 `[0-9a-f]{64}` \(V26 STAGED:", f"DRIVER: `run_configurations_v11.py`, SHA-256 `{E['RC11']}` (V27 STAGED: `run_configurations_v10.py` — reviewed at V26, retained — plus composed mode on `provenance_designs_v7` (EVENT-FORGED on a same-event contradiction; RETRY-EVENTS-UNAVAILABLE on an undeterminable delivery; EVENT-INCONSISTENT / EVENT-NOT-EARLIEST named); V26 was:")
rp(r"fixture `test_run_configurations_v10\.py` `[0-9a-f]{64}`, 23 tests", f"fixture `test_run_configurations_v11.py` `{E['TRC11']}`, 23 tests")
rp(r"`build_corpus_identity_v26\.py`, SHA-256 `[0-9a-f]{64}` \(V26 STAGED:", f"`build_corpus_identity_v27.py`, SHA-256 `{E['B27']}` (V27 STAGED: on provenance_designs_v7; fixture `test_build_corpus_identity_v27.py` `{E['TB27']}`, 8 tests; V26 was:")
rp(r"`_optionA_dev/beacon_v2/beacon_record_drand_v26\.py` `[0-9a-f]{64}` \(V26:", f"`_optionA_dev/beacon_v2/beacon_record_drand_v27.py` `{E['BD27']}` (V27: on provenance_designs_v7; v26 retained; V26:")
s=s.replace('`beacon_record_drand_v26.collect(fetch, T_sign, rule_sha256, statement_bytes, now)` (`_optionA_dev/beacon_v2/beacon_record_drand_v26.py`','`beacon_record_drand_v27.collect(fetch, T_sign, rule_sha256, statement_bytes, now)` (`_optionA_dev/beacon_v2/beacon_record_drand_v27.py`')
s=s.replace('`beacon_record_drand_v26.verdict(record, now, fetch, rule_sha256, statement_bytes)` recomputes','`beacon_record_drand_v27.verdict(record, now, fetch, rule_sha256, statement_bytes)` recomputes').replace('In addition `beacon_record_drand_v26.collect` REFUSES','In addition `beacon_record_drand_v27.collect` REFUSES')
s=s.replace('(3) `beacon_record_drand_v22.collect(fetch, T_sign, rule_sha256, statement_bytes, now)`','(3) `beacon_record_drand_v27.collect(fetch, T_sign, rule_sha256, statement_bytes, now)`')
rp(r"exercised by `test_beacon_record_drand_v26\.py` \(`[0-9a-f]{64}`, 7 tests", f"exercised by `test_beacon_record_drand_v27.py` (`{E['TBD27']}`, 7 tests")
rp(r"`coherent_attacks_v26\.py` \(`[0-9a-f]{64}`; rows 9m–9r = codex's V24 N2/N3 and V25 P1/P2 cases; earlier scripts retained as pinned", f"`coherent_attacks_v27.py` (`{E['ATT27']}`; rows 9m–9u = codex's V24 N2/N3, V25 P1/P2 and V26-1/2 cases; earlier scripts retained as pinned")
rp(r"`track2/provenance_designs_v6\.py` \(`[0-9a-f]{64}`; UNADOPTED;", f"`track2/provenance_designs_v7.py` (`{E['P7']}`; UNADOPTED; v7 = v6 + the stated contradiction predicate, tri-state delivery and named input-mismatch outcomes; fixture `track7/test_track7_fail_first.py` `{E['T7']}`, 4 tests fail-first; text tests `track7/test_track7_text_v27.py` `{E['TT7']}` (written against THIS text; 1 test) and the retained V26-specific `track6/test_track6_text_v26.py` `{E['TT6']}` (written against V26, run against V26 only); v6 (`track6/test_track6_fail_first.py`, 5 tests) retained;")
rp(r"`run_configurations_v10\.py` \(`[0-9a-f]{64}`\) refuses to load an identity unless", f"`run_configurations_v11.py` (`{E['RC11']}`) refuses to load an identity unless")
rp(r"The builder `build_corpus_identity_v26\.py` \(`[0-9a-f]{64}`\)", f"The builder `build_corpus_identity_v27.py` (`{E['B27']}`)")
s=s.replace("**3c. V26 — WHAT THE AMENDMENT COSTS","**3c. V27 — WHAT THE AMENDMENT COSTS")
s=s.replace("`validate_continuation_v6` obtaining the current remote head independently","`validate_continuation_v7` obtaining the current remote head independently")
s=s.replace("ABSENCE IS NEVER FORGERY at any of the three retrievals: a retained approval or history-open event missing from a feed is EVIDENCE-INCOMPLETE (retry), FORGED only when the feed carries a push delivering the same commit with different bytes (codex V25 P2)","ABSENCE IS NEVER FORGERY at any of the three retrievals: a retained approval or history-open event missing from a feed is EVIDENCE-INCOMPLETE (retry); FORGED only on an affirmative CONTRADICTION — a live push with the same event id, or delivering the same commit under the tri-state delivery check, whose canonical bytes differ, a difference only in `before` or `head` included (codex V25 P2, V26-1); a delivery that cannot be established because git objects are missing or a git command fails is UNDETERMINED → UNAVAILABLE (retry), never forgery (codex V26-2); a retained event that positively does not deliver the commit or names the wrong repository is INCONSISTENT-INPUT and a verbatim-present but not-earliest event is NOT-EARLIEST — terminal, named as input inconsistencies, not as 'different bytes'; EVIDENCE-EXPIRED is a loss, not a retry")
s=s.replace("the track-2 v6 helpers called INSIDE `load_identity` on the production call path","the track-2 v7 helpers called INSIDE `load_identity` on the production call path")
s=s.replace("_optionA_dev/corpus_identity/build_corpus_identity_v26.py --beacon-record","_optionA_dev/corpus_identity/build_corpus_identity_v27.py --beacon-record").replace("(after the collector CLI `beacon_record_drand_v26.py collect","(after the collector CLI `beacon_record_drand_v27.py collect")
rp(r"driver v10 23 \+ V15 driver 17 \+ history_v2 4 \+ witness v4 3 \+ builder v26 8 \+ V15 builder 4 \+ verdict v26 7 \+ verifier v2 4 \+ track 1 10 \+ track 2 v2 8 \+ track 2 v1 2 \+ track 3 10 \+ track 4 7 \+ track 5 6 \(its text test asserts the V25 self-label and is run with RULE_TEXT = the V25 text it was written for; every other text test runs against THIS text\) \+ track 6 5 = 118 tests", "driver v11 23 + V15 driver 17 + history_v2 4 + witness v4 3 + builder v27 8 + V15 builder 4 + verdict v27 7 + verifier v2 4 + track 1 10 + track 2 v2 8 + track 2 v1 2 + track 3 10 + track 4 7 + track 5 6 + track 6 5 + track 6 text (V26-specific) 1 + track 7 4 + track 7 text (V27-specific) 1 = 124 tests — TEXT-TEST ATTRIBUTION (Blanc 01:05): each text test is run against the document version its assertions were WRITTEN against (`TEXT_TEST_ATTRIBUTION_20260907.md`): the track-5 label test against the V25 text, the V26-specific text test against the V26 text, and only the version-agnostic tests (tracks 1/3/4, the track-6 sweep) plus the V27-specific test against THIS text; a pass of an older label test says nothing about this text")
s=s.replace("118 tests across the fifteen suites named in §3c;","124 tests across the seventeen suites named in §3c;")
s=s.replace("Re-run `coherent_attacks_v26.py` and add counter-cases of your own.","Re-run `coherent_attacks_v27.py` and add counter-cases of your own.")
s=s.replace("## 9. Questions for the seats at the V26 complete-package review (STAGED candidate; nothing adopted)","## 9. Questions for the seats at the V27 complete-package review (STAGED candidate; nothing adopted)").replace("one two-seat review on this amendment (V26, if ordered; V16–V25's counted)","one two-seat review on this amendment (V27, if ordered; V16–V26's counted)")
# clause (4): the old verifier cite → the pinned v2 verifier
line = s.split("\n")[32]
n_old = line.count("`verify_drand.py`")
s = s.replace("\n" + line + "\n", "\n" + line.replace("`verify_drand.py`", "`verify_drand_v2.py` (the pinned verifier; the V20 `verify_drand.py` is historical)") + "\n", 1) if n_old else s
for bad in ("3c. V26", "beacon_record_drand_v22.collect", "on the V22 candidate"): assert bad not in s, bad
open('OPTION_A_INSTRUMENT_SELECTION_RULE_DRAFT_V27_20260907.md','w',encoding='utf-8').write(s); print("V27 text written; verify_drand.py cites replaced in line 33:", n_old)
