# -*- coding: utf-8 -*-
import os, re; E=os.environ
p='OPTION_A_INSTRUMENT_SELECTION_RULE_DRAFT_V29_20260907.md'; s=open(p, encoding='utf-8').read()
def rp(pat, new):
    global s; m=re.search(pat, s); assert m, pat[:80]; s=s.replace(m.group(0), new, 1)
def rpf(pat, fn):
    global s; m=re.search(pat, s); assert m, pat[:80]; s=s.replace(m.group(0), fn(m), 1)
def sub(old, new):
    global s; assert old in s, old[:80]; s=s.replace(old, new, 1)
CL1="Before any retry is returned from load_identity, the implementation checks locally decidable type, repository and protected-ref mismatches in both retained approval and history-open events. This obligation applies before seed re-derivation availability returns, approval-feed availability returns, and history remote-head or fetch availability returns. Delivery checks that require unavailable remote objects remain undetermined; they do not excuse other locally decidable mismatches. In composed mode, deferred approval or open-event delivery must not bypass obtainable same-ID authentication merely because another stage has queued a retry. A retry is emitted only after the applicable higher-priority terminal checks have run. Offline undetermined delivery retains its explicitly named refusal."
CL2="NOT-EARLIEST requires a strictly earlier qualifying event under the explicitly specified ordering. Equal timestamps alone do not prove that another event is earlier; feed iteration order is not an unstated tie-break."
ORDER="PRECEDENCE ORDER, STATED ONCE (Blanc's order of 03:20 KST, `BLANC_ORDER_PRECEDENCE_IS_ONE_PATTERN.md`; the constant `PRECEDENCE` in `provenance_designs_v10`; when two or more verdict classes are simultaneously derivable the higher one wins, top to bottom, no exceptions): 0 LOCAL-TERMINAL (locally decidable refusals needing no external evidence — identity integrity, retained-event type / pinned repository / protected ref / positive non-delivery, a missing retained file) > 1 FORGED (an affirmative contradiction in obtained live evidence) > 2 NOT-EARLIEST (a strictly earlier qualifying event) > 3 EXPIRED (a loss) > 4 DERIVED-TERMINAL (refusals proven from obtained remote or retained evidence: history not-an-extension / diverged / batch / not-genesis-only, REDERIVE-<non-retry>, seed mismatch) > 5 RETRY-UNAVAILABLE (feed or remote down, undetermined delivery with nothing contradicting, seed re-derivation RETRY) > 6 RETRY-INCOMPLETE (absent, nothing contradicts) > 7 ACCEPT. ONE PLACE ENFORCES IT: `provenance_designs_v10.resolve` — driver v14's `composed_resolver` runs four CONTRIBUTING stages (A local sweep of both retained events, B one retrieval with the approval authentication and the open event's same-id check, C seed re-derivation with PRODUCTION's own re-deriver, D history continuation) and none decides; class-0 findings raised in the fixed offline check sequence before the resolver are consistent with the order because nothing outranks class 0; within a class the fixed stage sequence decides, never retrieval order; every finding is recorded in the identity's `_findings`. EXHIBITED PAIRWISE: `V30_PRECEDENCE_EXHIBIT_20260907.md` (21 class pairs, both derivation orders, same winner, always the higher class) and the complete-path pairs of tracks 8–10."
sub('DRAFT V29 — STAGED CANDIDATE (NOT GATED, NOT ADOPTED, NOT APPROVED)','DRAFT V30 — STAGED CANDIDATE (NOT GATED, NOT ADOPTED, NOT APPROVED)')
sub('V29 of 2026-09-07 is V28 after its complete-package review',
 "V30 of 2026-09-07 is V29 after its complete-package review (agy SIGNABLE; codex NOT-SIGNABLE, no fatal — `V29_REVIEW_OUTCOME_20260907.md`), with codex's V29-1/2/3/4 answered under BLANC'S ORDER OF 03:20 KST (`BLANC_ORDER_PRECEDENCE_IS_ONE_PATTERN.md`): V27-1, V27-2, V28-1/2, V29-1 and V29-2 were ONE pattern — a check returning before the rule that governs it — four found by a reviewer constructing a counter-case and one introduced by the lane's own repair; so V30 is NOT a sixth point fix. " + ORDER + " FAIL-FIRST (`TRACK10_FAIL_FIRST_RECEIPT_20260907.md`): run 1 against byte-copies of the V29 modules — codex's V29-1 row reproduces its exact `REDERIVE-RETRY`, the equal-time case flips, the four literal placeholders are found, the resolver does not exist; run 2: the complete-path case with codex's seven V29 rows (unverifiable seed bodies + undetermined approval + wrong repository → EVENT-INCONSISTENT; + genuine same-id contradiction → EVENT-FORGED; genuine approval → REDERIVE-RETRY, the legitimate retry; open event wrong repository with ls-remote down / with the approval feed at HTTP 503 → OPEN-EVENT-INCONSISTENT-INPUT; open event same-id contradiction with ls-remote down → OPEN-EVENT-FORGED; genuine open event with ls-remote down → RETRY-REMOTE-UNAVAILABLE), the strict-earlier case in both feed orders, and the resolver's own pairwise test all OK; run 2b: EVERY existing precedence test of tracks 8 and 9 re-run against the v10/v14 successors, OK, and the 23-test driver fixture OK. (V29-1) and (V29-2) are repaired by the resolver, not separately; codex's clause carried verbatim: \"" + CL1 + "\" (V29-4) `authenticate_event`: NOT-EARLIEST only on a STRICTLY earlier qualifying event; codex's clause verbatim: \"" + CL2 + "\" (V29-3) the four literal backreference tokens that stood where digests belong (the V28 and V29 edit scripts had used regex backreference syntax inside a plain string replacement; present since V28, caught by codex at V29) are replaced by the digests; the aggregate labels name the executed modules (driver v14, builder v30, verdict v30); the V30 edit script builds those clauses with a function, not a backreference, and the V30-specific text test asserts that no such token remains. V29 of 2026-09-07 was V28 after its complete-package review")
sub('History: V16–V21 were refused at gates and V22–V28 at complete-package reviews (each by codex; agy passed all thirteen);','History: V16–V21 were refused at gates and V22–V29 at complete-package reviews (each by codex; agy passed all fourteen);')
rp(r"DRIVER: `run_configurations_v13\.py`, SHA-256 `[0-9a-f]{64}` \(V29 STAGED:", f"DRIVER: `run_configurations_v14.py`, SHA-256 `{E['RC14']}` (V30 STAGED: `run_configurations_v13.py` — reviewed at V29, retained — with composed mode rebuilt as ONE RESOLVER (`composed_resolver`: four contributing stages, `provenance_designs_v10.resolve` decides by the stated order; the v13 stage-by-stage `composed_provenance` removed, not kept as dead code); V29 STAGED was:")
rp(r"fixture `test_run_configurations_v13\.py` `[0-9a-f]{64}`, 23 tests", f"fixture `test_run_configurations_v14.py` `{E['TRC14']}`, 23 tests")
sub('the track-2 v9 helpers called INSIDE `load_identity` on the production call path','the track-2 v10 helpers called INSIDE `load_identity` on the production call path')
rp(r"`build_corpus_identity_v29\.py`, SHA-256 `[0-9a-f]{64}` \(V29 STAGED:", f"`build_corpus_identity_v30.py`, SHA-256 `{E['B30']}` (V30 STAGED: on provenance_designs_v10; fixture `test_build_corpus_identity_v30.py` `{E['TB30']}`, 8 tests; V29 was:")
rp(r"`_optionA_dev/beacon_v2/beacon_record_drand_v29\.py` `[0-9a-f]{64}` \(V29:", f"`_optionA_dev/beacon_v2/beacon_record_drand_v30.py` `{E['BD30']}` (V30: on provenance_designs_v10; v29 retained; V29:")
rp(r"exercised by `test_beacon_record_drand_v29\.py` \(`[0-9a-f]{64}`, 7 tests", f"exercised by `test_beacon_record_drand_v30.py` (`{E['TBD30']}`, 7 tests")
nb=s.count('beacon_record_drand_v29'); s=s.replace('beacon_record_drand_v29','beacon_record_drand_v30'); nbu=len(re.findall(r'(?<!test_)build_corpus_identity_v29', s)); s=re.sub(r'(?<!test_)build_corpus_identity_v29','build_corpus_identity_v30', s); print('token replacements: beacon', nb, 'builder (non-fixture)', nbu)
rp(r"`coherent_attacks_v29\.py` \(`[0-9a-f]{64}`; rows 9m–9u = codex's V24 N2/N3, V25 P1/P2 and V26-1/2 cases, re-executed on driver v13 / provenance v9 — `V29_CANDIDATE_ATTACK_INSPECTION_20260907\.md`, same verdict in every row as V28;", f"`coherent_attacks_v30.py` (`{E['ATT30']}`; rows 9m–9u = codex's V24 N2/N3, V25 P1/P2 and V26-1/2 cases, re-executed on driver v14 / provenance v10 — `V30_CANDIDATE_ATTACK_INSPECTION_20260907.md`, same verdict in every row as V29;")
rpf(r"`track2/provenance_designs_v9\.py` \(`[0-9a-f]{64}`; UNADOPTED; v9 = v8 \+ codex's two precedence clauses on the COMPLETE paths \(`validate_continuation_v9` consults the feed before any retry; driver v13's precheck defers\) and rule \(iii\) restated; fixture `track9/test_track9_fail_first\.py` `([0-9a-f]{64})`, 3 tests fail-first \(1 complete-path case with seven sub-cases through driver v13, 1 rule-\(iii\) guard, 1 text\); text tests `track9/test_track9_text_v29\.py` `([0-9a-f]{64})` \(written against THIS text; 1 test\)",
    lambda m: f"`track2/provenance_designs_v10.py` (`{E['P10']}`; UNADOPTED; v10 = v9 + THE PRECEDENCE ORDER STATED ONCE (`PRECEDENCE`) and ONE RESOLVER (`resolve`, `finding`, `classify_history`, `local_precheck_event`; `validate_continuation_v10` is a contributor with v9's decision) and strictly-earlier ordering; fixture `track10/test_track10_fail_first.py` `{E['T10']}`, 4 tests fail-first (1 complete-path case with codex's seven V29 rows through driver v14, 1 strict-earlier case in both feed orders, 1 resolver pairwise case — 21 class pairs in both orders — and 1 text); exhibit `track10/exhibit_precedence_pairs.py` `{E['EX10']}` (`V30_PRECEDENCE_EXHIBIT_20260907.md`); text tests `track10/test_track10_text_v30.py` `{E['T10T']}` (written against THIS text; 1 test), the retained V29-specific `track9/test_track9_text_v29.py` `{m.group(2)}` (written against V29, run against V29 only), v9 (`track2/provenance_designs_v9.py`, fixture `track9/test_track9_fail_first.py` `{m.group(1)}`, 3 tests — its text case written against V29) retained; v9 = v8 + codex's two precedence clauses on the COMPLETE paths (`validate_continuation_v9` consults the feed before any retry; driver v13's precheck defers) and rule (iii) restated")
for path, dig, tok in (("track7/test_track7_fail_first.py", E['T7'], "\\1"), ("track7/test_track7_text_v27.py", E['T7T'], "\\2"), ("track8/test_track8_fail_first.py", E['T8'], "\\1"), ("track8/test_track8_text_v28.py", E['T8T'], "\\2")):
    old = f"`{path}` `{tok}`"; assert old in s, old; s = s.replace(old, f"`{path}` `{dig}`")
assert re.findall(r"`\\[0-9]`", s) == [], "backreference tokens remain"
rp(r"`run_configurations_v13\.py` \(`[0-9a-f]{64}`\) refuses to load an identity unless", f"`run_configurations_v14.py` (`{E['RC14']}`) refuses to load an identity unless")
rp(r"The builder `build_corpus_identity_v30\.py` \(`[0-9a-f]{64}`\)", f"The builder `build_corpus_identity_v30.py` (`{E['B30']}`)")
sub("**3c. V29 — WHAT THE AMENDMENT COSTS","**3c. V30 — WHAT THE AMENDMENT COSTS")
sub("UNREPAIRED CONTRADICTIONS: none known; anything a reviewer finds of that kind goes to this column and is repaired, never to the first. ", "UNREPAIRED CONTRADICTIONS: none known; anything a reviewer finds of that kind goes to this column and is repaired, never to the first. " + ORDER + " ")
sub("V28-1 and V28-2 — the witness-precheck and open-event retries that pre-empted those very rules on the complete paths, introduced by the V27-2 repair itself and filed as unrepaired at the V28 outcome — in THIS candidate (`TRACK9_FAIL_FIRST_RECEIPT_20260907.md`, combined-condition tests on the complete paths); the earlier ones in tracks 1–7.",
    "V28-1 and V28-2 — the witness-precheck and open-event retries that pre-empted those very rules on the complete paths, introduced by the V27-2 repair itself and filed as unrepaired at the V28 outcome — at V29 (`TRACK9_FAIL_FIRST_RECEIPT_20260907.md`); V29-1 and V29-2 — the seed re-derivation, remote-head and approval-feed retries that pre-empted the same rules, the fifth and sixth instances of ONE pattern — in THIS candidate, not by a point fix but by the single resolver (`TRACK10_FAIL_FIRST_RECEIPT_20260907.md`); the earlier ones in tracks 1–7.")
sub("driver v12 23 + V15 driver 17 + history_v2 4 + witness v4 3 + builder v28 8 + V15 builder 4 + verdict v28 7","driver v14 23 + V15 driver 17 + history_v2 4 + witness v4 3 + builder v30 8 + V15 builder 4 + verdict v30 7")
sub("+ track 9 3 + track 9 text (V29-specific) 1 = 136 tests","+ track 9 3 + track 9 text (V29-specific) 1 + track 10 4 + track 10 text (V30-specific) 1 = 141 tests")
sub("the V28-specific text test AND track 8's V27-3 text case (it asserts the V28 counts) against the V28 text, and only the version-agnostic tests (tracks 1/3/4, the track-6 sweep, track 7's fail-first, track 9's V28-3 assertions) plus the V29-specific test against THIS text",
    "the V28-specific text test AND track 8's V27-3 text case (it asserts the V28 counts) against the V28 text, the V29-specific text test against the V29 text, and only the version-agnostic tests (tracks 1/3/4, the track-6 sweep, track 7's fail-first, track 9's V28-3 assertions, track 10's V29-3 assertions) plus the V30-specific test against THIS text")
sub("136 tests across the 22 suites named in §3c;","141 tests across the 24 suites named in §3c;")
sub("Re-run `coherent_attacks_v29.py` and add counter-cases of your own.","Re-run `coherent_attacks_v30.py` and add counter-cases of your own.")
sub("## 9. Questions for the seats at the V29 complete-package review (STAGED candidate; nothing adopted)","## 9. Questions for the seats at the V30 complete-package review (STAGED candidate; nothing adopted)")
sub("(V29, if ordered; V16–V28's counted)","(V30, if ordered; V16–V29's counted)")
sub("the inspection of THIS candidate is `V29_CANDIDATE_ATTACK_INSPECTION_20260907.md`","the inspection of THIS candidate is `V30_CANDIDATE_ATTACK_INSPECTION_20260907.md`")
for bad in ("3c. V29", "136 tests across", "run_configurations_v13.py`, SHA-256", "V29_CANDIDATE_ATTACK_INSPECTION_20260907.md`, same verdict"): assert bad not in s, bad
open('OPTION_A_INSTRUMENT_SELECTION_RULE_DRAFT_V30_20260907.md','w',encoding='utf-8').write(s); print("V30 text written")
