import os
E = os.environ
src = open('OPTION_A_INSTRUMENT_SELECTION_RULE_DRAFT_V21_20260906.md', encoding='utf-8').read(); L = src.split('\n'); assert len(L) == 72
def sub(i, old, new, count=1):
    assert L[i].count(old) == count, (i, old[:70], L[i].count(old)); L[i] = L[i].replace(old, new)
sub(0, 'DRAFT V21 (NOT ADOPTED, NOT APPROVED)', 'DRAFT V22 — STAGED CANDIDATE (NOT GATED, NOT ADOPTED, NOT APPROVED)')
sub(2, 'V21 of 2026-09-06 (Blanc\'s bounded round, order of 19:48 KST + amendment 19:50) is V20 with', 'V22 of 2026-09-06 is a STAGED CANDIDATE prepared under Blanc\'s two-track order of 20:45 KST (cap lifted) and codex\'s coordination note of 20:43: TRACK 1 — the mechanical repairs of codex\'s V21 findings, each with a test that FAILED against byte-copies of the V21 modules before the repair and passes after (`TRACK1_FAIL_FIRST_RECEIPT_20260906.md`); TRACK 2 — the two provenance boundaries codex left open (a coherently forged GitHub event, a history rebuilt before the first freeze) are NOT closed by this candidate offline; their RECOMMENDED designs are staged as executable exhibits, UNADOPTED, in `TRACK2_PROVENANCE_DESIGNS_UNADOPTED_20260906.md` and `_optionA_dev/track2/`; the candidate DISCLOSES both as open (§3c) until Duho adopts a design. The complete object — the successful production path AND codex\'s coherent attacks re-run against these pinned bytes — is `V22_CANDIDATE_ATTACK_INSPECTION_20260906.md`. V21 was REFUSED (agy SIGNABLE; codex NOT-SIGNABLE: no recurrence of the V20 fatal, nine MAJORs — `V21_GATE_OUTCOME_AND_DIAGNOSIS_20260906.md`). V21 of 2026-09-06 (Blanc\'s bounded round, order of 19:48 KST + amendment 19:50) was V20 with')
sub(2, 'History: V16, V17, V18, V19 and V20 were refused (each by codex; agy passed all five);', 'History: V16, V17, V18, V19, V20 and V21 were refused (each by codex; agy passed all six);')
sub(2, 'V15 REMAINS OPERATIVE on paper until V21 is approved on its final bytes', 'V15 REMAINS OPERATIVE on paper until a candidate is approved on its final bytes')
# E1: factual erratum, not a design change
sub(18, '[INHERITED — PREPARED, NOT ADOPTED: the pinned V15 fixture `test_run_configurations.py` has 17 tests, not 10 (executed: `Ran 17 tests`); the V15 count is false; correcting a signed sentence is Duho\'s call (a); the V21 candidate states the true count here and changes nothing else]', '[FACTUAL ERRATUM in the signed V15 (Blanc 20:45; codex 20:43: an erratum, not a scientific choice): the pinned V15 fixture `test_run_configurations.py` has 17 tests, not 10 — executed, `Ran 17 tests`. The signed source is preserved; this annotation states the true count and is not a design change]')
# E3 pins
sub(20, 'DRIVER: `run_configurations_v5.py`, SHA-256 `d338e33dfbf84ed7127c6b32e529da6dcfd0cbf9704aba468cdc2aa2a426722c` (V21:', f'DRIVER: `run_configurations_v6.py`, SHA-256 `{E["D_RC6"]}` (V22 STAGED: `run_configurations_v5.py` `d338e33dfbf84ed7127c6b32e529da6dcfd0cbf9704aba468cdc2aa2a426722c` — refused at the V21 gate, retained — plus (codex V21 C2) W4 reproduced in the driver (`Protocol.approval_glob`, exactly one approval-record path in all history), (C3) a `witness-closed` history entry is terminal (`COLLECTION-CLOSED`), (C9) sentinel reconciliation requires a non-empty refusal cause on every journalled refusal and a render-end with the matching count, and (C11, UNADOPTED, default off) `Protocol.verify_split` — recompute the §3b split from the pinned catalogue files and require the identity\'s lists to equal it; fixture `test_run_configurations_v6.py` `{E["D_TRC6"]}`, 22 tests, ONE approval commit per repository (the v5 fixture\'s per-call records had masked W4), the end-to-end test exhibiting `verify_split` refusing a coherently sealed swapped list that the default driver accepts. V21 was:')
sub(20, '`build_corpus_identity_v21.py`, SHA-256 `048b42211a23f47ee4d97a9f6b7658b169736dbc2c4aa2f922f14dbb9d6a65d0` (V21:', f'`build_corpus_identity_v22.py`, SHA-256 `{E["D_B22"]}` (V22 STAGED: `build_corpus_identity_v21.py` `048b42211a23f47ee4d97a9f6b7658b169736dbc2c4aa2f922f14dbb9d6a65d0` retained, plus (codex V21 C4) the argument refusal disclosed in the sidecar and every failure after validation — catalogue, control, classification, output — logged as `builder-error` before refusing (the boundary wraps `build()`), approval glob V22; fixture `test_build_corpus_identity_v22.py` `{E["D_TB22"]}`, 8 tests; history `history_v2.py` `{E["D_H2"]}` (exclusive genesis creation; `witness-closed` terminal in `first_accept`; fixture `test_history_v2.py` `{E["D_TH2"]}`, 4 tests). V21 was:')
# 3b property: seed wording
sub(31, 'The seed is therefore f(R, public key).', 'The SEED is lowercase hex SHA-256 of the DECODED signature bytes (as `verify_drand_v2` computes it; the signature itself is the value, the seed its digest); it is therefore f(R, public key). Uniqueness, and "cannot exist before R\'s scheduled time", are conditional on the stated trust assumptions — the League of Entropy threshold (L1) and the pinned key (L2); verification proves validity under the key, not that a value was never released early by a threshold of nodes. `verify_drand_v2` verifies the round\'s signature over SHA-256(previous_signature ‖ R); it does not walk the predecessor chain.')
sub(31, 'same signature in different bytes = the same value (counted live-confirmed, the representation difference recorded in the verdict);', 'the same signature BYTES in a different encoding — key order, whitespace, extra fields, upper- or lower-case hex — = the same value (V22: equality is on the DECODED signature bytes, never on hex text; counted live-confirmed, the representation difference recorded in the verdict);')
sub(31, 'a DIFFERENT signature that also verifies under the pinned key for R would contradict uniqueness under one key — `REFUSE-CONFLICTING-VALID-SIGNATURES`, a defect of the key, not of a relay.', 'DIFFERENT signature bytes that also verify under the pinned key for R would contradict uniqueness under one key — `REFUSE-CONFLICTING-VALID-SIGNATURES`, a defect of the key, not of a relay (V21 compared hex strings, so an upper-cased signature reached this branch — codex V21 C6; the V22 verdict does not).')
sub(31, '`_optionA_dev/beacon_v2/exhibit_property_v21.py` (SHA-256 `148513160e1248e95505b9abf7c7e884ce9da041027dc11800db755611bc1ed0`; V20\'s', f'`_optionA_dev/beacon_v2/exhibit_property_v22.py` (SHA-256 `{E["D_EX22"]}`, the same exhibit on the v22 verdict; V21\'s `exhibit_property_v21.py` `148513160e1248e95505b9abf7c7e884ce9da041027dc11800db755611bc1ed0` and V20\'s')
sub(31, 'output `PROPERTY_EXHIBIT_V21_20260906.md`, digest `2160fa754ce3db25613389d58bacd3098763ea8536744558e9dae96c5b4f0ae1`', f'output `PROPERTY_EXHIBIT_V22_20260906.md`, digest `{E["EXD22"]}`')
# 3b order paragraph (line 33): filename, module names, byte-equality clause, token, fixture, exclusions, W4
sub(32, 'The approval record is the file `APPROVAL_RECORD_SELRULE_V20_<date>.md`', 'The approval record is the file `APPROVAL_RECORD_SELRULE_V22_<date>.md` (the name the builder and the driver search for: glob `APPROVAL_RECORD_SELRULE_V22*` — V21\'s text still said V20, codex V21 C8)')
sub(32, '(W4) FIRST APPROVAL IS FINAL: exactly one approval-record path for this version anywhere in history;', '(W4) FIRST APPROVAL IS FINAL: exactly one approval-record path for this version anywhere in history — checked by the witness at build time AND reproduced by the driver at every load (V22, codex V21 C2);')
sub(32, '`beacon_record_drand_v21.collect(fetch, T_sign, rule_sha256, statement_bytes, now)` (`_optionA_dev/beacon_v2/beacon_record_drand_v21.py` `24afe74eb2310c68ed707a0110d428e2053285ba460a861008a0c0b6e1b36cf3`; V20\'s', f'`beacon_record_drand_v22.collect(fetch, T_sign, rule_sha256, statement_bytes, now)` (`_optionA_dev/beacon_v2/beacon_record_drand_v22.py` `{E["D_BD22"]}`; V21\'s `beacon_record_drand_v21.py` `24afe74eb2310c68ed707a0110d428e2053285ba460a861008a0c0b6e1b36cf3` and V20\'s')
sub(32, 'and the exhibit\'s round 6441924 by name (`T-SIGN-PREDATES-AMENDMENT`, `T-PULSE-EXCLUDED`)', 'and BOTH historical fixture rounds by name — the exhibit\'s 6441924 and the nonce fixture\'s 6441904 (`EXCLUDED_ROUNDS = (6440756, 6441904, 6441924)`; V22, codex V21 C5) — (`T-SIGN-PREDATES-AMENDMENT`, `T-PULSE-EXCLUDED`)')
sub(32, '`beacon_record_drand_v21.verdict(record, now, fetch, rule_sha256, statement_bytes)` recomputes', '`beacon_record_drand_v22.verdict(record, now, fetch, rule_sha256, statement_bytes)` recomputes')
sub(32, 'with `fetch` given, each verifying relay is re-fetched live and must serve EQUAL bytes — a relay now serving different bytes that also verify is `REFUSE-LIVE-DIFFERS-BUT-VERIFIES` (impossible for a valid BLS signature; investigate), garbage or absence drops that relay from the live count, and fewer than 2 live confirmations is `RETRY`.', 'with `fetch` given, each verifying relay is re-fetched live and judged by the VALUE it carries (THE PROPERTY paragraph): equal bytes, or different bytes whose DECODED signature equals the retained one, confirm it live (the representation difference is recorded); a body that does not verify, or is absent, drops that relay from the live count; different signature BYTES that verify are `REFUSE-CONFLICTING-VALID-SIGNATURES`; fewer than 2 live confirmations is `RETRY`.')
sub(32, 'exercised by `test_beacon_record_drand.py` (`beff3592d6f31dc75c6dc88b26d0ea03e974a9b0a2ebafac00a9d0787e9f6099`, 6 tests on the real retained round', f'exercised by `test_beacon_record_drand_v22.py` (`{E["D_TBD22"]}`, 7 tests on the real retained round')
sub(32, 'In addition `beacon_record_drand_v21.collect` REFUSES', 'In addition `beacon_record_drand_v22.collect` REFUSES')
sub(32, 'and the exhibit round 6441924 — lower bounds and exclusions only.', 'and the historical fixture rounds 6441904 and 6441924 — lower bounds and exclusions only.')
# 3c
sub(37, '**3c. V21 — WHAT THE AMENDMENT COSTS, WHAT IS PRESERVED, HOW THE ORDER STAYS VISIBLE.** COLLECTION HISTORY, AUTHENTICATED (V19 audit M2; codex V20 M2): `_optionA_dev/collection_log.jsonl` is a hash chain (`corpus_identity/history.py`):', '**3c. V22 — WHAT THE AMENDMENT COSTS, WHAT IS PRESERVED, HOW THE ORDER STAYS VISIBLE, AND WHAT IS STILL OPEN.** COLLECTION HISTORY, TAMPER-EVIDENT WITHIN THE FILE (V19 audit M2; codex V20 M2; codex V21 C3): `_optionA_dev/collection_log.jsonl` is a hash chain (`corpus_identity/history_v2.py`):')
sub(37, 'and refuses to re-initiate an existing history or to log into one initiated for another approval (`HISTORY-EXISTS`, `HISTORY-GENESIS-MISMATCH`);', 'and refuses to initiate over ANY existing file (exclusive creation — the creation is the lock; V22) or to log into a history initiated for another approval (`HISTORY-EXISTS`, `HISTORY-GENESIS-MISMATCH`);')
sub(37, 'a deleted, edited, reordered or reset history fails `history.validate` and is refused (`HISTORY-INVALID`), disclosed beside the log (`<log>.pregenesis.jsonl`), never treated as a fresh start;', 'an interior deletion, edit or reorder, or a second genesis, fails `history_v2.validate` and is refused (`HISTORY-INVALID`), disclosed beside the log (`<log>.pregenesis.jsonl`); a `witness-closed` entry is TERMINAL (`first_accept` reports it as a conflict; the driver refuses `COLLECTION-CLOSED`); WHAT THE CHAIN DOES NOT PROVE, stated plainly (codex V21 C3): custody — a history DELETED AND REBUILT before the first freeze (fresh genesis, one accept, consistent lock and count) validates internally and LOADS, and a deleted SUFFIX that leaves an accept in place validates; closing this needs the head anchored OUTSIDE the file — the track-2 design (b), `TRACK2_PROVENANCE_DESIGNS_UNADOPTED_20260906.md`: the history-open commit pushed and witnessed like the approval record, every entry committed as it happens, `validate_continuation` requiring append-only extension through git objects — UNADOPTED, Duho\'s call; until adopted this is an OPEN BOUNDARY of the candidate, not a closed one;')
sub(37, 'The builder `build_corpus_identity_v21.py` (`048b42211a23f47ee4d97a9f6b7658b169736dbc2c4aa2f922f14dbb9d6a65d0`) requires the collector\'s genesis for THIS approval record and logs every path — pre-parse refusals, every verdict, witness refusals WITH their PENDING/CLOSED state, adoption refusals, the first ACCEPT (binding), conflicts (`builder-conflict`, then `COLLECTION-LOCKED`; a later accept-bearing entry naming a different record or seed is a semantic conflict, refused with or without the label), and ANY other exception (`builder-error`, then `BUILDER-ERROR`);', f'The builder `build_corpus_identity_v22.py` (`{E["D_B22"]}`) requires the collector\'s genesis for THIS approval record and logs: the argument refusal (sidecar, `builder-args-refusal`), pre-parse refusals, every verdict, witness refusals WITH their PENDING/CLOSED state, adoption refusals, the first ACCEPT (binding), conflicts (`builder-conflict`, then `COLLECTION-LOCKED`; a later accept-bearing entry naming a different record or seed is a semantic conflict, refused with or without the label), and any other exception anywhere in `build()` — validation, catalogue, control, classification, output — as `builder-error` before `BUILDER-ERROR` (V22: the boundary wraps `build()`; V21\'s wrapped the validator only and its "every path" was false — codex V21 C4); the collector CLI discloses argument failures in the sidecar named by `--log`, or in `beacon_v2/collector_argparse_failures.jsonl` when no `--log` was given; what is still NOT logged: nothing known — the seats are asked to look;')
sub(37, 'THE DRIVER\'S CONJUNCTION, FROM COMMITTED EVIDENCE (V19 audit M1; codex V20 FATAL + M1): `run_configurations_v5.py` (`d338e33dfbf84ed7127c6b32e529da6dcfd0cbf9704aba468cdc2aa2a426722c`) refuses to load an identity unless', f'THE DRIVER\'S CONJUNCTION, FROM COMMITTED EVIDENCE — WITH ITS TWO OPEN BOUNDARIES NAMED (V19 audit M1; codex V20 FATAL + M1; codex V21 C1/C2/C3): `run_configurations_v6.py` (`{E["D_RC6"]}`) refuses to load an identity unless')
sub(37, 'that commit is an ancestor of the protected remote ref, its digest equals the witness\'s,', 'that commit is an ancestor of the protected remote ref, it is the ONLY approval-record path for this version\'s glob in all history (W4, `APPROVAL-NOT-FIRST`), its digest equals the witness\'s,')
sub(37, 'the PushEvent is re-validated from its own bytes (type, protected ref, server time before T_pulse, delivery by head / commits / before..head ancestry via git, canonical digest equal to the witness\'s, retrieval provenance present);', 'the PushEvent is re-validated from its own bytes (type, protected ref, server time before T_pulse, delivery by head / commits / before..head ancestry via git, canonical digest equal to the witness\'s, retrieval provenance present) — OPEN BOUNDARY (codex V21 C1): this checks the retained event against ITSELF; a coherently forged event with a recomputed digest and invented provenance LOADS (attack 1 of the inspection); the driver does not re-query GitHub; the track-2 design (a) — live re-query of the pinned repository\'s events, verbatim presence, earliest qualifying, plus an independent OPS receipt for the expired case — is staged UNADOPTED; until adopted, the event is ATTESTED by the builder\'s run, not authenticated by the driver;')
sub(37, 'have the recorded entry count, and whose EARLIEST `builder-accept` names the identity\'s record, outcome and seed with no semantic conflict;', 'have the recorded entry count, contain no `witness-closed` entry, and whose EARLIEST `builder-accept` names the identity\'s record, outcome and seed with no semantic conflict (the chain\'s custody limit above applies here too);')
sub(37, 'and the seed RE-DERIVED from it by PRODUCTION\'s own re-deriver (`production_rederive_seed`, the offline drand-only verdict) equals the identity\'s seed. Any absent verifier is a refusal.', 'and the seed RE-DERIVED from it by PRODUCTION\'s own re-deriver (`production_rederive_seed`, the offline drand-only verdict) equals the identity\'s seed. Any absent verifier is a refusal. INHERITED LIMITATION, disclosed (codex V21 C11; the signed V15 driver): beyond size, type and disjointness the driver takes the three object lists, the pool and exclusion digests and the ordering/renderability metadata ON TRUST from the sealed identity — a coherently sealed swapped or arbitrary list loads; the staged `Protocol.verify_split` (default off) recomputes the split from the pinned catalogue files and the seed and refuses `SPLIT-NOT-REPRODUCED` (exhibited end-to-end on real builder output); adopting it changes what the signed driver trusts and is Duho\'s call. Offline, the retained relay bodies prove valid signatures under the pinned key, not that two physical hosts served them; the builder\'s live confirmation is not reproduced by the driver.')
sub(37, 'Fixtures: `test_build_corpus_identity_v21.py` (`63dfcad2058e2643f1a7e6f90f1eb0929a75b3b9c722c990cdf548d7ec77c179`, 8 tests', f'Fixtures (V22): `test_track1_fail_first.py` (`{E["D_T1"]}`, 10 tests, each covering one codex V21 finding — C2, C3 ×2, C4 ×3, C5, C6, C7/C8/C10 (the rule text itself), C9 — each shown FAILING against byte-copies of the V21 modules before the repair, `TRACK1_FAIL_FIRST_RECEIPT_20260906.md`); `coherent_attacks.py` (`{E["D_ATT"]}`; codex\'s coherent substitutions re-run against this candidate, output filed); `track2/provenance_designs.py` (`{E["D_P2"]}`) + `test_provenance_designs.py` (`{E["D_TP2"]}`, 2 tests; UNADOPTED; the live feed is fixture-supplied and labelled so); `test_build_corpus_identity_v21.py` (`63dfcad2058e2643f1a7e6f90f1eb0929a75b3b9c722c990cdf548d7ec77c179`, 8 tests')
sub(37, 'Run warning-strict (`-W error::ResourceWarning`): 22 + 17 + 4 + 3 + 8 + 4 + 7 + 4 = 69 tests, no ResourceWarning (V20\'s fixture leaked two file handles; fixed).', 'Run warning-strict (`-W error::ResourceWarning`) on the V22 candidate: driver v6 22 + V15 driver 17 + history_v2 4 + witness v4 3 + builder v22 8 + V15 builder 4 + verdict v22 7 + verifier v2 4 + track 1 10 + track 2 2 = 81 tests, no ResourceWarning.')
sub(37, 'COST (V21, stated for the drand-only design — V20 still carried V17\'s NIST cost text, refused as stale):', 'COST (V22; unchanged from V21 in substance):')
# §7 sentinel + holdout wording
sub(51, 'and the journal\'s `render-end` refused count equals the manifest\'s sentinel count; sentinel rows with no journal are refused (`SENTINEL-WITHOUT-RENDER-JOURNAL`);', 'every journalled refusal carries a NON-EMPTY cause (`reason`), the journal ends with a `render-end` (a journal without one is `RENDER-JOURNAL-INCOMPLETE`) whose refused count equals the manifest\'s sentinel count; sentinel rows with no journal are refused (`SENTINEL-WITHOUT-RENDER-JOURNAL`) (V22, codex V21 C9);')
sub(53, '[INHERITED — PREPARED, NOT ADOPTED: under the signed V15 this covenant is text only', '[The existing ONE-holdout REQUIREMENT stands as signed and is not changed here. Separately, a PROSPECTIVE IMPLEMENTATION enforcing it is PREPARED, NOT ADOPTED: under the signed V15 the covenant is text only')
# §9, §10
sub(63, '## 9. Questions for the seats at the V21 gate (Blanc\'s ONE bounded round; the cap re-arms after it)', '## 9. Questions for the seats at the V22 gate (STAGED candidate; a gate is NOT yet ordered — Blanc decides after reading both tracks)')
sub(64, 'AUTHORSHIP: all V21 code is Hwao\'s;', 'AUTHORSHIP: all V21/V22 code is Hwao\'s;')
sub(64, 'the V20 gate\'s FATAL and every listed finding are answered in `V20_REPORT_REPAIR_CHECKLIST_20260906.md` and `MINI_PREREG_SELRULE_V20_TO_V21_CHANGE_RECORD_20260906.md`; the reproduction is `V20_FATAL_REPRODUCTION_20260906.md`.', 'codex\'s V21 findings are answered in `V21_GATE_OUTCOME_AND_DIAGNOSIS_20260906.md` (classification), `TRACK1_FAIL_FIRST_RECEIPT_20260906.md` (each repair fail-first), `V22_CANDIDATE_ATTACK_INSPECTION_20260906.md` (codex\'s coherent attacks against THIS candidate — two still pass and are DISCLOSED as open boundaries) and `TRACK2_PROVENANCE_DESIGNS_UNADOPTED_20260906.md` (their recommended, unadopted closures).')
sub(65, '1. THE PRODUCTION PATH: is', '0. THE COMPLETE OBJECT: judge the candidate WITH its stated open boundaries — are they stated exactly, and is anything else open that the inspection does not list? Re-run `coherent_attacks.py` and add attacks of your own. 1. THE PRODUCTION PATH: is')
sub(65, '7. WHAT IS STILL MISSING for approval, as clause text; or state that nothing is. A fatal on the same surface STOPS this track (no V22).', '7. THE TRACK-2 DESIGNS: are (a) and (b) sufficient to close C1/C3, is the trust they introduce stated completely, and what would you change before Duho is asked to adopt them? 8. WHAT IS STILL MISSING for approval, as clause text; or state that nothing is.')
sub(67, 'one two-seat gate on this amendment (V21; V16–V20\'s counted)', 'one two-seat gate on this amendment (V22, if ordered; V16–V21\'s counted)')
open('OPTION_A_INSTRUMENT_SELECTION_RULE_DRAFT_V22_20260906.md', 'w', encoding='utf-8').write('\n'.join(L)); print('V22 staged text written')
