# -*- coding: utf-8 -*-
import os, re; E=os.environ
p='OPTION_A_INSTRUMENT_SELECTION_RULE_DRAFT_V28_20260907.md'; s=open(p, encoding='utf-8').read()
def rp(pat, new):
    global s; m=re.search(pat, s); assert m, pat[:80]; s=s.replace(m.group(0), new, 1)
def sub(old, new):
    global s; assert old in s, old[:80]; s=s.replace(old, new, 1)
C1="On both the approval and history-open paths, locally decidable retained-event mismatches are terminal before any evidence-unavailability return. In composed mode, unresolved delivery does not bypass live authentication: a same-ID canonical contradiction obtained from the live feed is terminal before an undetermined-delivery retry. Only when no higher-priority inconsistency is established may undetermined delivery or unavailable retrieval return the stage's retry disposition. Offline mode retains its explicitly named undetermined-delivery refusal."
C2="Same-commit contradiction is scoped to the pinned protected ref and evaluated only when the retained event is absent. If it is present verbatim, distinct qualifying events are resolved by earliest-event ordering; a later event does not invalidate an authentic earliest event. Conflicting same-ID evidence is refused even beside a verbatim copy, without asserting that this alone identifies which producer supplied false evidence."
sub('DRAFT V28 — STAGED CANDIDATE (NOT GATED, NOT ADOPTED, NOT APPROVED)','DRAFT V29 — STAGED CANDIDATE (NOT GATED, NOT ADOPTED, NOT APPROVED)')
sub('V28 of 2026-09-07 is V27 after its complete-package review',
 "V29 of 2026-09-07 is V28 after its complete-package review (agy SIGNABLE; codex NOT-SIGNABLE, no fatal — `V28_REVIEW_OUTCOME_20260907.md`), with codex's V28-1/2/3 answered FAIL-FIRST (`TRACK9_FAIL_FIRST_RECEIPT_20260907.md`: 3 tests failing against byte-copies of the V28 modules — the complete-path case reproducing codex's exact retry, the rule-(iii) guard, the text case; 3 passing after; the complete-path case carries seven sub-cases: approval delivery undetermined + genuine same-id contradiction in the feed → EVENT-FORGED; + wrong repository, with a healthy feed and with HTTP 503 → EVENT-INCONSISTENT; undetermined with nothing contradicting → RETRY-EVENTS-UNAVAILABLE, unchanged; the same three on the history-open stage → OPEN-EVENT-FORGED / OPEN-EVENT-INCONSISTENT-INPUT / EVIDENCE-UNAVAILABLE). V28-1 and V28-2 were UNREPAIRED CONTRADICTIONS the lane's own V27-2 repair had introduced — a tri-state precheck that returned a retry before the precedence rules could run — filed in column two of the register at the V28 outcome and repaired here; codex's clause text is carried verbatim into the code header, this paragraph and §3c: (V28-1) \"" + C1 + "\" — implemented by driver v13's witness-commit precheck DEFERRING an undetermined delivery to composed provenance (local_precheck → retrieval → same-id contradictions → only then the retry) while positive non-delivery stays terminal and offline keeps IDENTITY-WITNESS-COMMIT-UNDETERMINED; (V28-2) `validate_continuation_v9` consults the feed the same way before returning EVIDENCE-UNAVAILABLE; (V28-3) \"" + C2 + "\" — rule (iii) restated (the V28 phrasing 'another delivering push is an ordering question — NOT-EARLIEST' was too short: a later distinct qualifying push beside a verbatim earliest genuine event is AUTHENTIC; NOT-EARLIEST needs an EARLIER qualifying event), the two false filename↔digest associations corrected (the V28 edit's token replacement had renamed the historical builder-fixture clause; the V27 edit's line-33 replacement had put the historical verifier's digest beside the pinned verifier's name), the driver fixture header names itself, the inspection's row-1 note says INCONSISTENT-INPUT for the wrong-repository forgery, the questions file's contract sentence names both arms of FORGED with the absent-only qualification, the design document's outcomes row is restated for v9 (revision 9), and L-INH / L-AVAIL carry their mode qualifications. V28 of 2026-09-07 was V27 after its complete-package review")
sub('History: V16–V21 were refused at gates and V22–V27 at complete-package reviews (each by codex; agy passed all twelve);','History: V16–V21 were refused at gates and V22–V28 at complete-package reviews (each by codex; agy passed all thirteen);')
rp(r"DRIVER: `run_configurations_v12\.py`, SHA-256 `[0-9a-f]{64}` \(V28 STAGED:", f"DRIVER: `run_configurations_v13.py`, SHA-256 `{E['RC13']}` (V29 STAGED: `run_configurations_v12.py` — reviewed at V28, retained — plus composed mode on `provenance_designs_v9` (the witness-commit precheck defers an UNDETERMINED delivery to live authentication in composed mode; the open-event stage consults the feed before any retry; positive non-delivery terminal; offline keeps its named undetermined refusal); V28 STAGED was:")
rp(r"fixture `test_run_configurations_v12\.py` `[0-9a-f]{64}`, 23 tests", f"fixture `test_run_configurations_v13.py` `{E['TRC13']}`, 23 tests")
sub('the track-2 v8 helpers called INSIDE `load_identity` on the production call path','the track-2 v9 helpers called INSIDE `load_identity` on the production call path')
rp(r"`build_corpus_identity_v28\.py`, SHA-256 `[0-9a-f]{64}` \(V28 STAGED:", f"`build_corpus_identity_v29.py`, SHA-256 `{E['B29']}` (V29 STAGED: on provenance_designs_v9; fixture `test_build_corpus_identity_v29.py` `{E['TB29']}`, 8 tests; V28 was:")
sub(f"V27 was: on provenance_designs_v7; fixture `test_build_corpus_identity_v28.py` `{E['TB27']}`", f"V27 was: on provenance_designs_v7; fixture `test_build_corpus_identity_v27.py` `{E['TB27']}`")   # codex V28-3 (1)
rp(r"`_optionA_dev/beacon_v2/beacon_record_drand_v28\.py` `[0-9a-f]{64}` \(V28:", f"`_optionA_dev/beacon_v2/beacon_record_drand_v29.py` `{E['BD29']}` (V29: on provenance_designs_v9; v28 retained; V28:")
rp(r"exercised by `test_beacon_record_drand_v28\.py` \(`[0-9a-f]{64}`, 7 tests", f"exercised by `test_beacon_record_drand_v29.py` (`{E['TBD29']}`, 7 tests")
nb=s.count('beacon_record_drand_v28'); s=s.replace('beacon_record_drand_v28','beacon_record_drand_v29'); nbu=len(re.findall(r'(?<!test_)build_corpus_identity_v28', s)); s=re.sub(r'(?<!test_)build_corpus_identity_v28','build_corpus_identity_v29', s); print('token replacements: beacon', nb, 'builder (non-fixture)', nbu)
assert s.count('beacon_record_drand_v28') == 0, s.count('beacon_record_drand_v28')
assert s.count('build_corpus_identity_v28') == 1 and 'fixture `test_build_corpus_identity_v28.py` `' in s   # exactly the historical V28 fixture clause, with its own digest
rp(r"`coherent_attacks_v28\.py` \(`[0-9a-f]{64}`; rows 9m–9u = codex's V24 N2/N3, V25 P1/P2 and V26-1/2 cases, re-executed on driver v12 / provenance v8 — `V28_CANDIDATE_ATTACK_INSPECTION_20260907\.md`, same verdict in every row as V27;", f"`coherent_attacks_v29.py` (`{E['ATT29']}`; rows 9m–9u = codex's V24 N2/N3, V25 P1/P2 and V26-1/2 cases, re-executed on driver v13 / provenance v9 — `V29_CANDIDATE_ATTACK_INSPECTION_20260907.md`, same verdict in every row as V28;")
rp(r"`track2/provenance_designs_v8\.py` \(`[0-9a-f]{64}`; UNADOPTED; v8 = v7 \+ the three precedence rules with `local_precheck` before retrieval, the tri-state open-event stage of `validate_continuation_v8`, and UNDETERMINED for a git process-launch exception; fixture `track8/test_track8_fail_first\.py` `([0-9a-f]{64})`, 7 tests fail-first \(3 behavioural, 2 missing-interface, 1 complete-path through driver v12, 1 text\); text tests `track8/test_track8_text_v28\.py` `([0-9a-f]{64})` \(written against THIS text; 1 test\)",
   f"`track2/provenance_designs_v9.py` (`{E['P9']}`; UNADOPTED; v9 = v8 + codex's two precedence clauses on the COMPLETE paths (`validate_continuation_v9` consults the feed before any retry; driver v13's precheck defers) and rule (iii) restated; fixture `track9/test_track9_fail_first.py` `{E['T9']}`, 3 tests fail-first (1 complete-path case with seven sub-cases through driver v13, 1 rule-(iii) guard, 1 text); text tests `track9/test_track9_text_v29.py` `{E['T9T']}` (written against THIS text; 1 test), the retained V28-specific `track8/test_track8_text_v28.py` `\\2` (written against V28, run against V28 only), v8 (`track2/provenance_designs_v8.py`, fixture `track8/test_track8_fail_first.py` `\\1`, 7 tests — its text case is V28-specific and runs against the V28 text) retained; v8 = v7 + the three precedence rules with `local_precheck` before retrieval, the tri-state open-event stage of `validate_continuation_v8`, and UNDETERMINED for a git process-launch exception")
rp(r"`run_configurations_v12\.py` \(`[0-9a-f]{64}`\) refuses to load an identity unless", f"`run_configurations_v13.py` (`{E['RC13']}`) refuses to load an identity unless")
rp(r"The builder `build_corpus_identity_v29\.py` \(`[0-9a-f]{64}`\)", f"The builder `build_corpus_identity_v29.py` (`{E['B29']}`)")   # the token pass renamed the file; this pins the v29 digest
sub("V20's `verify_drand_v2.py` (the pinned verifier; the V20 `verify_drand.py` is historical) `a781b965e50ea947969f4559c267b88505b55d292b04d0b4739381216da6c20d`", f"V20's `verify_drand.py` `a781b965e50ea947969f4559c267b88505b55d292b04d0b4739381216da6c20d` (the pinned verifier is `verify_drand_v2.py` (`{E['VD2']}`); codex V28-3: the V27 edit had put the historical digest beside the pinned name)")   # codex V28-3 (2)
sub("**3c. V28 — WHAT THE AMENDMENT COSTS","**3c. V29 — WHAT THE AMENDMENT COSTS")
sub("L-INH, the inherited V15 trust in the object lists and pool/exclusion digests (verify_split UNADOPTED, off);","L-INH, the inherited V15 trust in the object lists and pool/exclusion digests — a default-mode implementation limit, not an irreducible one: `verify_split` is staged (UNADOPTED, off) and would refuse a coherently swapped list if adopted (codex V28);")
sub("L-AVAIL, GitHub's event window (300 events / 30 days) and the stateless RETRY dispositions (an inconsistent identity can stay pending; loss closes the approval under the rule).","L-AVAIL, GitHub's event window (300 events / 30 days; 30 s–6 h latency) — an EXTERNAL availability limit — combined with the rule's stateless closure enforcement (a genuinely unavailable identity can stay pending; loss closes the approval under the rule; no persisted loader state); this never covers an already-decidable mismatch, which is terminal on every path (codex V28).")
sub("V27-1 (precedence) and V27-2 (tri-state propagation) in THIS candidate (`TRACK8_FAIL_FIRST_RECEIPT_20260907.md`), the earlier ones in tracks 1–7.","V27-1 (precedence) and V27-2 (tri-state propagation) at V28 (`TRACK8_FAIL_FIRST_RECEIPT_20260907.md`); V28-1 and V28-2 — the witness-precheck and open-event retries that pre-empted those very rules on the complete paths, introduced by the V27-2 repair itself and filed as unrepaired at the V28 outcome — in THIS candidate (`TRACK9_FAIL_FIRST_RECEIPT_20260907.md`, combined-condition tests on the complete paths); the earlier ones in tracks 1–7. THE TWO PRECEDENCE CLAUSES IN FORCE: \"" + C1 + "\" \"" + C2 + "\"")
sub("+ track 8 7 + track 8 text (V28-specific) 1 = 132 tests","+ track 8 7 + track 8 text (V28-specific) 1 + track 9 3 + track 9 text (V29-specific) 1 = 136 tests")
sub("the track-5 label test against the V25 text, the V26-specific text test against the V26 text, the V27-specific text test against the V27 text, and only the version-agnostic tests (tracks 1/3/4, the track-6 sweep, the track-8 V27-3 assertions) plus the V28-specific test against THIS text",
    "the track-5 label test against the V25 text, the V26-specific text test against the V26 text, the V27-specific text test against the V27 text, the V28-specific text test AND track 8's V27-3 text case (it asserts the V28 counts) against the V28 text, and only the version-agnostic tests (tracks 1/3/4, the track-6 sweep, track 7's fail-first, track 9's V28-3 assertions) plus the V29-specific test against THIS text")
sub("132 tests across the 20 suites named in §3c;","136 tests across the 22 suites named in §3c;")
sub("Re-run `coherent_attacks_v28.py` and add counter-cases of your own.","Re-run `coherent_attacks_v29.py` and add counter-cases of your own.")
sub("## 9. Questions for the seats at the V28 complete-package review (STAGED candidate; nothing adopted)","## 9. Questions for the seats at the V29 complete-package review (STAGED candidate; nothing adopted)")
sub("(V28, if ordered; V16–V27's counted)","(V29, if ordered; V16–V28's counted)")
sub("the inspection of THIS candidate is `V28_CANDIDATE_ATTACK_INSPECTION_20260907.md`","the inspection of THIS candidate is `V29_CANDIDATE_ATTACK_INSPECTION_20260907.md`")
for bad in ("3c. V28", "132 tests across", "run_configurations_v12.py`, SHA-256", "V28_CANDIDATE_ATTACK_INSPECTION_20260907.md`, same verdict"): assert bad not in s, bad
open('OPTION_A_INSTRUMENT_SELECTION_RULE_DRAFT_V29_20260907.md','w',encoding='utf-8').write(s); print("V29 text written")
