import os, re; E=os.environ; p='OPTION_A_INSTRUMENT_SELECTION_RULE_DRAFT_V20_20260906.md'; s=open(p).read()
def rep(old,new,count=1):
    global s; assert s.count(old)==count, (s.count(old), old[:90]); s=s.replace(old,new)
lines=s.split('\n')
lines[0]='# OPTION (A) — INSTRUMENT SELECTION RULE, DRAFT V20 (NOT ADOPTED, NOT APPROVED) — DRAND-ONLY SAMPLING AMENDMENT OF THE SIGNED V15 (SOURCE DECISION BY DUHO, VIA CODEX VOICE, ~19:02 KST: "해")'
assert lines[2].startswith('V19 of 2026-09-06 is the fourth draft')
lines[2]='''V20 of 2026-09-06 replaces the two-source design of V15–V19 with ONE public randomness source, by Duho's decision: via codex voice at about 19:02 KST, after Codex presented the drand-only direction and its availability trade-off (wait, never switch source), Duho answered "해" ("Do it") — recorded by Codex in `.hermes/CODEX_DUHO_DRAND_ONLY_DECISION_20260906.md`; a source-direction decision, not a signature, not a review verdict, not a draw. History: V16, V17, V18 and V19 were refused (each by codex; agy passed all four); V19 fell on the property it claimed — with two sources, the failing side (NIST) leaves no authenticator, so the FIRST collection could still select the source; the author's 12:52 answer overstated this and the OPS coordinator released on it (recorded in the change record). V20 removes the choice: the seed is the drand mainnet default chain's threshold BLS signature for a prospectively fixed round, verified cryptographically under the pinned public key, bound to the pinned chain hash — a function of (round, key) that no relay, operator or collection time can change; unavailability is RETRY, never a different value. The signed V15 (fdd9eedd9938c2ba7df312cdc9b82a06612772ccc087e9365b33fd7d9d9a97d1, T_sign 2026-09-06T00:04:07Z) stays on file unchanged with its RETRY record 1c1d9d4bacc35319e91d46420b8f892e1126cc48059ec69156a0a718428aeb4b; its own defects are on record (\`V19_REPORT_AUDIT_TRIAGE_20260906.md\` §C) and are not repaired here. Preserved byte-for-byte from V15: sample sizes 400/200/2,000, floors 380/190/1,900, the 0.70 bar, the exclusions, ONE holdout, the label/pixel boundaries, custody, branch protection, the §6 pipeline identity (executing under the approved Tier-C V39). The V19 audit's two MAJOR findings are repaired here because every option needed them: the driver verifies the acceptance conjunction semantically (§3c) and the collection history is complete on every path (§3c). V15 REMAINS OPERATIVE on paper until V20 is approved on its final bytes; a clear pair is READY-FOR-APPROVAL, not permission; nothing is drawn under a draft.'''
s='\n'.join(lines)
# THE PROPERTY paragraph → drand-only version
i=s.index("**THE PROPERTY (V19, stated first).**"); j=s.index("**Order, provable.**", i)
s=s[:i]+f'''**THE PROPERTY (V20, stated first).** The seed for the fixed round R = round_for(T_pulse) on the drand mainnet default chain is that chain's threshold BLS signature over the fixed message SHA-256(previous_signature ‖ R as 8-byte big-endian): for a given R and a given chain public key there is exactly ONE valid signature, it cannot exist before R's scheduled time, and anyone can verify it under the pinned key without trusting this lane, any relay, or any archive of ours. The seed is therefore f(R, public key). Relays only transport it: a relay's bytes either verify — and are then THE value — or fail; a failing, garbled, absent or late relay is RETRY, and a later collection yields the same bytes or nothing. There is no second source, no fallback, no failure evidence to judge, and so no first-collection lever — the V19 fatal has nothing to act on. EXHIBITED, not asserted: `_optionA_dev/beacon_v2/exhibit_property_v20.py` (SHA-256 `{E['EXP20']}`) on the REAL public round 6441924 (retained from two relays, byte-identical; BLS-verified under the pinned key): (A) two FIRST collections at different wall-clock times → the same verified seed; (B) a first collection with three relays down and one serving garbage → RETRY with no seed, and a later first collection → the same seed as (A); (C) a relay later serving different bytes that still verify → REFUSED as impossible for a deterministic BLS signature, and tampered live bytes → RETRY; (D) the same record verified a year apart → identical; output `PROPERTY_EXHIBIT_V20_20260906.md`, digest `{E['EX20']}`, byte-reproducible. The exhibit's round 6441924 is EXCLUDED by name from ever being a study seed (`EXCLUDED_ROUNDS`). LIMITS (residual trust, plainly): (L1) the League of Entropy's threshold — if a threshold of nodes colludes they can bias a future round; no one outside the network can check that; (L2) the authenticity of the pinned public key — pinned from the network's info endpoint and retained (`chain_info_8990e7a9.json`, `{E['CI']}`), comparable by anyone to the network's published key; (L3) relay availability — fewer than two relays serving the round is RETRY, a delay; (L4) the verifier — py_ecc 8.0.0, a pure-Python BLS12-381 implementation pinned by version (`requirements_bls.txt`, `{E['REQ']}`), could in principle accept an invalid signature; the exhibit's negative controls (tampered signature, wrong key) bound this, and a second independent verifier may be run at collection; (L5) the operator can delay or abandon — visible, and neither changes the value.
'''+s[j:]
# (1) approval — unchanged text but names; (1a) glob V20; round current at T_sign exact rule
s=s.replace("APPROVAL_RECORD_SELRULE_V19_<date>.md","APPROVAL_RECORD_SELRULE_V20_<date>.md")
rep("quoting the drand mainnet round CURRENT at T_sign (round_for(T_sign) − 1 ≤ R ≤ round_for(T_sign))","quoting the drand mainnet round current at T_sign — EXACTLY: R ∈ {round_for(T_sign) − 1, round_for(T_sign)}, the round just closed or the one closing, because the latest CLOSED round at the instant of writing is one of these two; R's scheduled time is at or after MIN_T_SIGN")
# (2)–(4): replace the NIST evidence/verdict paragraph wholesale: from "(2) T_pulse =" to the end of the outcomes paragraph line 35 and LIMITS 38 — simpler: replace the specific sentences
rep("(2) T_pulse = the first whole minute ≥ T_sign + 600 s (`beacon_record.pulse_time`; observed: 01:00:00 → 01:10:00, 01:00:01 → 01:11:00).","(2) T_pulse = the first whole minute ≥ T_sign + 600 s (`verify_drand.pulse_time`; observed: 01:00:00 → 01:10:00, 01:00:01 → 01:11:00); ROUND = ⌊(T_pulse − 1595431050)/30⌋ + 1 (`verify_drand.round_for`); the round's scheduled time is ≥ T_pulse > T_sign, so it does not exist at approval (exhibited for a hypothetical approval 2026-09-07T01:00:07Z → T_pulse 01:11:00Z → round 6443748, `DRAND_ONLY_EXHIBIT_20260906.md`).")
i=s.index("(3) `beacon_record."); j=s.index("**Mapping seed → split, exact (unchanged):**", i)
s=s[:i]+f'''(3) `beacon_record_drand.collect(fetch, T_sign, rule_sha256, statement_bytes, now)` (`_optionA_dev/beacon_v2/beacon_record_drand.py` `{E['BD']}`) REFUSES to run before T_pulse (`BEACON-NOT-YET`), refuses a T_sign before `MIN_T_SIGN` = 2026-09-06T02:20:00Z and the public 2026-09-06T00:15:00Z pulse/round and the exhibit's round 6441924 by name (`T-SIGN-PREDATES-AMENDMENT`, `T-PULSE-EXCLUDED`), refuses a statement that lacks the rule digest or T_sign (`STATEMENT-DOES-NOT-BIND`), and writes a record (`BEACON-RECORD-4`) that contains ONLY inputs (T_sign, T_pulse, round, the pinned chain hash and public key, rule digest, statement bytes, collection UTC) and EVIDENCE BYTES — each pinned relay's raw body from the chain-hash-qualified path `/<chain hash>/public/<round>` (api, api2, api3.drand.sh; drand.cloudflare.com), or the error it returned — and no verdict, flag, seed or boolean. (4) `beacon_record_drand.verdict(record, now, fetch, rule_sha256, statement_bytes)` recomputes everything from those bytes, in this order: schema and pinned-chain identity, T_pulse/round derivation, MIN_T_SIGN and exclusions, rule digest and statement binding, then the CLOCK (`now < T_pulse` → `RETRY`), then for each retained body: JSON, `round` equal, signature 96 bytes (G2), `randomness = SHA-256(signature)`, **BLS12-381 verification under the pinned public key** (`verify_drand.verify`, `_optionA_dev/drand_only/verify_drand.py` `{E['VD']}`, py_ecc G2Basic, DST BLS_SIG_BLS12381G2_XMD:SHA-256_SSWU_RO_NUL_, message SHA-256(previous_signature ‖ round)), URL bound to the chain hash; ≥ 2 relays must verify and agree (they cannot verify and disagree); with `fetch` given, each verifying relay is re-fetched live and must serve EQUAL bytes — a relay now serving different bytes that also verify is `REFUSE-LIVE-DIFFERS-BUT-VERIFIES` (impossible for a valid BLS signature; investigate), garbage or absence drops that relay from the live count, and fewer than 2 live confirmations is `RETRY`. Outcomes: `ACCEPT-DRAND` (seed = the round's randomness, verified relays listed) | `RETRY` | `REFUSE-<token>`. The same function is the builder's boundary. Every REFUSE token the code can emit is exercised by `test_beacon_record_drand.py` (`{E['TBD']}`, 6 tests on the real retained round — the exclusion of that round is lifted only inside the fixture — including quorum, transport faults, tampered bodies, clock-first, bindings, and that the CLI logs every attempt including pre-parse errors); `verify_drand` itself by `test_verify_drand.py` (`{E['TVD']}`, 4 tests) and the drand-only exhibit `exhibit_drand_only.py` (`{E['EXDOP']}`, output digest `{E['EXDO']}`). NIST is not consulted; `nist_pulse.py`, `beacon_record.py` (V15) and `beacon_record_expedited.py` (V16–V19, `{E['BX']}`) are superseded and retained.
'''+s[j:]
# outcomes/LIMITS paragraph lines 35/38 of V19: remove the NIST-specific paragraphs between the mapping paragraph and "**Consequence for §3a.**"? They are "**What the beacon repairs…**" and "**LIMITS — findings for Duho…**". Replace LIMITS paragraph:
i=s.index("**LIMITS — findings for Duho, not gaps to paper over"); j=s.index("\n", i)
s=s[:i]+"**LIMITS (V20):** stated in THE PROPERTY paragraph above (L1–L5). The NIST limits of V15–V19 (2048-bit certificate against a 512-byte signature; unverified drand BLS; provenance only by live re-fetch; no normative serialization vector) no longer apply: NIST is not a source, and the drand signature IS verified."+s[j:]
# what-the-beacon-repairs paragraph: keep but note NIST-versus-drand no longer a choice
rep("**What the beacon repairs, and what it does not (unchanged in substance):**","**What the beacon repairs, and what it does not (V20):** there is no longer a NIST-versus-drand decision at all;")
# §3c: history + driver v4 + adoption; §7 command; pins
i=s.index("SOURCE-DECISION PROCEDURE (codex V16 item 2; V17 item 5; V18 item 3):"); j=s.index("(20 tests: V15's 17, plus adoption-fails-closed, sentinel-counted-and-unscored, and the acceptance-path refusals; its end-to-end test drives the V19 builder over a real git scaffold into the driver).", i)+len("(20 tests: V15's 17, plus adoption-fails-closed, sentinel-counted-and-unscored, and the acceptance-path refusals; its end-to-end test drives the V19 builder over a real git scaffold into the driver).")
s=s[:i]+f'''COLLECTION HISTORY, COMPLETE (V19 audit M2): the collector CLI logs EVERY attempt — `--log` is mandatory — including refusals and pre-parse/I-O errors (`collector-collect`, `collector-verify`, `collector-refusal`, `collector-error`); the builder `build_corpus_identity_v20.py` (`{E['B20']}`) logs every path — pre-parse refusals (`builder-pre-parse-refusal`), every verdict, witness/adoption refusals, the first ACCEPT (`builder-accept`, binding) and any conflicting later ACCEPT (`builder-conflict`, then `COLLECTION-LOCKED`) — to the append-only `_optionA_dev/collection_log.jsonl`; the identity carries the log's digest and first ACCEPT, its T_pulse, round, source and the adoption digest; the log is committed with the identity and the retained beacon record (E3 witness). ADOPTION BINDING: `_optionA_dev/ADOPTED_RULE_SHA256.txt` (exactly one 64-hex line and one newline) is committed WITH the approval record; the builder refuses unless it is a byte-equal blob at the witnessed approval commit and equals `--rule-sha256`. THE DRIVER'S CONJUNCTION (V19 audit M1): `run_configurations_v4.py` (`{E['RC4']}`) refuses to load an identity unless — in addition to the seal and freeze witness — its outcome is exactly `ACCEPT-DRAND` and its source the pinned chain; its approval witness carries an entire PushEvent for the protected ref delivering the approval commit with server time before T_pulse, and a nonce; the committed collection log's bytes match the identity, are the blob at the witnessed commit, and, PARSED, contain a first `builder-accept` naming the identity's record, outcome and seed with no `builder-conflict`; the adoption file is well-formed, equals the adopted digest, is a byte-equal blob at the approval commit, and matches the identity's adoption digest; the retained beacon record matches the identity's digest and the seed RE-DERIVED from it by the drand-only verdict equals the identity's seed. Fixtures: `test_build_corpus_identity_v20.py` (`{E['TB20']}`, 6 tests on the real round: accepted with history; every attempt logged incl. RETRY, witness refusal and pre-parse; a second collection locked out; adoption must be a blob at the approval commit; identity fields); `test_run_configurations_v4.py` (`{E['TRC4']}`, 20 tests; the acceptance conjunction refuses each of eleven defective identities — RETRY, invented and NIST outcomes, wrong source, missing/late witness, lock mismatch, log digest, logged conflict, malformed adoption, non-rederivable seed — and an emptied log after the seal; its end-to-end test drives the real round through the V20 builder into the driver; run under the pinned interpreter with the venv's packages on PYTHONPATH — E2's interpreter lock is unchanged).'''+s[j:]
rep("build_corpus_identity_v19.py --beacon-record <record> --rule-sha256 <the approved V19 digest> --signature-statement <the witnessed APPROVAL_RECORD_SELRULE_V19 file>","PYTHONPATH=_optionA_dev/_venv_bls/lib/python3.9/site-packages /usr/bin/python3 _optionA_dev/corpus_identity/build_corpus_identity_v20.py --beacon-record <record> --rule-sha256 <the approved V20 digest> --signature-statement <the witnessed APPROVAL_RECORD_SELRULE_V20 file>")
# E3 pins
pat=re.compile(r"`build_corpus_identity_v19\.py`, SHA-256 `[0-9a-f]{64}` \(V19: V15's `build_corpus_identity\.py` `3090af770f0329beddb2d8b64acae6d4a1b1da06025e616b6fb145bff47ca46c` plus the expedited beacon import, the approval-witness-v3 call, the complete collection history and the adoption-at-approval-commit binding; the V18 builder `[0-9a-f]{64}` is superseded and retained\)")
assert len(pat.findall(s))==1; s=pat.sub(f"`build_corpus_identity_v20.py`, SHA-256 `{E['B20']}` (V20: V15's `build_corpus_identity.py` `3090af770f0329beddb2d8b64acae6d4a1b1da06025e616b6fb145bff47ca46c` plus the drand-only verdict import, the approval-witness-v3 call, the complete collection history and the adoption-at-approval-commit binding; the V19 builder `{E['B19']}` is superseded and retained)", s)
pat=re.compile(r"`test_build_corpus_identity_v19\.py` `[0-9a-f]{64}` \(5 tests, listed in §3c\)")
assert len(pat.findall(s))==1; s=pat.sub(f"`test_build_corpus_identity_v20.py` `{E['TB20']}` (6 tests, listed in §3c; V19's fixture `{E['TB19']}` retained)", s)
pat=re.compile(r"`beacon_record_expedited\.py` `[0-9a-f]{64}` \(V19: V15's `beacon_record\.py` `023c4d7dfd18d2d6818ea09d41e78b44835dc95d20ff4ba69f36c0afd61bbb73` with the property stated in its docstring.{0,900}?the exhibit's reproducibility;")
assert len(pat.findall(s))==1; s=pat.sub(f"`beacon_record_drand.py` `{E['BD']}` (V20: the ONE verdict, drand-only — see §3b (3)–(4); fixture `test_beacon_record_drand.py` `{E['TBD']}`, 6 tests; the V16–V19 module `beacon_record_expedited.py` `{E['BX']}` and its fixture `{E['TBX']}` are superseded and retained;", s)
pat=re.compile(r"DRIVER: `run_configurations_v3\.py`, SHA-256 `[0-9a-f]{64}` \(V19:.{0,600}?as codex found\)")
assert len(pat.findall(s))==1; s=pat.sub(f"DRIVER: `run_configurations_v4.py`, SHA-256 `{E['RC4']}` (V20: V15's `run_configurations.py` `d486ae58f40d220e8d2a9a1d875e008059cdc3bb1d9aee0dffc7dc974c7d53aa` plus the adoption binding, the render-refused sentinel accounting and the SEMANTIC acceptance conjunction of §3c — fixture `test_run_configurations_v4.py` `{E['TRC4']}`, 20 tests; the V19 driver `{E['RC3']}` and its fixture `{E['TRC3']}` are superseded and retained)", s)
s=s.replace("one two-seat gate on this amendment (V19; V16–V18's counted)","one two-seat gate on this amendment (V20; V16–V19's counted)")
open(p,'w').write(s); print("V20 text edited")
