// Generated from frontier_map_v3 (57 clusters, 120,676 papers) + arXiv delta re-rank.
// structure as-of 2026-07-18 (last full re-cluster) · counts current-through the latest arXiv ingest.
// score = citation-activity (all-domain, 0-1); scoreV1 = galaxy-evolution controversy score (CO-vetoed=0).

export type Frontier = {
  cluster: number; name: string; desc: string; size: number; yearMedian: number;
  recentFrac: number; citeMedian: number; nDebates: number; nUnknowns: number;
  score: number; scoreV1: number; tractable: number; keywords: string[]; topic: string | null; topicFlagged: boolean;
};

export const FRONTIERS: Frontier[] = [
  {
    "cluster": 41,
    "name": "JWST high-redshift galaxy evolution and emission",
    "desc": "A galaxy-evolution cluster (1306 papers, median 2021) around Formation, Metallicity, JWST, Redshift, III, Evolution. Contested-measurement rate 0.11.",
    "size": 1306,
    "yearMedian": 2021,
    "recentFrac": 0.421,
    "citeMedian": 46.0,
    "nDebates": 145,
    "nUnknowns": 0,
    "score": 0.957,
    "scoreV1": 0.371,
    "tractable": 1,
    "keywords": [
      "formation",
      "metallicity",
      "jwst",
      "redshift",
      "iii",
      "evolution",
      "emission",
      "survey"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 33,
    "name": "Dark energy models and Hubble tension",
    "desc": "A cosmology cluster (1124 papers, median 2021) around Dark, Energy, Cdm, EDE, Hubble, BAO. Contested-measurement rate 0.44.",
    "size": 1124,
    "yearMedian": 2021,
    "recentFrac": 0.411,
    "citeMedian": 30.0,
    "nDebates": 491,
    "nUnknowns": 0,
    "score": 0.745,
    "scoreV1": 0.0,
    "tractable": 0,
    "keywords": [
      "dark",
      "energy",
      "cdm",
      "ede",
      "hubble",
      "bao",
      "tension",
      "parameter"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 53,
    "name": "Gaia-APOGEE Galactic Chemical Evolution",
    "desc": "A galaxy-evolution cluster (661 papers, median 2021) around Gaia, Chemical, Parameters, Apogee, Spectra, Abundances. Contested-measurement rate 0.05.",
    "size": 661,
    "yearMedian": 2021,
    "recentFrac": 0.339,
    "citeMedian": 24.0,
    "nDebates": 33,
    "nUnknowns": 0,
    "score": 0.633,
    "scoreV1": 0.208,
    "tractable": 1,
    "keywords": [
      "gaia",
      "chemical",
      "parameters",
      "apogee",
      "spectra",
      "abundances",
      "galactic",
      "clusters"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 36,
    "name": "Electroweak phase transition and bubble dynamics",
    "desc": "A cosmology cluster (477 papers, median 2021) around Phase, Electroweak, Gravitational, Transition, Bubble, Higgs. Contested-measurement rate 0.04.",
    "size": 477,
    "yearMedian": 2021,
    "recentFrac": 0.427,
    "citeMedian": 27.0,
    "nDebates": 20,
    "nUnknowns": 0,
    "score": 0.592,
    "scoreV1": 0.0,
    "tractable": 0,
    "keywords": [
      "phase",
      "electroweak",
      "gravitational",
      "transition",
      "bubble",
      "higgs",
      "wave",
      "transitions"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 28,
    "name": "SMBH accretion and gas formation",
    "desc": "A galaxy-evolution cluster (966 papers, median 2018) around Black, Hole, Accretion, Holes, Supermassive, Gas. Contested-measurement rate 0.05.",
    "size": 966,
    "yearMedian": 2018,
    "recentFrac": 0.297,
    "citeMedian": 31.0,
    "nDebates": 52,
    "nUnknowns": 0,
    "score": 0.588,
    "scoreV1": 0.183,
    "tractable": 1,
    "keywords": [
      "black",
      "hole",
      "accretion",
      "holes",
      "supermassive",
      "gas",
      "formation",
      "smbh"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 0,
    "name": "FRB host galaxies and IGM dispersion probes",
    "desc": "A cosmology cluster (441 papers, median 2022) around FRB, FRBs, Radio, Fast, Bursts, Host. Contested-measurement rate 0.10.",
    "size": 441,
    "yearMedian": 2022,
    "recentFrac": 0.463,
    "citeMedian": 20.0,
    "nDebates": 43,
    "nUnknowns": 0,
    "score": 0.577,
    "scoreV1": 0.0,
    "tractable": 0,
    "keywords": [
      "frb",
      "frbs",
      "radio",
      "fast",
      "bursts",
      "host",
      "dispersion",
      "igm"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 15,
    "name": "Lyman-α forest power spectrum in IGM reionization simulations",
    "desc": "A cosmology cluster (544 papers, median 2019) around Reionization, Forest, IGM, Simulations, Lyman-, Redshift. Contested-measurement rate 0.09.",
    "size": 544,
    "yearMedian": 2019,
    "recentFrac": 0.305,
    "citeMedian": 26.0,
    "nDebates": 47,
    "nUnknowns": 0,
    "score": 0.529,
    "scoreV1": 0.0,
    "tractable": 0,
    "keywords": [
      "reionization",
      "forest",
      "igm",
      "simulations",
      "lyman-",
      "redshift",
      "intergalactic",
      "power"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 16,
    "name": "Lyman-alpha escape fraction in high-redshift galaxies",
    "desc": "A galaxy-evolution cluster (896 papers, median 2019) around LAEs, LyC, Escape, Esc, Emission, Lyman. Contested-measurement rate 0.06.",
    "size": 896,
    "yearMedian": 2019,
    "recentFrac": 0.271,
    "citeMedian": 39.0,
    "nDebates": 51,
    "nUnknowns": 0,
    "score": 0.515,
    "scoreV1": 0.161,
    "tractable": 1,
    "keywords": [
      "laes",
      "lyc",
      "escape",
      "esc",
      "emission",
      "lyman",
      "lae",
      "fraction"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 42,
    "name": "Large-scale structure and matter power spectrum from galaxy surveys",
    "desc": "A cosmology cluster (4279 papers, median 2020) around Redshift, Power, Survey, Lensing, Bias, Spectrum. Contested-measurement rate 0.06.",
    "size": 4279,
    "yearMedian": 2020,
    "recentFrac": 0.332,
    "citeMedian": 21.0,
    "nDebates": 247,
    "nUnknowns": 0,
    "score": 0.515,
    "scoreV1": 0.0,
    "tractable": 0,
    "keywords": [
      "redshift",
      "power",
      "survey",
      "lensing",
      "bias",
      "spectrum",
      "surveys",
      "matter"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 23,
    "name": "Fuzzy dark matter solitons",
    "desc": "A cosmology cluster (446 papers, median 2021) around Matter, Dark, FDM, Soliton, SFDM, Ultralight. Contested-measurement rate 0.10.",
    "size": 446,
    "yearMedian": 2021,
    "recentFrac": 0.373,
    "citeMedian": 19.0,
    "nDebates": 45,
    "nUnknowns": 0,
    "score": 0.512,
    "scoreV1": 0.0,
    "tractable": 0,
    "keywords": [
      "matter",
      "dark",
      "fdm",
      "soliton",
      "sfdm",
      "ultralight",
      "fuzzy",
      "bec"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 24,
    "name": "Axion dark matter and ALP phenomenology",
    "desc": "A cosmology cluster (895 papers, median 2021) around Axion, Axions, Dark, Matter, Qcd, Alp. Contested-measurement rate 0.05.",
    "size": 895,
    "yearMedian": 2021,
    "recentFrac": 0.41,
    "citeMedian": 23.0,
    "nDebates": 41,
    "nUnknowns": 0,
    "score": 0.483,
    "scoreV1": 0.0,
    "tractable": 0,
    "keywords": [
      "axion",
      "axions",
      "dark",
      "matter",
      "qcd",
      "alp",
      "alps",
      "axion-photon"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 18,
    "name": "LISA and black hole binary gravitational waves",
    "desc": "A cosmology cluster (3019 papers, median 2021) around Black, Gravitational, Binary, Hole, Binaries, Wave. Contested-measurement rate 0.05.",
    "size": 3019,
    "yearMedian": 2021,
    "recentFrac": 0.388,
    "citeMedian": 26.0,
    "nDebates": 139,
    "nUnknowns": 0,
    "score": 0.478,
    "scoreV1": 0.0,
    "tractable": 0,
    "keywords": [
      "black",
      "gravitational",
      "binary",
      "hole",
      "binaries",
      "wave",
      "gravitational-wave",
      "lisa"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 50,
    "name": "r-process-enhanced metal-poor stars",
    "desc": "A galaxy-evolution cluster (460 papers, median 2020) around r-process, metal-poor, CEMP, Elements, Abundances, Abundance. Contested-measurement rate 0.08.",
    "size": 460,
    "yearMedian": 2020,
    "recentFrac": 0.348,
    "citeMedian": 24.0,
    "nDebates": 37,
    "nUnknowns": 0,
    "score": 0.477,
    "scoreV1": 0.2,
    "tractable": 1,
    "keywords": [
      "r-process",
      "metal-poor",
      "cemp",
      "elements",
      "abundances",
      "abundance",
      "chemical",
      "r-process-enhanced"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 45,
    "name": "Dark matter halo alignments in cosmic filaments",
    "desc": "A cosmology cluster (935 papers, median 2019) around Halo, Haloes, Matter, Dark, Alignment, Filaments. Contested-measurement rate 0.07.",
    "size": 935,
    "yearMedian": 2019,
    "recentFrac": 0.293,
    "citeMedian": 23.0,
    "nDebates": 62,
    "nUnknowns": 0,
    "score": 0.458,
    "scoreV1": 0.0,
    "tractable": 0,
    "keywords": [
      "halo",
      "haloes",
      "matter",
      "dark",
      "alignment",
      "filaments",
      "simulations",
      "alignments"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 13,
    "name": "Tidal Disruption Events and QPEs Around Black Holes",
    "desc": "A galaxy-evolution cluster (691 papers, median 2021) around TDE, TDEs, Disruption, Black, Tidal, Qpes. Contested-measurement rate 0.06.",
    "size": 691,
    "yearMedian": 2021,
    "recentFrac": 0.389,
    "citeMedian": 22.0,
    "nDebates": 43,
    "nUnknowns": 0,
    "score": 0.454,
    "scoreV1": 0.18,
    "tractable": 1,
    "keywords": [
      "tde",
      "tdes",
      "disruption",
      "black",
      "tidal",
      "qpes",
      "hole",
      "qpe"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 52,
    "name": "Milky Way spiral disk kinematics",
    "desc": "A galaxy-evolution cluster (658 papers, median 2019) around Disk, Disc, Galactic, Kpc, Milky, Way. Contested-measurement rate 0.04.",
    "size": 658,
    "yearMedian": 2019,
    "recentFrac": 0.278,
    "citeMedian": 26.0,
    "nDebates": 24,
    "nUnknowns": 0,
    "score": 0.453,
    "scoreV1": 0.135,
    "tractable": 1,
    "keywords": [
      "disk",
      "disc",
      "galactic",
      "kpc",
      "milky",
      "way",
      "velocity",
      "spiral"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 44,
    "name": "Primordial black holes from inflation",
    "desc": "A cosmology cluster (3695 papers, median 2020) around Inflation, PBH, PBHs, Primordial, Black, Inflationary. Contested-measurement rate 0.04.",
    "size": 3695,
    "yearMedian": 2020,
    "recentFrac": 0.313,
    "citeMedian": 25.0,
    "nDebates": 133,
    "nUnknowns": 0,
    "score": 0.449,
    "scoreV1": 0.0,
    "tractable": 0,
    "keywords": [
      "inflation",
      "pbh",
      "pbhs",
      "primordial",
      "black",
      "inflationary",
      "inflaton",
      "holes"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 12,
    "name": "CMB power spectrum and non-Gaussianity from Planck and WMAP",
    "desc": "A cosmology cluster (492 papers, median 2014) around CMB, Planck, Microwave, Wmap, Power, Non-gaussianity. Contested-measurement rate 0.11.",
    "size": 492,
    "yearMedian": 2014,
    "recentFrac": 0.08,
    "citeMedian": 18.0,
    "nDebates": 54,
    "nUnknowns": 0,
    "score": 0.449,
    "scoreV1": 0.0,
    "tractable": 0,
    "keywords": [
      "cmb",
      "planck",
      "microwave",
      "wmap",
      "power",
      "non-gaussianity",
      "temperature",
      "background"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 5,
    "name": "EoR intensity mapping and foreground separation",
    "desc": "A cosmology cluster (1575 papers, median 2020) around Reionization, Signal, Power, Spectrum, EoR, Foreground. Contested-measurement rate 0.03.",
    "size": 1575,
    "yearMedian": 2020,
    "recentFrac": 0.325,
    "citeMedian": 20.0,
    "nDebates": 47,
    "nUnknowns": 0,
    "score": 0.445,
    "scoreV1": 0.0,
    "tractable": 0,
    "keywords": [
      "reionization",
      "signal",
      "power",
      "spectrum",
      "eor",
      "foreground",
      "intensity",
      "epoch"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 40,
    "name": "Massive quiescent galaxy evolution in clusters",
    "desc": "A galaxy-evolution cluster (1796 papers, median 2017) around Formation, Quenching, Quiescent, Massive, Evolution, Star-forming. Contested-measurement rate 0.08.",
    "size": 1796,
    "yearMedian": 2017,
    "recentFrac": 0.217,
    "citeMedian": 32.0,
    "nDebates": 139,
    "nUnknowns": 0,
    "score": 0.438,
    "scoreV1": 0.141,
    "tractable": 1,
    "keywords": [
      "formation",
      "quenching",
      "quiescent",
      "massive",
      "evolution",
      "star-forming",
      "redshift",
      "cluster"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 56,
    "name": "Milky Way halo streams and RR Lyrae stars",
    "desc": "A galaxy-evolution cluster (810 papers, median 2019) around Lyrae, Halo, Stream, Streams, Rrab, Milky. Contested-measurement rate 0.03.",
    "size": 810,
    "yearMedian": 2019,
    "recentFrac": 0.267,
    "citeMedian": 26.0,
    "nDebates": 26,
    "nUnknowns": 0,
    "score": 0.434,
    "scoreV1": 0.123,
    "tractable": 1,
    "keywords": [
      "lyrae",
      "halo",
      "stream",
      "streams",
      "rrab",
      "milky",
      "way",
      "galactic"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 51,
    "name": "Gaia open cluster membership",
    "desc": "A galaxy-evolution cluster (446 papers, median 2021) around Clusters, Cluster, Open, Ngc, Gaia, Ocs. Contested-measurement rate 0.03.",
    "size": 446,
    "yearMedian": 2021,
    "recentFrac": 0.364,
    "citeMedian": 13.5,
    "nDebates": 14,
    "nUnknowns": 0,
    "score": 0.429,
    "scoreV1": 0.148,
    "tractable": 1,
    "keywords": [
      "clusters",
      "cluster",
      "open",
      "ngc",
      "gaia",
      "ocs",
      "members",
      "membership"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 54,
    "name": "Milky Way ultra-faint satellite kinematics",
    "desc": "A galaxy-evolution cluster (426 papers, median 2017) around Dwarf, Milky, Way, Velocity, Ultra-faint, Satellites. Contested-measurement rate 0.07.",
    "size": 426,
    "yearMedian": 2017,
    "recentFrac": 0.242,
    "citeMedian": 40.0,
    "nDebates": 30,
    "nUnknowns": 0,
    "score": 0.411,
    "scoreV1": 0.142,
    "tractable": 1,
    "keywords": [
      "dwarf",
      "milky",
      "way",
      "velocity",
      "ultra-faint",
      "satellites",
      "metallicity",
      "spheroidal"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 35,
    "name": "ALMA SMGs at high redshift",
    "desc": "A galaxy-evolution cluster (1640 papers, median 2018) around Dust, SMGs, Formation, Gas, Emission, Alma. Contested-measurement rate 0.07.",
    "size": 1640,
    "yearMedian": 2018,
    "recentFrac": 0.218,
    "citeMedian": 32.0,
    "nDebates": 113,
    "nUnknowns": 0,
    "score": 0.401,
    "scoreV1": 0.128,
    "tractable": 1,
    "keywords": [
      "dust",
      "smgs",
      "formation",
      "gas",
      "emission",
      "alma",
      "star-forming",
      "redshift"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 22,
    "name": "Strong gravitational lensing and microlensing signatures",
    "desc": "A cosmology cluster (1115 papers, median 2019) around Lens, Lensing, Lenses, Lensed, Strong, Microlensing. Contested-measurement rate 0.08.",
    "size": 1115,
    "yearMedian": 2019,
    "recentFrac": 0.299,
    "citeMedian": 19.0,
    "nDebates": 89,
    "nUnknowns": 0,
    "score": 0.4,
    "scoreV1": 0.0,
    "tractable": 0,
    "keywords": [
      "lens",
      "lensing",
      "lenses",
      "lensed",
      "strong",
      "microlensing",
      "gravitational",
      "images"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 55,
    "name": "Cepheids and TRGB in Magellanic Clouds",
    "desc": "A galaxy-evolution cluster (606 papers, median 2019) around Cepheids, Lmc, Magellanic, Smc, Cepheid, Cloud. Contested-measurement rate 0.09.",
    "size": 606,
    "yearMedian": 2019,
    "recentFrac": 0.278,
    "citeMedian": 23.0,
    "nDebates": 55,
    "nUnknowns": 0,
    "score": 0.378,
    "scoreV1": 0.16,
    "tractable": 1,
    "keywords": [
      "cepheids",
      "lmc",
      "magellanic",
      "smc",
      "cepheid",
      "cloud",
      "distance",
      "trgb"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 31,
    "name": "Massive star mass-loss in RSGs, AGBs, and LBVs",
    "desc": "A galaxy-evolution cluster (543 papers, median 2020) around Rsgs, Agb, Lbv, Lbvs, Mass-loss, Supergiants. Contested-measurement rate 0.08.",
    "size": 543,
    "yearMedian": 2020,
    "recentFrac": 0.343,
    "citeMedian": 18.0,
    "nDebates": 45,
    "nUnknowns": 0,
    "score": 0.371,
    "scoreV1": 0.152,
    "tractable": 1,
    "keywords": [
      "rsgs",
      "agb",
      "lbv",
      "lbvs",
      "mass-loss",
      "supergiants",
      "rsg",
      "massive"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 19,
    "name": "CGM gas and DLA absorption in galactic medium",
    "desc": "A galaxy-evolution cluster (1942 papers, median 2018) around Gas, Cgm, Absorption, Absorbers, Dlas, Dla. Contested-measurement rate 0.07.",
    "size": 1942,
    "yearMedian": 2018,
    "recentFrac": 0.237,
    "citeMedian": 25.0,
    "nDebates": 129,
    "nUnknowns": 0,
    "score": 0.367,
    "scoreV1": 0.127,
    "tractable": 1,
    "keywords": [
      "gas",
      "cgm",
      "absorption",
      "absorbers",
      "dlas",
      "dla",
      "medium",
      "galactic"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 4,
    "name": "Dual AGN and black hole binaries",
    "desc": "A galaxy-evolution cluster (423 papers, median 2019) around AGN, Black, AGN, Binary, Dual, Emission. Contested-measurement rate 0.03.",
    "size": 423,
    "yearMedian": 2019,
    "recentFrac": 0.307,
    "citeMedian": 16.0,
    "nDebates": 11,
    "nUnknowns": 0,
    "score": 0.365,
    "scoreV1": 0.112,
    "tractable": 1,
    "keywords": [
      "agn",
      "black",
      "agns",
      "binary",
      "dual",
      "emission",
      "hole",
      "active"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 27,
    "name": "AGN-driven molecular outflows and emission lines",
    "desc": "A galaxy-evolution cluster (1425 papers, median 2018) around Gas, AGN, Emission, Outflow, Molecular, Outflows. Contested-measurement rate 0.04.",
    "size": 1425,
    "yearMedian": 2018,
    "recentFrac": 0.242,
    "citeMedian": 26.0,
    "nDebates": 52,
    "nUnknowns": 0,
    "score": 0.364,
    "scoreV1": 0.103,
    "tractable": 1,
    "keywords": [
      "gas",
      "agn",
      "emission",
      "outflow",
      "molecular",
      "outflows",
      "line",
      "nucleus"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 17,
    "name": "Jellyfish galaxies and ram pressure stripping in NGC surveys",
    "desc": "A galaxy-evolution cluster (1065 papers, median 2019) around Gas, Formation, Ngc, Rps, Ram, Stripping. Contested-measurement rate 0.04.",
    "size": 1065,
    "yearMedian": 2019,
    "recentFrac": 0.264,
    "citeMedian": 19.0,
    "nDebates": 41,
    "nUnknowns": 0,
    "score": 0.338,
    "scoreV1": 0.106,
    "tractable": 1,
    "keywords": [
      "gas",
      "formation",
      "ngc",
      "rps",
      "ram",
      "stripping",
      "jellyfish",
      "survey"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 46,
    "name": "Barred spiral galaxy formation",
    "desc": "A galaxy-evolution cluster (724 papers, median 2018) around Bar, Bars, Spiral, Barred, Formation, Orbits. Contested-measurement rate 0.04.",
    "size": 724,
    "yearMedian": 2018,
    "recentFrac": 0.255,
    "citeMedian": 18.0,
    "nDebates": 31,
    "nUnknowns": 0,
    "score": 0.337,
    "scoreV1": 0.106,
    "tractable": 1,
    "keywords": [
      "bar",
      "bars",
      "spiral",
      "barred",
      "formation",
      "orbits",
      "disc",
      "arms"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 30,
    "name": "Cosmic strings and domain walls in the early universe",
    "desc": "A cosmology cluster (483 papers, median 2018) around String, Strings, Gravitational, Loops, Walls, Domain. Contested-measurement rate 0.17.",
    "size": 483,
    "yearMedian": 2018,
    "recentFrac": 0.284,
    "citeMedian": 16.0,
    "nDebates": 82,
    "nUnknowns": 0,
    "score": 0.334,
    "scoreV1": 0.0,
    "tractable": 0,
    "keywords": [
      "string",
      "strings",
      "gravitational",
      "loops",
      "walls",
      "domain",
      "nambu-goto",
      "one-scale"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 11,
    "name": "CMB polarization and lensing power spectra",
    "desc": "A cosmology cluster (891 papers, median 2018) around CMB, Polarization, Microwave, Lensing, Background, Power. Contested-measurement rate 0.03.",
    "size": 891,
    "yearMedian": 2018,
    "recentFrac": 0.232,
    "citeMedian": 16.0,
    "nDebates": 26,
    "nUnknowns": 0,
    "score": 0.325,
    "scoreV1": 0.0,
    "tractable": 0,
    "keywords": [
      "cmb",
      "polarization",
      "microwave",
      "lensing",
      "background",
      "power",
      "maps",
      "ghz"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 25,
    "name": "Radio relics and X-ray sloshing in galaxy clusters",
    "desc": "A cosmology cluster (741 papers, median 2018) around Radio, Cluster, Clusters, X-ray, Emission, Abell. Contested-measurement rate 0.07.",
    "size": 741,
    "yearMedian": 2018,
    "recentFrac": 0.267,
    "citeMedian": 21.0,
    "nDebates": 49,
    "nUnknowns": 0,
    "score": 0.322,
    "scoreV1": 0.0,
    "tractable": 0,
    "keywords": [
      "radio",
      "cluster",
      "clusters",
      "x-ray",
      "emission",
      "abell",
      "sloshing",
      "relics"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 21,
    "name": "Radio AGN surveys at GHz and MHz frequencies",
    "desc": "A galaxy-evolution cluster (1213 papers, median 2018) around Radio, Sources, GHz, AGN, Survey, Emission. Contested-measurement rate 0.04.",
    "size": 1213,
    "yearMedian": 2018,
    "recentFrac": 0.243,
    "citeMedian": 20.0,
    "nDebates": 53,
    "nUnknowns": 0,
    "score": 0.321,
    "scoreV1": 0.101,
    "tractable": 1,
    "keywords": [
      "radio",
      "sources",
      "ghz",
      "agn",
      "survey",
      "emission",
      "source",
      "mhz"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 29,
    "name": "AGN X-ray emission and BLR line diagnostics",
    "desc": "A galaxy-evolution cluster (2696 papers, median 2017) around AGN, X-ray, AGN, Emission, Blr, Line. Contested-measurement rate 0.05.",
    "size": 2696,
    "yearMedian": 2017,
    "recentFrac": 0.219,
    "citeMedian": 23.0,
    "nDebates": 131,
    "nUnknowns": 0,
    "score": 0.299,
    "scoreV1": 0.092,
    "tractable": 1,
    "keywords": [
      "agn",
      "x-ray",
      "agns",
      "emission",
      "blr",
      "line",
      "active",
      "bal"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 47,
    "name": "Molecular formation in protostellar disks",
    "desc": "A galaxy-evolution cluster (8936 papers, median 2019) around Molecular, Formation, Gas, Emission, Dust, Protostellar. Contested-measurement rate 0.04.",
    "size": 8936,
    "yearMedian": 2019,
    "recentFrac": 0.25,
    "citeMedian": 20.0,
    "nDebates": 326,
    "nUnknowns": 0,
    "score": 0.291,
    "scoreV1": 0.088,
    "tractable": 1,
    "keywords": [
      "molecular",
      "formation",
      "gas",
      "emission",
      "dust",
      "protostellar",
      "disk",
      "methanol"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 49,
    "name": "Multiple stellar populations in globular clusters",
    "desc": "A galaxy-evolution cluster (957 papers, median 2018) around Globular, Clusters, Cluster, Gcs, Ngc, Populations. Contested-measurement rate 0.05.",
    "size": 957,
    "yearMedian": 2018,
    "recentFrac": 0.22,
    "citeMedian": 21.0,
    "nDebates": 49,
    "nUnknowns": 0,
    "score": 0.283,
    "scoreV1": 0.091,
    "tractable": 1,
    "keywords": [
      "globular",
      "clusters",
      "cluster",
      "gcs",
      "ngc",
      "populations",
      "galactic",
      "abundances"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 26,
    "name": "X-ray cluster surveys and ICM lensing at high redshift",
    "desc": "A cosmology cluster (1216 papers, median 2017) around Clusters, Cluster, X-ray, Gas, Redshift, Survey. Contested-measurement rate 0.10.",
    "size": 1216,
    "yearMedian": 2017,
    "recentFrac": 0.185,
    "citeMedian": 24.0,
    "nDebates": 116,
    "nUnknowns": 0,
    "score": 0.281,
    "scoreV1": 0.0,
    "tractable": 0,
    "keywords": [
      "clusters",
      "cluster",
      "x-ray",
      "gas",
      "redshift",
      "survey",
      "lensing",
      "icm"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 38,
    "name": "Teleparallel gravity and Noether symmetry",
    "desc": "A cosmology cluster (568 papers, median 2018) around Gravity, Teleparallel, Torsion, Scalar, Energy, Matter. Contested-measurement rate 0.07.",
    "size": 568,
    "yearMedian": 2018,
    "recentFrac": 0.266,
    "citeMedian": 25.0,
    "nDebates": 40,
    "nUnknowns": 0,
    "score": 0.263,
    "scoreV1": 0.0,
    "tractable": 0,
    "keywords": [
      "gravity",
      "teleparallel",
      "torsion",
      "scalar",
      "energy",
      "matter",
      "noether",
      "theory"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 32,
    "name": "Galactic dynamo and Faraday polarization",
    "desc": "A galaxy-evolution cluster (941 papers, median 2018) around Magnetic, Field, Dynamo, Faraday, Fields, Polarization. Contested-measurement rate 0.04.",
    "size": 941,
    "yearMedian": 2018,
    "recentFrac": 0.236,
    "citeMedian": 20.0,
    "nDebates": 37,
    "nUnknowns": 0,
    "score": 0.259,
    "scoreV1": 0.078,
    "tractable": 1,
    "keywords": [
      "magnetic",
      "field",
      "dynamo",
      "faraday",
      "fields",
      "polarization",
      "galactic",
      "turbulence"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 7,
    "name": "Type Ia supernova progenitors and explosion mechanisms",
    "desc": "A cosmology cluster (1424 papers, median 2016) around SNe, Type, Supernova, Supernovae, Host, Light. Contested-measurement rate 0.07.",
    "size": 1424,
    "yearMedian": 2016,
    "recentFrac": 0.22,
    "citeMedian": 34.0,
    "nDebates": 96,
    "nUnknowns": 0,
    "score": 0.254,
    "scoreV1": 0.0,
    "tractable": 0,
    "keywords": [
      "sne",
      "type",
      "supernova",
      "supernovae",
      "host",
      "light",
      "progenitor",
      "explosion"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 34,
    "name": "Interacting dark energy scalar field",
    "desc": "A cosmology cluster (769 papers, median 2017) around Dark, Energy, Matter, Interaction, Interacting, Scalar. Contested-measurement rate 0.19.",
    "size": 769,
    "yearMedian": 2017,
    "recentFrac": 0.222,
    "citeMedian": 21.0,
    "nDebates": 147,
    "nUnknowns": 0,
    "score": 0.249,
    "scoreV1": 0.0,
    "tractable": 0,
    "keywords": [
      "dark",
      "energy",
      "matter",
      "interaction",
      "interacting",
      "scalar",
      "constant",
      "field"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 39,
    "name": "Chameleon gravity and dark matter screening",
    "desc": "A cosmology cluster (631 papers, median 2017) around Gravity, Chameleon, Modified, Dark, Matter, Symmetron. Contested-measurement rate 0.06.",
    "size": 631,
    "yearMedian": 2017,
    "recentFrac": 0.214,
    "citeMedian": 25.0,
    "nDebates": 35,
    "nUnknowns": 0,
    "score": 0.24,
    "scoreV1": 0.0,
    "tractable": 0,
    "keywords": [
      "gravity",
      "chameleon",
      "modified",
      "dark",
      "matter",
      "symmetron",
      "screening",
      "field"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 10,
    "name": "PNe emission from AGB circumstellar shells",
    "desc": "A galaxy-evolution cluster (900 papers, median 2019) around Pne, Planetary, Nebulae, Nebula, Emission, Agb. Contested-measurement rate 0.10.",
    "size": 900,
    "yearMedian": 2019,
    "recentFrac": 0.26,
    "citeMedian": 12.0,
    "nDebates": 87,
    "nUnknowns": 0,
    "score": 0.235,
    "scoreV1": 0.093,
    "tractable": 1,
    "keywords": [
      "pne",
      "planetary",
      "nebulae",
      "nebula",
      "emission",
      "agb",
      "circumstellar",
      "lines"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 6,
    "name": "Modified Newtonian Dynamics",
    "desc": "A galaxy-evolution cluster (694 papers, median 2018) around Mond, Newtonian, Matter, Dark, Gravity, Rar. Contested-measurement rate 0.18.",
    "size": 694,
    "yearMedian": 2018,
    "recentFrac": 0.23,
    "citeMedian": 12.0,
    "nDebates": 126,
    "nUnknowns": 0,
    "score": 0.196,
    "scoreV1": 0.116,
    "tractable": 1,
    "keywords": [
      "mond",
      "newtonian",
      "matter",
      "dark",
      "gravity",
      "rar",
      "dynamics",
      "modified"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 48,
    "name": "Globular clusters and ultra-compact dwarfs in galaxy halos",
    "desc": "A galaxy-evolution cluster (542 papers, median 2016) around Gcs, Globular, Ucds, Cluster, Ngc, Clusters. Contested-measurement rate 0.04.",
    "size": 542,
    "yearMedian": 2016,
    "recentFrac": 0.155,
    "citeMedian": 25.0,
    "nDebates": 22,
    "nUnknowns": 0,
    "score": 0.192,
    "scoreV1": 0.047,
    "tractable": 1,
    "keywords": [
      "gcs",
      "globular",
      "ucds",
      "cluster",
      "ngc",
      "clusters",
      "ucd",
      "halo"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 20,
    "name": "Blazar jet emission and flux variability",
    "desc": "A galaxy-evolution cluster (1770 papers, median 2017) around Jet, Blazars, Blazar, Radio, Emission, Ray. Contested-measurement rate 0.03.",
    "size": 1770,
    "yearMedian": 2017,
    "recentFrac": 0.21,
    "citeMedian": 22.0,
    "nDebates": 50,
    "nUnknowns": 0,
    "score": 0.178,
    "scoreV1": 0.044,
    "tractable": 1,
    "keywords": [
      "jet",
      "blazars",
      "blazar",
      "radio",
      "emission",
      "ray",
      "lac",
      "flux"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 37,
    "name": "WIMP dark matter annihilation and Higgs portal searches",
    "desc": "A cosmology cluster (3089 papers, median 2017) around Dark, Matter, Neutrino, Annihilation, Wimp, Dama. Contested-measurement rate 0.06.",
    "size": 3089,
    "yearMedian": 2017,
    "recentFrac": 0.191,
    "citeMedian": 27.0,
    "nDebates": 193,
    "nUnknowns": 0,
    "score": 0.164,
    "scoreV1": 0.0,
    "tractable": 0,
    "keywords": [
      "dark",
      "matter",
      "neutrino",
      "annihilation",
      "wimp",
      "dama",
      "gev",
      "higgs"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 8,
    "name": "SNR dust and radio emission",
    "desc": "A galaxy-evolution cluster (713 papers, median 2017) around Snrs, Snr, Supernova, Emission, Remnant, Dust. Contested-measurement rate 0.03.",
    "size": 713,
    "yearMedian": 2017,
    "recentFrac": 0.202,
    "citeMedian": 16.0,
    "nDebates": 23,
    "nUnknowns": 0,
    "score": 0.154,
    "scoreV1": 0.037,
    "tractable": 1,
    "keywords": [
      "snrs",
      "snr",
      "supernova",
      "emission",
      "remnant",
      "dust",
      "remnants",
      "radio"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 9,
    "name": "Primordial magnetic fields from inflation",
    "desc": "A cosmology cluster (461 papers, median 2016) around Magnetic, Fields, Field, Pmfs, Magnetogenesis, Primordial. Contested-measurement rate 0.04.",
    "size": 461,
    "yearMedian": 2016,
    "recentFrac": 0.167,
    "citeMedian": 18.0,
    "nDebates": 18,
    "nUnknowns": 0,
    "score": 0.151,
    "scoreV1": 0.0,
    "tractable": 0,
    "keywords": [
      "magnetic",
      "fields",
      "field",
      "pmfs",
      "magnetogenesis",
      "primordial",
      "inflation",
      "pmf"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 14,
    "name": "Relativistic backreaction in inhomogeneous cosmology",
    "desc": "A cosmology cluster (842 papers, median 2016) around Relativistic, Universe, Redshift, Ltb, Effects, Backreaction. Contested-measurement rate 0.11.",
    "size": 842,
    "yearMedian": 2016,
    "recentFrac": 0.162,
    "citeMedian": 19.0,
    "nDebates": 93,
    "nUnknowns": 0,
    "score": 0.142,
    "scoreV1": 0.0,
    "tractable": 0,
    "keywords": [
      "relativistic",
      "universe",
      "redshift",
      "ltb",
      "effects",
      "backreaction",
      "newtonian",
      "szekeres"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 3,
    "name": "Millisecond Pulsar Radio Emission in the Galactic Context",
    "desc": "A galaxy-evolution cluster (497 papers, median 2015) around Pulsars, Pulsar, Psr, Msps, Emission, Radio. Contested-measurement rate 0.04.",
    "size": 497,
    "yearMedian": 2015,
    "recentFrac": 0.179,
    "citeMedian": 25.5,
    "nDebates": 21,
    "nUnknowns": 0,
    "score": 0.107,
    "scoreV1": 0.026,
    "tractable": 1,
    "keywords": [
      "pulsars",
      "pulsar",
      "psr",
      "msps",
      "emission",
      "radio",
      "millisecond",
      "galactic"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 43,
    "name": "Quantum bounce in loop cosmology",
    "desc": "A cosmology cluster (550 papers, median 2016) around Quantum, Bounce, Bouncing, Cosmology, Universe, Rip. Contested-measurement rate 0.03.",
    "size": 550,
    "yearMedian": 2016,
    "recentFrac": 0.143,
    "citeMedian": 21.5,
    "nDebates": 17,
    "nUnknowns": 0,
    "score": 0.081,
    "scoreV1": 0.0,
    "tractable": 0,
    "keywords": [
      "quantum",
      "bounce",
      "bouncing",
      "cosmology",
      "universe",
      "rip",
      "scalar",
      "loop"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 1,
    "name": "GRB afterglow and host galaxy evolution",
    "desc": "A cosmology cluster (727 papers, median 2013) around GRB, Grbs, Gamma-ray, Afterglow, Bursts, Host. Contested-measurement rate 0.09.",
    "size": 727,
    "yearMedian": 2013,
    "recentFrac": 0.121,
    "citeMedian": 27.0,
    "nDebates": 65,
    "nUnknowns": 0,
    "score": 0.074,
    "scoreV1": 0.0,
    "tractable": 0,
    "keywords": [
      "grb",
      "grbs",
      "gamma-ray",
      "afterglow",
      "bursts",
      "host",
      "burst",
      "redshift"
    ],
    "topic": null,
    "topicFlagged": false
  },
  {
    "cluster": 2,
    "name": "X-ray ULXs and HMXB/LMXB luminosity sources",
    "desc": "A galaxy-evolution cluster (415 papers, median 2014) around X-ray, Ulx, Ulxs, Sources, Lmxbs, Hmxbs. Contested-measurement rate 0.04.",
    "size": 415,
    "yearMedian": 2014,
    "recentFrac": 0.103,
    "citeMedian": 21.0,
    "nDebates": 18,
    "nUnknowns": 0,
    "score": 0.041,
    "scoreV1": 0.013,
    "tractable": 1,
    "keywords": [
      "x-ray",
      "ulx",
      "ulxs",
      "sources",
      "lmxbs",
      "hmxbs",
      "source",
      "luminosity"
    ],
    "topic": null,
    "topicFlagged": false
  }
];
