#!/usr/bin/env python3
"""Increment-1 adapter: map the 57-cluster frontier_map_v3_reranked.json (score_v1, keywords,
strict_tension...) into the frontend Frontier[] TS shape used by frontiersData.ts —
repaying the 2-snapshot lineage debt (live map is an older 32-cluster/12k snapshot).
Writes to a STAGING file for review; does NOT overwrite the live frontiersData.ts.
Names/descs are keyword-derived (LLM polish is a follow-up). Surfaces two honest
dates: structure-as-of (last re-cluster) and counts-current-through (last ingest)."""
import json, os, glob
ENG=os.path.dirname(os.path.abspath(__file__))
m=json.load(open(f"{ENG}/frontier_map_v3_reranked.json")); cl=m["clusters"]
cmeta=json.load(open(f"{ENG}/centroids_meta.json")) if os.path.exists(f"{ENG}/centroids_meta.json") else {}
# counts-current-through = latest ingested paper date in the delta store (else structure date)
current="2026-07-18"; dl=f"{ENG}/delta/new_papers.jsonl"
if os.path.exists(dl):
    ys=[json.loads(l).get("year") for l in open(dl)]; current="post-2026-07-18 (delta store active)"
def title(kws): return " · ".join(k.capitalize() for k in kws[:3])
def desc(c):
    kws=", ".join(c["keywords"][:6]); scope="galaxy-evolution" if c["ga_frac"]>=c["co_frac"] else "cosmology"
    return (f"A {scope} cluster ({c['size']} papers, median {c['year_median']}) around {kws}. "
            f"Contested-measurement rate {c['strict_tension']:.2f}; tractable={'yes' if c['tractable'] else 'no'}.")
rows=[]
for c in sorted(cl,key=lambda x:-x["score_v1"]):
    rows.append({"cluster":c["cluster"],"name":title(c["keywords"]),"desc":desc(c),
        "size":c["size"],"yearMedian":c["year_median"],"recentFrac":round(c["recent_frac"],3),
        "citeMedian":c["cite_median"],"nDebates":int(round(c["strict_tension"]*c["size"])),
        "nUnknowns":0,"score":round(c["score_v1"],3),"keywords":c["keywords"],
        "topic":None,"topicFlagged":False})
ts=("// STAGING — generated by gen_frontiers_data.py from frontier_map_v3_reranked.json (57 clusters, 120,676 papers).\n"
    f"// structure as-of: {cmeta.get('structure_as_of','2026-07-18')} (last full re-cluster) · counts current-through: {current}.\n"
    "// Review before replacing the live frontiersData.ts (32-cluster snapshot). Names/descs keyword-derived; topic links need remapping.\n\n"
    "export type Frontier = {\n  cluster: number; name: string; desc: string; size: number; yearMedian: number;\n"
    "  recentFrac: number; citeMedian: number; nDebates: number; nUnknowns: number;\n"
    "  score: number; keywords: string[]; topic: string | null; topicFlagged: boolean;\n};\n\n"
    "export const FRONTIERS: Frontier[] = "+json.dumps(rows,indent=2)+";\n")
open(f"{ENG}/frontiersData.v3.staging.ts","w").write(ts)
print(f"wrote frontiersData.v3.staging.ts — {len(rows)} clusters (was 32), sorted by score_v1")
print("top 6 frontiers (score · name):")
for r in rows[:6]: print(f"  {r['score']:.3f}  C{r['cluster']:<2} {r['name']}  (nDebates={r['nDebates']}, size={r['size']})")
print("\nFREEZE NOTE: rank_frontiers_v3 must reuse v1_constants from the snapshot, not recompute per run:")
print("  v1_constants =", json.dumps(m["v1_constants"]))
