import pathlib,json,ast
W=pathlib.Path(__file__).resolve().parent; H=W.parent; lane=H.parent
C=' '.join((lane/'R3C2_D1_D7_CANDIDATE_CLAUSES_20260906.md').read_text().replace('\n> ',' ').split())
B=' '.join((lane/'R3C2_BATCH_PREPARATION_UNADOPTED_20260906.md').read_text().split())
items=[
('Codex 1','C',"The reconciliation (`R3C2_CANDIDATE_REVIEW_RECONCILIATION_20260906.md`) lists the intended repairs by topic; revision 2 implemented many of them and this revision 3 implements the round-2 residuals (a seedless selection bypass, an import re-filed under another reason code, a symbol floor that failed open, join not checking orphan claims, input-id form or the predecessor chain, pin-sheet path form, counts, and the sentence replacements both reviewers required). Remaining limits are custody matters the clauses state as such.",False,'Overclaims closure: printed counts and output vocabulary remain wrong; executable gaps are not solely custody.'),
('Codex 2','C',"For eligible imports the intended status, origin and value agree; the evidence records differ (which file and line `origin_evidence` names), and wording A needs the same explicit eligibility and locator rules before equivalence beyond these examples can be claimed.",True,'Accurately limits equivalence; A remains unstaged.'),
('Codex 3','C',"Whether the quotation cites THAT value is seat judgement; the second seat and C6 may detect an error, but can share it, and C6 re-classifies inputs only for selected claims.",True,'Accurate semantic and sampling limits.'),
('Codex 4','C',"Revision 2 added controls for these cases; round 2 found a seedless-selection bypass (a selection without a seed skipped recomputation and a zero-claim audit passed) and a vocabulary gap, repaired in revision 3 with their controls; census and seal authenticity also depend on custody.",False,'Seedless case repaired; vocabulary only partly repaired: omission result strings still differ.'),
('Codex 5','C',"`CENSUS_COMPLETE` and `CENSUS_PARTIAL` then require a run record supporting enumeration before ledger exposure and re-derivation commitment before release, in addition to the repaired machine checks.",True,'Accurate conditional run-record requirement, not evidence that a run occurred.'),
('Codex 6','C',"A PASS accompanied by satisfactory dispatch and release evidence supports the intended independent enumeration and blind re-derivation; shared error and prior exposure remain possible; it is bounded evidence, not proof of corpus completeness.",True,'Accurately qualified.'),
('Codex 7','C',"**D7 in code** (`audit seal-enumeration | select | handout | seal-rederivation | compare`): implements the clause's stages; the exposure chronology itself is custody, verified by the dispatch and release record, not by these commands (`handout` reads the sealed candidates and therefore runs only in the custodian's hands).",True,'Accurate as a description of stages and custody; does not establish full output-schema conformance.'),
('Codex 8','B',"Batch 1 is light but not the lightest (batches 9 and 11 are smaller on both measures); a light first batch confirms less about capacity than a heavy one would — a heavier first batch is the stronger pilot, at a higher risk of the failure it is testing for.",True,'Merged with Kimi F6; pinned table confirms both smaller batches. Pilot comparison is a workload rationale, not a measured success probability.'),
('Codex 9','B',"The pinned partition implementation deterministically computes these bytes from this manifest and 12; identical serialization and implementation are required for byte equality (kimi recomputed it byte-identical with the pinned code).",True,'Correct reproducibility qualification; Kimi attribution matches its prior report.'),
('Codex 10','B',"Whole-text ownership preserves a claim's local context; cross-batch imports are not blocked by withheld evidence if each dispatch supplies and verifies all manifest texts as required — a dispatch check recording the availability and byte verification of all 89 texts per session is part of the run plan, since final ownership coverage alone does not verify earlier reference access, and neither coverage nor join verifies the lookup logs.",True,'Correct conditional access and logging limits.'),
('Codex 11','B',"The comparison code is unchanged; sections 1 and 3 require equivalent evidence access and global identifiers; dispatch checks and the repaired join must verify their implementation.",True,'Accurate in context: batching uses the same audit comparator; not a claim that D7 code never changed between revisions.'),
('Codex 12','B',"Per-claim outcomes and classes use the operative rules explicitly accepted for this run, including any accepted D1/D2 changes, over the validated joined files.",True,'Correctly names conditional operative rules instead of asserting V23 identity.'),
('Codex 13','B',"It is the difference between a census that could not run (one observed failure) and one that might — whether it can run is what batch 1 is designed to test.",True,'Merged with Kimi F7; limits inference to the recorded failure and proposed test.'),
('Codex 14','B',"(Blocks a first run on the evidence of the limb-B death finding: the unbatched seat died; whether this batching is the remedy is what batch 1 tests; the principal may choose another workable execution design.)",True,'No universal impossibility or exclusive-remedy claim remains.'),
('Kimi F6','B',"Batch 1 is light but not the lightest (batches 9 and 11 are smaller on both measures); a light first batch confirms less about capacity than a heavy one would — a heavier first batch is the stronger pilot, at a higher risk of the failure it is testing for.",True,'Same merged replacement as Codex 8.'),
('Kimi F7','B',"It is the difference between a census that could not run (one observed failure) and one that might — whether it can run is what batch 1 is designed to test.",True,'Same merged replacement as Codex 13; its second requested sentence is quoted under Codex 14.')]
for label,doc,quote,accurate,why in items:
    assert quote in (C if doc=='C' else B),label
    print(label+': FOUND; '+('ACCURATE' if accurate else 'INACCURATE'))
disclosure='what landed is the deterministic first-line rule — no seat discretion, no `ORIGIN_DISPUTED` case, no others-listed requirement'
assert disclosure in C; print('DESIGNATED_LOCATOR_DISCLOSURE=FOUND')
assert 'the seals fix WHAT was committed, the dispatch record — inventoried and access-proven like the seats\' — fixes WHEN, relative to release' in C
assert 'prior exposure cannot be excluded' in C
tree=ast.parse((H/'r3c2_ledger_tools_STAGED.py').read_text()); handout=next(n for n in tree.body if isinstance(n,ast.FunctionDef) and n.name=='cmd_audit_handout')
assert any(isinstance(n,ast.Call) and isinstance(n.func,ast.Name) and n.func.id=='sha' for n in ast.walk(tree))
assert 'Path(sc).read_text()' in ast.get_source_segment((H/'r3c2_ledger_tools_STAGED.py').read_text(),handout)
hd=json.loads((W/'audit/handout.json').read_text()); assert all(set(r)=={'claim_id','source_file','source_line'} for r in hd)
print('CUSTODY_FLOOR=FOUND; HANDOUT_READS_SEALED_CANDIDATES=True; HANDOUT_FIELDS=claim_id/source_file/source_line')
p=json.loads((H/'partition_12_of_89.json').read_text()); bs={b['batch']:b for b in p['batches']}
for k in [1,9,11]: print('BATCH_%d bytes=%d nonblank_lines=%d'%(k,bs[k]['bytes'],bs[k]['nonblank_lines']))
for k in [9,11]: assert all(bs[k][m]<bs[1][m] for m in ['bytes','nonblank_lines'])
print('CANDIDATE_PRINTED_CONTROLS_84='+str('controls=84 passed=84 failed=0' in C)); print('BATCH_PRINTED_CONTROLS_102='+str('controls=102 passed=102 failed=0' in B))
(W/'sentence_results.json').write_text(json.dumps(items,indent=1))
