#!/usr/bin/env python3
from __future__ import annotations

import argparse
import html
import importlib.util
import json
import os
import time
import urllib.request
from pathlib import Path
from typing import Any

from googleapiclient.errors import HttpError
from googleapiclient.http import MediaFileUpload

ROOT = Path(__file__).resolve().parent
LOCAL_HANDOFF = ROOT / "CANARY_LOCAL_HANDOFF.json"
DETERMINISTIC_QA = ROOT / "qa/deterministic_qa.json"
VISUAL_QA = ROOT / "qa/visual_qa.json"
V2_PUBLISHER = Path("/Users/duhokim/NebulaMind/NebulaMind/.hermes/handoffs/paper-videos-v2-20260723T034035Z/publish_paper_videos_v2.py")
CHANNEL_ID = "UCUHBNGk8ozEnisQRuchoS4Q"
OLD_V3_ID_CONTEXT_ONLY = "unxDehCBlqQ"
CAPTION_NAME = "English (manual V4)"
CHECKPOINT = ROOT / "youtube_publication_checkpoint.json"
PREFLIGHT = ROOT / "youtube_publication_preflight.json"
RECEIPT = ROOT / "youtube_publication_receipt.json"
TITLE = "NebulaMind Paper: The z≈9–10 Unlensed Metallicity Deficit | Introduction + Evidence V4"
DESCRIPTION = """A question-first, evidence-led V4 explanation of why five unlensed galaxies at redshift 9–10 appear oxygen-poor relative to nearby galaxies of the same stellar mass.

The video reads the paper's real mass–metallicity plot, compares two local benchmarks, checks an independent stack of roughly 1,500 galaxies, and separates the robust direction from the systematics-limited effect size.

Natural-paced Michael narration with a fictional male presenter and exact-audio lip-sync; manual English captions included.

Read the current manuscript: https://nebulamind.net/studies/z9-10-unlensed-metallicity-deficit.pdf

Machine-generated by an autonomous research pipeline; descriptive, not validated; automated review is not journal or human peer review. This is not a formal statistical detection.

NebulaMind Lab (autonomous run)
#Astronomy #GalaxyEvolution #JWST #NebulaMind"""


def load_v2_module() -> Any:
    spec = importlib.util.spec_from_file_location("v2pub", V2_PUBLISHER)
    if spec is None or spec.loader is None:
        raise RuntimeError("could not load proven YouTube publisher primitives")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


v2pub = load_v2_module()


def atomic_json(path: Path, value: dict[str, Any]) -> None:
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(json.dumps(value, indent=2, ensure_ascii=False) + "\n")
    os.replace(temporary, path)


def load_locked_inputs() -> dict[str, Any]:
    handoff = json.loads(LOCAL_HANDOFF.read_text())
    deterministic = json.loads(DETERMINISTIC_QA.read_text())
    visual = json.loads(VISUAL_QA.read_text())
    if handoff.get("marker") != "NEBULAMIND_V4_Z9_LOCAL_CANARY_HANDOFF_COMPLETE" or "PASS" not in handoff.get("status", ""):
        raise RuntimeError("local V4 handoff is not complete")
    if deterministic.get("marker") != "NEBULAMIND_V4_Z9_DETERMINISTIC_QA_PASS" or any(value != "PASS" for value in deterministic.get("checks", {}).values()):
        raise RuntimeError("deterministic QA is not complete")
    if visual.get("marker") != "NEBULAMIND_V4_Z9_ENCODED_VISUAL_QA_PASS" or visual.get("overall") != "PASS":
        raise RuntimeError("encoded visual QA is not complete")
    video = Path(handoff["artifact"]["path"])
    srt = Path(handoff["captions"]["path"])
    if not video.is_file() or not srt.is_file():
        raise FileNotFoundError("locked video or SRT is missing")
    if v2pub.sha256(video) != handoff["artifact"]["sha256"] or v2pub.sha256(srt) != handoff["captions"]["sha256"]:
        raise RuntimeError("locked upload hash drift")
    if handoff["artifact"]["duration_seconds"] > 180.0:
        raise RuntimeError("duration no longer satisfies signed V4 cap")
    if len(TITLE) > 100 or len(DESCRIPTION) > 5000:
        raise RuntimeError("YouTube metadata length overflow")
    boundary = "Machine-generated by an autonomous research pipeline; descriptive, not validated; automated review is not journal or human peer review. This is not a formal statistical detection."
    if boundary not in DESCRIPTION:
        raise RuntimeError("description is missing the exact status boundary")
    return {"handoff": handoff, "deterministic": deterministic, "visual": visual, "video": video, "srt": srt}


def checkpoint_for(inputs: dict[str, Any]) -> dict[str, Any]:
    handoff = inputs["handoff"]
    if CHECKPOINT.is_file():
        checkpoint = json.loads(CHECKPOINT.read_text())
        if checkpoint.get("source_sha256") not in {None, "", handoff["artifact"]["sha256"]}:
            raise RuntimeError("checkpoint source hash conflicts with locked artifact")
        if checkpoint.get("caption_sha256") not in {None, "", handoff["captions"]["sha256"]}:
            raise RuntimeError("checkpoint caption hash conflicts with locked SRT")
        if checkpoint.get("title") not in {None, "", TITLE}:
            raise RuntimeError("checkpoint title conflicts with intended metadata")
    else:
        checkpoint = {}
    checkpoint.update({
        "key": "z9-metallicity-v4",
        "source": str(inputs["video"]),
        "source_sha256": handoff["artifact"]["sha256"],
        "source_bytes": handoff["artifact"]["bytes"],
        "caption": str(inputs["srt"]),
        "caption_sha256": handoff["captions"]["sha256"],
        "title": TITLE,
        "description": DESCRIPTION,
        "expected_duration": handoff["artifact"]["duration_seconds"],
        "old_v3_id_context_only": OLD_V3_ID_CONTEXT_ONLY,
        "video_id": checkpoint.get("video_id", ""),
        "url": checkpoint.get("url", ""),
        "caption_id": checkpoint.get("caption_id", ""),
        "privacy": checkpoint.get("privacy", "local"),
        "processing": checkpoint.get("processing", "not_uploaded"),
        "status": checkpoint.get("status", "LOCAL_QA_COMPLETE"),
    })
    atomic_json(CHECKPOINT, checkpoint)
    return checkpoint


def upload_once(youtube: Any, video: Path) -> str:
    request = youtube.videos().insert(
        part="snippet,status",
        body={
            "snippet": {
                "title": TITLE,
                "description": DESCRIPTION,
                "categoryId": "28",
                "defaultLanguage": "en",
                "defaultAudioLanguage": "en",
                "tags": [
                    "NebulaMind", "astronomy", "galaxy evolution", "JWST",
                    "metallicity", "plain language", "scientific explainer",
                    "evidence plot", "male presenter",
                ],
            },
            "status": {
                "privacyStatus": "unlisted",
                "selfDeclaredMadeForKids": False,
                "embeddable": True,
            },
        },
        media_body=MediaFileUpload(str(video), chunksize=8 * 1024 * 1024, resumable=True),
    )
    response = None
    failures = 0
    while response is None:
        try:
            status, response = request.next_chunk()
            if status:
                print(f"upload {int(status.progress() * 100)}%", flush=True)
        except HttpError as exc:
            if exc.resp.status not in v2pub.RETRIABLE or failures >= 5:
                raise
            time.sleep(2**failures)
            failures += 1
    return response["id"]


def caption_rows(youtube: Any, video_id: str) -> list[dict[str, Any]]:
    return youtube.captions().list(part="snippet", videoId=video_id).execute().get("items", [])


def ensure_caption(youtube: Any, srt: Path, video_id: str, checkpoint: dict[str, Any]) -> tuple[str, str]:
    matches = [
        item for item in caption_rows(youtube, video_id)
        if item["snippet"].get("language") == "en" and item["snippet"].get("name") == CAPTION_NAME
    ]
    if len(matches) > 1:
        raise RuntimeError(f"duplicate V4 manual captions on {video_id}")
    if matches:
        caption = matches[0]
    else:
        caption = youtube.captions().insert(
            part="snippet",
            body={"snippet": {
                "videoId": video_id,
                "language": "en",
                "name": CAPTION_NAME,
                "isDraft": False,
            }},
            media_body=MediaFileUpload(str(srt), mimetype="application/x-subrip", resumable=False),
        ).execute()
        checkpoint["caption_id"] = caption["id"]
        checkpoint["caption_inserted_at"] = v2pub.now()
        atomic_json(CHECKPOINT, checkpoint)
    caption_id = caption["id"]
    deadline = time.time() + 300
    while time.time() < deadline:
        current = [item for item in caption_rows(youtube, video_id) if item["id"] == caption_id]
        if current:
            status = current[0]["snippet"].get("status")
            if status == "serving":
                return caption_id, status
            if status == "failed":
                raise RuntimeError(f"caption failed for {video_id}")
        time.sleep(6)
    raise TimeoutError(f"caption serving timeout for {video_id}")


def signed_out_watch(video_id: str) -> dict[str, Any]:
    url = f"https://www.youtube.com/watch?v={video_id}"
    request = urllib.request.Request(url, headers={"User-Agent": "NebulaMind-publication-verifier/4.0"})
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            body = html.unescape(response.read(4 * 1024 * 1024).decode("utf-8", errors="replace"))
            return {
                "url": url,
                "http_status": response.status,
                "title_present": TITLE in body,
                "video_id_present": video_id in body,
                "playability_ok_present": '"playabilityStatus":{"status":"OK"' in body,
            }
    except Exception as exc:
        return {"url": url, "error": f"{type(exc).__name__}: {exc}"}


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--execute", action="store_true", help="perform the explicitly approved upload, caption, and public transaction")
    args = parser.parse_args()
    inputs = load_locked_inputs()
    checkpoint = checkpoint_for(inputs)
    youtube = v2pub.service()
    uploads = v2pub.channel_uploads(youtube)
    owned = v2pub.inventory(youtube, uploads)
    exact_matches = [item for item in owned if item["title"] == TITLE]
    version_context = [item for item in owned if "z≈9–10 Unlensed Metallicity Deficit" in item["title"]]
    video_id = checkpoint.get("video_id", "")
    if video_id:
        if not any(item["id"] == video_id for item in owned):
            raise RuntimeError("checkpoint video ID is absent from owned-channel inventory")
        if exact_matches and video_id not in [item["id"] for item in exact_matches]:
            raise RuntimeError("checkpoint conflicts with exact-title inventory")
    elif exact_matches:
        raise RuntimeError(f"exact-title duplicate collision: {exact_matches}")
    preflight = {
        "marker": "NEBULAMIND_V4_Z9_YOUTUBE_PREFLIGHT_PASS",
        "checked_at_utc": v2pub.now(),
        "channel_id": CHANNEL_ID,
        "execute": args.execute,
        "title": TITLE,
        "title_length": len(TITLE),
        "description_length": len(DESCRIPTION),
        "source": str(inputs["video"]),
        "source_sha256": inputs["handoff"]["artifact"]["sha256"],
        "caption": str(inputs["srt"]),
        "caption_sha256": inputs["handoff"]["captions"]["sha256"],
        "checkpoint_video_id": video_id,
        "exact_title_matches": exact_matches,
        "older_version_context": version_context,
        "old_v3_mutations": False,
        "other_video_mutations": False,
        "website_mutations": False,
        "git_mutations": False,
        "runtime_mutations": False,
    }
    atomic_json(PREFLIGHT, preflight)
    if not args.execute:
        print(json.dumps(preflight, indent=2, ensure_ascii=False))
        return

    if not video_id:
        print("z9-v4: uploading once as unlisted", flush=True)
        try:
            video_id = upload_once(youtube, inputs["video"])
        except Exception:
            refreshed = v2pub.inventory(youtube, uploads)
            candidates = [item for item in refreshed if item["title"] == TITLE]
            checkpoint.update({"status": "UPLOAD_AMBIGUOUS_STOPPED", "ambiguous_candidates": candidates, "last_checked_at": v2pub.now()})
            atomic_json(CHECKPOINT, checkpoint)
            raise
        checkpoint.update({
            "video_id": video_id,
            "url": f"https://youtu.be/{video_id}",
            "privacy": "unlisted",
            "processing": "uploaded_processing",
            "status": "UNLISTED_PROCESSING",
            "uploaded_at": v2pub.now(),
        })
        atomic_json(CHECKPOINT, checkpoint)

    state = v2pub.wait_processing(youtube, video_id)
    if state["title"] != TITLE or state["description"] != DESCRIPTION:
        raise RuntimeError("server metadata mismatch")
    if state["privacy"] != "unlisted" or state["embeddable"] is not True or state["selfDeclaredMadeForKids"] is not False:
        raise RuntimeError(f"unsafe unlisted state: {state}")
    if abs(v2pub.parse_iso_duration(state["duration"]) - float(inputs["handoff"]["artifact"]["duration_seconds"])) > 2.0:
        raise RuntimeError(f"server duration mismatch: {state['duration']}")
    checkpoint.update({"privacy": "unlisted", "processing": "succeeded", "status": "UNLISTED_PROCESSING_SUCCEEDED", "server_state": state, "verified_at": v2pub.now()})
    atomic_json(CHECKPOINT, checkpoint)
    print(f"z9-v4: unlisted processing succeeded {video_id}", flush=True)

    caption_id, caption_status = ensure_caption(youtube, inputs["srt"], video_id, checkpoint)
    checkpoint.update({
        "caption_id": caption_id,
        "caption_status": caption_status,
        "status": "UNLISTED_CAPTIONS_SERVING",
        "caption_verified_at": v2pub.now(),
    })
    atomic_json(CHECKPOINT, checkpoint)
    print("z9-v4: manual V4 captions serving", flush=True)

    gate_state = v2pub.video_state(youtube, video_id)
    serving = [
        item for item in caption_rows(youtube, video_id)
        if item["id"] == caption_id and item["snippet"].get("status") == "serving"
    ]
    if gate_state["privacy"] != "unlisted" or gate_state["processing"] != "succeeded" or not serving:
        raise RuntimeError("final public gate failed")
    v2pub.set_public(youtube, video_id)
    settlement = v2pub.sustained_public(youtube, video_id)
    checkpoint.update({
        "privacy": "public",
        "processing": "succeeded",
        "caption_status": "serving",
        "status": "PUBLIC_PROCESSING_SUCCEEDED_MANUAL_CAPTIONS_SERVING",
        "published_at": checkpoint.get("published_at") or v2pub.now(),
        "settlement": settlement,
    })
    atomic_json(CHECKPOINT, checkpoint)

    final_state = v2pub.video_state(youtube, video_id)
    final_captions = caption_rows(youtube, video_id)
    caption_match = [item for item in final_captions if item["id"] == caption_id and item["snippet"].get("status") == "serving"]
    if final_state["privacy"] != "public" or final_state["processing"] != "succeeded" or final_state["embeddable"] is not True or not caption_match:
        raise RuntimeError("final owner-state verification failed")
    external = v2pub.oembed(video_id, TITLE)
    watch = signed_out_watch(video_id)
    receipt = {
        "marker": "NEBULAMIND_V4_Z9_YOUTUBE_PUBLICATION_COMPLETE",
        "completed_at_utc": v2pub.now(),
        "channel_id": CHANNEL_ID,
        "id": video_id,
        "url": checkpoint["url"],
        "title": final_state["title"],
        "description": final_state["description"],
        "privacy": final_state["privacy"],
        "processing": final_state["processing"],
        "embeddable": final_state["embeddable"],
        "duration": final_state["duration"],
        "caption_id": caption_id,
        "caption_name": CAPTION_NAME,
        "caption_status": "serving",
        "source": str(inputs["video"]),
        "source_sha256": inputs["handoff"]["artifact"]["sha256"],
        "source_bytes": inputs["handoff"]["artifact"]["bytes"],
        "caption": str(inputs["srt"]),
        "caption_sha256": inputs["handoff"]["captions"]["sha256"],
        "settlement": settlement,
        "oembed": external,
        "signed_out_watch": watch,
        "old_v3_id_unchanged": OLD_V3_ID_CONTEXT_ONLY,
        "old_v3_mutations": False,
        "other_video_mutations": False,
        "website_mutations": False,
        "cockpit_mutations": False,
        "database_mutations": False,
        "git_mutations": False,
        "runtime_mutations": False,
    }
    atomic_json(RECEIPT, receipt)
    print(json.dumps(receipt, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
