# Snapshot from an executed defect-only run on 2026-09-07T09:55:23.420254+09:00
# Frozen reviewed data; snapshot from the implementation, not independently derived.
# Authoring this snapshot does not constitute review or sign-off by its author.

DECLARED = {'adoption': {'adoption': [['LOCAL-TERMINAL', 'ADOPTION-MISMATCH', 'S0h-adoption']],
              'adoption-identity': [['LOCAL-TERMINAL', 'IDENTITY-RULE-DIGEST', 'S0h-adoption']],
              'conjunction': [['LOCAL-TERMINAL', 'ADOPTION-MISMATCH', 'S1-conjunction']],
              'seed': [['LOCAL-TERMINAL', 'REDERIVE-REFUSE-RULE-DIGEST', 'S4-seed']]},
 'adoption-identity': {'adoption-identity': [['LOCAL-TERMINAL', 'IDENTITY-RULE-DIGEST', 'S0h-adoption']],
                       'conjunction': [['LOCAL-TERMINAL', 'IDENTITY-RULE-DIGEST', 'S1-conjunction']]},
 'approval-delivery': {'approval-delivery': [['LOCAL-TERMINAL', 'EVENT-INCONSISTENT', 'S0d-delivery']],
                       'approval-live': [['LOCAL-TERMINAL', 'EVENT-INCONSISTENT', 'S3a-approval']],
                       'conjunction': [['LOCAL-TERMINAL', 'EVENT-INCONSISTENT', 'S1-conjunction']]},
 'approval-live': {'approval-live': [['FORGED', 'EVENT-FORGED', 'S3a-approval']]},
 'approval-local': {'approval-live': [['LOCAL-TERMINAL', 'EVENT-INCONSISTENT', 'S3a-approval']],
                    'approval-local': [['LOCAL-TERMINAL', 'EVENT-INCONSISTENT', 'S0c-identity']]},
 'conjunction': {'conjunction': [['LOCAL-TERMINAL', 'IDENTITY-LOCK-MISMATCH', 'S1-conjunction']]},
 'history-remote': {'history-remote': [['DERIVED-TERMINAL', 'HISTORY-CONTINUATION', 'S5-history']]},
 'history-working-tree': {'conjunction': [['LOCAL-TERMINAL', 'COLLECTION-LOG-DIGEST', 'S1-conjunction']],
                          'history-working-tree': [['DERIVED-TERMINAL',
                                                    'HISTORY-CONTINUATION',
                                                    'S5-history']]},
 'identity-local': {'conjunction': [['LOCAL-TERMINAL', 'IDENTITY-POOL-DIGEST', 'S1-conjunction']],
                    'identity-local': [['LOCAL-TERMINAL', 'IDENTITY-POOL-DIGEST', 'S0f-integrity']]},
 'identity-time-order': {'conjunction': [['LOCAL-TERMINAL', 'IDENTITY-T-PULSE', 'S1-conjunction']],
                         'identity-time-order': [['LOCAL-TERMINAL',
                                                  'IDENTITY-WITNESS-LATE',
                                                  'S0f-integrity']]},
 'lists': {'lists': [['LOCAL-TERMINAL', 'IDENTITY-tuning_objids-SIZE-OR-TYPE', 'S0e-lists']]},
 'nonce': {'conjunction': [['LOCAL-TERMINAL', 'NONCE-UNAUTHENTICATED', 'S1-conjunction']],
           'nonce': [['LOCAL-TERMINAL', 'NONCE-UNAUTHENTICATED', 'S0g-nonce']]},
 'open-delivery-auth': {'open-delivery-auth': [['LOCAL-TERMINAL', 'HISTORY-CONTINUATION', 'S5-history'],
                                               ['LOCAL-TERMINAL', 'HISTORY-CONTINUATION', 'S5-history']],
                        'open-same-id': [['FORGED',
                                          'HISTORY-CONTINUATION: OPEN-EVENT-FORGED',
                                          'S3b-open-same-id']]},
 'open-local': {'open-delivery-auth': [['LOCAL-TERMINAL', 'HISTORY-CONTINUATION', 'S5-history']],
                'open-local': [['LOCAL-TERMINAL',
                                'HISTORY-CONTINUATION: OPEN-EVENT-INCONSISTENT-INPUT',
                                'S0a-open']],
                'open-same-id': [['FORGED', 'HISTORY-CONTINUATION: OPEN-EVENT-FORGED', 'S3b-open-same-id']]},
 'open-same-id': {'open-delivery-auth': [['FORGED', 'HISTORY-CONTINUATION', 'S5-history']],
                  'open-same-id': [['FORGED', 'HISTORY-CONTINUATION: OPEN-EVENT-FORGED', 'S3b-open-same-id']],
                  'per-entry': [['DERIVED-TERMINAL', 'HISTORY-CONTINUATION', 'S5-history']]},
 'per-entry': {'per-entry': [['DERIVED-TERMINAL', 'HISTORY-CONTINUATION', 'S5-history'],
                             ['DERIVED-TERMINAL', 'HISTORY-CONTINUATION', 'S5-history'],
                             ['RETRY-INCOMPLETE', 'RETRY-HISTORY-CONTINUATION', 'S5-history']]},
 'seed': {'seed': [['RETRY-UNAVAILABLE', 'REDERIVE-RETRY', 'S4-seed']]}}
