#!/usr/bin/env python3
"""GENERATED RECORD of what beacon_v2 was OBSERVED to do (prose is written from this, never before it). Runs the live-sample authentication,
the fixture suites, the negative probes, and inspects the builder's validator source; writes BEACON_V2_OBSERVED_BEHAVIOUR_<date>.md."""
import json, subprocess, sys, time, inspect, importlib.util
from pathlib import Path
from datetime import datetime, timezone
HERE = Path(__file__).resolve().parent; sys.path.insert(0, str(HERE)); LANE = HERE.parents[1]
import nist_pulse as npulse, beacon_record as br, drand_round
out = []; W = out.append
W("# beacon_v2 — observed behaviour (generated by _optionA_dev/beacon_v2/observed_behaviour.py; deterministic: no timestamps or durations, so the file hash reproduces)")
W("Every statement is derived from a result printed by executing the named function; nothing here was written before it ran.\n")
ev = {"pulse_body": (HERE / "_sample_pulse_last.json").read_bytes(), "leaf_pem": (HERE / "_sample_certificate.pem").read_bytes(), "intermediate_pems": [(HERE / "_digicert_intermediate.pem").read_bytes()], "next_body": b'{"pulse":{"localRandomValue":"00"}}'}
c = npulse.authenticate(ev, datetime(2026, 9, 5, 15, 13, tzinfo=timezone.utc), npulse.pinned_roots())
W("## 1. Retained live NIST pulse (2026-09-05T15:13:00Z, chain 2, pulse 1928259) under `nist_pulse.authenticate` with the PINNED DigiCert root"); W("| check | observed |"); W("|---|---|")
for k in ("timestamp_is_t_pulse", "uri_is_nist_chain2", "status_code_zero", "certificate_id_is_sha512_of_leaf_der", "output_is_sha512_of_message_and_signature", "signature_verifies_under_leaf", "leaf_key_bits", "signature_bytes", "precommitment_links_to_next", "accepted"): W(f"| `{k}` | {c.get(k)} |")
for k, v in c["anchor"].items(): W(f"| `anchor.{k}` | {v} |")
W(f"\nRead-out: the served certificate ANCHORS to the pinned root and names the beacon host; `output` binds the bytes to the signature; `signature_verifies_under_leaf` = {c['signature_verifies_under_leaf']} ({c['leaf_key_bits']}-bit key vs {c['signature_bytes']}-byte signature); `precommitment_links_to_next` = {c['precommitment_links_to_next']} (the next pulse is not retained in this sample); `accepted` = {c['accepted']}. Under `beacon_record.verdict` this pulse yields RETRY, never a seed.\n")
def run(cmd, cwd):
    r = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True); tail = [__import__("re").sub(r" in [0-9.]+s", "", l) for l in (r.stdout + r.stderr).splitlines() if l.startswith("Ran ") or l == "OK" or l.startswith("FAILED")]; return " / ".join(tail) or f"rc={r.returncode}"
W("## 2. Fixture suites, executed now under `-W error::ResourceWarning`"); W("| suite | result |"); W("|---|---|")
W(f"| beacon_v2: test_beacon_v2 (includes `test_zzz_every_token_is_exercised`) | {run([sys.executable, '-W', 'error::ResourceWarning', '-m', 'unittest', 'test_beacon_v2'], HERE)} |")
W(f"| corpus_identity: test_build_corpus_identity | {run([sys.executable, '-W', 'error::ResourceWarning', '-m', 'unittest', 'test_build_corpus_identity'], HERE.parent / 'corpus_identity')} |")
W(f"| fourier_chirality: test_fourier_chirality + test_run_configurations | {run([sys.executable, '-W', 'error::ResourceWarning', '-m', 'unittest', 'test_fourier_chirality', 'test_run_configurations'], HERE.parent / 'fourier_chirality')} |")
subprocess.run([sys.executable, str(HERE / "negative_probes.py")], cwd=HERE, capture_output=True, text=True); rec = json.loads((HERE / "negative_probes_receipt.json").read_text())
W("\n## 3. Negative probes (`negative_probes.py`, executed now; genuine records from `beacon_record.collect`, one alteration per row)"); W("| probe | `beacon_record.verdict` | `build_corpus_identity.build` |"); W("|---|---|---|")
for x in rec["probes"]: W(f"| {x['probe']} | {x['verdict']} | {x['builder']} |")
built = [x for x in rec["probes"] if x["builder"] == "BUILT"]; W(f"\nRead-out: {len(rec['probes'])} probes; the builder BUILT an identity in {len(built)} — {'; '.join(x['probe'] for x in built)}. Every other row was refused, and the builder's token carries the verdict's token in parentheses.\n")
bspec = importlib.util.spec_from_file_location("bci", HERE.parent / "corpus_identity" / "build_corpus_identity.py"); bci = importlib.util.module_from_spec(bspec); bspec.loader.exec_module(bci)
src = inspect.getsource(bci._validate_beacon_record); vsrc = inspect.getsource(br.verdict); csrc = inspect.getsource(br.collect)
W("## 4. Structure, by source inspection after execution")
import re as _re
calls_verdict = "beacon_record.verdict(" in src; reads_no_flag = ("pulse_verification" not in src and "accepted" not in src); requires_accept = "startswith('ACCEPT')" in src
fields = sorted(set(_re.findall(r'rec\["([a-z_]+)"\]', csrc)) | {"nist", "drand"}); stores_no_verdict = ("accepted" not in csrc and "seed_hex" not in csrc)
n_nist_live = vsrc.count("nist_pulse.collect(fetch"); n_drand_live = vsrc.count("drand_round.collect(fetch"); has_void = "DRAND-VOID-PRIMARY-AUTHENTICABLE" in vsrc
tokens = sorted({"REFUSE-" + t for t in _re.findall(r'refuse\("([A-Z0-9-]+)"', vsrc)} | {"ACCEPT-NIST", "ACCEPT-DRAND", "RETRY", "UNAVAILABLE"})
W(f"- `build_corpus_identity._validate_beacon_record` calls `beacon_record.verdict`: {calls_verdict}; reads no per-check field of the record: {reads_no_flag}; refuses unless the outcome starts with ACCEPT: {requires_accept}.")
W(f"- `beacon_record.collect` writes only inputs and base64 evidence bytes — fields: {fields}; it stores no verdict: {stores_no_verdict}.")
W(f"- `beacon_record.verdict` re-fetches live when `fetch` is given (NIST collect appears {n_nist_live} times, drand collect {n_drand_live} time) and refuses a fallback when NIST is authenticable now: {has_void}.")
W(f"- Outcome tokens defined in `beacon_record.py`: {tokens} — `test_zzz_every_token_is_exercised` fails if any is never produced by a test.")
W("\n## 5. Limits observed (findings for the principal)")
W(f"- NIST: the live pulse's signature does not verify under the certificate NIST serves ({c['leaf_key_bits']}-bit key, {c['signature_bytes']}-byte signature) although that certificate anchors to DigiCert; `verdict` therefore RETRIES and, from T_pulse + 24 h, falls back. Whether NIST serves a verifying certificate is outside our control.")
W("- drand: the BLS proof is not verified (no BLS12-381 library on the lane); the fallback's authentication is ≥ 2 of 4 PINNED relay hostnames agreeing, recomputed from retained bytes and re-fetched live. Hostname distinctness is the only independence available from bytes.")
W("- Provenance: that a record's bytes came from the pinned fetcher is not provable from the record; the available proof is `verdict(..., fetch=...)`'s live re-fetch equality against the public sources at build time.")
W("- Normative vector: the NISTIR 8213 serialization is confirmed only by the live output-binding equality (`output_is_sha512_of_message_and_signature` = True on the retained pulse); no independently sourced test vector exists on the lane.")
(LANE / "BEACON_V2_OBSERVED_BEHAVIOUR_20260906.md").write_text("\n".join(out) + "\n"); print("\n".join(out))
