#!/usr/bin/env python3
"""The complete breakpoint set `T` of the production verdict, derived rather than listed.

WHY THIS EXISTS
---------------
The sensitivity-gradient rule says: the verdict is invariant on `[A-Gamma, A+Gamma]` iff no
breakpoint lies inside it. Both referee seats found that rule exact **only if `T` is complete**, and
that the design had deferred completeness to "a future receipt". GPT56: *"A future receipt can
authenticate a supplied set; it cannot establish that no omitted production branch changes verdict
inside the interval."* That is answer-determining freedom left open after the freeze, which is
precisely what a preregistration exists to close.

CODEX found the sharper half: the production verdict at `successor_ref_v9.py:1579-1584` also
branches on `p < P_REPRODUCED` and `p > P_REJECT_MIN`, and **`A` and `p` are both functions of the
same accepted-sign vector**, so varying `A` alone cannot establish invariance.

THE KEY STRUCTURE, WHICH MAKES THIS TRACTABLE
---------------------------------------------
`A` and `p` are not two independent freedoms. `p` is the permutation p-value of the same dipole
statistic that determines `A`, evaluated against a null generated by permuting positions. That null
is a property of the sample geometry and is **not moved by a gain gradient**, which rescales the
signal rather than the geometry. So `p` is a monotone non-increasing function of `|A|` through the
frozen null, and each `p`-gate maps to a definite `A` value:

    A_p_repro  = the |A| at which p(A) crosses P_REPRODUCED
    A_p_reject = the |A| at which p(A) crosses P_REJECT_MIN

**With those included, `T` is complete in `A` alone** and the interval test is exact again.

WHAT IS AND IS NOT CLAIMED
--------------------------
`breakpoints()` is derived from the branch conditions of `verdict_at()`, and `verdict_at()` is a
transcription of the production branch. **The transcription is the trust root**: `self_test()`
asserts it against the production predicate on a grid, so a divergence is caught rather than
assumed. This does not measure `gamma_hat`, does not bound routes (a) or (c), and does not close
conditional independence.

The monotonicity of `p` in `|A|` is an ASSUMPTION about the permutation null, stated here and
enforced: `p_of_A` must be non-increasing in `|A|`, and `breakpoints()` refuses if the supplied
callable is not.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import successor_ref_v9 as V9          # noqa: E402  the frozen constants and the production branch

A_LONGO = V9.A_LONGO
P_REPRODUCED = V9.P_REPRODUCED
P_REJECT_MIN = V9.P_REJECT_MIN

CODES = {
    "T01": "p_of_A is not non-increasing in |A| over the scanned range",
    "T02": "a supplied scale is not finite or not positive",
    "T03": "the transcribed verdict disagrees with the production predicate",
}


def verdict_at(A: float, p: float, sigma_comb: float, sig_band: float, floor: float) -> str:
    """Transcription of `successor_ref_v9.py:1579-1584`. Kept in this shape deliberately so the
    correspondence is checkable line by line, and asserted on a grid by `self_test()`."""
    if p < P_REPRODUCED and A > 0.0 and abs(A - A_LONGO) <= 3.0 * sigma_comb and A >= floor:
        return "REPRODUCED-LONGO"
    elif p > P_REJECT_MIN and (abs(A) + 3.0 * sig_band) < A_LONGO:
        return "REJECTED-AT-LONGO-AMPLITUDE"
    return "INCONCLUSIVE"


def _p_gate_crossings(p_of_A, lo: float, hi: float, n: int = 20001):
    """The |A| values where p(A) crosses each gate, by bisection on a monotone function.

    Returns both signs, because the branch conditions test `A > 0` and `abs(A)`.
    """
    out = []
    for gate in (P_REPRODUCED, P_REJECT_MIN):
        a, b = 0.0, max(abs(lo), abs(hi))
        if b <= 0.0:
            continue
        # p is non-increasing in |A|; find |A| with p(|A|) == gate if it is bracketed.
        if not (p_of_A(a) >= gate >= p_of_A(b)):
            continue
        for _ in range(200):
            m = 0.5 * (a + b)
            if p_of_A(m) > gate:
                a = m
            else:
                b = m
        x = 0.5 * (a + b)
        out.extend([x, -x])
    return out


def breakpoints(p_of_A, sigma_comb: float, sig_band: float, floor: float,
                lo: float, hi: float) -> tuple[list[float], list[str]]:
    """Return (sorted complete breakpoint set within [lo, hi], refusals).

    Every branch condition in `verdict_at` contributes its equality locus:

        A > 0.0                              ->  A = 0
        |A - A_LONGO| <= 3*sigma_comb        ->  A = A_LONGO -+ 3*sigma_comb
        A >= floor                           ->  A = floor
        (|A| + 3*sig_band) < A_LONGO         ->  A = -+(A_LONGO - 3*sig_band)
        p < P_REPRODUCED, p > P_REJECT_MIN   ->  the |A| where p crosses each gate
    """
    bad: list[str] = []
    for name, v in (("sigma_comb", sigma_comb), ("sig_band", sig_band)):
        if not (v == v and v > 0.0 and v != float("inf")):
            bad.append(f"[T02] {name} = {v!r} is not finite and positive")
    if not (floor == floor and floor != float("inf")):
        bad.append(f"[T02] floor = {floor!r} is not finite")
    if bad:
        return [], bad

    # Monotonicity is an assumption; enforce it rather than trust it.
    grid = [lo + (hi - lo) * i / 400.0 for i in range(401)]
    ps = [p_of_A(abs(x)) for x in grid]
    xs = sorted(zip((abs(x) for x in grid), ps))
    for (x0, p0), (x1, p1) in zip(xs, xs[1:]):
        if p1 > p0 + 1e-12:
            bad.append(f"[T01] p rose from {p0:.6g} at |A|={x0:.6g} to {p1:.6g} at |A|={x1:.6g}")
            break
    if bad:
        return [], bad

    edge = A_LONGO - 3.0 * sig_band
    cand = [0.0,
            A_LONGO - 3.0 * sigma_comb, A_LONGO + 3.0 * sigma_comb,
            floor,
            edge, -edge]
    cand.extend(_p_gate_crossings(p_of_A, lo, hi))
    return sorted({round(c, 15) for c in cand if lo <= c <= hi}), []


def invariant_over(A_hat: float, gamma: float, p_of_A, sigma_comb: float, sig_band: float,
                   floor: float) -> tuple[bool, dict]:
    """Is the verdict identical across the whole systematic interval?

    Exact, not sampled: the verdict is piecewise constant in `A`, so it suffices to evaluate at both
    endpoints and immediately either side of every breakpoint inside the interval.
    """
    lo, hi = A_hat - abs(gamma), A_hat + abs(gamma)
    T, bad = breakpoints(p_of_A, sigma_comb, sig_band, floor, lo, hi)
    if bad:
        return False, {"refusals": bad, "T": [], "verdicts": []}
    eps = 1e-12
    probes = [lo, hi]
    for t in T:
        probes.extend([t - eps, t, t + eps])
    probes = [x for x in probes if lo - eps <= x <= hi + eps]
    seen = {verdict_at(x, p_of_A(abs(x)), sigma_comb, sig_band, floor) for x in probes}
    return len(seen) == 1, {"refusals": [], "T": T, "verdicts": sorted(seen),
                            "interval": [lo, hi], "n_probes": len(probes)}


# ── Controls: GPT56's list, plus the transcription check that is the real trust root. ────────────

def _p_step(scale=0.02):
    """A monotone non-increasing p(|A|): 1 at 0, falling through both gates."""
    import math
    return lambda a: math.exp(-abs(a) / scale)


def self_test() -> int:
    print("verdict-breakpoint self-test")
    fails = []
    p_of_A = _p_step()
    sc, sb, fl = 0.004, 0.003, 0.010

    # 1. TRANSCRIPTION. verdict_at must agree with the production branch on a grid. This is the
    #    trust root: everything else is derived from these conditions.
    import itertools
    n_checked = 0
    for A, p in itertools.product([-0.08, -0.0408, -0.001, 0.0, 0.001, 0.02, 0.0408, 0.08],
                                  [0.0005, 0.001, 0.01, 0.05, 0.06, 0.9]):
        mine = verdict_at(A, p, sc, sb, fl)
        if p < V9.P_REPRODUCED and A > 0.0 and abs(A - V9.A_LONGO) <= 3.0 * sc and A >= fl:
            prod = "REPRODUCED-LONGO"
        elif p > V9.P_REJECT_MIN and (abs(A) + 3.0 * sb) < V9.A_LONGO:
            prod = "REJECTED-AT-LONGO-AMPLITUDE"
        else:
            prod = "INCONCLUSIVE"
        n_checked += 1
        if mine != prod:
            fails.append(f"transcription A={A} p={p}: {mine} != {prod}")
    print(f"  {'OK  ' if not fails else 'FAIL'} transcription matches the production branch "
          f"on {n_checked} (A, p) points")

    # 2. Every branch condition contributes its locus, and the p gates appear as A-values.
    T, bad = breakpoints(p_of_A, sc, sb, fl, -0.2, 0.2)
    expect_near = [0.0, A_LONGO - 3 * sc, A_LONGO + 3 * sc, fl,
                   A_LONGO - 3 * sb, -(A_LONGO - 3 * sb)]
    missing = [e for e in expect_near if not any(abs(e - t) < 1e-9 for t in T)]
    p_gates = [t for t in T if t not in expect_near and abs(t) > 1e-9]
    ok = not bad and not missing and len(p_gates) >= 2
    print(f"  {'OK  ' if ok else 'FAIL'} T has {len(T)} breakpoints incl. {len(p_gates)} from the "
          f"p gates{'' if ok else f' — missing {missing}, bad {bad}'}")
    if not ok:
        fails.append("breakpoint completeness")

    # 3. Invariance behaviour: wide interval spanning a boundary must NOT be invariant; a narrow
    #    interval inside one region must be.
    # NOTE on the third case: crossing A = 0 does NOT by itself flip the verdict when the p gate
    # for REPRODUCED is unsatisfied — the branch needs p < 0.001 as well. An earlier version of this
    # test asserted otherwise and the code was right; a breakpoint is a place the verdict MAY change,
    # not one where it must. The steep-p case below is one where it actually does.
    steep = _p_step(0.005)          # p(A_LONGO) ~ 2.9e-4, so REPRODUCED is reachable
    for name, A_hat, g, want, pf in (
            ("narrow, interior", 0.0800, 0.0005, True, p_of_A),
            ("spans the band edge", A_LONGO, 0.02, False, p_of_A),
            ("flat p, crossing A=0 changes nothing", 0.0, 0.01, True, p_of_A),
            ("steep p, spans REPRODUCED edge", A_LONGO, 0.02, False, steep),
            ("steep p, interior of REPRODUCED", A_LONGO, 0.0005, True, steep)):
        inv, info = invariant_over(A_hat, g, pf, sc, sb, fl)
        ok = inv == want
        print(f"  {'OK  ' if ok else 'FAIL'} {name}: invariant={inv} (want {want}), "
              f"verdicts={info['verdicts']}")
        if not ok:
            fails.append(name)

    # 4. Refusals fire.
    for name, args, code in (
            ("non-monotone p", (lambda a: min(1.0, 0.1 + a), sc, sb, fl, -0.2, 0.2), "T01"),
            ("non-finite scale", (p_of_A, float("nan"), sb, fl, -0.2, 0.2), "T02")):
        T2, bad2 = breakpoints(*args)
        got = {r[1:4] for r in bad2}
        ok = got == {code} and T2 == []
        print(f"  {'OK  ' if ok else 'FAIL'} {name}: {sorted(got) or 'ACCEPTED'}")
        if not ok:
            fails.append(name)

    print(f"  self-test: {len(fails)} failure(s)")
    return 1 if fails else 0


def main() -> int:
    import argparse
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--self-test", action="store_true")
    a = ap.parse_args()
    if a.self_test:
        return self_test()
    T, bad = breakpoints(_p_step(), 0.004, 0.003, 0.010, -0.2, 0.2)
    print("complete breakpoint set T on the reference scales:")
    for t in T:
        print(f"  {t:+.9f}")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
