import hashlib,json
from pathlib import Path
A=Path("/Users/duhokim/NebulaMind/NebulaMind/.hermes/handoffs/galaxy-evolution/wiki-expansion-20260715");RAW=A/"area_review_09_forster_schreiber_wuyts_2020_DR_RAW_PACKET.md";REG=A/"area_review_09_forster_schreiber_wuyts_2020_CURATED_SOURCE_REGISTRY.json";OUT=A/"area_review_09_forster_schreiber_wuyts_2020_DR_PACKET.md";r=json.loads(REG.read_text());u=[x for x in r['sources'] if x['source_status']=='PASS'];q=[x for x in r['sources'] if x['source_status']!='PASS'];assert(len(u),len(q))==(49,3)
def t(h,rows):
 e=lambda v:str(v).replace('|','\\|').replace('\n',' ')
 return '\n'.join(['| '+' | '.join(h)+' |','|'+'|'.join(['---']*len(h))+'|']+['| '+' | '.join(e(v) for v in z)+' |' for z in rows])
E=[
('REV09-E01','review_synthesis','Cosmic noon, centered near z about 2, is the peak era of cosmic star formation and a major assembly epoch for present-day massive galaxies.','The review emphasizes massive, observable star-forming populations mainly at z about 1-3, not every galaxy.','High as a population synthesis.','[REV09-R00]'),
('REV09-E02','observation','Massive star-forming galaxies occupy a relatively tight SFR-stellar-mass main sequence through cosmic noon.','SFR indicators, dust corrections, IMF, mass completeness, and treatment of high-mass curvature differ across surveys.','High for a sequence; moderate for exact slope and normalization.','[REV09-R00] [REV09-P025] [REV09-P026] [REV09-P028] [REV09-P029]'),
('REV09-E03','observation','Main-sequence star formation dominates the cosmic-noon SFR budget; strong starburst outliers contribute a minority.','IR-selected z about 2 samples and a chosen offset from the main sequence define starbursts.','High for the selected population.','[REV09-R00] [REV09-P027]'),
('REV09-E04','observation','Massive main-sequence galaxies at z about 1-3 contain large molecular-gas reservoirs with shorter depletion times than local disks.','CO or dust gas tracers require excitation and alpha_CO assumptions and are biased toward detectable massive galaxies.','High for elevated gas fractions, moderate for absolute masses.','[REV09-R00] [REV09-P013] [REV09-P014] [REV09-P015] [REV09-P030]'),
('REV09-E05','observation','A large fraction of resolved, massive star-forming galaxies at cosmic noon are rotation-dominated turbulent disks.','Emission-line selected/resolved IFU samples; inclination, beam smearing, sensitivity, and v/sigma criteria matter.','High for surveyed massive SFGs; not a claim that all z~2 galaxies are disks.','[REV09-R00] [REV09-P005] [REV09-P006] [REV09-P008] [REV09-P016]'),
('REV09-E06','observation','Ionized-gas velocity dispersions are elevated at high redshift and decline toward lower redshift.','Halpha-based disk samples with forward modeling; unresolved rotation and beam smearing must be removed.','High for the trend, moderate for the turbulence driver.','[REV09-R00] [REV09-P005] [REV09-P041]'),
('REV09-E07','observation','Inner regions of many massive cosmic-noon disks are baryon dominated in dynamical models.','Within roughly one effective radius; sensitive to inclination, pressure support, IMF, gas mass, halo profile, and sample selection.','Moderate; low central dark matter is not absence of a dark halo.','[REV09-R00] [REV09-P011] [REV09-P022] [REV09-P039] [REV09-P042] [REV09-P043] [REV09-P049]'),
('REV09-E08','observation','At fixed stellar mass, star-forming galaxies are smaller at higher redshift.','Rest-optical Sérsic/GALFIT sizes in 3D-HST/CANDELS; wavelength, surface-brightness, and mass completeness matter.','High for population evolution.','[REV09-R00] [REV09-P020]'),
('REV09-E09','observation','Kiloparsec-scale star-forming clumps are common in resolved images and line maps of gas-rich high-redshift disks.','Clump masses and incidence are strongly affected by PSF blending, rest-frame wavelength, dust, and selection.','High for clumpy appearance; moderate for intrinsic clump properties.','[REV09-R00] [REV09-P009] [REV09-P017] [REV09-P018] [REV09-P031] [REV09-P038] [REV09-P046]'),
('REV09-E10','observation','Bulge growth, dense central cores, and compact star-forming systems are linked observationally to pathways toward quiescence.','CANDELS/3D-HST structural selections; progenitor matching is statistical rather than object-by-object proof.','Moderate to high for correlations, moderate for causal sequence.','[REV09-R00] [REV09-P021] [REV09-P023] [REV09-P024]'),
('REV09-E11','observation','Broad ionized-gas components show galaxy-scale outflows in normal star-forming samples at cosmic noon.','This core claim excludes AGN-only evidence; velocity and mass loading depend on line decomposition, extinction, density, and geometry.','High for incidence, low-to-moderate for mass flux.','[REV09-R00] [REV09-P019] [REV09-P044]'),
('REV09-E12','review_synthesis','The combined scaling relations, gas reservoirs, disks, and outflows support a regulated equilibrium-growth picture with accretion, star formation, feedback, and recycling.','Framework-level synthesis; no single scaling relation uniquely validates one physical implementation.','High as a synthesis, moderate for quantitative channel rates.','[REV09-R00] [REV09-P034] [REV09-P035]'),
]
D=[
('REV09-D01','Main-sequence slope and normalization','Near-linear versus bent/high-mass-flattened relations and different redshift evolution.','SFR indicators, dust, IMF, selection, stacking, and bulge contamination shift fits.','[REV09-R00] [REV09-P025] [REV09-P026] [REV09-P028] [REV09-P029]'),
('REV09-D02','Disks versus mergers','Most massive main-sequence SFGs show ordered rotation, while disturbed systems and mergers remain important.','Resolution, depth, kinematic classification, pair timescales, and sample selection prevent a universal fraction.','[REV09-R00] [REV09-P005] [REV09-P006] [REV09-P008]'),
('REV09-D03','Turbulence drivers','Gravitational instability/accretion versus stellar-feedback energy and momentum injection.','Both scale with gas fraction and SFR; beam smearing and multiphase tracers complicate energy budgets.','[REV09-R00] [REV09-P041] [REV09-P048]'),
('REV09-D04','Clump longevity and migration','Long-lived bound clumps migrate inward versus short-lived clumps disrupted by feedback.','Ages, masses, and radial gradients are resolution/model dependent; simulations differ in feedback strength.','[REV09-R00] [REV09-P009] [REV09-P032] [REV09-P033] [REV09-P038]'),
('REV09-D05','Low inferred inner dark-matter fractions','Baryon-dominated inner disks or apparent low fractions caused by pressure support, IMF/gas masses, halo contraction/cores, and selection.','Rotation curves rarely extend far beyond the luminous disk and mass components are degenerate.','[REV09-R00] [REV09-P011] [REV09-P012] [REV09-P022] [REV09-P039] [REV09-P042]'),
('REV09-D06','IMF, SED, and dust systematics','Different stellar population histories, attenuation laws, and IMFs alter stellar masses and SFRs.','Integrated photometry cannot uniquely recover age-dust-metallicity mixtures.','[REV09-R00] [REV09-P001] [REV09-P050] [REV09-P051]'),
('REV09-D07','Compaction versus inside-out growth','Central compaction before quenching versus gradual inside-out disk growth with bulge buildup.','Cross-sectional populations do not uniquely reconstruct tracks; resolved SEDs are dust/model sensitive.','[REV09-R00] [REV09-P021] [REV09-P023] [REV09-P024] [REV09-P038]'),
('REV09-D08','Simulation-observation comparison','Cold-stream, unstable-disk, and feedback models reproduce subsets of observed scaling relations but not uniquely.','Forward modeling must reproduce selection, resolution, tracers, and correlated observables together.','[REV09-R00] [REV09-P034] [REV09-P035] [REV09-P033]'),
]
N=[
('REV09-N01','z ~ 2; lookback time ~10 Gyr','redshift; years','Review definition of cosmic noon and the prime formation epoch of present-day massive systems.','Review-level benchmark; detailed surveys span broader z ranges.','[REV09-R00]'),
('REV09-N02','sigma_MS ~ 0.2-0.3 dex','dex in log SFR at fixed stellar mass','Observed main-sequence scatter after harmonizing literature calibrations.','Depends on errors, timescale of SFR tracer, IMF, dust, and inclusion of quiescent/bulge-dominated objects.','[REV09-R00] [REV09-P025]'),
('REV09-N03','t_dep = M_mol/SFR ~ 0.7-1.0 Gyr','Gyr','Massive main-sequence galaxies at z about 1-3.','CO excitation and alpha_CO or dust-to-gas calibration dominate; starbursts are shorter.','[REV09-R00] [REV09-P014] [REV09-P015]'),
('REV09-N04','sigma_0 ~ 50 km/s at z ~ 2.3 and ~25 km/s at z ~ 0.9','km s^-1','Intrinsic ionized-gas dispersion in rotation-dominated KMOS3D disks.','Halpha tracer and beam-smearing/rotation forward modeling required.','[REV09-R00] [REV09-P005]'),
('REV09-N05','R_eff proportional to (1+z)^-0.75 for late types; about (1+z)^-1.48 for quiescent galaxies','effective-radius scaling at fixed mass','3D-HST/CANDELS rest-optical size-mass evolution over 0 < z < 3.','Population and wavelength dependent; not an individual growth track.','[REV09-R00] [REV09-P020]'),
('REV09-N06','Q ~ 1','dimensionless','Marginal gravitational stability benchmark for gas-rich turbulent disks.','Definition and coefficient depend on gas+stars, thickness, rotation curve, and resolution.','[REV09-R00] [REV09-P046] [REV09-P047] [REV09-P048]'),
('REV09-N07','median f_DM(<R_eff) ~ 8% for a Chabrier IMF','fraction of dynamical mass','MOSDEF z about 2 star-forming sample with gas masses inferred from dust-corrected Halpha SFR and the Kennicutt-Schmidt relation.','Inclination, v/sigma, gas scaling, IMF, and dynamical geometry are decisive.','[REV09-P042]'),
('REV09-N08','M_clump ~ 10^7-10^9 M_sun','solar masses','Off-center rest-UV/optical or Halpha clumps at z about 1-3.','Kiloparsec PSF blending and SED assumptions can strongly inflate masses.','[REV09-R00] [REV09-P009] [REV09-P031]'),
]
U=[
('REV09-U01','A selection-complete census of disk, merger, and dispersion-dominated fractions across mass and redshift.','Needed to connect detailed IFU samples to the whole population.','Mass-complete resolved spectroscopy with uniform depth and mock-observation corrections.','[REV09-R00] [REV09-P005] [REV09-P006]'),
('REV09-U02','The energy source and phase structure of high-z turbulence.','Controls disk stability, transport, clump formation, and dynamical masses.','Matched ionized/molecular kinematics plus resolved energy and momentum budgets.','[REV09-R00] [REV09-P041] [REV09-P048]'),
('REV09-U03','Whether giant clumps survive and migrate or disrupt rapidly.','Determines their contribution to bulges and secular evolution.','Resolved multi-band ages, gas masses, outflows, and feedback-resolving simulations forward modeled to the same PSF.','[REV09-R00] [REV09-P009] [REV09-P033] [REV09-P038]'),
('REV09-U04','Robust dark-matter profiles beyond the effective radius at cosmic noon.','Needed to distinguish baryon dominance, cored halos, and modeling bias.','Deep extended rotation curves with gas, stars, pressure support, lensing, and hierarchical halo priors.','[REV09-R00] [REV09-P012] [REV09-P022] [REV09-P043]'),
('REV09-U05','Causal pathways linking normal SFGs, compact SFGs, and quenched descendants.','Cross-sectional correlations do not establish evolutionary tracks.','Number-density/progenitor modeling plus resolved ages, gas, structure, and environment over time.','[REV09-R00] [REV09-P021] [REV09-P023] [REV09-P024] [REV09-P045]'),
('REV09-U06','A joint model that reproduces scaling relations, internal structure, gas, kinematics, and outflows together.','Matching one observable does not identify one unique feedback/accretion model.','Survey-matched synthetic observations and multi-observable inference across simulation variants.','[REV09-R00] [REV09-P034] [REV09-P035] [REV09-P044]'),
]
L=['# Review Base 09 — Förster Schreiber & Wuyts (2020): Star-Forming Galaxies at Cosmic Noon','','Status: READY_FOR_HWAO_REVIEW — advisory source base only; no live wiki/database/trust/deployment/publication/git mutation.','',f"Raw custody SHA-256: `{hashlib.sha256(RAW.read_bytes()).hexdigest()}`",'','## 1. Review Identity and Scope Map','',t(['Field','Value'],[('Review key','[REV09-R00]'),('Authors','Natascha M. Förster Schreiber and Stijn Wuyts'),('Year / journal','2020, Annual Review of Astronomy and Astrophysics 58, 661-725'),('DOI','10.1146/annurev-astro-032620-021910'),('arXiv','2010.10171'),('ADS','2020ARA&A..58..661F'),('Authorized scope','Massive star-forming galaxies chiefly at z about 1-3: populations, scaling relations, resolved structure, gas, kinematics, dynamics, clumps, secular growth, stellar feedback, and descendants.'),('Explicit exclusions','Post-2020 work, AGN-only physics, uncited candidates, all-z~2 generalizations, one-line-width rotation claims, and unique model claims from one observable.')]),'','## 2. Established Findings','',t(['ID','Epistemic type','Bounded finding','Boundary','Confidence','Sources'],E),'','## 3. Open Debates and Tensions','',t(['ID','Topic','Competing positions','Why unresolved / boundary','Sources'],D),'','## 4. Key Measurements, Model Benchmarks, and Calibrations','',t(['ID','Value / equation','Units','Context','Status / caveat','Sources'],N),'','## 5. What Remained Unknown in 2020','',t(['ID','Gap','Why it matters','Needed test','Sources'],U),'','## 6. Primary-Citation Harvest','']
for s in u:L.append(f"[{s['key']}] {s['authors']} ({s['year']}, {s['journal']}) | title={s['title']} | DOI:{s['doi']}; arXiv:{s['arxiv'] or 'none'}; ADS:{s['ads_bibcode']} | role={s['role']} | review_locator={s['review_locator']} | {s['boundary']} | source_status=PASS_COMPOSITE_ID_AND_REVIEW_MEMBERSHIP")
L+=['','### Supporting reviews','','None counted separately in this curated harvest.','','## 7. DO_NOT_USE_UNVERIFIED','']
for s in q:L.append(f"UNCITED_NOT_USABLE | [{s['key']}] {s['authors']} ({s['year']}) — {s['title']} | DOI:{s['doi'] or 'none'}; arXiv:{s['arxiv'] or 'none'}; ADS:{s['ads_bibcode'] or 'none'} | {s['quarantine_reason']}")
L += ['UNCITED_NOT_USABLE | all z~2 galaxies are disks or all are mergers | none | selection-collapsing overclaim.','UNCITED_NOT_USABLE | every clump is long-lived and migrates, or every clump disrupts rapidly | none | unresolved longevity debate.','UNCITED_NOT_USABLE | one line width proves rotation or low central dark matter means no halo | none | dynamical-model overreach.','UNCITED_NOT_USABLE | matching one scaling relation validates one unique model | none | multi-observable degeneracy.','UNCITED_NOT_USABLE | post-2020/JWST/ML browsing results | none | outside review temporal boundary.','','## 8. Review and Source Identity Ledger','','[REV09-R00] Förster Schreiber NM & Wuyts S (2020, Annual Review of Astronomy and Astrophysics) | title=Star-Forming Galaxies at Cosmic Noon | DOI:10.1146/annurev-astro-032620-021910; arXiv:2010.10171; ADS:2020ARA&A..58..661F | role=review_synthesis | source_status=PASS_ADS_CROSSREF_ARXIV','']
for s in u:L.append(f"[{s['key']}] {s['authors']} ({s['year']}, {s['journal']}) | title={s['title']} | DOI:{s['doi']}; arXiv:{s['arxiv'] or 'none'}; ADS:{s['ads_bibcode']} | role={s['role']} | boundary={s['boundary']} | source_status=PASS_COMPOSITE_ID_AND_REVIEW_MEMBERSHIP")
L+=['','REVIEW_BASE_09_DR_COMPLETE_REFERENCE_ONLY',''];OUT.write_text('\n'.join(L));print(json.dumps({'packet':str(OUT),'primary':len(u),'quarantined':len(q),'sha256':hashlib.sha256(OUT.read_bytes()).hexdigest()},sort_keys=True))
