import hashlib
import json
from pathlib import Path
AREA=Path("/Users/duhokim/NebulaMind/NebulaMind/.hermes/handoffs/galaxy-evolution/wiki-expansion-20260715")
RAW=AREA/"area_review_08_tumlinson_peeples_werk_2017_DR_RAW_PACKET.md"; REG=AREA/"area_review_08_tumlinson_peeples_werk_2017_CURATED_SOURCE_REGISTRY.json"; OUT=AREA/"area_review_08_tumlinson_peeples_werk_2017_DR_PACKET.md"
r=json.loads(REG.read_text()); usable=[s for s in r["sources"] if s["source_status"]=="PASS"]; primary=[s for s in usable if s["role"]!="supporting_review"]; supporting=[s for s in usable if s["role"]=="supporting_review"]; quarantined=[s for s in r["sources"] if s["source_status"]!="PASS"]
assert (len(primary),len(supporting),len(quarantined))==(67,1,5)
def table(h,rows):
 def e(v): return str(v).replace("|","\\|").replace("\n"," ")
 return "\n".join(["| "+" | ".join(h)+" |","|"+"|".join(["---"]*len(h))+"|"]+["| "+" | ".join(e(v) for v in row)+" |" for row in rows])
E=[
("REV08-E01","review_synthesis","The CGM is gas outside a galaxy's stellar disk/ISM and inside its virial radius.","Geometric working definition; boundaries can overlap satellites, outflows, and the IGM.","High as a review convention, not a sharp physical discontinuity.","[REV08-R00]"),
("REV08-E02","observation","The CGM is multiphase in ionization and complex in kinematics.","HI through highly ionized metal lines sample different densities and temperatures; velocity does not uniquely map to radius.","High for multiphase phenomenology; phase masses remain model-dependent.","[REV08-R00] [REV08-P030] [REV08-P069] [REV08-P072]"),
("REV08-E03","observation","Cool HI-bearing gas is common around both star-forming and passive low-redshift galaxies.","COS-Halos-like galaxy selection, impact parameters inside roughly the virial radius, and UV-detectable columns.","High for covering incidence; total mass requires ionization corrections.","[REV08-R00] [REV08-P068] [REV08-P071]"),
("REV08-E04","observation","Strong O VI is widespread around star-forming L-star galaxies and is much weaker around passive galaxies in the COS-Halos sample.","O VI at z about 0.2 within 150 kpc; ionization origin is not uniquely fixed.","High for the sample correlation, moderate for physical interpretation.","[REV08-R00] [REV08-P061] [REV08-P070]"),
("REV08-E05","observation","Photoionization modeling implies a large cool-CGM baryonic reservoir around L-star galaxies.","Low/intermediate ions plus HI under an extragalactic UV background, metallicity priors, and radial integration to Rvir.","Moderate; mass is sensitive to density, UV background, and unresolved phase structure.","[REV08-R00] [REV08-P064] [REV08-P073]"),
("REV08-E06","observation","A substantial fraction of metals produced by galaxies resides outside their stellar disks.","COS-Halos metal accounting; combines ion-specific lower limits with ionization and abundance assumptions.","Moderate; no single ion closes the metal budget.","[REV08-R00] [REV08-P062] [REV08-P070]"),
("REV08-E07","observation","Dust is detected statistically beyond galaxy disks and contributes to the CGM metal inventory.","Quasar reddening cross-correlations; dust mass and radius depend on opacity and grain models.","Moderate at population level.","[REV08-R00] [REV08-P057]"),
("REV08-E08","observation","Direct soft-X-ray detections of hot coronae were limited to a small set of luminous nearby galaxies and did not by themselves establish universal baryon closure.","Hot T > 10^6 K gas; profile extrapolation, foreground subtraction, and metallicity assumptions dominate.","High for limited detections, low-to-moderate for total hot mass.","[REV08-R00] [REV08-P003] [REV08-P004] [REV08-P005] [REV08-P019] [REV08-P035]"),
("REV08-E09","observation","At z about 2-3, absorption around galaxies is stronger and more extended than random IGM absorption, showing enriched, dynamic high-redshift CGM.","Lyman-break galaxy samples, stacked/background sightlines, and projected separations.","High for excess absorption; flow direction remains ambiguous.","[REV08-R00] [REV08-P001] [REV08-P065]"),
("REV08-E10","observation","Low-ion absorption depends on galaxy orientation, with enhanced minor-axis incidence consistent with biconical outflows in statistical samples.","Mg II around disk galaxies; azimuth is a probabilistic diagnostic rather than a unique label for each absorber.","Moderate to high statistically.","[REV08-R00] [REV08-P020] [REV08-P021] [REV08-P052]"),
("REV08-E11","observation","Cool-CGM metallicities span a broad range, including very metal-poor and enriched systems.","HI-selected LLSs and COS-Halos absorbers; photoionization background and component structure matter.","High for diversity, moderate for bimodality and origin assignments.","[REV08-R00] [REV08-P054] [REV08-P064]"),
("REV08-E12","hydrodynamic_simulation","Simulations predict that absorption-selected CGM gas mixes fresh accretion, recycled winds, and older outflows.","Model-dependent feedback, resolution, ionization post-processing, and synthetic sightline selection.","Moderate; histories are known in simulations but not directly observed.","[REV08-R00] [REV08-P032] [REV08-P045] [REV08-P046]"),
("REV08-E13","hydrodynamic_simulation","Small cool clouds moving through hot halo gas are vulnerable to disruption and mixing.","Cloud size, cooling, conduction, magnetic fields, and numerical resolution control survival.","High for idealized disruption mechanisms, uncertain for realistic magnetized radiative CGM clouds.","[REV08-R00] [REV08-P007] [REV08-P017] [REV08-P018] [REV08-P056]"),
("REV08-E14","review_synthesis","The CGM is a reservoir and transfer medium for accretion, feedback, and recycling that regulates galaxy gas supply.","Population-level synthesis; individual absorption components cannot be assigned a unique trajectory from line-of-sight velocity alone.","High as a framework, moderate for quantitative channel rates.","[REV08-R00] [REV08-P023] [REV08-P024] [REV08-P050] [REV08-P053]"),
]
D=[
("REV08-D01","Cool-cloud survival","Rapid hydrodynamic shredding versus survival/growth aided by cooling, conduction suppression, magnetic fields, or continual regeneration.","Cloud sizes, interfaces, and microphysics were unresolved observationally and numerically.","[REV08-R00] [REV08-P007] [REV08-P018] [REV08-P055] [REV08-P056]"),
("REV08-D02","O VI ionization and temperature","Collisionally ionized gas near 10^5.5 K versus photoionized or non-equilibrium interfaces/cooling flows.","One O VI column does not fix density, path length, temperature, or total mass.","[REV08-R00] [REV08-P041] [REV08-P042] [REV08-P061] [REV08-P069] [REV08-P070]"),
("REV08-D03","CGM baryon closure","Large cool/warm reservoirs versus still-unmeasured hot and low-density phases.","Radial extrapolation, metallicity, UV background, and halo-mass normalization dominate.","[REV08-R00] [REV08-P003] [REV08-P005] [REV08-P073]"),
("REV08-D04","Metallicity as an origin tag","Very low metallicity suggests fresh accretion and high metallicity suggests outflow/recycling, but mixing and ionization create overlap.","Metallicity alone cannot uniquely reconstruct trajectory or launch time.","[REV08-R00] [REV08-P046] [REV08-P054] [REV08-P064]"),
("REV08-D05","Inflow versus outflow identification","Major-axis co-rotation and minor-axis absorption are statistical clues, but projection and recycling make individual classifications degenerate.","Requires galaxy geometry, component kinematics, metallicity, and preferably multiple sightlines.","[REV08-R00] [REV08-P024] [REV08-P046] [REV08-P052]"),
("REV08-D06","Hydrostatic versus dynamic halos","Virialized pressure-supported coronae versus halos continually disturbed by accretion, fountains, cooling, and nonthermal support.","Sparse X-ray profiles and uncertain boundary conditions prevented a unique model.","[REV08-R00] [REV08-P042] [REV08-P050]"),
("REV08-D07","Feedback-model dependence","Different wind loading, velocity, hydrodynamic coupling, and recycling prescriptions yield different CGM columns and phase masses.","Galaxy-integrated calibration does not uniquely constrain halo-scale gas histories.","[REV08-R00] [REV08-P044] [REV08-P058] [REV08-P060]"),
("REV08-D08","Simulation-observation comparison","Matching one ion profile can hide wrong temperature, density, metallicity, or gas origin distributions.","Synthetic spectra require the same UV background, ionization, resolution, and sample selection as observations.","[REV08-R00] [REV08-P033] [REV08-P045] [REV08-P046]"),
]
N=[
("REV08-N01","R_disk < r <= R_vir","physical radial domain","Working CGM boundary outside the stellar disk/ISM and inside the virial radius.","Definition; satellites and interfaces make the edge non-sharp.","[REV08-R00]"),
("REV08-N02","b^2 = 2kT/m_i + b_nt^2","(km s^-1)^2 when b terms use km s^-1","Thermal plus nonthermal decomposition of an ion's Doppler parameter.","Requires aligned components; one ion alone cannot separate T and b_nt.","[REV08-R00] [REV08-P069]"),
("REV08-N03","M_cool = 6.5 x 10^10 M_sun","solar masses","COS-Halos L-star galaxies integrated to Rvir using PIE models for low/intermediate ions and HI.","UV background, metallicity, geometry, and phase assumptions apply.","[REV08-R00] [REV08-P073]"),
("REV08-N04","M_cool = (9.2 +/- 4.3) x 10^10 M_sun","solar masses","Non-parametric COS-Halos refinement integrated to 160 kpc with Lyman-limit coverage.","Review-reported estimate; still ionization/model dependent.","[REV08-R00] [REV08-P064]"),
("REV08-N05","M_warm > 2 x 10^9 M_sun","solar masses","O VI-traced warm CGM around L-star galaxies, with solar metallicity, maximum f_OVI=0.2, and a sharp 150 kpc edge.","Strict lower limit; all three assumptions minimize mass.","[REV08-R00] [REV08-P070]"),
("REV08-N06","T = 10^5.3-10^5.6 K","kelvin","Narrow CIE temperature interval that produces substantial O VI.","Does not exclude photoionization or non-equilibrium gas.","[REV08-R00] [REV08-P041] [REV08-P070]"),
("REV08-N07","T_vir = G M_halo m_p / (k R_vir); T_vir >= 10^6 K for M_halo >= 10^12 M_sun","kelvin","Order-of-magnitude virial temperature scaling used for hot halo expectations.","Coefficient depends on mean particle mass and virial convention.","[REV08-R00] [REV08-P038] [REV08-P042]"),
("REV08-N08","M_hot <= (0.5-1.5) x 10^10 M_sun","solar masses","Milky Way hot-halo upper range under an NFW-like density assumption, corresponding to only 2-5 percent of the missing halo mass.","A flatter beta profile raises inferred mass; profile choice is decisive.","[REV08-R00] [REV08-P003]"),
]
U=[
("REV08-U01","A complete temperature-resolved CGM baryon census.","Needed to determine whether halos close their expected baryon budgets.","Joint UV/EUV/X-ray absorption, emission, and SZ constraints with radial profiles.","[REV08-R00] [REV08-P003] [REV08-P042] [REV08-P073]"),
("REV08-U02","The dominant physical origin of O VI and other intermediate ions.","Controls inferred temperature, path length, cooling rate, and mass.","Multiple ions, linewidth comparisons, non-equilibrium models, and independent density diagnostics.","[REV08-R00] [REV08-P041] [REV08-P061] [REV08-P069]"),
("REV08-U03","How cool clouds form, survive, and exchange mass with hot gas.","Sets accretion efficiency and observability of multiphase flows.","Radiative magnetized simulations plus interface-resolving spectra.","[REV08-R00] [REV08-P007] [REV08-P055] [REV08-P056]"),
("REV08-U04","Quantitative inflow, outflow, and recycling rates by halo mass and epoch.","Required to close galaxy gas-regulator equations.","Tomographic sightlines, resolved galaxy geometry, metallicities, and time-resolved simulations.","[REV08-R00] [REV08-P024] [REV08-P046] [REV08-P058]"),
("REV08-U05","CGM structure and mass outside the L-star, low-redshift regime.","Dwarfs, massive passive halos, and high-z galaxies may host different phases and feedback states.","Uniform surveys spanning stellar mass, halo mass, redshift, and star-formation state.","[REV08-R00] [REV08-P022] [REV08-P027] [REV08-P065]"),
("REV08-U06","Whether simulations reproduce the same physical phases, not only selected ion columns.","A model can match an observable for the wrong density-temperature-metallicity distribution.","Forward-modeled multi-ion spectra and emission with controlled numerical resolution and feedback variants.","[REV08-R00] [REV08-P033] [REV08-P045] [REV08-P046]"),
]
L=["# Review Base 08 — Tumlinson, Peeples & Werk (2017): The Circumgalactic Medium","","Status: READY_FOR_HWAO_REVIEW — advisory source base only; no live wiki/database/trust/deployment/publication/git mutation.","",f"Raw custody SHA-256: `{hashlib.sha256(RAW.read_bytes()).hexdigest()}`","","## 1. Review Identity and Scope Map","",table(["Field","Value"],[
("Review key","[REV08-R00]"),("Authors","Jason Tumlinson, Molly S. Peeples, and Jessica K. Werk"),("Year / journal","2017, Annual Review of Astronomy and Astrophysics 55, 389-432"),("DOI","10.1146/annurev-astro-091916-055240"),("arXiv","1709.09180"),("ADS","2017ARA&A..55..389T"),("Authorized scope","Gas outside the disk/ISM and inside Rvir; multiphase structure, absorbers/emission, mass/metals, flows, and simulation interpretation through 2017."),("Explicit exclusions","Post-2017 work, AGN-only physics, uncited candidates, one-ion-to-total-mass claims, and unique flow/model assignments from one sightline.")]),"","## 2. Established Findings","",table(["ID","Epistemic type","Bounded finding","Boundary","Confidence","Sources"],E),"","## 3. Open Debates and Tensions","",table(["ID","Topic","Competing positions","Why unresolved / boundary","Sources"],D),"","## 4. Key Measurements, Model Benchmarks, and Calibrations","",table(["ID","Value / equation","Units","Context","Status / caveat","Sources"],N),"","## 5. What Remained Unknown in 2017","",table(["ID","Gap","Why it matters","Needed test","Sources"],U),"","## 6. Primary-Citation Harvest",""]
for s in primary: L.append(f"[{s['key']}] {s['authors']} ({s['year']}, {s['journal']}) | title={s['title']} | DOI:{s['doi'] or 'none'}; arXiv:{s['arxiv'] or 'none'}; ADS:{s['ads_bibcode']} | role={s['role']} | review_locator={s['review_locator']} | {s['boundary']} | source_status=PASS_COMPOSITE_ID_AND_REVIEW_MEMBERSHIP")
L += ["","### Supporting reviews",""]
for s in supporting: L.append(f"[{s['key']}] {s['authors']} ({s['year']}, {s['journal']}) | title={s['title']} | DOI:{s['doi'] or 'none'}; arXiv:{s['arxiv'] or 'none'}; ADS:{s['ads_bibcode']} | role=supporting_review | review_locator={s['review_locator']} | {s['boundary']} | source_status=PASS_COMPOSITE_ID_AND_REVIEW_MEMBERSHIP")
L += ["","## 7. DO_NOT_USE_UNVERIFIED",""]
for s in quarantined: L.append(f"UNCITED_NOT_USABLE | [{s['key']}] {s['authors']} ({s['year']}) — {s['title']} | DOI:{s['doi'] or 'none'}; arXiv:{s['arxiv'] or 'none'}; ADS:{s['ads_bibcode'] or 'none'} | {s['quarantine_reason']}")
L += ["UNCITED_NOT_USABLE | one ion traces all CGM gas or O VI uniquely fixes one temperature/origin | none | phase and ionization-model overreach.","UNCITED_NOT_USABLE | every absorber is uniquely inflow or outflow, or one halo closes the cosmic baryon budget | none | geometry and census overreach.","UNCITED_NOT_USABLE | matching one column-density profile validates one unique feedback model | none | observable-to-physics degeneracy.","UNCITED_NOT_USABLE | post-2017/JWST/ML browsing results | none | outside the review temporal boundary.","","## 8. Review and Source Identity Ledger","","[REV08-R00] Tumlinson J, Peeples MS & Werk JK (2017, Annual Review of Astronomy and Astrophysics) | title=The Circumgalactic Medium | DOI:10.1146/annurev-astro-091916-055240; arXiv:1709.09180; ADS:2017ARA&A..55..389T | role=review_synthesis | source_status=PASS_ADS_CROSSREF_ARXIV",""]
for s in usable: L.append(f"[{s['key']}] {s['authors']} ({s['year']}, {s['journal']}) | title={s['title']} | DOI:{s['doi'] or 'none'}; arXiv:{s['arxiv'] or 'none'}; ADS:{s['ads_bibcode']} | role={s['role']} | boundary={s['boundary']} | source_status=PASS_COMPOSITE_ID_AND_REVIEW_MEMBERSHIP")
L += ["","REVIEW_BASE_08_DR_COMPLETE_REFERENCE_ONLY",""]
OUT.write_text("\n".join(L)); print(json.dumps({"packet":str(OUT),"primary":len(primary),"supporting":len(supporting),"quarantined":len(quarantined),"sha256":hashlib.sha256(OUT.read_bytes()).hexdigest()},sort_keys=True))
