import hashlib,json
from pathlib import Path
A=Path('/Users/duhokim/NebulaMind/NebulaMind/.hermes/handoffs/galaxy-evolution/wiki-expansion-20260715');RAW=A/'area_review_12_blanton_moustakas_2009_DR_RAW_PACKET.md';REG=A/'area_review_12_blanton_moustakas_2009_CURATED_SOURCE_REGISTRY.json';OUT=A/'area_review_12_blanton_moustakas_2009_DR_PACKET.md';r=json.loads(REG.read_text());p=[x for x in r['sources'] if x['source_status']=='PASS' and x['role']!='supporting_review'];sr=[x for x in r['sources'] if x['source_status']=='PASS' and x['role']=='supporting_review'];q=[x for x in r['sources'] if x['source_status']!='PASS'];assert(len(p),len(sr),len(q))==(44,2,6)
def t(h,rows):
 e=lambda v:str(v).replace('|','\\|').replace('\n',' ')
 return '\n'.join(['| '+' | '.join(h)+' |','|'+'|'.join(['---']*len(h))+'|']+['| '+' | '.join(e(v) for v in z)+' |' for z in rows])
E=[
('REV12-E01','observation','Local optical luminosity, stellar-mass, and atomic-HI mass functions provide distinct censuses with different selection boundaries.','Nearby surveys; optical surface-brightness, stellar M/L/IMF, and 21-cm flux completeness differ.','High.','[REV12-R00] [REV12-P011] [REV12-P027] [REV12-P041] [REV12-P052]'),
('REV12-E02','observation','Nearby galaxies occupy a strongly bimodal optical color-magnitude distribution rather than one continuous Gaussian population.','Rest-frame optical colors; dust, inclination, aperture, luminosity, and selection affect assignment.','High.','[REV12-P010] [REV12-P042]'),
('REV12-E03','observation','Dense environments contain larger red/early-type fractions, while many within-class scaling relations change less than the population mixture.','Environment estimator, luminosity/mass matching, central/satellite status, and morphology/color definition apply.','High for population shift; moderate for invariance details.','[REV12-R00] [REV12-P013] [REV12-P015] [REV12-P018] [REV12-P044] [REV12-P045]'),
('REV12-E04','observation','Color, morphology, concentration/Sérsic structure, and star-formation state are correlated but non-equivalent galaxy descriptors.','Dusty disks, face-on systems, post-starbursts, S0s, and bulge-disk composites create mismatches.','High.','[REV12-P001] [REV12-P003] [REV12-P010] [REV12-P013] [REV12-P014] [REV12-P018]'),
('REV12-E05','observation','Bulge-disk decomposition reveals composite structure obscured by one-component classifications.','Imaging depth, seeing, bars, dust, wavelength, and decomposition priors matter.','High qualitatively.','[REV12-P003] [REV12-P006] [REV12-P009]'),
('REV12-E06','simulation/observation','Bars exchange angular momentum, rearrange disk material, and can be strengthened, slowed, or regenerated depending on halo and interaction history.','Disk stability, gas fraction, halo response, and bar definition affect transfer.','High for secular dynamics; model-dependent rates.','[REV12-P004] [REV12-P005] [REV12-P019] [REV12-P032]'),
('REV12-E07','calibration','Broad-band color can estimate stellar M/L for normal histories, but IMF, dust, bursts, and metallicity set systematic limits.','Integrated optical/NIR populations; extreme dust or recent bursts violate simple relations.','High.','[REV12-P026] [REV12-P027]'),
('REV12-E08','observation','Gas-rich low-mass galaxies and resolved nearby disks anchor baryonic scaling and star-formation laws beyond optical light alone.','HI-dominated dwarfs and sub-kpc disk regions; molecular conversion and survey limits apply.','High within samples.','[REV12-P025] [REV12-P037] [REV12-P052]'),
('REV12-E09','observation','S0 galaxies overlap spirals and ellipticals in different observables, consistent with multiple formation pathways rather than one taxonomy-to-history map.','Cluster/group selection, fading, bulge fraction, globular clusters, and rotation matter.','Moderate.','[REV12-P021] [REV12-P024]'),
('REV12-E10','observation/analytic_theory','Early-type galaxies define tight structural-kinematic scaling relations with a Fundamental-Plane tilt relative to simple homology.','Bandpass, aperture, stellar populations, IMF, non-homology, dark matter, and sample selection matter.','High.','[REV12-P030] [REV12-P031] [REV12-P039] [REV12-P040]'),
('REV12-E11','observation','Brightest cluster galaxies have luminosity-size-dispersion behavior not fully represented by ordinary early-type scaling samples.','BCG identification, extended-light photometry, and cluster selection dominate systematics.','High qualitatively.','[REV12-P034]'),
('REV12-E12','observation','Close interactions can enhance star formation and dry mergers can add stellar mass to red galaxies, but disturbances alone do not uniquely determine merger rates.','Pair selection, projection, timescale, gas fraction, and morphological observability time apply.','High for triggered effects; moderate for integrated rates.','[REV12-P022] [REV12-P023] [REV12-P028] [REV12-P029]'),
('REV12-E13','calibration','The SDSS and value-added catalogs transformed local-galaxy statistics but inherited flux, fiber, aperture, seeing, deblending, and surface-brightness selection.','Survey/data-release and derived-catalog versions must be carried with claims.','High.','[REV12-P002] [REV12-P033] [REV12-P041] [REV12-P043]'),
]
D=[
('REV12-D01','Taxonomy versus physics','Discrete Hubble/color/concentration classes versus continuous multi-parameter structure and star formation.','Correlated proxies disagree for composite, dusty, inclined, and transitioning galaxies.','[REV12-P001] [REV12-P003] [REV12-P010] [REV12-P013] [REV12-P014] [REV12-P018]'),
('REV12-D02','Environmental mechanism','Ram pressure, starvation, harassment, tidal effects, mergers, or halo-scale processes as dominant transformations.','Population correlations do not uniquely identify a mechanism or timescale.','[REV12-P015] [REV12-P017] [REV12-P018] [REV12-P044] [REV12-P045]'),
('REV12-D03','Scale of environment','Nearest-neighbor/local density, group membership, halo mass, cluster-centric radius, and large-scale density as the relevant variable.','Estimators are correlated and respond differently to survey edges, fingers of God, and central/satellite status.','[REV12-P033] [REV12-P044] [REV12-P045]'),
('REV12-D04','Low-mass abundance','A steep intrinsic dwarf population versus surface-brightness/volume incompleteness shaping the GSMF faint end.','Nearby volume, photometric deblending, distances, and stellar M/L dominate.','[REV12-P011] [REV12-P025] [REV12-P038]'),
('REV12-D05','S0 formation','Faded/quenched spirals versus merger-built or secularly transformed lenticulars.','Tully-Fisher offsets, bulges, clusters, kinematics, and stellar populations admit mixed pathways.','[REV12-P021] [REV12-P024]'),
('REV12-D06','Elliptical dynamical support','Rotation, anisotropy, triaxiality, and merger remnants behind projected early-type structure.','Sparse or one-dimensional kinematics can hide face-on fast rotators and decoupled cores.','[REV12-P008] [REV12-P029] [REV12-P031] [REV12-P039] [REV12-P040]'),
('REV12-D07','Merger contribution','Major/minor and wet/dry mergers versus secular evolution as dominant recent growth channels.','Pair and disturbance timescales, projection, gas fraction, and selection produce different inferred rates.','[REV12-P022] [REV12-P023] [REV12-P028] [REV12-P032]'),
('REV12-D08','Stellar-mass scale','Color-M/L estimates are mutually consistent at fixed IMF, but absolute mass depends on IMF and SFH.','Low-mass stars are not directly constrained by integrated light; dust and bursts break simple relations.','[REV12-P011] [REV12-P026] [REV12-P027]'),
]
N=[
('REV12-N01','phi(L)dL = phi* (L/L*)^alpha exp(-L/L*) d(L/L*)','number density per luminosity','Schechter-function local luminosity-function baseline; bandpass and h conventions must accompany parameters.','SDSS flux-limited samples; surface-brightness incompleteness affects faint end.','[REV12-P041] [REV12-P038]'),
('REV12-N02','GSMF secondary faint-end slope alpha_2 ~ -1.6','dimensionless slope','Local z<~0.05 double-Schechter-style stellar-mass function with Chabrier-like IMF scale.','Potential incompleteness below ~10^8.5 M_sun and stellar-M/L systematics.','[REV12-P011]'),
('REV12-N03','log10(M_HI*/M_sun) = 9.80 +/- 0.03(stat) +/- 0.03(sys) for h_75 convention','dex / M_sun','HIPASS 4315-source blind 21-cm sample; characteristic HIMF mass.','Convert the published h_75 scaling before comparing to other H0 conventions.','[REV12-P052]'),
('REV12-N04','HIMF alpha = -1.37 +/- 0.03(stat) +/- 0.05(sys)','dimensionless slope','HIPASS blind local 21-cm mass function.','Radio-flux completeness and environmental/cosmic-variance boundaries apply.','[REV12-P052]'),
('REV12-N05','Omega_HI = (3.5 +/- 0.4 +/- 0.4) x 10^-4 h_75^-1','dimensionless density','Local atomic-hydrogen density from HIPASS.','Published h convention and HI self-absorption/systematic treatment apply.','[REV12-P052]'),
('REV12-N06','(u-r)_cut = 2.06 - 0.244 tanh[(M_r + 20.07)/1.09]','magnitudes','Empirical luminosity-dependent divider between fitted red and blue color components.','SDSS rest-frame color/magnitude convention; a classifier, not a physical morphology boundary.','[REV12-P010]'),
('REV12-N07','N_n: neighbors within R_p=500 h^-1 kpc and |Delta v|<600 km/s above M_r-5logh<-18.5','count / projected aperture','One local SDSS environment estimator used in the review synthesis.','Fiber collisions, boundaries, velocity projection, and threshold selection apply.','[REV12-P044] [REV12-P045]'),
('REV12-N08','diet-Salpeter masses ~0.05 dex above Kroupa/Chabrier scale','dex','Bell et al. optical/NIR color-M/L convention for normal galaxy populations.','Approximate conversion; SFH, dust, and SPS differences remain.','[REV12-R00] [REV12-P026] [REV12-P027]'),
]
U=[
('REV12-U01','Asymptotic local GSMF and HIMF behavior for ultra-low-mass/low-surface-brightness galaxies.','Separates real dwarf abundance from optical/radio incompleteness.','Deep wide imaging, accurate distances, and blind HI surveys with matched volumes.','[REV12-P011] [REV12-P025] [REV12-P052]'),
('REV12-U02','Resolved two-dimensional stellar and gas kinematics for statistically representative morphologies.','Distinguishes fast/slow rotation, anisotropy, bars, and composite structures.','Multiplexed IFU surveys with matched deep imaging and dynamical models.','[REV12-P008] [REV12-P029] [REV12-P039] [REV12-P040]'),
('REV12-U03','Timescale and dominant mechanism of environmental transformation.','Needed to turn morphology/color/SFR correlations into evolutionary pathways.','Resolved HI/CO and stellar ages across infall phase space with controlled groups.','[REV12-P015] [REV12-P017] [REV12-P018] [REV12-P044] [REV12-P045]'),
('REV12-U04','Robust local merger rate split by mass ratio and gas content.','Constrains hierarchical stellar-mass assembly.','Complete spectroscopic pairs plus deep tidal-feature imaging and calibrated observability times.','[REV12-P022] [REV12-P023] [REV12-P028]'),
('REV12-U05','How SMBH growth and maintenance feedback connect to bulges, disks, and merger histories.','Determines whether major mergers are required for black-hole-galaxy scaling.','Dynamical black-hole masses and accretion histories in bulgeless, barred, and undisturbed systems.','[REV12-P036]'),
('REV12-U06','Universality of the stellar IMF across galaxy type and internal environment.','Sets absolute stellar masses and Fundamental-Plane interpretation.','Gravity-sensitive high-S/N spectra plus independent dynamics/lensing across radii.','[REV12-P026] [REV12-P027] [REV12-P030]'),
]
L=['# Review Base 12 — Blanton & Moustakas (2009): Physical Properties and Environments of Nearby Galaxies','','Status: READY_FOR_HWAO_REVIEW — canonical advisory packet; raw custody preserved and independently reconciled.','',f"Raw custody SHA-256: `{hashlib.sha256(RAW.read_bytes()).hexdigest()}`",'','## 1. Review Identity and Scope Map','',t(['Field','Value'],[('Review key','[REV12-R00]'),('Authors','Michael R. Blanton; John Moustakas'),('Year / journal','2009, Annual Review of Astronomy and Astrophysics 47, 159-210'),('DOI','10.1146/annurev-astro-082708-101734'),('arXiv','0908.3017'),('ADS','2009ARA&A..47..159B'),('Authorized scope','Nearby relatively luminous galaxies: luminosity/stellar/HI mass functions, color and structural distributions, morphology, environment, scaling relations, spirals/S0s/ellipticals, mergers, and 2009 survey systematics.'),('Explicit exclusions','Post-2009 work, uncited browsing spillover, proxy equivalence, causal environmental claims from correlations, and cross-survey densities without IMF/h/band/completeness conversion.')]),'','## 2. Established Findings','',t(['ID','Epistemic type','Bounded finding','Boundary','Confidence','Sources'],E),'','## 3. Open Debates and Tensions','',t(['ID','Topic','Competing positions','Why unresolved / boundary','Sources'],D),'','## 4. Key Measurements and Calibrations','',t(['ID','Value / equation','Units','Definitions and regime','Status / caveat','Sources'],N),'','## 5. What Remained Unknown in 2009','',t(['ID','Gap','Why it matters','Needed test','Sources'],U),'','## 6. Primary-Citation Harvest','']
for s in p:L.append(f"[{s['key']}] {s['authors']} ({s['year']}, {s['journal']}) | title={s['title']} | DOI:{s['doi'] or 'none'}; arXiv:{s['arxiv'] or 'none'}; ADS:{s['ads_bibcode']} | role={s['role']} | review_locator={s['review_locator']} | {s['boundary']} | source_status=PASS_ADS_AND_REVIEW_MEMBERSHIP")
L+=['','### Supporting reviews','']
for s in sr:L.append(f"[{s['key']}] {s['authors']} ({s['year']}, {s['journal']}) | title={s['title']} | DOI:{s['doi'] or 'none'}; arXiv:{s['arxiv'] or 'none'}; ADS:{s['ads_bibcode']} | role=supporting_review | review_locator={s['review_locator']} | {s['boundary']} | source_status=PASS_ADS_AND_REVIEW_MEMBERSHIP")
L+=['','## 7. DO_NOT_USE_UNVERIFIED','']
for s in q:L.append(f"UNCITED_NOT_USABLE | [{s['key']}] {s['title']} | DOI:{s['doi'] or 'none'}; arXiv:{s['arxiv'] or 'none'}; ADS:{s['ads_bibcode'] or 'none'} | {s['quarantine_reason']}")
L+=['UNCITED_NOT_USABLE | color, morphology, concentration, Sérsic index, spectral type, and star-formation state are interchangeable | none | correlated but non-equivalent observables.','UNCITED_NOT_USABLE | environment correlation proves one transformation mechanism | none | causal overreach.','UNCITED_NOT_USABLE | group, nearest-neighbor density, halo mass, cluster membership, and large-scale density are interchangeable | none | estimator mismatch.','UNCITED_NOT_USABLE | mass/luminosity/gas functions from different surveys share one selection volume and h/IMF convention | none | survey and convention mismatch.','UNCITED_NOT_USABLE | post-2009 browsing results | none | outside temporal boundary.','','## 8. Review and Source Identity Ledger','','[REV12-R00] Blanton MR; Moustakas J (2009, Annual Review of Astronomy and Astrophysics) | title=Physical Properties and Environments of Nearby Galaxies | DOI:10.1146/annurev-astro-082708-101734; arXiv:0908.3017; ADS:2009ARA&A..47..159B | role=review_synthesis | source_status=PASS_ADS_CROSSREF_ARXIV','']
for s in p+sr:L.append(f"[{s['key']}] {s['authors']} ({s['year']}, {s['journal']}) | title={s['title']} | DOI:{s['doi'] or 'none'}; arXiv:{s['arxiv'] or 'none'}; ADS:{s['ads_bibcode']} | role={s['role']} | boundary={s['boundary']} | source_status=PASS_ADS_AND_REVIEW_MEMBERSHIP")
L+=['','REVIEW_BASE_12_DR_COMPLETE_REFERENCE_ONLY',''];OUT.write_text('\n'.join(L));print(json.dumps({'packet':str(OUT),'primary':len(p),'supporting':len(sr),'quarantined':len(q),'sha256':hashlib.sha256(OUT.read_bytes()).hexdigest()},sort_keys=True))
