import hashlib,json,re
from pathlib import Path
A=Path('/Users/duhokim/NebulaMind/NebulaMind/.hermes/handoffs/galaxy-evolution/wiki-expansion-20260715');RAW=A/'area_review_20_renzini_2006_DR_RAW_PACKET.md';REG=A/'area_review_20_renzini_2006_CURATED_SOURCE_REGISTRY.json';OUT=A/'area_review_20_renzini_2006_DR_PACKET.md';V=A/'area_review_20_renzini_2006_VALIDATION.json';d=json.loads(REG.read_text());S={x['key']:x for x in d['sources']};q={k for k,x in S.items() if x['status']!='USABLE'}
E=[
('E01','The bulk of stars in massive cluster early-type galaxies formed early, consistent with formation redshift at least about 3 under passive-SFH assumptions.','cluster ETGs, local through z~1.3','high',['P001','P006','P008','P022','P034']),
('E02','Field spheroids show younger luminosity/SSP-equivalent ages and more recent activity on average than mass-matched cluster counterparts.','field versus cluster ETGs to z~1.2','high',['P014','P036','P046','P047']),
('E03','Stellar formation duration anticorrelates with galaxy mass: more massive ETGs are older and more alpha-enhanced.','local ETGs across velocity dispersion','high',['P035','P036','P041','P046']),
('E04','Massive passive galaxies already existed by z~1-2, while lower-mass red-sequence membership continued to build.','massive ETGs and red sequence','moderate-high',['P006','P010','P011','P040']),
('E05','The comoving abundance of passive ETGs becomes less secure and generally lower beyond z~1, with strong selection and cosmic-variance dependence.','high-redshift cosmological fields','moderate',['P010','P011','P040']),
('E06','SSP-equivalent ages are strongly luminosity weighted, so small young components can dominate optical age diagnostics.','integrated unresolved stellar populations','high',['P009','P038','P046']),
('E07','The cluster color-magnitude relation is very tight and its slope is primarily consistent with a mass-metallicity sequence under passive models.','Coma/Virgo and distant clusters','high',['P008','P027','P034']),
('E08','Fundamental-Plane zero-point evolution is broadly consistent with passive M/L evolution but is altered by sample selection and progenitor bias.','ETGs to z~1.3','high',['P014','P018','P019','P026','P037','P039','P047']),
('E09','Absolute stellar masses and M/L depend strongly on the low-mass IMF and SPS prescription; Chabrier-like and Salpeter-like normalizations are not interchangeable.','SPS modeling','high',['P009','P015','P029']),
('E10','Massive ETGs show enhanced alpha-to-iron ratios, consistent with short dominant star-formation timescales under chemical-evolution assumptions.','local massive ETGs','high',['P035','P036','P046']),
('E11','ULIRGs and high-redshift starbursts are plausible dissipative progenitor phases, but object-by-object ancestry was not established in 2006.','ULIRGs/SMGs, high-z','moderate',['P011','P024']),
('E12','Morphological, red-color and passive-spectral selections identify overlapping but non-identical ETG populations.','local/high-z survey selection','high',['P002','P005','P037','P047'])]
Db=[
('D01','CMR scatter from metallicity alone versus residual age/frosting variation','Optical colors suffer age-metallicity degeneracy and young light dominates.',['P008','P009','P027','P038','P046']),
('D02','Fundamental-Plane tilt from stellar populations/IMF versus structural non-homology/dark matter','High-z resolved dynamics and IMF-independent masses were unavailable at scale.',['P004','P012','P018','P019','P031']),
('D03','Small apparent FP evolution versus strong progenitor-bias correction','Individual descendants cannot be followed and newly quenched systems enter samples over time.',['P037','P039','P047']),
('D04','Salpeter-like versus turnover IMF','Unresolved populations do not directly count low-mass stars, shifting M/L by order two.',['P009','P015','P029']),
('D05','Nearly constant versus substantially declining massive-ETG number density to z~1','Selection, completeness, cosmic variance and passive corrections differed.',['P010','P011','P040']),
('D06','Post-starbursts as major transformation phases versus minor frosting on old spheroids','Optical SSP ages poorly constrain the young mass fraction.',['P009','P017','P046','P047']),
('D07','Supernova feedback alone versus AGN feedback for massive-halo quenching','Feedback coupling and cooling prescriptions were parameterized in 2006 models.',['P016','P036']),
('D08','Main-sequence/RGB-dominated versus strong TP-AGB contribution to intermediate-age near-IR light','TP-AGB lifetimes and mass loss were poorly calibrated.',['P009','P029','P038'])]
N=[
('N01','Cluster FP M/L evolution','Delta log(M/L_B) approximately -0.46 z','cluster ETGs to z~1','passband, IMF, cosmology, selection and passive-SFH dependent',['P037','P039']),
('N02','Field FP M/L evolution','roughly -0.55 z in review synthesis; individual samples can be steeper','field ETGs to z~1','mass and morphology-selection dependent',['P014','P047']),
('N03','Age-metallicity degeneracy','partial log age / partial [Fe/H] at fixed B-V approximately -0.9','SSP isochrone colors','model and passband heuristic',['P030','P038']),
('N04','Worthey 3/2 rule','factor 3 metallicity error mimics factor 2 age error','broad-band optical SSPs','heuristic for old populations',['P038']),
('N05','Cluster CMR intrinsic scatter','less than about 0.05 mag in U-V/V-K','Coma/Virgo early types','selection, photometric and aperture dependent',['P008']),
('N06','Alpha enhancement range','[Mg/Fe] roughly 0.05-0.3, increasing with velocity dispersion','local ETGs above about 100 km/s','index-response and SSP-equivalent interpretation dependent',['P035','P036','P046']),
('N07','Local spheroid stellar-mass share','review-era estimate about 75%, with pure ellipticals about 22%','z~0 census','IMF, decomposition and dust dependent',['P021']),
('N08','Field-cluster SSP-equivalent age offset','field ETGs about 1-2 Gyr younger on average','mass-matched z<1 samples','progenitor and luminosity-weighting dependent',['P014','P036','P047']),
('N09','GOODS-N field FP evolution','mean d log(M/L_B)/dz about -0.72 with quoted statistical/systematic terms','226 morphologically selected spheroid/bulge systems at 0.2<z<1.2','luminosity bias and mass dependence retained',['P047']),
('N10','Red-sequence stellar-mass growth','order factor 2 since z~1 in COMBO-17 analysis','red-selected galaxies','color selection, mass completeness, IMF and merger interpretation dependent',['P010'])]
U=[
('U01','Sizes and structural evolution of passive galaxies beyond z~1.5','It distinguishes compact formation from later dry envelope assembly.','Large rest-frame-optical high-resolution samples.'),('U02','Physical coupling of AGN feedback','Semi-analytic quenching required energy injection without resolved coupling.','Multiphase outflow and cooling-flow measurements plus resolved simulations.'),('U03','IMF variation with galaxy mass and epoch','It rescales M/L, stellar mass and inferred formation efficiency.','Gravity-sensitive spectra plus dynamical/lensing masses.'),('U04','The detailed field red-sequence assembly path at 0<z<1','Number-density studies disagreed on transformation rates.','Wide mass-complete spectroscopy with uniform morphology/color selection.'),('U05','Resolved age and abundance gradients at high redshift','Integrated spectra could not distinguish dissipative cores from later envelope growth.','AO/space-resolved spectroscopy with matched local diagnostics.'),('U06','The TP-AGB near-IR contribution near 1 Gyr','It can shift high-z stellar masses by order two.','Empirical intermediate-age cluster calibration and improved stellar tracks.')]
lines=['# Review Base 20 — Renzini 2006 — Curated Deep Research Packet','', '> Advisory/reference-only synthesis. Raw Deep Research custody is preserved separately. No wiki, database, trust, deployment, publication, repository, or conversation mutation is authorized.','', '## 1. Review identity and scope map','', '- Review: Stellar Population Diagnostics of Elliptical Galaxy Formation (2006).','- Composite identity: DOI `10.1146/annurev.astro.44.051905.092450`; arXiv `astro-ph/0603479`; ADS `2006ARA&A..44..141R`.','- Scope: local and high-redshift early-type stellar populations, scaling relations, formation epochs, demographic evolution and model tensions through 2006.','- Boundary: formation of stars, quenching, morphological transformation and final assembly are separate clocks.','']
lines+=['## 2. Established findings','']
for i,s,reg,c,refs in E:lines += [f'### REV20-{i}',f'- Bounded statement: {s}',f'- Population/redshift/environment: {reg}',f'- Confidence: {c}',f'- Sources: '+', '.join(f'[REV20-{x}]' for x in refs),'']
lines+=['## 3. Open debates and tensions','']
for i,s,w,refs in Db:lines += [f'### REV20-{i}',f'- Competing positions: {s}.',f'- Why unresolved in 2006: {w}',f'- Sources: '+', '.join(f'[REV20-{x}]' for x in refs),'']
lines+=['## 4. Key measurements and calibrations','']
for i,n,v,frame,u,refs in N:lines += [f'### REV20-{i}',f'- Measurement/calibration: {n}.',f'- Value/equation: {v}.',f'- Population/redshift/environment: {frame}.',f'- Uncertainty/status: {u}.',f'- Sources: '+', '.join(f'[REV20-{x}]' for x in refs),'']
lines+=['## 5. What remained unknown in 2006','']
for i,s,w,need in U:lines += [f'### REV20-{i}',f'- Unknown: {s}.',f'- Why it mattered: {w}',f'- Decisive need: {need}','']
lines+=['## 6. Curated source registry','', '| Key | Status | Role | Composite identity | Title / candidate | Boundary |','|---|---|---|---|---|---|']
for x in d['sources']:
 ident='; '.join(z for z in [f'DOI {x.get("doi")}' if x.get('doi') else None,f'arXiv {x.get("arxiv")}' if x.get('arxiv') else None,f'ADS {x.get("ads_bibcode")}' if x.get('ads_bibcode') else None] if z) or 'none';title=(x.get('title') or x.get('candidate') or '').replace('|','/');bound=(x.get('scientific_boundary') or x.get('reason') or '').replace('|','/');lines.append(f'| REV20-{x["key"]} | {x["status"]} | {x["role"]} | {ident} | {title} | {bound} |')
lines+=['','## 7. DO_NOT_USE_UNVERIFIED quarantine','', '- Thirty rows are `UNCITED_NOT_USABLE`: seven browsing candidates absent from the complete review bibliography, one invalid citation/title/bibcode hybrid, and twenty-two post-2006 retrospective sources named in the raw quarantine. None is cited above.','', '## 8. Composite identity and boundary ledger','', '- Forty usable primary papers are exact bibliography members with reconciled composite identities; three cited papers supplement 37 usable raw rows after seven spillovers and one identity hybrid were quarantined.','- Progenitor bias, changing red-sequence membership and morphology/color/spectral selection remain attached to every demographic claim.','- Luminosity-, mass- and SSP-equivalent ages are not merged; small young components can dominate SSP-equivalent age.','- [Z/H], [Fe/H], [alpha/Fe], Mg indices and colors remain separate, with abundance-response/SPS assumptions.','- IMF, SPS, isochrone, passband, aperture, K-correction, cosmology and passive-evolution assumptions remain attached.','- Cluster, group and field environments require mass- and selection-matched comparisons.','- Formation redshift and final assembly redshift are not interchangeable; dry mergers do not reset stellar birth times.','- Raw custody is preserved unchanged; this packet performs no live mutation.','', 'REVIEW_BASE_20_CANONICAL_COMPLETE_REFERENCE_ONLY','']
OUT.write_text('\n'.join(lines));t=OUT.read_text();claims=t.split('## 6. Curated source registry',1)[0];refs=set(re.findall(r'REV20-(P\d{3})',claims));counts={'established':len(E),'debates':len(Db),'measurements':len(N),'unknowns':len(U),'usable_primary':40,'supporting_reviews':0,'quarantined':30};o={'status':'PASS','counts':counts,'all_claim_refs_usable':all(S[k]['status']=='USABLE' for k in refs),'quarantine_reference_violations':sorted(refs&q),'marker_pass':t.rstrip().endswith('REVIEW_BASE_20_CANONICAL_COMPLETE_REFERENCE_ONLY'),'raw_preserved_sha256':hashlib.sha256(RAW.read_bytes()).hexdigest(),'registry_sha256':hashlib.sha256(REG.read_bytes()).hexdigest(),'canonical_sha256':hashlib.sha256(OUT.read_bytes()).hexdigest()};o['pass']=o['all_claim_refs_usable'] and not o['quarantine_reference_violations'] and o['marker_pass'] and min(len(E),len(Db),len(N),len(U))>=6 and counts['usable_primary']>=40
if not o['pass']:o['status']='FAIL'
V.write_text(json.dumps(o,indent=2)+'\n');assert o['pass'];print(o)
