import hashlib,json
from pathlib import Path
A=Path('/Users/duhokim/NebulaMind/NebulaMind/.hermes/handoffs/galaxy-evolution/wiki-expansion-20260715');RAW=A/'area_review_16_carilli_walter_2013_DR_RAW_PACKET.md';REG=A/'area_review_16_carilli_walter_2013_CURATED_SOURCE_REGISTRY.json';OUT=A/'area_review_16_carilli_walter_2013_DR_PACKET.md';r=json.loads(REG.read_text());p=[x for x in r['sources'] if x['source_status']=='PASS' and x['role']!='supporting_review'];sr=[x for x in r['sources'] if x['source_status']=='PASS' and x['role']=='supporting_review'];q=[x for x in r['sources'] if x['source_status']!='PASS'];assert(len(p),len(sr),len(q))==(40,4,11)
def t(h,rows):
 e=lambda v:str(v).replace('|','\\|').replace('\n',' ')
 return '\n'.join(['| '+' | '.join(h)+' |','|'+'|'.join(['---']*len(h))+'|']+['| '+' | '.join(e(v) for v in z)+' |' for z in rows])
E=[
('REV16-E01','review synthesis','By 2013, molecular gas had been detected in roughly two hundred z>1 galaxies spanning quasar hosts, SMGs, radio galaxies, and increasing samples of main-sequence disks.','Heterogeneous, luminosity/lensing/AGN-selected samples; not a volume-complete census.','High.','[REV16-R00] [REV16-P002] [REV16-P003] [REV16-P005] [REV16-P042]'),
('REV16-E02','measurement','Massive z~1-2.5 main-sequence disks commonly have much larger molecular gas fractions than comparable local spirals.','CO transition/excitation, alpha_CO, helium, stellar IMF, selection, and gas-fraction definition apply.','High.','[REV16-P002] [REV16-P003] [REV16-P013]'),
('REV16-E03','measurement/calibration','Main-sequence disks and compact merger/starbursts occupy different characteristic depletion-time regimes when population-specific CO conversions are adopted.','The apparent separation depends on alpha_CO, excitation, lensing, SFR IMF, size, and regression choice.','High for characteristic difference; discreteness debated.','[REV16-P001] [REV16-P004] [REV16-P015] [REV16-P030] [REV16-P042]'),
('REV16-E04','measurement','CO excitation ladders differ by population: high-J-only measurements can miss extended, low-excitation molecular reservoirs.','Line ratios, aperture/beam, differential lensing, CMB, and one- versus multi-component LVG models apply.','High.','[REV16-P006] [REV16-P008] [REV16-P012] [REV16-P018] [REV16-P019]'),
('REV16-E05','calibration','Molecular masses inferred from CO are dominated by alpha_CO and excitation-systematics; low ULIRG-like and high Galactic-like conversions are not interchangeable.','State L-prime(1-0), r_J1, helium, metallicity, surface density, dynamics, and population.','High.','[REV16-P001] [REV16-P026] [REV16-P030] [REV16-P031]'),
('REV16-E06','measurement','CO and [CII] imaging can resolve kiloparsec-scale dynamics, multiplicity, mergers, compact starbursts, and rotating disks at high redshift.','Inclination, lens model, beam smearing, tracer extent, noncircular motions, and unresolved companions apply.','High.','[REV16-P009] [REV16-P016] [REV16-P017] [REV16-P043]'),
('REV16-E07','measurement','[CII] 158 micron is an exceptionally bright high-redshift line useful for redshift confirmation and dynamics, but its luminosity mixes neutral and ionized phases.','PDR fraction, diffuse ionized gas, optical depth, abundance, AGN, FIR definition, and lensing apply.','High.','[REV16-P009] [REV16-P010] [REV16-P021]'),
('REV16-E08','measurement','L_[CII]/L_FIR tends to decrease in warm, very luminous compact systems, while some less-luminous high-z sources show stronger ratios.','Heterogeneous selection, FIR/TIR definition, dust temperature, AGN, surface brightness, and nondetections apply.','High for trend; physical partition model-dependent.','[REV16-P009] [REV16-P010] [REV16-P021]'),
('REV16-E09','measurement/model','[CI] and dust continuum provide complementary gas constraints but require abundance, excitation, opacity, temperature, dust-to-gas, and CMB assumptions.','No tracer is conversion-free; matched apertures and lens correction required.','High.','[REV16-P011] [REV16-P030] [REV16-P041]'),
('REV16-E10','calibration','The rising CMB both heats cold gas/dust and reduces observed line/continuum contrast against the background.','Effect grows with redshift and is strongest for cold components; radiative equilibrium, optical depth, and observing band apply.','High.','[REV16-P025]'),
('REV16-E11','simulation/model','Cold accretion and gravitational instability can sustain gas-rich turbulent clumpy disks, while mergers can also produce or re-form rotating structures.','Simulations differ in feedback, cooling, resolution, halo regime, and observational forward modeling.','High for model possibilities; pathway attribution uncertain.','[REV16-P023] [REV16-P024] [REV16-P032] [REV16-P033] [REV16-P034]'),
('REV16-E12','measurement','CO in z=6.42 J1148+5251 established large molecular reservoirs in an early quasar host, with [CII] later resolving an intense compact starburst.','One extreme AGN host; alpha_CO, excitation, inclination, FIR AGN fraction, and dynamical geometry apply.','High.','[REV16-P005] [REV16-P009] [REV16-P017]'),
('REV16-E13','measurement','Broad [CII] wings in J1148+5251 provided evidence for a galaxy-scale quasar-driven outflow at z>6.','Outflow mass/rate depend on [CII] phase fraction, abundance, density, radius, geometry, and velocity definition.','High for broad wings; quantitative flux model-dependent.','[REV16-P007]'),
]
D=[
('REV16-D01','CO conversion','Two population-dependent alpha_CO values versus a continuous metallicity/surface-density/dispersion-dependent conversion.','Dynamical masses, dust, metallicity, dark matter, IMF, and multiphase structure remain degenerate.','[REV16-P001] [REV16-P026] [REV16-P030] [REV16-P031]'),
('REV16-D02','Star-formation sequences','Distinct disk and starburst gas-SFR sequences versus one continuous relation after dynamical-time/conversion corrections.','Population-dependent alpha_CO, selection, size, IMF, and regression can create or erase offsets.','[REV16-P004] [REV16-P015] [REV16-P042] [REV16-P046]'),
('REV16-D03','SMG morphology','Major-merger dominance versus a mixed population including extended disks and multiples.','Angular resolution, tracer/excitation, lensing, beam smearing, and merger-stage selection differ.','[REV16-P016] [REV16-P018] [REV16-P019] [REV16-P043]'),
('REV16-D04','Disk fueling','Cold-stream accretion with violent disk instability versus merger-driven supply and rapid disk re-formation.','Kinematic rotation is not a unique formation-history diagnostic.','[REV16-P023] [REV16-P024] [REV16-P032] [REV16-P033] [REV16-P034]'),
('REV16-D05','[CII] deficit','Ionization parameter/dust-bounded regions, high gas temperature/saturation, compactness, AGN, opacity, or phase mix as dominant cause.','Small heterogeneous samples and mixed FIR definitions permit several explanations.','[REV16-P009] [REV16-P010] [REV16-P021] [REV16-P040]'),
('REV16-D06','[CI] gas tracing','[CI] as a stable total-molecular-mass tracer versus abundance/excitation/chemistry sensitivity.','Carbon abundance, optical depth, partition function, cosmic rays, and phase co-spatiality uncertain.','[REV16-P011] [REV16-P040] [REV16-P041]'),
('REV16-D07','High-J representativeness','Single warm component inferred from high-J CO versus additional extended cold gas revealed by low-J lines.','Beam, sensitivity, lensing, and excitation-model choices differ.','[REV16-P006] [REV16-P008] [REV16-P012] [REV16-P018] [REV16-P019]'),
('REV16-D08','Maximum starbursts/feedback','Compact systems near radiation-pressure/Eddington-like limits versus geometry/conversion artifacts and short duty cycles.','Inclination, size, opacity, IMF, AGN FIR, and alpha_CO control surface densities.','[REV16-P009] [REV16-P017] [REV16-P007]'),
]
N=[
('REV16-N01',"L'_CO = 3.25e7 (S_CO Delta v) D_L^2 nu_obs^-2 (1+z)^-3",'K km s^-1 pc^2','S_CO Delta v in Jy km s^-1, D_L in Mpc, nu_obs in GHz; brightness-temperature line luminosity.','Correct lensing and aperture; distinguish L from L-prime and state transition.','[REV16-P022]'),
('REV16-N02',"M_mol = alpha_CO L'_CO(1-0)",'Msun','Molecular mass from CO(1-0) brightness luminosity; specify whether helium is included.','alpha_CO approximately 0.8 for compact local-ULIRG convention versus approximately 4.3 including helium for Milky-Way-like disks; not universal.','[REV16-P001] [REV16-P031]'),
('REV16-N03',"r_J1 = L'_CO(J->J-1) / L'_CO(1-0)",'dimensionless','Excitation correction from observed transition J to CO(1-0).','Population/SLED, aperture, optical depth, CMB, and differential lensing apply; never assume r=1 silently.','[REV16-P006] [REV16-P008] [REV16-P012]'),
('REV16-N04','f_gas,bary = M_mol/(M_mol+M_star); alternatively mu_gas=M_mol/M_star','dimensionless','Two non-equivalent gas-fraction conventions.','State alpha_CO, helium, stellar IMF, atomic-gas omission, and whether upper limits are included.','[REV16-P002] [REV16-P003] [REV16-P013]'),
('REV16-N05','t_dep = M_mol/SFR; SFE = SFR/M_mol = 1/t_dep','yr; yr^-1','Molecular depletion time and inverse efficiency.','No inflow/recycling; state alpha_CO, IMF/SFR calibration, AGN FIR subtraction, and population.','[REV16-P004] [REV16-P015] [REV16-P042]'),
('REV16-N06','Sigma_SFR = 2.5e-4 (Sigma_gas / 1 Msun pc^-2)^1.4','Msun yr^-1 kpc^-2','Published disk-averaged local global Schmidt-law fit; gas includes stated atomic+molecular convention.','Index uncertainty about 0.15; IMF, alpha_CO, helium, area, and sample regime apply.','[REV16-P046]'),
('REV16-N07','M_dyn/Msun = 2.33e5 (v_c/km s^-1)^2 (R/kpc)','Msun','Circular dynamical mass within radius R; if v_obs=v_c sin i then divide by sin^2 i.','Geometry, inclination, beam smearing, pressure support, noncircular motion, lens model, and tracer radius apply.','[REV16-P009] [REV16-P012] [REV16-P016] [REV16-P017]'),
('REV16-N08','T_CMB(z) = 2.725(1+z)','K','CMB temperature sets heating floor and background against line/dust brightness.','Observed contrast depends on excitation/dust temperature and optical depth, not temperature floor alone.','[REV16-P025]'),
('REV16-N09','[CII] rest wavelength approximately 157.74 micron; rest frequency approximately 1900.54 GHz','micron; GHz','Fine-structure transition used for high-z redshifts, dynamics, and ISM diagnostics.','Phase mixture, optical depth, abundance, CMB, lensing, and FIR definition apply.','[REV16-P009] [REV16-P010] [REV16-P021]'),
('REV16-N10','L_intrinsic = L_observed / mu','same luminosity units','Scalar lensing correction using magnification mu.','Differential magnification makes one mu invalid when CO transitions, dust, or [CII] have different spatial distributions.','[REV16-P018] [REV16-P021] [REV16-P041]'),
]
U=[
('REV16-U01','Unbiased molecular-gas census across mass, SFR, metallicity, and redshift.','Known samples were bright, AGN/SMG/color/lensing selected.','Blind low-J CO/[CII] spectral surveys with complete selection functions and deep continuum counterparts.','[REV16-R00] [REV16-P002] [REV16-P003]'),
('REV16-U02','Physical and population dependence of alpha_CO at high redshift.','It dominates gas fractions, depletion times, and inferred sequence offsets.','Same galaxies measured with dynamics, dust, optically thin tracers, metallicity, and resolved CO ladders.','[REV16-P001] [REV16-P026] [REV16-P030] [REV16-P031]'),
('REV16-U03','Frequency of mergers versus unstable rotating disks among SMGs and main-sequence systems.','Formation pathway changes duty cycle and feedback interpretation.','Unlensed sub-kpc multi-transition imaging with matched stellar/dust morphology and forward-modeled kinematics.','[REV16-P016] [REV16-P018] [REV16-P019] [REV16-P024]'),
('REV16-U04','Origin and phase partition of [CII] and its luminosity deficit.','Sets [CII]-based SFR, gas, and dynamical interpretations.','Resolved [CII], [NII], [OI], CO, continuum, and ionized-gas observations over luminosity/surface-brightness range.','[REV16-P010] [REV16-P014] [REV16-P021] [REV16-P040]'),
('REV16-U05','Cold-gas content and excitation in ordinary reionization-era galaxies.','Quasar hosts were extreme and CMB/metallicity effects grow rapidly.','Deep low-excitation molecular, [CII]/[OIII], dust, and lens-independent samples with CMB-aware radiative transfer.','[REV16-P005] [REV16-P009] [REV16-P020] [REV16-P025]'),
('REV16-U06','Complete inflow-outflow-recycling connection to high gas fractions.','Gas reservoirs alone do not reveal supply, residence time, or permanent ejection.','CGM absorption/emission plus resolved ISM dynamics and cosmological multiphase simulations for matched samples.','[REV16-P007] [REV16-P023] [REV16-P033] [REV16-P034]'),
]
L=['# Review Base 16 — Carilli & Walter (2013): Cool Gas in High-Redshift Galaxies','','Status: READY_FOR_HWAO_REVIEW — canonical advisory packet; raw custody preserved and independently reconciled.','',f"Raw custody SHA-256: `{hashlib.sha256(RAW.read_bytes()).hexdigest()}`",'','## 1. Review Identity and Scope Map','',t(['Field','Value'],[('Review key','[REV16-R00]'),('Authors','C. L. Carilli; F. Walter'),('Year / journal','2013, Annual Review of Astronomy and Astrophysics 51, 105-161'),('DOI','10.1146/annurev-astro-082812-140953'),('arXiv','1301.0371'),('ADS','2013ARA&A..51..105C'),('Authorized scope','Molecular/atomic cool gas in z>1 quasars, SMGs, radio galaxies, main-sequence disks, and early galaxies: CO, [CI], [CII], dust, masses, excitation, dynamics, star formation, lensing, and CMB.'),('Explicit exclusions','Post-2013 ALMA/JWST; uncited browsing; silent alpha_CO/r_J1/lensing conversions; mixed f_gas definitions; population mixing; one-phase [CII] interpretation; geometry-free dynamical masses.')]),'','## 2. Established Findings','',t(['ID','Epistemic type','Bounded finding','Regime / boundary','Confidence','Sources'],E),'','## 3. Open Debates and Tensions','',t(['ID','Topic','Competing positions','Why unresolved / boundary','Sources'],D),'','## 4. Key Measurements and Model Calibrations','',t(['ID','Value / equation','Units','Definitions and regime','Status / caveat','Sources'],N),'','## 5. What Remained Unknown in 2013','',t(['ID','Gap','Why it matters','Needed test','Sources'],U),'','## 6. Primary-Citation Harvest','']
for s in p:L.append(f"[{s['key']}] {s['authors']} ({s['year']}, {s['journal']}) | title={s['title']} | DOI:{s['doi'] or 'none'}; arXiv:{s['arxiv'] or 'none'}; ADS:{s['ads_bibcode']} | role={s['role']} | review_locator={s['review_locator']} | {s['boundary']} | source_status=PASS_ADS_AND_REVIEW_MEMBERSHIP")
L+=['','### Supporting reviews and textbook context','']
for s in sr:L.append(f"[{s['key']}] {s['authors']} ({s['year']}, {s['journal']}) | title={s['title']} | DOI:{s['doi'] or 'none'}; arXiv:{s['arxiv'] or 'none'}; ADS:{s['ads_bibcode']} | role=supporting_review | review_locator={s['review_locator']} | {s['boundary']} | source_status=PASS_ADS_AND_REVIEW_MEMBERSHIP")
L+=['','## 7. DO_NOT_USE_UNVERIFIED','']
for s in q:L.append(f"UNCITED_NOT_USABLE | [{s['key']}] {s['title']} | DOI:{s['doi'] or 'none'}; arXiv:{s['arxiv'] or 'none'}; ADS:{s['ads_bibcode'] or 'none'} | {s['quarantine_reason']}")
L+=['UNCITED_NOT_USABLE | gas mass without alpha_CO, helium, transition, and r_J1 | none | conversion context missing.','UNCITED_NOT_USABLE | Mgas/Mstar and Mgas/(Mgas+Mstar) called the same gas fraction | none | denominator mismatch.','UNCITED_NOT_USABLE | high-J CO assumed to trace all cold gas | none | excitation and aperture mismatch.','UNCITED_NOT_USABLE | one lens magnification silently applied across distinct tracers | none | differential lensing.','UNCITED_NOT_USABLE | [CII] assigned to a single phase | none | neutral/ionized phase mixture.','UNCITED_NOT_USABLE | post-2013 ALMA/JWST result | none | outside temporal boundary.','','## 8. Composite Source Identity Ledger','','[REV16-R00] Carilli, C. L.; Walter, F. (2013, Annual Review of Astronomy and Astrophysics) | title=Cool Gas in High-Redshift Galaxies | DOI:10.1146/annurev-astro-082812-140953; arXiv:1301.0371; ADS:2013ARA&A..51..105C | role=review_synthesis_and_labeled_2013_review_calibrations | source_status=PASS_ADS_CROSSREF_ARXIV','']
for s in p+sr:L.append(f"[{s['key']}] {s['authors']} ({s['year']}, {s['journal']}) | title={s['title']} | DOI:{s['doi'] or 'none'}; arXiv:{s['arxiv'] or 'none'}; ADS:{s['ads_bibcode']} | role={s['role']} | boundary={s['boundary']} | source_status=PASS_ADS_AND_REVIEW_MEMBERSHIP")
L+=['','REVIEW_BASE_16_DR_COMPLETE_REFERENCE_ONLY',''];OUT.write_text('\n'.join(L));print(json.dumps({'packet':str(OUT),'primary':len(p),'supporting':len(sr),'quarantined':len(q),'sha256':hashlib.sha256(OUT.read_bytes()).hexdigest()},sort_keys=True))
