import hashlib,json
from pathlib import Path
A=Path('/Users/duhokim/NebulaMind/NebulaMind/.hermes/handoffs/galaxy-evolution/wiki-expansion-20260715');RAW=A/'area_review_15_veilleux_cecil_bland_hawthorn_2005_DR_RAW_PACKET.md';REG=A/'area_review_15_veilleux_cecil_bland_hawthorn_2005_CURATED_SOURCE_REGISTRY.json';OUT=A/'area_review_15_veilleux_cecil_bland_hawthorn_2005_DR_PACKET.md';r=json.loads(REG.read_text());p=[x for x in r['sources'] if x['source_status']=='PASS'];q=[x for x in r['sources'] if x['source_status']!='PASS'];assert(len(p),len(q))==(42,17)
def t(h,rows):
 e=lambda v:str(v).replace('|','\\|').replace('\n',' ')
 return '\n'.join(['| '+' | '.join(h)+' |','|'+'|'.join(['---']*len(h))+'|']+['| '+' | '.join(e(v) for v in z)+' |' for z in rows])
E=[
('REV15-E01','review synthesis/observation','Galaxy-scale winds occur in intense local starbursts, infrared-luminous systems, some active galaxies, and high-redshift star-forming galaxies.','Detection fraction depends on orientation, tracer, aperture, sensitivity, and velocity criterion; presence does not prove halo escape.','High.','[REV15-R00] [REV15-P004] [REV15-P009] [REV15-P010] [REV15-P012]'),
('REV15-E02','analytic/calibration','Thermalized stellar ejecta and supernova energy can form a hot, overpressured starburst wind whose ideal adiabatic speed scales as the square root of energy injection divided by mass injection.','Chevalier-Clegg steady spherical injection; thermalization efficiency, extra mass loading, cooling, injection radius, and gravity apply.','High for model scaling.','[REV15-P003] [REV15-P005] [REV15-P015]'),
('REV15-E03','observation','Resolved warm-ionized winds commonly show bipolar or conical structures aligned with the host minor axis and bounded by filaments or shells.','Projection, extinction, disk inclination, density-squared emissivity, and local merger/AGN geometry apply.','High.','[REV15-P006] [REV15-P024] [REV15-P029] [REV15-P036] [REV15-P038]'),
('REV15-E04','observation','Galactic winds are multiphase: hot X-ray plasma, warm ionized gas, cool neutral absorption, warm molecular gas, dust, and relativistic particles trace different components.','No one tracer measures total mass, energy, momentum, metals, or volume filling factor.','High.','[REV15-P016] [REV15-P022] [REV15-P026] [REV15-P027] [REV15-P035] [REV15-P037]'),
('REV15-E05','simulation/observation','Soft X-ray and optical filament emission can be dominated by shocked interfaces and entrained ambient gas rather than the volume-filling free wind.','Emission-measure weighting, nonequilibrium ionization, abundance, absorption, conduction/mixing, and unresolved interfaces apply.','High.','[REV15-P015] [REV15-P016] [REV15-P028]'),
('REV15-E06','observation','Blueshifted Na I D and UV interstellar absorption reveal cool outflowing gas with covering, saturation, ionization, depletion, and geometry corrections.','Sightline and foreground-resonance absorption; velocity centroids/maxima and global solid angle must be stated separately.','High.','[REV15-P007] [REV15-P008] [REV15-P009] [REV15-P010] [REV15-P011] [REV15-P022]'),
('REV15-E07','observation','Extraplanar warm-ionized emission correlates with intense star formation, supporting disk-wide activity and star-formation surface density as wind predictors.','Edge-on local sample; sensitivity, dust, area definition, and diffuse-ionized-gas contamination apply.','High.','[REV15-P004] [REV15-P027] [REV15-P030]'),
('REV15-E08','measurement/model','Observed cool/warm velocities can approach or exceed model escape speeds in some systems, but permanent escape is not established by line-of-sight speed alone.','Potential shape/extent, projection, drag, phase exchange, halo gas, and launch radius apply.','High for caution; object-dependent escape.','[REV15-P007] [REV15-P011] [REV15-P017] [REV15-P021] [REV15-P031]'),
('REV15-E09','simulation','Dwarf-galaxy simulations can eject freshly synthesized metals more efficiently than the bulk interstellar gas.','Two-dimensional injection/cooling/halo prescriptions; metal escape differs from total gas loss.','High within modeled regime.','[REV15-P017] [REV15-P021]'),
('REV15-E10','observation','At z~3, interstellar absorption blueshifts and Ly-alpha/emission-line offsets provide strong evidence for widespread outflows in UV-selected star-forming galaxies.','Stacking, resonant transfer, systemic-redshift tracer, sample selection, and unresolved geometry apply.','High.','[REV15-P012] [REV15-P013] [REV15-P025] [REV15-P039]'),
('REV15-E11','analytic/simulation','Feedback-driven mass, energy, and metal loss can alter dwarf-galaxy evolution, luminosity functions, and IGM enrichment in models.','Cosmological implementations were subgrid/parameterized; coupling, recycling, phase structure, and resolution dominate quantitative outcomes.','High for qualitative relevance.','[REV15-P018] [REV15-P019] [REV15-P020] [REV15-P021] [REV15-P034]'),
('REV15-E12','observation/analytic','AGN can contribute substantial mechanical power and shape circumnuclear/outflow kinematics, especially in composite and active systems.','AGN versus starburst attribution requires energetics, geometry, age, radio/X-ray structure, and phase-resolved coupling.','High for mixed driving; source partition object-dependent.','[REV15-P010] [REV15-P033] [REV15-P036]'),
]
D=[
('REV15-D01','Driving channel','Hot thermal pressure versus radiation pressure, cosmic rays, magnetic stresses, jets, or AGN winds.','Multiple channels coexist; coupling and phase diagnostics were incomplete.','[REV15-P003] [REV15-P005] [REV15-P010] [REV15-P033] [REV15-P036]'),
('REV15-D02','Thermalization and mass loading','Efficient supernova/wind thermalization with modest loading versus strong cooling and heavy entrainment.','The free wind is faint; X-rays emphasize interfaces, leaving energy and mass injection degenerate.','[REV15-P003] [REV15-P005] [REV15-P015] [REV15-P016]'),
('REV15-D03','Cool-cloud acceleration','Ram-pressure entrainment of pre-existing clouds versus in-situ cooling/fragmentation and other forces.','Hydrodynamic cloud destruction times conflicted with observed cool-gas extent and speed.','[REV15-P008] [REV15-P009] [REV15-P022] [REV15-P028]'),
('REV15-D04','Escape versus fountain','Permanent escape into the IGM versus slowing, mixing, and recycling through a halo fountain.','Projection and uncertain halo potential/drag prevent trajectory reconstruction.','[REV15-P007] [REV15-P011] [REV15-P017] [REV15-P021] [REV15-P031]'),
('REV15-D05','Mass and energy census','Cool/warm phases dominate measured mass versus hot phase dominates energy/metals.','Different tracers have incompatible density, geometry, ionization, and filling-factor biases.','[REV15-P009] [REV15-P015] [REV15-P016] [REV15-P022] [REV15-P026]'),
('REV15-D06','High-z impact','Winds as principal IGM-enrichment/feedback mechanism versus limited transport and strong recycling.','Sparse direct halo constraints and parameterized cosmological winds allowed broad outcomes.','[REV15-P012] [REV15-P013] [REV15-P020] [REV15-P025] [REV15-P039]'),
('REV15-D07','AGN/starburst partition','AGN-dominated versus starburst-dominated power in composite ULIRGs and nuclear outflows.','Bolometric corrections, duty cycles, obscuration, coupling, and spatial overlap are uncertain.','[REV15-P010] [REV15-P033] [REV15-P036]'),
('REV15-D08','Wind threshold','A sharp star-formation intensity threshold versus a continuous probability/sensitivity relation.','Area definitions, inclination, tracer depth, and selection can create or blur a threshold.','[REV15-P004] [REV15-P027] [REV15-P030]'),
]
N=[
('REV15-N01','v_infinity = (2 Edot / Mdot)^(1/2)','velocity; commonly km s^-1','Ideal adiabatic terminal speed for total injected mechanical energy rate Edot and injected plus loaded mass rate Mdot.','Chevalier-Clegg scaling; multiply Edot by retained thermalization and include all loading in Mdot; neglects gravity/radiative loss.','[REV15-P003] [REV15-P005]'),
('REV15-N02','Edot_* approximately 7e41 (SFR / 1 Msun yr^-1) erg s^-1 after continuous-starburst equilibrium','erg s^-1','Order-of-magnitude stellar-wind plus supernova mechanical input for a stated population-synthesis IMF and age.','Injection, not observed retained wind power; IMF, metallicity, age, and thermalization apply.','[REV15-P005]'),
('REV15-N03','eta_phase = Mdot_out,phase / SFR','dimensionless','Mass-loading factor for an explicitly named gas phase, SFR calibration, radius, geometry, velocity definition, and ionization/depletion correction.','Do not compare eta values unless numerator phase and denominator conventions match.','[REV15-P008] [REV15-P009] [REV15-P010] [REV15-P011]'),
('REV15-N04','Mdot_thin approximately Omega C_f mu m_p N_H R v','mass per time','Thin-shell/conical estimate using solid angle Omega, covering fraction C_f, hydrogen column N_H, characteristic radius R, and deprojected radial speed v.','Steady-flow and shell geometry; clumping, saturation, abundance/depletion, ionization, projection, and radius dominate.','[REV15-P009] [REV15-P010] [REV15-P011] [REV15-P022]'),
('REV15-N05','Edot_kin = 0.5 Mdot_out v^2; pdot_out = Mdot_out v','erg s^-1; dyn','Bulk kinetic energy and momentum flux for a defined phase and characteristic velocity.','Add turbulence/enthalpy separately; observed phase is not total; velocity weighting and geometry apply.','[REV15-P008] [REV15-P010] [REV15-P024] [REV15-P038]'),
('REV15-N06','T_s approximately 1.4e5 (v_s / 100 km s^-1)^2 K','K','Strong-shock post-shock temperature for ionized gas with standard mean molecular weight.','Shock speed is not automatically bulk wind speed; electron-ion equilibration, cooling, abundance, and nonequilibrium ionization apply.','[REV15-P015] [REV15-P016] [REV15-P028]'),
('REV15-N07','v_esc(r) approximately sqrt(2) v_c [1 + ln(r_max/r)]^(1/2)','km s^-1','Truncated isothermal-sphere escape-speed approximation using circular speed v_c and outer truncation r_max.','Potential model, launch radius, projection, hydrodynamic drag, and phase changes apply.','[REV15-P007] [REV15-P011] [REV15-P017] [REV15-P021]'),
('REV15-N08','Sigma_SFR approximately 0.1 Msun yr^-1 kpc^-2','Msun yr^-1 kpc^-2','Empirical order-of-magnitude star-formation intensity associated with local superwind hosts.','Not a universal hard boundary; area, extinction/SFR calibration, inclination, sample, and tracer sensitivity apply.','[REV15-P004] [REV15-P027]'),
('REV15-N09','Delta v(Ly-alpha minus IS absorption) of order several hundred km s^-1; median near 400 km s^-1 in the cited z~3 composite sample','km s^-1','Rest-UV velocity separation used as an outflow/resonant-transfer indicator in Lyman-break galaxies.','Not the terminal speed; systemic-redshift precision, stacking, radiative transfer, covering, and selection apply.','[REV15-P013]'),
('REV15-N10','E_kin approximately >=2e53 erg for the cited NGC 1482 warm-ionized bicone estimate','erg','Object-specific kinetic-energy lower bound from warm gas and biconical geometry.','One emitting phase; density, filling factor, extinction, velocity deprojection, and unseen phases apply.','[REV15-P038]'),
]
U=[
('REV15-U01','Direct properties of the volume-filling hot free wind.','It likely carries much energy/metals but is faint and confused with bright interfaces.','Hard-X-ray/UV absorption and calorimetry with spatially resolved interface modeling.','[REV15-P015] [REV15-P016] [REV15-P028]'),
('REV15-U02','Complete multiphase mass, momentum, energy, and metal budgets for the same galaxies.','Single-phase estimates cannot close feedback conservation laws.','Matched neutral, ionized, molecular, hot, dust, and cosmic-ray measurements with common geometry.','[REV15-P009] [REV15-P016] [REV15-P022] [REV15-P026]'),
('REV15-U03','How cool clouds survive and accelerate to observed radii and velocities.','Simple hydrodynamic models disrupt clouds rapidly.','Resolved 3D MHD/conduction/cooling calculations tied to phase-resolved kinematics.','[REV15-P008] [REV15-P015] [REV15-P028]'),
('REV15-U04','Fraction of launched gas and metals that permanently escapes versus recycles.','Controls baryon loss, metallicity evolution, and IGM enrichment.','Halo-scale absorption/emission tomography plus realistic potentials and long-duration multiphase simulations.','[REV15-P011] [REV15-P017] [REV15-P021]'),
('REV15-U05','Thermalization efficiency and additional mass loading near the injection zone.','They set hot-wind temperature, speed, cooling, and coupling by large factors.','Resolve cluster-scale injection and constrain hot-fluid temperature/density independently.','[REV15-P003] [REV15-P005] [REV15-P015]'),
('REV15-U06','Relative AGN and starburst driving in composite systems across duty cycles.','Source partition changes feedback scaling and affected phase/geometry.','Time-resolved stellar/AGN energetics, ages, radio/X-ray structure, and phase-resolved momentum flux.','[REV15-P010] [REV15-P033] [REV15-P036]'),
]
L=['# Review Base 15 — Veilleux, Cecil & Bland-Hawthorn (2005): Galactic Winds','','Status: READY_FOR_HWAO_REVIEW — canonical advisory packet; raw custody preserved and independently reconciled.','',f"Raw custody SHA-256: `{hashlib.sha256(RAW.read_bytes()).hexdigest()}`",'','## 1. Review Identity and Scope Map','',t(['Field','Value'],[('Review key','[REV15-R00]'),('Authors','Sylvain Veilleux; Gerald Cecil; Joss Bland-Hawthorn'),('Year / journal','2005, Annual Review of Astronomy and Astrophysics 43, 769-826'),('DOI','10.1146/annurev.astro.43.072103.150610'),('arXiv','astro-ph/0504435'),('ADS','2005ARA&A..43..769V'),('Authorized scope','Physics, multiphase observations, energetics, kinematics, launch, escape/recycling, enrichment, and galaxy-evolution implications of stellar- and AGN-driven galactic winds through 2005.'),('Explicit exclusions','Post-2005 work; uncited browsing spillover; one-phase totals; unqualified escape; mixed velocity definitions; geometry-free mass rates; conflated stellar/AGN channels.')]),'','## 2. Established Findings','',t(['ID','Epistemic type','Bounded finding','Regime / boundary','Confidence','Sources'],E),'','## 3. Open Debates and Tensions','',t(['ID','Topic','Competing positions','Why unresolved / boundary','Sources'],D),'','## 4. Key Measurements and Model Calibrations','',t(['ID','Value / equation','Units','Definitions and regime','Status / caveat','Sources'],N),'','## 5. What Remained Unknown in 2005','',t(['ID','Gap','Why it matters','Needed test','Sources'],U),'','## 6. Primary-Citation Harvest','']
for s in p:L.append(f"[{s['key']}] {s['authors']} ({s['year']}, {s['journal']}) | title={s['title']} | DOI:{s['doi'] or 'none'}; arXiv:{s['arxiv'] or 'none'}; ADS:{s['ads_bibcode']} | role={s['role']} | review_locator={s['review_locator']} | {s['boundary']} | source_status=PASS_ADS_AND_REVIEW_MEMBERSHIP")
L+=['','### Supporting reviews','','None counted separately; all 42 usable rows are primary measurements, simulations, analytic models, or calibrations.','','## 7. DO_NOT_USE_UNVERIFIED','']
for s in q:L.append(f"UNCITED_NOT_USABLE | [{s['key']}] {s['title']} | DOI:{s['doi'] or 'none'}; arXiv:{s['arxiv'] or 'none'}; ADS:{s['ads_bibcode'] or 'none'} | {s['quarantine_reason']}")
L+=['UNCITED_NOT_USABLE | a blueshifted sightline uniquely determines a global mass-loss rate | none | radius, solid angle, column, covering, ionization, and projection are required.','UNCITED_NOT_USABLE | observed line-of-sight gas necessarily escapes the halo | none | gravitational potential, drag, projection, and recycling unresolved.','UNCITED_NOT_USABLE | soft X-rays directly measure the volume-filling free-wind energy | none | interface and emission-measure bias.','UNCITED_NOT_USABLE | one gas phase supplies the total wind mass/energy/metal budget | none | multiphase mismatch.','UNCITED_NOT_USABLE | starburst and AGN mechanical power are interchangeable | none | launch channel and coupling differ.','UNCITED_NOT_USABLE | post-2005 CGM, FIRE, ALMA, or JWST results | none | outside temporal boundary.','','## 8. Composite Source Identity Ledger','','[REV15-R00] Veilleux, Sylvain; Cecil, Gerald; Bland-Hawthorn, Joss (2005, Annual Review of Astronomy and Astrophysics) | title=Galactic Winds | DOI:10.1146/annurev.astro.43.072103.150610; arXiv:astro-ph/0504435; ADS:2005ARA&A..43..769V | role=review_synthesis_and_labeled_2005_review_calibrations | source_status=PASS_ADS_CROSSREF_ARXIV','']
for s in p:L.append(f"[{s['key']}] {s['authors']} ({s['year']}, {s['journal']}) | title={s['title']} | DOI:{s['doi'] or 'none'}; arXiv:{s['arxiv'] or 'none'}; ADS:{s['ads_bibcode']} | role={s['role']} | boundary={s['boundary']} | source_status=PASS_ADS_AND_REVIEW_MEMBERSHIP")
L+=['','REVIEW_BASE_15_DR_COMPLETE_REFERENCE_ONLY',''];OUT.write_text('\n'.join(L));print(json.dumps({'packet':str(OUT),'primary':len(p),'quarantined':len(q),'sha256':hashlib.sha256(OUT.read_bytes()).hexdigest()},sort_keys=True))
