import hashlib,json
from pathlib import Path
A=Path('/Users/duhokim/NebulaMind/NebulaMind/.hermes/handoffs/galaxy-evolution/wiki-expansion-20260715');RAW=A/'area_review_17_bland_hawthorn_gerhard_2016_DR_RAW_PACKET.md';REG=A/'area_review_17_bland_hawthorn_gerhard_2016_CURATED_SOURCE_REGISTRY.json';OUT=A/'area_review_17_bland_hawthorn_gerhard_2016_DR_PACKET.md';V=A/'area_review_17_bland_hawthorn_gerhard_2016_VALIDATION.json';D=json.loads(REG.read_text());S={x['key']:x for x in D['sources']};usable={k for k,x in S.items() if x['status']=='USABLE'};q={k for k,x in S.items() if x['status']=='UNCITED_NOT_USABLE'}
def refs(keys):
 assert set(keys)<=usable
 return ', '.join(f'REV17-{k}' for k in keys)
E=[
('REV17-E01','synthesis','The Milky Way is an L-star barred disk and lies near the green valley in external-galaxy comparisons, but its integrated placement depends on dust and population assumptions.','whole Galaxy / external context','high',['P004','P019','P022','P023']),
('REV17-E02','measurement synthesis','A common-IMF synthesis gives a current star-formation rate near 1.65 solar masses per year and a stellar mass of order five to six times 10^10 solar masses.','whole Galaxy; Kroupa/Chabrier-like IMF conventions','high',['P004','P019','P046']),
('REV17-E03','measurement + dynamical modeling','The central box/peanut structure is the vertically thickened part of the bar; red-clump maps and cylindrical rotation strongly favor a bar-built bulge.','inner about 3 kpc','high',['P005','P006','P007','P008','P032']),
('REV17-E04','measurement + gas modeling','The planar bar extends beyond the box/peanut bulge to about 5 kpc, while its angle and pattern speed remain model-dependent.','inner disk; Sun-Galactic-centre geometry explicit','medium-high',['P039','P042','P043','P044']),
('REV17-E05','measurement + modeling','The stellar disk has population-dependent radial and vertical scales; a single thin/thick double exponential is an approximation rather than a unique decomposition.','disk; geometric versus mono-abundance populations','high',['P002','P003','P026','P027','P028']),
('REV17-E06','measurement','Geometric, chemical, age and kinematic definitions of the thick disk select overlapping but non-identical stellar populations.','solar cylinder and wider disk','high',['P002','P012','P026']),
('REV17-E07','measurement synthesis','Pre-Gaia geometric and dynamical constraints converged near R0 about 8.2 kpc and circular speed near 235-240 km/s, with covariance between them.','Galactocentric frame; LSR/circular speed distinct','medium-high',['P010','P045','P046']),
('REV17-E08','kinematic calibration','The Sun has a substantial peculiar velocity relative to the LSR; asymmetric-drift treatment is essential, especially for the V component.','heliocentric to LSR transform','high',['P011','P047']),
('REV17-E09','dynamical inference','Milky Way virial-mass estimates cluster around 10^12 solar masses but span a factor of roughly two because tracers, anisotropy and halo definitions differ.','dark halo; Mvir/Rvir definition required','medium',['P016','P017','P046','P048']),
('REV17-E10','measurement','The stellar halo contains coherent streams and is not globally phase mixed, so simple equilibrium inference is unsafe for unfiltered samples.','outer stellar halo','high',['P025','P048']),
('REV17-E11','dynamical modeling','Local vertical dynamics and global mass models require a dark component, but local density estimates covary with disk surface density and equilibrium assumptions.','solar neighborhood / global halo','medium-high',['P003','P016','P046']),
('REV17-E12','simulation + gas modeling','Inner-Galaxy gas terminal velocities contain strong non-circular bar and spiral streaming; they cannot be read as an axisymmetric rotation curve without modeling.','inner gas disk','high',['P001','P014','P042','P043','P044']),
('REV17-E13','simulation + contextual inference','The Galaxy has experienced a comparatively quiet recent merger history, while the halo retains signatures of earlier accretion.','assembly history','medium',['P025','P035','P037'])]
Db=[
('REV17-D01','A short fast bar inferred from local resonances versus a longer slower bar favored by photometric and gas-flow models.','Pattern speed, bar length, spiral coupling and solar constants are covariant.',['P013','P039','P042','P043','P044']),
('REV17-D02','A compact classical bulge in addition to the box/peanut bar versus an almost pure-disk, bar-built bulge.','Population mixing, extinction and model degeneracy limit the classical-bulge fraction.',['P006','P031','P032','P038']),
('REV17-D03','One geometric thick disk versus a continuum of mono-abundance populations with varying scale lengths/heights.','Geometric, chemical, age and kinematic selections do not map one-to-one.',['P002','P012','P026']),
('REV17-D04','Disk scale length near 2-3 kpc with estimator/population dependence.','Star counts, dynamics, passbands, flare/warp treatment and radial breaks differ.',['P002','P003','P027','P028','P046']),
('REV17-D05','Competing R0, V0 and solar-motion combinations.','Maser, S-star and local-kinematic constraints have different frame and covariance structures.',['P010','P011','P045','P046','P047']),
('REV17-D06','A relatively light halo below 10^12 solar masses versus heavier estimates near 1.5-2 times 10^12 solar masses.','Satellite/escape-speed/BHB tracers and virial definitions differ; anisotropy is uncertain.',['P016','P017','P046','P048']),
('REV17-D07','A smooth equilibrium stellar halo versus a stream-rich disequilibrium halo.','Selection, substructure excision and incomplete transverse velocities change Jeans results.',['P025','P048']),
('REV17-D08','The Galaxy as a genuinely transitioning green-valley system versus an ordinary star-forming spiral shifted by dust and viewing geometry.','Integrated color/SFR reconstructions are indirect and IMF/dust dependent.',['P004','P019','P022','P023'])]
N=[
('REV17-N01','R0 = 8.2 ± 0.1 kpc as the review-era synthesis value.','kpc','Galactocentric; Sgr A* distance scale','S-star orbits, masers and mass-model combination','systematic covariance exceeds a naive single-study error',['P010','P045','P046']),
('REV17-N02','Vc(R0) approximately 238 ± 15 km/s; distinguish this from total solar azimuthal speed and mean stellar rotation.','km/s','Galactocentric circular speed at R0','masers and global mass models','model/frame dependent',['P010','P046']),
('REV17-N03','Solar peculiar motion (U,V,W) approximately (11.1, 12.24, 7.25) km/s, with U toward the centre and V in rotation.','km/s','heliocentric relative to LSR; handedness stated','local stellar kinematics with revised asymmetric drift','population/model systematic',['P047']),
('REV17-N04','SFR = 1.65 ± 0.19 solar masses per year; stellar mass about (5-6)×10^10 solar masses.','solar masses/year; solar masses','whole Galaxy','hierarchical synthesis and common IMF','dust, IMF and stellar-population model dependent',['P004','P019','P046']),
('REV17-N05','Representative thin-disk radial scale length about 2.6 ± 0.5 kpc; geometric scale heights about 0.3 kpc thin and 0.9 kpc thick.','kpc','disk; double-exponential convention','star counts and dynamics','population, warp, flare and selection dependent',['P002','P003','P026','P027','P028']),
('REV17-N06','Bar angle about 28-33 degrees from the Sun-centre line and half-length about 5 ± 0.2 kpc.','degrees; kpc','Galactocentric plane','red-clump/IR maps plus gas dynamics','bar/long-bar decomposition and R0 dependent',['P005','P039','P042','P044']),
('REV17-N07','Dynamical mass in the box/peanut bulge volume approximately 1.84 ± 0.07×10^10 solar masses.','solar masses','inner VVV bulge aperture','made-to-measure N-body model','aperture and mass-to-light model specific',['P006']),
('REV17-N08','Virial mass is of order 1.0-1.3×10^12 solar masses; quoted values require Rvir/overdensity definition.','solar masses','dark halo to virial radius','escape-speed, BHB Jeans and global models','anisotropy/equilibrium and profile dependent',['P016','P017','P046','P048']),
('REV17-N09','Local dark-matter density about 0.010-0.013 solar masses pc^-3, approximately 0.38-0.49 GeV cm^-3.','solar masses/pc^3; GeV/cm^3','solar neighborhood','vertical dynamics and global mass models','disk surface-density covariance and equilibrium systematic',['P003','P046']),
('REV17-N10','Exponential disk: Sigma(R)=Sigma0 exp(-R/Rd); Sérsic component: I(R)=Ie exp{-bn[(R/Re)^(1/n)-1]}.','surface density or intensity','component-specific radial coordinates','structural decomposition','Rd, Re, n, passband and fitted range must travel with each value',['P005','P027','P028','P046'])]
U=[
('REV17-U01','The bar pattern speed and whether the long bar and box/peanut are one continuous structure.','Full 6D bulge/disk kinematics and self-consistent gas+stellar models.',['P005','P039','P044']),
('REV17-U02','The classical-bulge mass fraction, if any.','Extinction-robust chemistry, ages and non-axisymmetric dynamical decomposition.',['P006','P032','P038']),
('REV17-U03','A population-resolved map of disk scale length, height, flare and warp.','Uniform distances, ages, abundances and selection functions across the disk.',['P002','P026']),
('REV17-U04','The dark-halo virial mass, shape and radial density profile.','Distant tracer proper motions, streams and disequilibrium-aware models.',['P016','P025','P048']),
('REV17-U05','Whether local velocity substructure primarily traces bar resonances, spiral structure or perturbations.','Time-dependent non-axisymmetric models with precise phase-space data.',['P013','P014']),
('REV17-U06','The timing and mass spectrum of the Galaxy’s accretion history.','Large chemically tagged 6D samples tied to cosmological simulations.',['P025','P035','P037'])]
lines=['# Review Base 17 canonical advisory packet — Bland-Hawthorn & Gerhard 2016','', 'status: READY_FOR_HWAO_REVIEW','advisory_only: true','canonical_packet_released: true','wiki_write_performed_by_tori: false','', '## 1. Review identity and scope map','', '- Review: Bland-Hawthorn & Gerhard (2016), *The Galaxy in Context: Structural, Kinematic, and Integrated Properties*.','- Identity: DOI `10.1146/annurev-astro-081915-023441`; arXiv `1602.07702`; ADS `2016ARA&A..54..529B`.','- Scope: integrated Milky Way properties, bulge/bar, disks, solar constants, gas kinematics, stellar/dark halos and assembly history, with frame and component boundaries explicit.','- The review is synthesis; load-bearing claims below cite independently reconciled primary sources.','', '## 2. Established findings','']
for k,t,s,reg,c,ks in E:lines += [f'### {k}',f'- Epistemic type: {t}',f'- Bounded statement: {s}',f'- Component/frame/regime: {reg}',f'- Confidence: {c}',f'- Sources: {refs(ks)}','']
lines += ['## 3. Open debates and tensions','']
for k,pos,why,ks in Db:lines += [f'### {k}',f'- Competing positions: {pos}',f'- Why unresolved: {why}',f'- Sources: {refs(ks)}','']
lines += ['## 4. Key measurements and model calibrations','']
for k,val,unit,frame,tracer,status,ks in N:lines += [f'### {k}',f'- Value/equation: {val}',f'- Units: {unit}',f'- Coordinate/frame/component: {frame}',f'- Tracer/sample/model: {tracer}',f'- Uncertainty/status: {status}',f'- Sources: {refs(ks)}','']
lines += ['## 5. What remained unknown in 2016','']
for k,unk,need,ks in U:lines += [f'### {k}',f'- Unknown: {unk}',f'- Decisive need: {need}',f'- Sources: {refs(ks)}','']
lines += ['## 6. Curated primary-citation harvest','',f'- Usable primary papers: {sum(x.get("role")=="primary" and x["status"]=="USABLE" for x in S.values())}.',f'- Supporting reviews: {sum(x.get("role")=="supporting_review" and x["status"]=="USABLE" for x in S.values())}.','', '| Key | Role | Authors/year | Title | DOI | arXiv | ADS | Review membership | Scientific boundary |','|---|---|---|---|---|---|---|---|---|']
for k in sorted(usable,key=lambda z:int(z[1:])):
 x=S[k];lines.append(f'| REV17-{k} | {x["role"]} | {x["authors_year"]} | {x["title"].replace("|","/")} | {x.get("doi") or "none"} | {x.get("arxiv") or "none"} | {x.get("ads_bibcode") or "none"} | {x["review_membership"]} | {x["scientific_boundary"].replace("|","/")} |')
lines += ['', '## 7. DO_NOT_USE_UNVERIFIED quarantine','', 'All entries below are `UNCITED_NOT_USABLE` and appear in no canonical claim source list.','', '| Key | Candidate | Reason |','|---|---|---|']
for k in sorted(q,key=lambda z:int(z[1:])):
 x=S[k];lines.append(f'| REV17-{k} | {(x.get("candidate") or x.get("authors_year") or x.get("title")).replace("|","/")} | {x.get("reason") or x.get("review_membership")} |')
lines += ['', '## 8. Composite identity and boundary ledger','', '- Every usable row carries a DOI/arXiv/ADS composite where available and exact membership in the complete 515-reference review bibliography.','- Six ADS-valid raw rows were absent from that bibliography and are quarantined; three review-cited primaries were added to preserve the primary-source floor.','- Coordinate-frame mismatch: R0, Vc, total solar azimuthal speed, peculiar motion and mean stellar rotation are not interchangeable.','- Component-definition mismatch: geometric, chemical, age and kinematic disk/bulge definitions are retained separately.','- Distance/extinction/IMF dependence: all integrated luminosity, stellar mass and SFR values retain these assumptions.','- Equilibrium boundary: streams, bar/spiral streaming and halo disequilibrium are not inputs to unqualified axisymmetric Jeans or circular-speed claims.','- Raw custody is preserved unchanged; this canonical packet is advisory and performs no live wiki/DB/trust mutation.','', 'REVIEW_BASE_17_CANONICAL_COMPLETE_REFERENCE_ONLY','']
OUT.write_text('\n'.join(lines));txt=OUT.read_text();claim_text=txt.split('## 7. DO_NOT_USE_UNVERIFIED quarantine',1)[0];viol=sorted(set(__import__('re').findall(r'REV17-(P\d{3})',claim_text))&q);counts={'established':len(E),'debates':len(Db),'measurements':len(N),'unknowns':len(U),'usable_primary':41,'supporting_reviews':1,'quarantined':13};checks={'marker':txt.rstrip().endswith('REVIEW_BASE_17_CANONICAL_COMPLETE_REFERENCE_ONLY'),'counts':counts,'quarantine_reference_violations':viol,'raw_preserved_sha256':hashlib.sha256(RAW.read_bytes()).hexdigest(),'registry_sha256':hashlib.sha256(REG.read_bytes()).hexdigest(),'canonical_sha256':hashlib.sha256(OUT.read_bytes()).hexdigest()};checks['pass']=checks['marker'] and not viol and min(len(E),len(Db),len(N),len(U))>=6 and counts['usable_primary']>=40;V.write_text(json.dumps(checks,indent=2)+'\n');assert checks['pass'];print(checks)
