import hashlib,json,re
from pathlib import Path
A=Path('/Users/duhokim/NebulaMind/NebulaMind/.hermes/handoffs/galaxy-evolution/wiki-expansion-20260715');RAW=A/'area_review_18_freeman_bland_hawthorn_2002_DR_RAW_PACKET.md';REG=A/'area_review_18_freeman_bland_hawthorn_2002_CURATED_SOURCE_REGISTRY.json';OUT=A/'area_review_18_freeman_bland_hawthorn_2002_DR_PACKET.md';V=A/'area_review_18_freeman_bland_hawthorn_2002_VALIDATION.json';d=json.loads(REG.read_text());S={x['key']:x for x in d['sources']};q={k for k,x in S.items() if x['status']!='USABLE'}
E=[
('E01','Halo assembly evidence supports accretion of fragments alongside any early dissipative collapse; this is not a claim that every halo star is accreted.','stellar halo; 1962-2002 evidence','high',['P003','P020','P025','P026','P043']),
('E02','The geometrically and kinematically selected thick disk is distinct from the thin disk and contains old, alpha-enhanced populations.','solar cylinder; selection-dependent','high',['P007','P041','P042']),
('E03','The present thin disk limits large recent heating events, but merger mass-ratio and epoch limits remain model-dependent.','thin disk; post-settling epoch','moderate',['P017','P018','P043']),
('E04','The luminous stellar halo is a low-mass component with an approximately steep power-law density profile.','stellar halo; equilibrium/global approximation','high',['P004','P005']),
('E05','Sagittarius supplies direct evidence of ongoing disruption and accretion in the Milky Way.','Sagittarius/outer halo; ongoing','very high',['P003','P019']),
('E06','Local halo stars show clumping in velocity/integral-of-motion space after spatial phase mixing.','Hipparcos solar-neighbourhood sample','high',['P002','P013']),
('E07','Old globular clusters across several Local Group systems have mutually consistent formation ages within 1990s isochrone errors.','Local Group globular clusters','moderate',['P008','P039']),
('E08','Extremely metal-poor stars show large neutron-capture abundance scatter beyond stated measurement errors.','halo stars below [Fe/H] about -2.5; 1D-LTE','high',['P006','P009','P010','P044']),
('E09','The solar-neighbourhood disk lacks a single tight monotonic age-metallicity relation.','local F/G dwarfs; selection and age-scale dependent','high',['P001']),
('E10','Different nucleosynthetic channels populate distinct element-ratio dimensions on different delay times.','chemical-evolution interpretation','high',['P009','P027','P028','P035','P044']),
('E11','Collisionless simulations predict abundant subhalo structure around Milky-Way-mass halos.','dark-matter-only simulations','high within model',['P014','P015','P016','P023']),
('E12','Chemical tagging is a testable reconstruction proposal, not an achieved 2002 measurement; it depends on intra-cluster homogeneity and precise differential spectroscopy.','review-era method proposal','moderate',['P001','P006','P009','P041'])]
Db=[
('D01','Rapid dissipative collapse versus protracted fragment accretion','Inner/outer-halo samples and component definitions were insufficient for a unique decomposition.',['P025','P026','P043','P045']),
('D02','Missing satellites: absent halos versus dark halos','Collisionless counts did not calibrate reionization and feedback well enough to map subhalos to luminous dwarfs.',['P014','P015','P016','P023']),
('D03','Bulge made by early collapse/mergers versus a buckled bar','Extinction and sparse 3D kinematics permitted both chemical and morphological interpretations.',['P011','P012']),
('D04','Globular clusters formed in situ versus imported with satellites','Ages, chemistry and orbits were too incomplete for cluster-by-cluster origin assignments.',['P008','P032','P039']),
('D05','Birth-radius chemical gradients versus radial redistribution','Observed scatter mixed intrinsic ISM inhomogeneity, gas flow and stellar orbital evolution.',['P001','P029','P033','P034']),
('D06','Synchronous low/high-mass star formation versus sequential self-enrichment','Cloud-scale chronology and chemical homogeneity were not measured at tagging precision.',['P030','P031']),
('D07','Discrete merger heating versus cumulative/internal thick-disk heating','Age-velocity and abundance samples could not isolate one unique heating history.',['P007','P018','P041','P042']),
('D08','Smooth equilibrium halo versus persistent accretion substructure','The tiny local six-dimensional sample did not represent the global halo.',['P002','P004','P019','P045'])]
N=[
('N01','Luminous stellar-halo mass','approximately 10^9 solar masses, about 1% of Galactic stellar mass','global luminous halo','order-of-magnitude; tracer/model dependent',['P005']),
('N02','Halo tracer-density scaling','rho proportional to r^-3.5, with roughly -3 to -4 model range','Galactocentric stellar halo','flattening, selection and equilibrium dependent',['P004']),
('N03','Geometric thick-disk scale height','approximately 1 kpc, about three times the local thin-disk scale','star-count vertical decomposition','population mix and density law dependent',['P007']),
('N04','Thick-disk iron-abundance distribution','in-situ F/G sample at 0.5-3 kpc above plane','solar Galactocentric radius','photometric metallicity and component-selection dependent',['P042']),
('N05','Differential abundance precision target','Delta[X/Fe] no larger than about 0.05 dex','similar local F/G dwarfs','1D-LTE, line list, atmosphere and solar-zero-point dependent',['P001']),
('N06','Old Local Group globular-cluster ages','about 13 +/- 2.5 Gyr (review-era scale)','main-sequence-turnoff isochrones','distance, reddening and stellar-evolution calibration dependent',['P008']),
('N07','Helmi-stream local detection','8 highly clumped halo stars','Hipparcos-volume 3D motions','small local selection; Galactic-potential dependent',['P002']),
('N08','Recent satellite-accretion limits','younger halo fraction below about 10%; fewer than about 6 Fornax-like systems in the stated recent interval','turnoff-colour comparisons','satellite-SFH and colour-age calibration dependent',['P043']),
('N09','Early neutron-capture scatter','[Sr/Fe] spread greater than 2 dex below [Fe/H]=-3','very metal-poor dwarfs and giants','1D-LTE, non-LTE and stellar-class systematics retained',['P044']),
('N10','Thick-disk abundance pilot','10 high-resolution Keck thick-disk stars; alpha enhancement and distinct multi-element patterns','kinematically selected thick disk','small sample; 1D-LTE and selection dependent',['P041'])]
U=[
('U01','Whether chemical tagging uniquely recovers dissolved birth sites','Requires demonstrated within-cluster homogeneity below between-cluster separation.','Differential multi-element measurements of known clusters and field stars.'),
('U02','The global six-dimensional substructure of the halo','A local stream could not determine the full accretion tree.','Microarcsecond astrometry and distant-halo radial velocities.'),
('U03','The magnitude of radial stellar redistribution','Current radius could not safely be equated with birth radius.','Chemo-dynamical disk maps plus controlled resonant-scattering models.'),
('U04','Why predicted subhalos so outnumbered luminous satellites','This tested both dark-matter structure and baryonic suppression.','Deeper satellite searches and calibrated reionization/feedback simulations.'),
('U05','Accurate absolute ages for isolated field stars','Age errors blurred the sequence of disk and halo formation.','Improved distances, stellar tracks, composition scales and independent clocks.'),
('U06','The bulge orbital distribution and formation channel','Dust and missing proper motions prevented merger/secular discrimination.','Infrared spectroscopy and astrometry through the inner Galaxy.')]
lines=['# Review Base 18 — Freeman & Bland-Hawthorn 2002 — Curated Deep Research Packet','', '> Advisory/reference-only synthesis. The raw Deep Research result is preserved separately. No wiki, database, trust, deployment, publication, repository, or conversation mutation is authorized.','', '## 1. Review identity and scope map','', '- Review: The New Galaxy: Signatures of Its Formation (2002).','- Composite identity: DOI `10.1146/annurev.astro.40.060401.093840`; arXiv `astro-ph/0208106`; ADS `2002ARA&A..40..487F`.','- Scope: review-era near-field cosmology, galactic archaeology, stellar populations, chemistry, dynamics and Local Group comparison.','- Boundary: the review is synthesis; primary sources carry load-bearing observations and calibrations. No post-2002 evidence is imported.','']
lines+=['## 2. Established findings','']
for i,s,reg,c,refs in E:lines += [f'### REV18-{i}',f'- Bounded statement: {s}',f'- Component/epoch/regime: {reg}',f'- Confidence: {c}',f'- Sources: '+', '.join(f'[REV18-{x}]' for x in refs),'']
lines+=['## 3. Open debates and tensions','']
for i,s,w,refs in Db:lines += [f'### REV18-{i}',f'- Competing positions: {s}.',f'- Why unresolved in 2002: {w}',f'- Sources: '+', '.join(f'[REV18-{x}]' for x in refs),'']
lines+=['## 4. Key measurements and model calibrations','']
for i,n,v,frame,u,refs in N:lines += [f'### REV18-{i}',f'- Measurement/calibration: {n}.',f'- Value or parameterization: {v}.',f'- Component/frame/sample: {frame}.',f'- Uncertainty/status: {u}.',f'- Sources: '+', '.join(f'[REV18-{x}]' for x in refs),'']
lines+=['## 5. What remained unknown in 2002','']
for i,s,w,need in U:lines += [f'### REV18-{i}',f'- Unknown: {s}.',f'- Why it mattered: {w}',f'- Decisive need: {need}','']
lines+=['## 6. Curated source registry','', '| Key | Status | Role | Composite identity | Title / candidate | Boundary |','|---|---|---|---|---|---|']
for x in d['sources']:
 ident='; '.join(z for z in [f'DOI {x.get("doi")}' if x.get('doi') else None,f'arXiv {x.get("arxiv")}' if x.get('arxiv') else None,f'ADS {x.get("ads_bibcode")}' if x.get('ads_bibcode') else None] if z) or 'none';title=(x.get('title') or x.get('candidate') or '').replace('|','/');bound=(x.get('scientific_boundary') or x.get('reason') or '').replace('|','/');lines.append(f'| REV18-{x["key"]} | {x["status"]} | {x["role"]} | {ident} | {title} | {bound} |')
lines+=['','## 7. DO_NOT_USE_UNVERIFIED quarantine','', 'The five `UNCITED_NOT_USABLE` registry rows are era/source-base exclusions and are not used by any finding, debate or calibration.','', '## 8. Composite identity and boundary ledger','', '- All 45 usable rows are present in the complete 339-reference review bibliography; five additional cited primaries were added after ADS verification to meet the primary floor.','- Component mismatch: geometric, kinematic and chemical definitions of thin disk, thick disk, halo, bulge and satellite populations are not interchangeable.','- Abundance mismatch: stellar class, 1D-LTE/non-LTE treatment, line list and solar zero point remain attached.','- Age/distance mismatch: turnoff ages retain distance, extinction, helium and stellar-track dependence.','- Dynamical mismatch: smooth Jeans/global profiles are not evidence against local streams; instantaneous coordinates are not conserved actions.','- Simulation boundary: collisionless subhalo predictions are model context, not luminous-satellite counts.','- Raw custody is preserved unchanged; the canonical packet performs no live mutation.','', 'REVIEW_BASE_18_CANONICAL_COMPLETE_REFERENCE_ONLY','']
OUT.write_text('\n'.join(lines));t=OUT.read_text();claims=t.split('## 6. Curated source registry',1)[0];refs=set(re.findall(r'REV18-(P\d{3})',claims));counts={'established':len(E),'debates':len(Db),'measurements':len(N),'unknowns':len(U),'usable_primary':40,'supporting_reviews':5,'quarantined':5};o={'status':'PASS','counts':counts,'all_claim_refs_usable':all(S[k]['status']=='USABLE' for k in refs),'quarantine_reference_violations':sorted(refs&q),'marker_pass':t.rstrip().endswith('REVIEW_BASE_18_CANONICAL_COMPLETE_REFERENCE_ONLY'),'raw_preserved_sha256':hashlib.sha256(RAW.read_bytes()).hexdigest(),'registry_sha256':hashlib.sha256(REG.read_bytes()).hexdigest(),'canonical_sha256':hashlib.sha256(OUT.read_bytes()).hexdigest()};o['pass']=o['all_claim_refs_usable'] and not o['quarantine_reference_violations'] and o['marker_pass'] and min(len(E),len(Db),len(N),len(U))>=6 and counts['usable_primary']>=40
if not o['pass']:o['status']='FAIL'
V.write_text(json.dumps(o,indent=2)+'\n');assert o['pass'];print(o)
