import hashlib,json,re
from pathlib import Path
A=Path('/Users/duhokim/NebulaMind/NebulaMind/.hermes/handoffs/galaxy-evolution/wiki-expansion-20260715');RAW=A/'area_review_19_sanchez_2020_DR_RAW_PACKET.md';REG=A/'area_review_19_sanchez_2020_CURATED_SOURCE_REGISTRY.json';OUT=A/'area_review_19_sanchez_2020_DR_PACKET.md';V=A/'area_review_19_sanchez_2020_VALIDATION.json';d=json.loads(REG.read_text());S={x['key']:x for x in d['sources']};q={k for k,x in S.items() if x['status']!='USABLE'}
E=[
('E01','Fossil-record fits generally recover older central than outer stellar populations in nearby galaxies, consistent with average inside-out assembly but dependent on SPS/SFH assumptions.','CALIFA spaxels/annuli; roughly kpc resolution','high',['P010','P011','P012','P048']),
('E02','Within star-forming spaxels, star-formation-rate surface density correlates with local stellar-mass surface density (resolved SFMS).','Halpha-selected, roughly kpc regions','high',['P008','P022']),
('E03','Undisturbed star-forming disks show a characteristic negative oxygen-abundance gradient when radius is normalized by effective radius.','HII-region/spaxel measurements; deprojected disk','high',['P031']),
('E04','Extended low-ionization emission in retired regions can be powered by old stellar populations rather than nuclear accretion.','LIER/HOLMES classifications; EW and line-ratio dependent','high',['P007','P013','P014']),
('E05','Local gas-phase oxygen abundance correlates with local stellar-mass surface density, with saturation at high density on a chosen strong-line scale.','star-forming kpc regions','high',['P009','P030','P045','P050']),
('E06','Molecular-gas surface density and SFR surface density correlate on kpc scales, with roughly constant depletion time in normal disks under a stated alpha_CO.','matched CO and SFR maps','high',['P016','P017','P025']),
('E07','Strong-line oxygen calibrations preserve relative trends more robustly than their absolute abundance zero points.','HII-region spectra; calibration dependent','high',['P042','P044']),
('E08','High-mass systems can show central oxygen-profile flattening or drops, conditional on ionization masks and abundance calibrator.','inner disk/bulge, below about 0.5 Re','moderate',['P015','P031']),
('E09','Integrated scaling relations can emerge from the spatial distribution and weighting of resolved relations, but this is not by itself causal proof.','resolved-to-integrated comparison','moderate-high',['P020','P023','P045']),
('E10','Departure from the star-forming main sequence is associated with lower cold-gas fractions and may also involve efficiency changes.','global/aperture-matched nearby samples','moderate-high',['P018','P019']),
('E11','IFS survey conclusions are bounded by reconstructed PSFs and physical sampling of roughly kpc scale, which blend HII regions and diffuse emission.','CALIFA/MaNGA/SAMI survey designs','high',['P001','P002','P003','P046']),
('E12','Resolved MZR studies generally find any secondary SFR dependence weaker and more sample/calibrator sensitive than the primary mass relation.','CALIFA/MaNGA/SAMI star-forming samples','moderate',['P021','P023','P047','P049'])]
Db=[
('D01','Is the rSFMS directly regulated by stellar surface density, or inherited through gas scaling relations?','Matched resolved molecular-gas coverage and causal controls were incomplete.',['P008','P016','P017','P025']),
('D02','Does inside-out quenching reflect gas removal/starvation, reduced efficiency, or morphological stabilization?','Local gas masses and alpha_CO were uncertain in central high-pressure regions.',['P018','P019','P028']),
('D03','Direct-Te versus photoionization strong-line abundance scales','Weak auroral lines disappear in metal-rich centers and model scales can differ by several tenths of a dex.',['P042','P044']),
('D04','Constant versus locally varying CO-to-H2 conversion factor','Independent gas-mass constraints at matched resolution were sparse.',['P017','P018','P025']),
('D05','Whether an SFR-dependent fundamental metallicity relation exists locally','Signal changes with calibrator, aperture, mass range and selection.',['P021','P023','P047','P049']),
('D06','Leakage from HII regions versus in-situ HOLMES as the dominant DIG/LIER source','Kiloparsec PSFs mix multiple ionizing sources and geometries.',['P007','P013','P014']),
('D07','Whether mergers/AGN permanently quench or temporarily redistribute central star formation','Resolved cold-gas and controlled post-merger time sequences were limited.',['P026','P028','P036']),
('D08','Universal normalized oxygen gradient versus morphology/environment-dependent families','Different radial domains, deprojections, calibrators and interacting-system cuts changed results.',['P015','P031','P044'])]
N=[
('N01','Characteristic disk oxygen gradient','about -0.10 +/- 0.03 dex per Re','0.5-2 Re, deprojected star-forming disk','selection and strong-line-calibration dependent',['P031']),
('N02','Retired-region WHAN threshold','EW(Halpha) below 3 angstrom, with line-ratio classification','spaxel/region','continuum subtraction and DIG mixing dependent',['P007']),
('N03','Resolved-SFMS slope','log Sigma_SFR = alpha log Sigma_* + beta, alpha about 0.7-1.0','star-forming roughly kpc regions','fit method, IMF, dust, S/N and covariance dependent',['P008','P022']),
('N04','Molecular depletion time','tau_dep = Sigma_H2/Sigma_SFR about 2 Gyr','normal nearby disk regions, kpc scale','alpha_CO, SFR tracer and lifecycle sampling dependent',['P016','P017']),
('N05','Marino O3N2 calibration','12+log(O/H)=8.533-0.214 O3N2','HII regions on direct-Te empirical scale','about 0.18 dex random for direct calibration',['P044']),
('N06','Marino N2 calibration precision','about 0.16 dex random for direct-Te calibration','HII regions','N/O and ionization-parameter sensitivity',['P044']),
('N07','Kewley maximum-starburst BPT curve','log([OIII]/Hbeta)=0.61/(log([NII]/Halpha)-0.47)+1.19','dereddened emission-line ratios','model upper envelope, not an empirical pure-SF cut',['P005']),
('N08','Large-survey physical resolution','order 1-1.5 kpc after PSF reconstruction','CALIFA/MaNGA/SAMI typical nearby samples','redshift and instrument dependent; not HII-region resolution',['P001','P002','P003','P046']),
('N09','CALIFA DR3 scope','667 galaxies; 1576 datacubes across V500/V1200/COMBO products','z about 0.005-0.03','diameter selection and setup-dependent coverage',['P046']),
('N10','Inside-out fossil-record structural ratio','half-mass radii smaller than half-light radii on average; strongest reported ratios depend on mass/morphology','CALIFA stellar-population fits','SPS, dust, age-metallicity degeneracy and radial coverage dependent',['P048'])]
U=[
('U01','The multiphase inflow/outflow/fountain mass budget','It sets gas supply and metal redistribution.','Matched ionized, neutral and molecular disk-halo kinematics.'),('U02','An absolute gas-phase abundance scale','Yield and baryon-budget inference cannot tolerate calibration offsets.','Auroral/far-IR/recombination-line anchors across metallicity.'),('U03','Spatial IMF variation','It would bias both Sigma_* and Sigma_SFR.','High-S/N gravity-sensitive absorption maps with independent dynamical constraints.'),('U04','Whether z~0 radial archaeology traces actual progenitor evolution','Migration and SPS degeneracy can mimic inside-out history.','Matched resolved observations across cosmic time plus forward models.'),('U05','Three-dimensional separation of arms, DIG and projected structures','Inclination and PSF blending contaminate local classifications.','Higher-resolution spectral imaging and 3D forward convolution.'),('U06','How star-formation laws change below a complete GMC lifecycle scale','Gas and young-star tracers decorrelate at tens to hundreds of parsecs.','Matched ALMA/optical maps with age-resolved region statistics.')]
lines=['# Review Base 19 — Sánchez 2020 — Curated Deep Research Packet','', '> Advisory/reference-only synthesis. The raw Deep Research result is preserved byte-for-byte, including an inherited #18 wrapper-label defect; the embedded result and exact conversation belong to #19. No live mutation is authorized.','', '## 1. Review identity and scope map','', '- Review: Spatially Resolved Spectroscopic Properties of Low-Redshift Star-Forming Galaxies (2020).','- Composite identity: DOI `10.1146/annurev-astro-012120-013326`; arXiv `1911.06925`; ADS `2020ARA&A..58...99S`.','- Scope: optical IFS of low-redshift galaxies, resolved ionization, stellar populations, star formation, gas metallicity and local/global scaling relations.','- Boundary: Sánchez 2020 is synthesis; primary papers carry load-bearing measurements.','']
lines+=['## 2. Established findings','']
for i,s,reg,c,refs in E:lines += [f'### REV19-{i}',f'- Bounded statement: {s}',f'- Sample/scale/regime: {reg}',f'- Confidence: {c}',f'- Sources: '+', '.join(f'[REV19-{x}]' for x in refs),'']
lines+=['## 3. Open debates and tensions','']
for i,s,w,refs in Db:lines += [f'### REV19-{i}',f'- Competing positions: {s}.',f'- Why unresolved in 2020: {w}',f'- Sources: '+', '.join(f'[REV19-{x}]' for x in refs),'']
lines+=['## 4. Key measurements and calibrations','']
for i,n,v,frame,u,refs in N:lines += [f'### REV19-{i}',f'- Measurement/calibration: {n}.',f'- Value/equation: {v}.',f'- Sample/scale: {frame}.',f'- Uncertainty/status: {u}.',f'- Sources: '+', '.join(f'[REV19-{x}]' for x in refs),'']
lines+=['## 5. What remained unknown in 2020','']
for i,s,w,need in U:lines += [f'### REV19-{i}',f'- Unknown: {s}.',f'- Why it mattered: {w}',f'- Decisive need: {need}','']
lines+=['## 6. Curated source registry','', '| Key | Status | Role | Composite identity | Title / candidate | Boundary |','|---|---|---|---|---|---|']
for x in d['sources']:
 ident='; '.join(z for z in [f'DOI {x.get("doi")}' if x.get('doi') else None,f'arXiv {x.get("arxiv")}' if x.get('arxiv') else None,f'ADS {x.get("ads_bibcode")}' if x.get('ads_bibcode') else None] if z) or 'none';title=(x.get('title') or x.get('candidate') or '').replace('|','/');bound=(x.get('scientific_boundary') or x.get('reason') or '').replace('|','/');lines.append(f'| REV19-{x["key"]} | {x["status"]} | {x["role"]} | {ident} | {title} | {bound} |')
lines+=['','## 7. DO_NOT_USE_UNVERIFIED quarantine','', '- Seventeen registry rows are `UNCITED_NOT_USABLE`: ten ADS-valid browsing candidates absent from the complete arXiv review bibliography and seven post-review/unproven candidates named by the raw quarantine. None is used above.','', '## 8. Composite identity and boundary ledger','', '- The 40 usable primaries are bibliography members with ADS-resolved identities; eight cited primaries supplement 32 usable raw rows after ten browsing-spillover rows were quarantined.','- Survey/release overlap: CALIFA, MaNGA, SAMI and AMUSING samples and releases are not statistically independent by default.','- Aperture/PSF boundary: spaxels, Voronoi bins, HII-region extractions and annuli are distinct; all observed maps are PSF-convolved.','- Ionization boundary: BPT/WHAN cuts, EW, DIG and continuum subtraction remain attached.','- Metallicity boundary: direct-Te, O3N2/N2 and photoionization scales are not merged.','- IMF/SPS/dust boundary: masses, SFRs, ages and metallicities retain their model and attenuation assumptions.','- Gas boundary: molecular, atomic and total gas retain tracer and alpha_CO conversion.','- Shared-variable covariance and radial/deprojection conventions remain explicit; correlations are not promoted to causes.','- Raw custody is preserved unchanged; this packet performs no wiki/DB/trust/deploy/publish/git or conversation mutation.','', 'REVIEW_BASE_19_CANONICAL_COMPLETE_REFERENCE_ONLY','']
OUT.write_text('\n'.join(lines));t=OUT.read_text();claims=t.split('## 6. Curated source registry',1)[0];refs=set(re.findall(r'REV19-(P\d{3})',claims));counts={'established':len(E),'debates':len(Db),'measurements':len(N),'unknowns':len(U),'usable_primary':40,'supporting_reviews':0,'quarantined':17};o={'status':'PASS','counts':counts,'all_claim_refs_usable':all(S[k]['status']=='USABLE' for k in refs),'quarantine_reference_violations':sorted(refs&q),'marker_pass':t.rstrip().endswith('REVIEW_BASE_19_CANONICAL_COMPLETE_REFERENCE_ONLY'),'raw_preserved_sha256':hashlib.sha256(RAW.read_bytes()).hexdigest(),'registry_sha256':hashlib.sha256(REG.read_bytes()).hexdigest(),'canonical_sha256':hashlib.sha256(OUT.read_bytes()).hexdigest(),'raw_wrapper_label_defect':True};o['pass']=o['all_claim_refs_usable'] and not o['quarantine_reference_violations'] and o['marker_pass'] and min(len(E),len(Db),len(N),len(U))>=6 and counts['usable_primary']>=40
if not o['pass']:o['status']='FAIL'
V.write_text(json.dumps(o,indent=2)+'\n');assert o['pass'];print(o)
