import hashlib,json
from pathlib import Path
A=Path("/Users/duhokim/NebulaMind/NebulaMind/.hermes/handoffs/galaxy-evolution/wiki-expansion-20260715");RAW=A/'area_review_10_conroy_2013_DR_RAW_PACKET.md';REG=A/'area_review_10_conroy_2013_CURATED_SOURCE_REGISTRY.json';OUT=A/'area_review_10_conroy_2013_DR_PACKET.md';r=json.loads(REG.read_text());p=[x for x in r['sources'] if x['source_status']=='PASS' and x['role']!='supporting_review'];sr=[x for x in r['sources'] if x['source_status']=='PASS' and x['role']=='supporting_review'];q=[x for x in r['sources'] if x['source_status']!='PASS'];assert(len(p),len(sr),len(q))==(40,3,5)
def t(h,rows):
 e=lambda v:str(v).replace('|','\\|').replace('\n',' ')
 return '\n'.join(['| '+' | '.join(h)+' |','|'+'|'.join(['---']*len(h))+'|']+['| '+' | '.join(e(v) for v in z)+' |' for z in rows])
E=[
('REV10-E01','review_synthesis','An SPS prediction combines an IMF, stellar-evolution isochrones, and stellar spectra to form simple stellar populations, then convolves them with SFH, enrichment, and dust for composite populations.','Every inferred quantity inherits the adopted ingredients and priors.','High as model architecture.','[REV10-R00] [REV10-P001] [REV10-P003] [REV10-P043]'),
('REV10-E02','calibration','Stellar mass is among the more robust SED-derived galaxy properties, but it remains an SPS-dependent mass-to-light scaling rather than a direct observation.','Normal SFHs and adequate wavelength coverage; IMF and hidden old populations set systematics.','High for relative robustness, moderate for absolute scale.','[REV10-R00] [REV10-P029] [REV10-P030] [REV10-P033]'),
('REV10-E03','calibration','Assumed star-formation-history flexibility can materially change recovered mass, age, and past SFR because young stars outshine older mass.','Integrated light and finite S/N; regularization and priors control nonparametric recovery.','High for the degeneracy, model-dependent in magnitude.','[REV10-R00] [REV10-P035] [REV10-P036] [REV10-P037]'),
('REV10-E04','calibration','Old-population optical colors and many indices suffer a strong age-metallicity degeneracy.','Most severe for populations older than about 5 Gyr and limited optical information.','High; full spectra and selected index combinations can reduce but not erase it.','[REV10-R00] [REV10-P038] [REV10-P039] [REV10-P040]'),
('REV10-E05','analytic_theory','Panchromatic energy-balance models connect attenuated UV-optical starlight to infrared dust emission.','Requires adequate UV-to-IR coverage and assumptions about dust heating by young versus old stars.','High for energy conservation, moderate for decomposed SFR/dust parameters.','[REV10-R00] [REV10-P024] [REV10-P026] [REV10-P027]'),
('REV10-E06','calibration','Extinction and attenuation laws are not interchangeable or universal because geometry and stellar age alter effective attenuation.','Milky-Way sightline extinction, starburst attenuation, and normal-galaxy mixtures have different domains.','High.','[REV10-R00] [REV10-P022] [REV10-P023] [REV10-P041]'),
('REV10-E07','calibration','TP-AGB treatment drives large near-IR SPS differences for intermediate-age populations.','Ages roughly 0.1-2 Gyr; metallicity, SFH, circumstellar dust, and calibration samples matter.','High for model disagreement; disputed physical amplitude.','[REV10-R00] [REV10-P002] [REV10-P008] [REV10-P034]'),
('REV10-E08','calibration','Optical color-based mass-to-light estimates are generally less sensitive to TP-AGB prescriptions than near-IR estimates.','Dusty starbursts and heavily obscured systems can violate the practical advantage.','Moderate to high.','[REV10-R00] [REV10-P001] [REV10-P033]'),
('REV10-E09','calibration','Low-mass IMF normalization strongly controls stellar mass-to-light ratios while contributing little integrated light.','IMF extrapolation below directly light-dominating masses; remnants and low-mass cutoff matter.','High.','[REV10-R00] [REV10-P015] [REV10-P016] [REV10-P017]'),
('REV10-E10','observation','Gravity-sensitive spectra, dynamics, and lensing provided evidence by 2013 that massive early-type galaxies may have heavier IMF normalizations than the Milky Way.','Massive old systems; abundance responses, dark matter, and dynamical modeling remain degenerate.','Moderate; not proof of one universal IMF trend.','[REV10-R00] [REV10-P018] [REV10-P019] [REV10-P020] [REV10-P021]'),
('REV10-E11','calibration','UV, recombination-line, and IR SFR indicators average star formation over different timescales and dust sensitivities.','Calibration assumes an IMF, metallicity, SFH duration, and dust heating decomposition.','High.','[REV10-R00] [REV10-P028] [REV10-P031] [REV10-P032] [REV10-P041]'),
('REV10-E12','calibration','Nebular lines and continuum can materially contaminate broadband SEDs of high-equivalent-width galaxies and bias stellar parameters if omitted.','Strongest for high-sSFR, low-metallicity, high-redshift systems as lines traverse filters.','High for contamination, model-dependent for parameter shifts.','[REV10-R00] [REV10-P042]'),
('REV10-E13','calibration','Empirical and theoretical stellar libraries have complementary limitations in parameter and abundance coverage.','Empirical libraries reflect local abundance patterns; theoretical spectra inherit atmosphere and line-list errors.','High.','[REV10-R00] [REV10-P011] [REV10-P012] [REV10-P013] [REV10-P014]'),
]
D=[
('REV10-D01','TP-AGB strength','TP-AGB-heavy versus lighter near-IR contributions at intermediate ages.','Cluster calibrators, stochasticity, metallicity, SFH, and dust permit competing fits.','[REV10-R00] [REV10-P002] [REV10-P003] [REV10-P008] [REV10-P034]'),
('REV10-D02','IMF universality','Milky-Way-like universal IMF versus systematic variation with velocity dispersion or abundance.','Spectral features, dynamics, lensing, abundance patterns, remnants, and dark matter are degenerate.','[REV10-R00] [REV10-P017] [REV10-P018] [REV10-P019] [REV10-P020] [REV10-P021]'),
('REV10-D03','Flexible versus parametric SFHs','Simple exponential/rising histories versus nonparametric, burst-capable reconstructions.','Flexible models reduce bias but increase prior dependence and time-bin covariance.','[REV10-R00] [REV10-P035] [REV10-P036] [REV10-P037]'),
('REV10-D04','Dust law and geometry','Universal foreground-like laws versus variable attenuation from mixed geometry and stellar ages.','UV slope, IRX, inclination, composition, and star-dust geometry covary.','[REV10-R00] [REV10-P022] [REV10-P023] [REV10-P024] [REV10-P041]'),
('REV10-D05','Age-metallicity-dust separation','Broadband optical constraints versus full spectra and extended wavelength baselines.','The same reddening and features can be produced by correlated changes and abundance ratios.','[REV10-R00] [REV10-P038] [REV10-P039] [REV10-P040]'),
('REV10-D06','Absolute stellar-mass accuracy','About factor-two practical estimates versus larger SPS/IMF/SFH systematics.','Formal fit errors omit model mismatch and unseen low-mass/old populations.','[REV10-R00] [REV10-P029] [REV10-P030] [REV10-P033]'),
('REV10-D07','SFR calibration and timescale','UV, Halpha, IR, and SED-fit SFRs need not agree for bursty or dusty populations.','Each tracer weights different stellar ages and dust heating sources.','[REV10-R00] [REV10-P028] [REV10-P031] [REV10-P032] [REV10-P041]'),
('REV10-D08','Optical-only versus panchromatic inference','Optical spectra tightly constrain some populations, while UV/IR are needed for young stars and obscured energy.','Adding bands can add model systematics as well as information; energy balance needs IR coverage.','[REV10-R00] [REV10-P027] [REV10-P030] [REV10-P032]'),
]
N=[
('REV10-N01','L_SSP(lambda,t,Z) = integral phi(m) L_star(lambda,m,t,Z) dm','luminosity per wavelength','Core SSP construction from IMF-weighted stellar spectra along an isochrone.','Schematic; normalization, remnants, binaries, and interpolation differ by SPS code.','[REV10-R00] [REV10-P001] [REV10-P003]'),
('REV10-N02','m_low ~ 0.08-0.1 M_sun; m_up ~ 100 M_sun','solar masses','Typical SPS IMF integration bounds described by the review.','Code and IMF dependent; luminous SEDs weakly constrain m_low directly.','[REV10-R00] [REV10-P015] [REV10-P016] [REV10-P017]'),
('REV10-N03','sigma(log M_star) ~ 0.3 dex','dex','Generic practical statistical uncertainty for normal-SFH stellar masses.','Does not include full IMF, SPS, dust, and SFH systematic envelope.','[REV10-R00] [REV10-P029] [REV10-P030]'),
('REV10-N04','Delta log M_star up to ~0.6 dex in extreme SFH choices','dex','Review benchmark for mass shifts from restrictive versus flexible SFHs.','Extreme model comparison, not a universal per-galaxy error bar.','[REV10-R00] [REV10-P035] [REV10-P036] [REV10-P037]'),
('REV10-N05','~60-80% of stellar mass can reside in low-mass stars contributing little optical/NIR light','percent of stellar mass','Illustrates IMF-driven hidden-mass sensitivity for old populations.','Fraction depends on IMF limits, remnants, age, and definition of current versus formed mass.','[REV10-R00] [REV10-P015] [REV10-P016] [REV10-P017]'),
('REV10-N06','Delta age factor ~3 mimics Delta metallicity factor ~2','dimensionless factors','Worthey 3/2 rule for old populations in optical colors/indices.','Approximate and population/index dependent; full spectra can improve separation.','[REV10-R00] [REV10-P038]'),
('REV10-N07','S/N >~100 per Angstrom','signal-to-noise per Angstrom','Review benchmark for separating age and metallicity with carefully chosen absorption indices.','Resolution, calibration, velocity dispersion, and abundance models apply.','[REV10-R00] [REV10-P039] [REV10-P040]'),
('REV10-N08','UV SFR timescale ~100 Myr; Halpha timescale <~10 Myr','Myr','Characteristic response times of massive-star UV continuum and ionizing-photon recombination lines.','Assumes sustained SF and an IMF; bursty histories invalidate steady-state conversions.','[REV10-R00] [REV10-P028] [REV10-P031] [REV10-P032]'),
]
U=[
('REV10-U01','Predictive stellar evolution for TP-AGB, horizontal-branch, blue-straggler, overshoot, rotation, and mass-loss phases.','These short phases can dominate selected wavelengths and bias ages/masses.','Resolved populations across age/metallicity plus improved tracks propagated into SPS.','[REV10-R00] [REV10-P002] [REV10-P007] [REV10-P008] [REV10-P009] [REV10-P010]'),
('REV10-U02','Whether and how the IMF varies across galaxies.','Sets absolute stellar masses, yields, remnants, and feedback budgets.','Joint abundance-sensitive spectra, dynamics, lensing, and spatial gradients with common models.','[REV10-R00] [REV10-P018] [REV10-P019] [REV10-P020] [REV10-P021]'),
('REV10-U03','Unbiased nonparametric recovery of full SFHs and enrichment histories.','Galaxy growth tracks cannot be inferred reliably from light-weighted ages alone.','Mock-tested flexible inference with calibrated priors, spectra, and panchromatic data.','[REV10-R00] [REV10-P035] [REV10-P036] [REV10-P037]'),
('REV10-U04','General dust attenuation and emission models across geometry, inclination, and galaxy type.','Dust corrections dominate SFR and color interpretation.','Resolved UV-to-FIR radiative transfer and energy-balance tests beyond starbursts.','[REV10-R00] [REV10-P023] [REV10-P024] [REV10-P026] [REV10-P027] [REV10-P041]'),
('REV10-U05','Accurate abundance-response functions across stellar parameter space.','IMF- and metallicity-sensitive spectral features can mimic abundance changes.','High-S/N empirical libraries and validated atmosphere models with non-solar patterns.','[REV10-R00] [REV10-P013] [REV10-P014] [REV10-P039] [REV10-P040]'),
('REV10-U06','A complete accounting of SPS model discrepancy in demographic error budgets.','Mass functions and cosmic stellar mass density can be precision-limited by shared model systematics.','Cross-code hierarchical fits with common data, priors, calibration, and external dynamical checks.','[REV10-R00] [REV10-P001] [REV10-P003] [REV10-P004] [REV10-P029]'),
]
L=['# Review Base 10 — Conroy (2013): Modeling the Panchromatic Spectral Energy Distributions of Galaxies','','Status: READY_FOR_HWAO_REVIEW — canonical packet recovered from complete review bibliography after raw response under-harvest; advisory only.','',f"Raw custody SHA-256: `{hashlib.sha256(RAW.read_bytes()).hexdigest()}`",'','## 1. Review Identity and Scope Map','',t(['Field','Value'],[('Review key','[REV10-R00]'),('Author','Charlie Conroy'),('Year / journal','2013, Annual Review of Astronomy and Astrophysics 51, 393-455'),('DOI','10.1146/annurev-astro-082812-141017'),('arXiv','1301.7095'),('ADS','2013ARA&A..51..393C'),('Authorized scope','Stellar population synthesis, FUV-to-FIR SEDs, stellar evolution/libraries, IMF, SFH, metallicity/abundances, dust, nebular emission, and inferred galaxy properties through 2013.'),('Explicit exclusions','Post-2013 work, AGN-only SEDs, model-free inference claims, universal attenuation/IMF claims, and unique SFHs from one SED.')]),'','## 2. Established Findings','',t(['ID','Epistemic type','Bounded finding','Boundary','Confidence','Sources'],E),'','## 3. Open Debates and Tensions','',t(['ID','Topic','Competing positions','Why unresolved / boundary','Sources'],D),'','## 4. Key Measurements, Model Benchmarks, and Calibrations','',t(['ID','Value / equation','Units','Context','Status / caveat','Sources'],N),'','## 5. What Remained Unknown in 2013','',t(['ID','Gap','Why it matters','Needed test','Sources'],U),'','## 6. Primary-Citation Harvest','']
for s in p:L.append(f"[{s['key']}] {s['authors']} ({s['year']}, {s['journal']}) | title={s['title']} | DOI:{s['doi'] or 'none'}; arXiv:{s['arxiv'] or 'none'}; ADS:{s['ads_bibcode']} | role={s['role']} | review_locator={s['review_locator']} | {s['boundary']} | source_status=PASS_ADS_AND_REVIEW_MEMBERSHIP")
L+=['','### Supporting reviews','']
for s in sr:L.append(f"[{s['key']}] {s['authors']} ({s['year']}, {s['journal']}) | title={s['title']} | DOI:{s['doi'] or 'none'}; arXiv:{s['arxiv'] or 'none'}; ADS:{s['ads_bibcode']} | role=supporting_review | review_locator={s['review_locator']} | {s['boundary']} | source_status=PASS_ADS_AND_REVIEW_MEMBERSHIP")
L+=['','## 7. DO_NOT_USE_UNVERIFIED','']
for s in q:L.append(f"UNCITED_NOT_USABLE | [{s['key']}] {s['title']} | DOI:{s['doi'] or 'none'}; arXiv:{s['arxiv'] or 'none'}; ADS:{s['ads_bibcode'] or 'none'} | {s['quarantine_reason']}")
L+=['UNCITED_NOT_USABLE | SED-derived mass, SFR, or age is model-free | none | SPS and prior dependence erased.','UNCITED_NOT_USABLE | one color uniquely fixes age or metallicity, one attenuation law is universal, or one IMF is proven universal | none | degeneracy and domain overreach.','UNCITED_NOT_USABLE | optical-only fits determine dust emission or matching one SED validates one unique SFH | none | missing energy-balance information and inverse-problem non-uniqueness.','UNCITED_NOT_USABLE | post-2013/JWST/ML browsing results | none | outside review temporal boundary.','','## 8. Review and Source Identity Ledger','','[REV10-R00] Conroy C (2013, Annual Review of Astronomy and Astrophysics) | title=Modeling the Panchromatic Spectral Energy Distributions of Galaxies | DOI:10.1146/annurev-astro-082812-141017; arXiv:1301.7095; ADS:2013ARA&A..51..393C | role=review_synthesis | source_status=PASS_ADS_CROSSREF_ARXIV','']
for s in p+sr:L.append(f"[{s['key']}] {s['authors']} ({s['year']}, {s['journal']}) | title={s['title']} | DOI:{s['doi'] or 'none'}; arXiv:{s['arxiv'] or 'none'}; ADS:{s['ads_bibcode']} | role={s['role']} | boundary={s['boundary']} | source_status=PASS_ADS_AND_REVIEW_MEMBERSHIP")
L+=['','REVIEW_BASE_10_DR_COMPLETE_REFERENCE_ONLY',''];OUT.write_text('\n'.join(L));print(json.dumps({'packet':str(OUT),'primary':len(p),'supporting':len(sr),'quarantined':len(q),'sha256':hashlib.sha256(OUT.read_bytes()).hexdigest()},sort_keys=True))
