import hashlib,json
from pathlib import Path
A=Path('/Users/duhokim/NebulaMind/NebulaMind/.hermes/handoffs/galaxy-evolution/wiki-expansion-20260715');RAW=A/'area_review_14_kewley_nicholls_sutherland_2019_DR_RAW_PACKET.md';REG=A/'area_review_14_kewley_nicholls_sutherland_2019_CURATED_SOURCE_REGISTRY.json';OUT=A/'area_review_14_kewley_nicholls_sutherland_2019_DR_PACKET.md';r=json.loads(REG.read_text());p=[x for x in r['sources'] if x['source_status']=='PASS' and x['role']!='supporting_review'];sr=[x for x in r['sources'] if x['source_status']=='PASS' and x['role']=='supporting_review'];q=[x for x in r['sources'] if x['source_status']!='PASS'];assert(len(p),len(sr),len(q))==(40,2,13)
def t(h,rows):
 e=lambda v:str(v).replace('|','\\|').replace('\n',' ')
 return '\n'.join(['| '+' | '.join(h)+' |','|'+'|'.join(['---']*len(h))+'|']+['| '+' | '.join(e(v) for v in z)+' |' for z in rows])
E=[
('REV14-E01','calibration/review synthesis','UV, optical, and IR lines probe complementary ionization zones and must be combined rather than treated as interchangeable diagnostics.','Line availability, extinction, aperture, density, metallicity, excitation source, and model grid apply.','High.','[REV14-R00] [REV14-P005] [REV14-P010] [REV14-P020]'),
('REV14-E02','atomic physics','Collisionally excited auroral-to-nebular ratios constrain electron temperature, while density-sensitive doublets constrain electron density in the emitting ion.','Atomic coefficients, low/high-density limits, temperature, recombination contribution, sky subtraction, and zone matching apply.','High.','[REV14-P005] [REV14-P020] [REV14-P041]'),
('REV14-E03','calibration','Direct-Te, recombination-line, empirical strong-line, and photoionization-model metallicities occupy systematically different abundance scales.','Normally 12+log(O/H); temperature structure, depletion, atomic data, abundance pattern, and calibration range apply.','High.','[REV14-P018] [REV14-P020] [REV14-P034] [REV14-P035] [REV14-P048]'),
('REV14-E04','calibration','Optical BPT diagrams separate dominant excitation statistically, but mixing among star formation, AGN, shocks, and diffuse gas prevents a pure one-label causal interpretation.','Integrated fibers versus spaxels; S/N cuts, aperture, abundance, ionization parameter, N/O, and mixing apply.','High.','[REV14-P013] [REV14-P015] [REV14-P026] [REV14-P032] [REV14-P033] [REV14-P046]'),
('REV14-E05','simulation','Fast radiative shocks and precursors trace model-dependent trajectories through optical/UV line-ratio space that overlap AGN and composite excitation.','Shock velocity, magnetic parameter, abundance, density, precursor, geometry, and code version apply.','High for grid predictions.','[REV14-P003] [REV14-P004] [REV14-P017] [REV14-P027]'),
('REV14-E06','simulation/calibration','Ionization parameter, metallicity, pressure/density, abundance ratios, stellar spectrum, and dust jointly shape strong-line ratios; no single ratio isolates all properties.','Photoionization-grid priors and coupled parameter degeneracies apply.','High.','[REV14-P018] [REV14-P029] [REV14-P031] [REV14-P033] [REV14-P034]'),
('REV14-E07','observation','Diffuse ionized gas can enhance low-ionization line ratios, move spaxels toward composite/LI(N)ER-like regions, and bias inferred metallicity gradients.','Surface-brightness/resolution selection, ionizing-source mixture, galaxy inclination, and diagnostic choice apply.','High.','[REV14-P014] [REV14-P015] [REV14-P049]'),
('REV14-E08','observation/simulation','High-redshift star-forming galaxies are offset from the local [NII] BPT sequence because nebular abundance ratios, radiation hardness, density/pressure, and ionization differ.','Selection, stacking, AGN rejection, stellar models, N/O at fixed O/H, and redshift/sample range apply.','High for offset; model-dependent decomposition.','[REV14-P028] [REV14-P036] [REV14-P047]'),
('REV14-E09','calibration','Nitrogen-bearing metallicity diagnostics depend on N/O as well as O/H and can be biased when abundance-pattern evolution differs from local calibrators.','Primary/secondary nitrogen history, time delay, ionization, DIG, and calibration family apply.','High.','[REV14-P007] [REV14-P034] [REV14-P044] [REV14-P047]'),
('REV14-E10','calibration','Infrared fine-structure lines reduce dust attenuation and temperature sensitivity but still depend on ionization zone, aperture, density, abundance, and excitation source.','Integrated dusty galaxies; extinction-insensitive does not mean model-independent.','High.','[REV14-P002] [REV14-P010]'),
('REV14-E11','calibration','Joint Bayesian/grid methods can infer metallicity and ionization parameter from many lines while making model and prior dependence explicit.','HII-region grids do not describe DIG, shocks, or AGN unless those components are included.','High.','[REV14-P018] [REV14-P021] [REV14-P029] [REV14-P049]'),
('REV14-E12','observation','Local mass-metallicity relations are robust population correlations, but their normalization changes substantially with metallicity calibration.','Stellar mass/SFR assumptions, fiber aperture, selection, DIG, and abundance scale apply.','High.','[REV14-P009] [REV14-P021] [REV14-P035] [REV14-P045] [REV14-P048]'),
('REV14-E13','calibration','Dust correction and the assumed stellar-population synthesis affect emission-line SFRs and the modeled ionizing spectrum.','Attenuation geometry, differential gas-star reddening, stellar tracks, rotation, and binaries apply.','High.','[REV14-R00] [REV14-P022] [REV14-P029]'),
]
D=[
('REV14-D01','Abundance scale','Direct-Te/recombination abundance scales versus photoionization-model strong-line scales.','Temperature gradients/fluctuations, atomic data, depletion, and model spectra yield persistent offsets.','[REV14-P020] [REV14-P034] [REV14-P035] [REV14-P038] [REV14-P041] [REV14-P048]'),
('REV14-D02','Electron energy distribution','Maxwell-Boltzmann electrons with temperature structure versus kappa-like nonthermal distributions.','Different observables can mimic each other and atomic/recombination uncertainties remain.','[REV14-P038] [REV14-P041]'),
('REV14-D03','High-redshift BPT offset','Harder stellar spectra, higher U/pressure, elevated N/O, AGN/shocks, or selection as dominant cause.','The parameters covary and different diagnostic planes respond differently.','[REV14-P028] [REV14-P036] [REV14-P047]'),
('REV14-D04','Composite/LI(N)ER emission','AGN, shocks, evolved stars, leakage, or DIG as the source of low-ionization ratios.','Integrated apertures and spatial mixing prevent unique attribution from one 2D diagram.','[REV14-P004] [REV14-P015] [REV14-P026] [REV14-P027] [REV14-P046] [REV14-P049]'),
('REV14-D05','Ionization parameter proxy','O32 and related ratios as U estimators versus strong dependence on metallicity, spectrum, geometry, and optical depth.','No one-dimensional mapping survives all model regimes.','[REV14-P018] [REV14-P028] [REV14-P034] [REV14-P036]'),
('REV14-D06','Metallicity gradients','True abundance structure versus DIG, spatial resolution, calibration, and mixing biases.','Different strong-line diagnostics respond differently to DIG and N/O.','[REV14-P014] [REV14-P049]'),
('REV14-D07','Solar/abundance pattern','One scaled-solar abundance axis versus independent C/O, N/O, Fe/O, depletion, and stellar/gas metallicities.','Line cooling and ionizing spectra respond to element ratios, not one scalar Z.','[REV14-P007] [REV14-P008] [REV14-P011] [REV14-P047]'),
('REV14-D08','Diagnostic transfer','Local empirical calibrations applied at high redshift versus redshift-specific model/empirical sequences.','Ionizing spectra, density/pressure, N/O, and selection evolve.','[REV14-P036] [REV14-P044] [REV14-P047] [REV14-P048]'),
]
N=[
('REV14-N01','R_O3 = I([O III] lambda4363) / (I(lambda4959)+I(lambda5007))','dimensionless flux ratio','Auroral-to-nebular O++ temperature diagnostic; invert with atomic collision strengths and density.','Weak auroral line; recombination, reddening, temperature structure, and zone matching apply.','[REV14-P005] [REV14-P020] [REV14-P041]'),
('REV14-N02','R_S2 = I([S II] lambda6717) / I([S II] lambda6731)','dimensionless flux ratio','Electron-density diagnostic for the S+ zone at assumed Te; approaches low/high-density limits.','Saturates outside sensitive range; blended components and DIG affect integrated values.','[REV14-R00] [REV14-P049]'),
('REV14-N03','O32 = (I([O III] lambda4959)+I(lambda5007)) / (I([O II] lambda3726)+I(lambda3729))','dimensionless flux ratio','Ionization-sensitive ratio spanning O+ and O++ zones.','Strongly depends on metallicity, spectrum, dust correction, pressure, geometry, and leakage; not U alone.','[REV14-P018] [REV14-P028] [REV14-P034]'),
('REV14-N04','R23 = (I([O II] lambda3726+3729)+I([O III] lambda4959+5007)) / I(Hbeta)','dimensionless flux ratio','Classical strong-line oxygen index.','Double-valued with O/H; branch and ionization parameter must be resolved.','[REV14-P034] [REV14-P040]'),
('REV14-N05','log([O III]5007/Hbeta) = 0.61/(log([N II]6584/Halpha)-0.47)+1.19','log10 line ratios','Theoretical maximum-starburst boundary in the [NII] BPT plane.','Local model envelope, not a universal redshift-independent causal classifier.','[REV14-P033]'),
('REV14-N06','log([O III]5007/Hbeta) = 0.61/(log([N II]6584/Halpha)-0.05)+1.30','log10 line ratios','Empirical SDSS star-forming/composite boundary.','Sample/SN/aperture-specific and not transferable unchanged to resolved DIG or high z.','[REV14-P032]'),
('REV14-N07','O3N2 = log10{([O III]5007/Hbeta)/([N II]6584/Halpha)}; 12+log(O/H)=8.73-0.32 O3N2','dex abundance','Empirical O3N2 metallicity calibration for HII-like excitation over its published index range.','N/O, ionization, DIG, high-z sequence, and calibration range apply.','[REV14-P044]'),
('REV14-N08','P/k approximately (n_e+n_ion) T_e; approximately 2 n_e T_e for fully ionized hydrogen','K cm^-3','Order-of-magnitude thermal pressure relation tied to the density/temperature zone measured.','Composition, ionization fraction, multiple density zones, and constant-pressure versus constant-density model convention apply.','[REV14-R00] [REV14-P031]'),
('REV14-N09','N2 = log10([N II]6584/Halpha)','dex line-ratio index','Compact abundance/excitation indicator using close wavelengths.','Saturates at high abundance and depends strongly on N/O, U, DIG, and AGN/shocks.','[REV14-P007] [REV14-P044] [REV14-P049]'),
('REV14-N10','Strong-line calibration offsets can approach several tenths of a dex in 12+log(O/H)','dex','Comparisons among theoretical and empirical metallicity scales in local galaxy samples.','Use published cross-calibration only inside overlapping ranges; conversion does not remove physical assumptions.','[REV14-P035] [REV14-P048]'),
]
U=[
('REV14-U01','Self-consistent stellar-plus-nebular models for the hardest ionizing spectra across age, metallicity, rotation, and binaries.','Controls high-z BPT/UV interpretation and inferred U/Z.','Benchmark stellar atmospheres/populations against resolved nebulae and multiwavelength line sets.','[REV14-P022] [REV14-P028] [REV14-P036] [REV14-P047]'),
('REV14-U02','Three-dimensional density/temperature/abundance structure inside representative HII regions and galaxies.','One-zone calibrations can bias Te, ne, pressure, and abundance.','Resolved UV-optical-IR spectroscopy with 3D radiation-hydrodynamic photoionization models.','[REV14-R00] [REV14-P014] [REV14-P018]'),
('REV14-U03','Universal treatment of DIG and excitation mixing in integrated and resolved spectra.','DIG biases classification, metallicity, U, and gradients.','Resolution-matched component models constrained by surface brightness and stellar populations.','[REV14-P014] [REV14-P015] [REV14-P049]'),
('REV14-U04','Absolute nebular abundance scale and the origin of recombination/CEL discrepancies.','Sets the zero point of galaxy chemical evolution.','Improved atomic data plus multiple auroral, recombination, IR, and stellar abundance constraints in the same regions.','[REV14-P020] [REV14-P038] [REV14-P041]'),
('REV14-U05','Robust excitation separation for unresolved high-redshift galaxies with incomplete wavelength coverage.','AGN/shock/DIG contamination biases SFR and abundance evolution.','Joint UV-optical-IR diagnostics and spatial/kinematic information validated against full-spectrum local analogs.','[REV14-P004] [REV14-P026] [REV14-P036] [REV14-P047]'),
('REV14-U06','Independent evolution of O/H, N/O, C/O, Fe/O, depletion, U, and pressure across cosmic time.','A single metallicity coordinate cannot reproduce all line ratios.','Large direct-temperature and multi-element samples with matched stellar metallicities and flexible abundance-pattern grids.','[REV14-P007] [REV14-P011] [REV14-P036] [REV14-P047]'),
]
L=['# Review Base 14 — Kewley, Nicholls & Sutherland (2019): Understanding Galaxy Evolution Through Emission Lines','','Status: READY_FOR_HWAO_REVIEW — canonical advisory packet; raw custody preserved and independently reconciled.','',f"Raw custody SHA-256: `{hashlib.sha256(RAW.read_bytes()).hexdigest()}`",'','## 1. Review Identity and Scope Map','',t(['Field','Value'],[('Review key','[REV14-R00]'),('Authors','Lisa J. Kewley; David C. Nicholls; Ralph S. Sutherland'),('Year / journal','2019, Annual Review of Astronomy and Astrophysics 57, 511-570'),('DOI','10.1146/annurev-astro-081817-051832'),('arXiv','1910.09730'),('ADS','2019ARA&A..57..511K'),('Authorized scope','UV, optical, and IR emission-line diagnostics for excitation, abundance, U, pressure/density, DIG, shocks, AGN, star formation, gradients, and redshift evolution.'),('Explicit exclusions','Post-2019 work; uncited browsing spillover; diagnostic transfer outside calibration ranges; mixing HII, DIG, NLR, shock, integrated, and spaxel regimes; unconverted metallicity scales.')]),'','## 2. Established Findings','',t(['ID','Epistemic type','Bounded finding','Regime / boundary','Confidence','Sources'],E),'','## 3. Open Debates and Tensions','',t(['ID','Topic','Competing positions','Why unresolved / boundary','Sources'],D),'','## 4. Key Measurements and Diagnostic Calibrations','',t(['ID','Value / equation','Units','Definitions and regime','Status / caveat','Sources'],N),'','## 5. What Remained Unknown in 2019','',t(['ID','Gap','Why it matters','Needed test','Sources'],U),'','## 6. Primary-Citation Harvest','']
for s in p:L.append(f"[{s['key']}] {s['authors']} ({s['year']}, {s['journal']}) | title={s['title']} | DOI:{s['doi'] or 'none'}; arXiv:{s['arxiv'] or 'none'}; ADS:{s['ads_bibcode']} | role={s['role']} | review_locator={s['review_locator']} | {s['boundary']} | source_status=PASS_ADS_AND_REVIEW_MEMBERSHIP")
L+=['','### Supporting reviews and textbooks','']
for s in sr:L.append(f"[{s['key']}] {s['authors']} ({s['year']}, {s['journal']}) | title={s['title']} | DOI:{s['doi'] or 'none'}; arXiv:{s['arxiv'] or 'none'}; ADS:{s['ads_bibcode']} | role=supporting_review | review_locator={s['review_locator']} | {s['boundary']} | source_status=PASS_ADS_AND_REVIEW_MEMBERSHIP")
L+=['','## 7. DO_NOT_USE_UNVERIFIED','']
for s in q:L.append(f"UNCITED_NOT_USABLE | [{s['key']}] {s['title']} | DOI:{s['doi'] or 'none'}; arXiv:{s['arxiv'] or 'none'}; ADS:{s['ads_bibcode'] or 'none'} | {s['quarantine_reason']}")
L+=['UNCITED_NOT_USABLE | BPT location is a unique causal excitation label | none | aperture and excitation mixing violate one-label inference.','UNCITED_NOT_USABLE | direct-Te, empirical strong-line, and model metallicities are one common scale | none | calibration-scale mismatch.','UNCITED_NOT_USABLE | O32 measures only ionization parameter | none | spectrum, abundance, geometry, pressure, and leakage covary.','UNCITED_NOT_USABLE | local line-ratio boundaries transfer unchanged to high redshift | none | physical-condition and abundance-pattern evolution.','UNCITED_NOT_USABLE | DIG-free HII-region grids may be applied to DIG | none | source/model mismatch.','UNCITED_NOT_USABLE | post-2019/JWST browsing results | none | outside temporal boundary.','','## 8. Composite Source Identity Ledger','','[REV14-R00] Kewley LJ; Nicholls DC; Sutherland RS (2019, Annual Review of Astronomy and Astrophysics) | title=Understanding Galaxy Evolution Through Emission Lines | DOI:10.1146/annurev-astro-081817-051832; arXiv:1910.09730; ADS:2019ARA&A..57..511K | role=review_synthesis_and_labeled_2019_review_calibrations | source_status=PASS_ADS_CROSSREF_ARXIV','']
for s in p+sr:L.append(f"[{s['key']}] {s['authors']} ({s['year']}, {s['journal']}) | title={s['title']} | DOI:{s['doi'] or 'none'}; arXiv:{s['arxiv'] or 'none'}; ADS:{s['ads_bibcode']} | role={s['role']} | boundary={s['boundary']} | source_status=PASS_ADS_AND_REVIEW_MEMBERSHIP")
L+=['','REVIEW_BASE_14_DR_COMPLETE_REFERENCE_ONLY',''];OUT.write_text('\n'.join(L));print(json.dumps({'packet':str(OUT),'primary':len(p),'supporting':len(sr),'quarantined':len(q),'sha256':hashlib.sha256(OUT.read_bytes()).hexdigest()},sort_keys=True))
