import hashlib,json
from pathlib import Path
A=Path('/Users/duhokim/NebulaMind/NebulaMind/.hermes/handoffs/galaxy-evolution/wiki-expansion-20260715');RAW=A/'area_review_11_wechsler_tinker_2018_DR_RAW_PACKET.md';REG=A/'area_review_11_wechsler_tinker_2018_CURATED_SOURCE_REGISTRY.json';OUT=A/'area_review_11_wechsler_tinker_2018_DR_PACKET.md';r=json.loads(REG.read_text());p=[x for x in r['sources'] if x['source_status']=='PASS' and x['role']!='supporting_review'];sr=[x for x in r['sources'] if x['source_status']=='PASS' and x['role']=='supporting_review'];q=[x for x in r['sources'] if x['source_status']!='PASS'];assert(len(p),len(sr),len(q))==(40,3,9)
def t(h,rows):
 e=lambda v:str(v).replace('|','\\|').replace('\n',' ')
 return '\n'.join(['| '+' | '.join(h)+' |','|'+'|'.join(['---']*len(h))+'|']+['| '+' | '.join(e(v) for v in z)+' |' for z in rows])
E=[
('REV11-E01','calibration','The central-galaxy stellar-to-halo mass relation is strongly non-linear, with maximum integrated galaxy-formation efficiency near a Milky-Way-scale halo.','Central galaxies; halo mass definition, IMF, stellar-mass function, redshift, and scatter model shift the parameters.','High.','[REV11-R00] [REV11-P001] [REV11-P002] [REV11-P020] [REV11-P025]'),
('REV11-E02','observation/calibration','At z~0 the peak integrated efficiency M*/(f_b M_h) remains below about 20%.','Central stellar mass divided by the cosmic baryon allotment, not instantaneous SFR efficiency; near M_h~10^12 M_sun.','High as review-level bound.','[REV11-R00] [REV11-P001] [REV11-P002] [REV11-P020]'),
('REV11-E03','observation/calibration','Intrinsic scatter in central stellar mass at fixed halo mass above the pivot is small, generally below about 0.2 dex.','Usually lognormal and inferred jointly from abundance, clustering, and lensing; measurement errors must be removed.','Moderate to high.','[REV11-R00] [REV11-P006] [REV11-P018] [REV11-P042]'),
('REV11-E04','review_synthesis','Below the pivot, M* falls steeply with decreasing halo mass and the slope/scatter become increasingly uncertain toward dwarfs.','Incompleteness, reionization, stellar-mass estimates, stripping, and central-versus-satellite definitions dominate.','High for steep decline; low for extreme-dwarf parameters.','[REV11-R00] [REV11-P001] [REV11-P002] [REV11-P022]'),
('REV11-E05','calibration','At group and cluster masses, central stellar mass grows much more slowly than halo mass.','BCG photometry, intracluster light, halo mass calibration, and central/total stellar mass must be distinguished.','High qualitatively.','[REV11-R00] [REV11-P006] [REV11-P025] [REV11-P042]'),
('REV11-E06','analytic_theory/calibration','HOD and CLF models require separate central and satellite occupation distributions to reproduce galaxy abundance and scale-dependent clustering.','Statistical population model, not a unique physical assignment; sample selection and halo definition apply.','High.','[REV11-P003] [REV11-P004] [REV11-P005] [REV11-P007] [REV11-P035]'),
('REV11-E07','calibration','Abundance matching can reproduce galaxy abundance and clustering by rank-ordering galaxies and halos/subhalos using a chosen proxy with scatter.','Monotonicity, proxy choice, orphan treatment, disruption, and stellar-mass systematics are assumptions.','High as an empirical framework.','[REV11-P014] [REV11-P018] [REV11-P019] [REV11-P041]'),
('REV11-E08','observation','The one-halo/two-halo transition produces measurable departures from a single power law in galaxy clustering, and the one-halo term constrains satellites.','Projected clustering and HOD interpretation; redshift-space, fiber, and sample selection corrections apply.','High.','[REV11-P005] [REV11-P021] [REV11-P032] [REV11-P035]'),
('REV11-E09','observation','Galaxy-galaxy lensing and clustering provide complementary constraints on mean halo mass, satellite fraction, and occupation.','Weak lensing is ensemble total-mass inference with projection/photo-z/shear systematics; conclusions remain model dependent.','High.','[REV11-P006] [REV11-P042]'),
('REV11-E10','simulation','Dark-matter halo clustering depends on formation history and concentration at fixed halo mass: halo assembly bias.','Amplitude and sign depend on halo mass, secondary definition, environment, and simulation/halo finder.','High in collisionless simulations.','[REV11-P008] [REV11-P009] [REV11-P010]'),
('REV11-E11','observation','Satellite galaxy star formation and color differ from comparable centrals, and infall histories imply delayed then relatively rapid quenching for local satellites.','Group finding, preprocessing, backsplash/ejected systems, infall definition, and stellar-mass selection apply.','High for demographic difference, moderate for detailed timescales.','[REV11-P031] [REV11-P044]'),
('REV11-E12','simulation/calibration','Precision galaxy-halo models rely on calibrated halo mass functions and halo bias relations from N-body simulations.','Cosmology, overdensity definition, redshift, baryonic back-reaction, and numerical resolution limit transfer.','High within calibrated domains.','[REV11-P012] [REV11-P013] [REV11-P034] [REV11-P039]'),
('REV11-E13','calibration','Secondary galaxy properties can be linked statistically to halo age, concentration, or accretion to reproduce color- and property-dependent clustering.','Success does not establish a unique causal variable; correlated halo properties permit alternative mappings.','Moderate.','[REV11-P017] [REV11-P028] [REV11-P041] [REV11-P043] [REV11-P046]'),
]
D=[
('REV11-D01','Galaxy assembly bias','Mass-only occupation versus explicit coupling of galaxy properties to halo formation history or concentration.','Halo masses and secondary properties are noisy and correlated; environment can mimic the signal.','[REV11-P008] [REV11-P010] [REV11-P017] [REV11-P030] [REV11-P041]'),
('REV11-D02','Origin of SHMR scatter','Merger/accretion history, concentration, spin, baryonic stochasticity, and measurement error as dominant contributors.','Inferred intrinsic scatter depends on deconvolution and cross-correlated galaxy observables.','[REV11-P006] [REV11-P009] [REV11-P018] [REV11-P046]'),
('REV11-D03','Optimal abundance-matching proxy','Present Vmax/M, peak V or M, infall values, or compound concentration-sensitive proxies.','Satellite stripping/disruption, resolution, and orphan galaxies change small-scale clustering.','[REV11-P011] [REV11-P014] [REV11-P041]'),
('REV11-D04','Satellite quenching mechanism','Starvation/strangulation, ram pressure, tidal effects, and preprocessing with different timing.','Demographics constrain delay and fade times better than a unique physical mechanism.','[REV11-P031] [REV11-P044]'),
('REV11-D05','Low-mass SHMR','Steep abundance-matching extrapolation versus broader/scattered dwarf occupation and incomplete luminous samples.','Ultra-faint completeness, reionization, tidal histories, and dynamical mass conversion are uncertain.','[REV11-R00] [REV11-P001] [REV11-P002] [REV11-P022]'),
('REV11-D06','Orphan galaxies','Track galaxies after numerical subhalo loss versus omit them or absorb their effect in HOD profiles.','Disruption and dynamical-friction times depend on resolution and baryonic structure.','[REV11-P007] [REV11-P033] [REV11-P041]'),
('REV11-D07','Baryonic modification of halo statistics','Apply dark-matter-only mass/profile calibrations versus include contraction, expansion, and mass redistribution.','Effects are scale-, mass-, and feedback-model dependent and can rival precision targets.','[REV11-P012] [REV11-P040]'),
('REV11-D08','Halo-mass inference method','Clustering/HOD, abundance, groups, weak lensing, satellite dynamics, X-ray, and SZ constraints have different degeneracies.','Stellar mass, projection, miscentering, mass calibration, selection, and cosmology prevent method-free comparison.','[REV11-P005] [REV11-P006] [REV11-P042] [REV11-P045]'),
]
N=[
('REV11-N01','M_h,pivot ~ 10^12 M_sun','M_sun','Central-galaxy SHMR near z=0; virial or spherical-overdensity halo mass.','Abundance-matching/joint constraints; shifts ~0.1-0.3 dex with mass definitions, IMF, and redshift.','[REV11-R00] [REV11-P001] [REV11-P002] [REV11-P020]'),
('REV11-N02','M*/(f_b M_h) ~ 0.15-0.20 at peak','dimensionless','Integrated central stellar mass efficiency near the pivot at z~0.','Below 20% review bound; not instantaneous baryon conversion.','[REV11-R00] [REV11-P001] [REV11-P002] [REV11-P020]'),
('REV11-N03','sigma_log M*|Mh ~ 0.16-0.20 dex above M_h~10^12.5 M_sun','dex','Intrinsic central stellar-mass scatter, often assumed lognormal.','Joint clustering/lensing/abundance inference; measurement errors and shape assumptions apply.','[REV11-R00] [REV11-P006] [REV11-P018] [REV11-P042]'),
('REV11-N04','M*_central roughly proportional to M_h^(~1/3) at high mass','power-law slope','Group/cluster regime; central stellar mass versus host halo mass.','Approximate synthesis; BCG outskirts, ICL, IMF, and halo-mass calibration alter slope.','[REV11-R00] [REV11-P025]'),
('REV11-N05','<N_sat> = <N_cen> [(M_h-M_0)/M_1]^alpha, alpha ~ 1','galaxies per halo','Standard threshold-sample satellite HOD at masses above cutoff.','Empirical parameterization; exact convention and central prefactor vary.','[REV11-P004] [REV11-P005] [REV11-P007] [REV11-P035]'),
('REV11-N06','P(N_cen=1|M_h) ~ 0.5[1+erf((log M_h-log M_min)/sigma_logM)]','probability','Soft central occupation threshold in standard HOD models.','Width mixes intrinsic galaxy-halo scatter and sample-observable scatter.','[REV11-P003] [REV11-P004] [REV11-P035]'),
('REV11-N07','satellite delay ~2-4 Gyr; rapid e-folding <~0.8 Gyr','Gyr','Local SDSS satellites with M*>5e9 M_sun, using simulated infall histories.','Depends on infall definition, preprocessing, and empirical central-SFR baseline.','[REV11-P044]'),
('REV11-N08','halo mass-function calibration at ~5% level over its tested domain','percent','Spherical-overdensity halos in large N-body suites over calibrated mass/redshift/cosmology ranges.','Not universal across definitions; baryons and extrapolation add systematics.','[REV11-P012] [REV11-P039]'),
]
U=[
('REV11-U01','Direct observational isolation of galaxy assembly bias at fixed halo mass.','Mass-only HOD cosmology and environmental inference can be biased.','Joint clustering and lensing/group mass measurements with controlled secondary-property selections and realistic mocks.','[REV11-P017] [REV11-P030] [REV11-P041]'),
('REV11-U02','SHMR mean and scatter at z>4.','Sets early galaxy efficiency and reionization-era boundary conditions.','Complete rest-optical stellar masses, clustering/lensing or dynamical halo constraints, and forward selection modeling.','[REV11-R00] [REV11-P001] [REV11-P002]'),
('REV11-U03','Low-mass occupation, slope, and scatter below M_h~10^11 M_sun.','Tests feedback, reionization, and small-scale dark-matter predictions.','Volume-complete nearby dwarf census plus resolved kinematics and calibrated satellite/central histories.','[REV11-R00] [REV11-P022]'),
('REV11-U04','Full covariance of stellar mass, color/SFR, size, gas, and morphology at fixed halo properties.','Required for realistic mocks and causal galaxy-evolution tests.','Multi-observable group/lensing/clustering inference with flexible correlated-scatter models.','[REV11-P017] [REV11-P028] [REV11-P043] [REV11-P046]'),
('REV11-U05','Baryonic impact on halo mass functions, profiles, and bias at survey precision.','Dark-matter-only calibrations may not meet future cosmology systematics.','Large-volume hydrodynamic emulators calibrated to gas, lensing, X-ray, and SZ observations.','[REV11-P012] [REV11-P013] [REV11-P040]'),
('REV11-U06','Satellite disruption, orphan survival, and radial/spatial bias.','Controls one-halo clustering and inferred satellite fractions.','Resolution-converged baryonic simulations plus small-scale lensing and satellite phase-space data.','[REV11-P007] [REV11-P033] [REV11-P044]'),
]
L=['# Review Base 11 — Wechsler & Tinker (2018): The Connection Between Galaxies and Their Dark Matter Halos','','Status: READY_FOR_HWAO_REVIEW — canonical advisory packet; raw custody preserved and independently reconciled.','',f"Raw custody SHA-256: `{hashlib.sha256(RAW.read_bytes()).hexdigest()}`",'','## 1. Review Identity and Scope Map','',t(['Field','Value'],[('Review key','[REV11-R00]'),('Authors','Risa H. Wechsler; Jeremy L. Tinker'),('Year / journal','2018, Annual Review of Astronomy and Astrophysics 56, 435-487'),('DOI','10.1146/annurev-astro-081817-051756'),('arXiv','1804.03097'),('ADS','2018ARA&A..56..435W'),('Authorized scope','Statistical galaxy-halo connection: HOD/CLF, abundance matching, SHMR, scatter, centrals/satellites, clustering, lensing, groups, assembly bias, redshift evolution, physical/cosmological use through 2018.'),('Explicit exclusions','Post-2018 work, uncited dark-matter/cosmology spillover, method-independent halo masses, causal quenching from correlations, and unbounded halo/stellar-mass definition mixing.')]),'','## 2. Established Findings','',t(['ID','Epistemic type','Bounded finding','Boundary','Confidence','Sources'],E),'','## 3. Open Debates and Tensions','',t(['ID','Topic','Competing positions','Why unresolved / boundary','Sources'],D),'','## 4. Key Measurements and Model Calibrations','',t(['ID','Value / equation','Units','Definitions and regime','Status / caveat','Sources'],N),'','## 5. What Remained Unknown in 2018','',t(['ID','Gap','Why it matters','Needed test','Sources'],U),'','## 6. Primary-Citation Harvest','']
for s in p:L.append(f"[{s['key']}] {s['authors']} ({s['year']}, {s['journal']}) | title={s['title']} | DOI:{s['doi'] or 'none'}; arXiv:{s['arxiv'] or 'none'}; ADS:{s['ads_bibcode']} | role={s['role']} | review_locator={s['review_locator']} | {s['boundary']} | source_status=PASS_ADS_AND_REVIEW_MEMBERSHIP")
L+=['','### Supporting reviews','']
for s in sr:L.append(f"[{s['key']}] {s['authors']} ({s['year']}, {s['journal']}) | title={s['title']} | DOI:{s['doi'] or 'none'}; arXiv:{s['arxiv'] or 'none'}; ADS:{s['ads_bibcode']} | role=supporting_review | review_locator={s['review_locator']} | {s['boundary']} | source_status=PASS_ADS_AND_REVIEW_MEMBERSHIP")
L+=['','## 7. DO_NOT_USE_UNVERIFIED','']
for s in q:L.append(f"UNCITED_NOT_USABLE | [{s['key']}] {s['title']} | DOI:{s['doi'] or 'none'}; arXiv:{s['arxiv'] or 'none'}; ADS:{s['ads_bibcode'] or 'none'} | {s['quarantine_reason']}")
L+=['UNCITED_NOT_USABLE | HOD, SHAM, abundance matching, weak lensing, or group catalogs recover method-independent halo truth | none | each is conditional on definitions, selection, and model assumptions.','UNCITED_NOT_USABLE | halo mass, peak mass, infall mass, and present subhalo mass are interchangeable | none | physically distinct quantities.','UNCITED_NOT_USABLE | galaxy-halo correlation proves a unique causal quenching mechanism | none | causal overreach.','UNCITED_NOT_USABLE | integrated M*/(f_b M_h) is instantaneous star-formation efficiency | none | distinct definitions.','UNCITED_NOT_USABLE | post-2018 browsing results | none | outside temporal boundary.','','## 8. Review and Source Identity Ledger','','[REV11-R00] Wechsler RH; Tinker JL (2018, Annual Review of Astronomy and Astrophysics) | title=The Connection Between Galaxies and Their Dark Matter Halos | DOI:10.1146/annurev-astro-081817-051756; arXiv:1804.03097; ADS:2018ARA&A..56..435W | role=review_synthesis | source_status=PASS_ADS_CROSSREF_ARXIV','']
for s in p+sr:L.append(f"[{s['key']}] {s['authors']} ({s['year']}, {s['journal']}) | title={s['title']} | DOI:{s['doi'] or 'none'}; arXiv:{s['arxiv'] or 'none'}; ADS:{s['ads_bibcode']} | role={s['role']} | boundary={s['boundary']} | source_status=PASS_ADS_AND_REVIEW_MEMBERSHIP")
L+=['','REVIEW_BASE_11_DR_COMPLETE_REFERENCE_ONLY',''];OUT.write_text('\n'.join(L));print(json.dumps({'packet':str(OUT),'primary':len(p),'supporting':len(sr),'quarantined':len(q),'sha256':hashlib.sha256(OUT.read_bytes()).hexdigest()},sort_keys=True))
