import hashlib,json
from pathlib import Path
A=Path('/Users/duhokim/NebulaMind/NebulaMind/.hermes/handoffs/galaxy-evolution/wiki-expansion-20260715');RAW=A/'area_review_13_mckee_ostriker_2007_DR_RAW_PACKET.md';REG=A/'area_review_13_mckee_ostriker_2007_CURATED_SOURCE_REGISTRY.json';OUT=A/'area_review_13_mckee_ostriker_2007_DR_PACKET.md';r=json.loads(REG.read_text());p=[x for x in r['sources'] if x['source_status']=='PASS' and x['role']!='supporting_review'];sr=[x for x in r['sources'] if x['source_status']=='PASS' and x['role']=='supporting_review'];q=[x for x in r['sources'] if x['source_status']!='PASS'];assert(len(p),len(sr),len(q))==(40,5,13)
def t(h,rows):
 e=lambda v:str(v).replace('|','\\|').replace('\n',' ')
 return '\n'.join(['| '+' | '.join(h)+' |','|'+'|'.join(['---']*len(h))+'|']+['| '+' | '.join(e(v) for v in z)+' |' for z in rows])
E=[
('REV13-E01','review synthesis','Supersonic turbulence both creates dense fluctuations that can collapse and supplies nonthermal support against global collapse.','Isothermal/turbulent cloud models and molecular-cloud linewidths; outcome depends on driving, Mach number, magnetization, gravity, and scale.','High qualitatively.','[REV13-R00] [REV13-P002] [REV13-P009] [REV13-P010] [REV13-P043]'),
('REV13-E02','simulation','Undriven supersonic hydrodynamic and MHD turbulence loses energy on roughly a flow-crossing time, even with strong magnetic fields.','Periodic isothermal boxes; decay time is not directly a GMC lifetime and does not identify the driver.','High for model class.','[REV13-P044] [REV13-P045] [REV13-P042]'),
('REV13-E03','observation','Molecular-cloud linewidth, size, and luminosity relations indicate supersonic internal motions and structured, approximately self-gravitating cloud populations.','CO-selected Galactic GMCs; distance, optical depth, X_CO, cloud segmentation, and virial geometry apply.','High for sample correlations.','[REV13-P013] [REV13-P018]'),
('REV13-E04','observation/analytic theory','Magnetic fields are dynamically important in many molecular clouds, while measured mass-to-flux ratios often lie near or somewhat above critical.','Zeeman line-of-sight fields, projection, nondetections, tracer density, and assumed geometry dominate inference.','Moderate.','[REV13-P021] [REV13-P022] [REV13-P040] [REV13-P046]'),
('REV13-E05','analytic theory/simulation','Magnetic subcriticality can delay collapse through flux loss, but supercritical turbulent regions can collapse locally despite magnetic support.','Ionization, grain chemistry, geometry, turbulence, and boundary conditions control ambipolar-diffusion and collapse times.','High in bounded regimes; contested population prevalence.','[REV13-P011] [REV13-P021] [REV13-P022] [REV13-P043] [REV13-P049]'),
('REV13-E06','observation/calibration','Star formation converts gas slowly on galactic and GMC-average dynamical times compared with unregulated global free fall.','SFR tracer lifetime, molecular conversion, cloud definition, evolutionary stage, and averaging scale differ.','High.','[REV13-P003] [REV13-P009] [REV13-P030] [REV13-P034]'),
('REV13-E07','analytic theory','Turbulence-regulated models predict low star-formation efficiency per free-fall time from the fraction of a density PDF above a collapse threshold.','Isothermal lognormal PDF, virial parameter, Mach number, forcing, magnetic field, and multi-free-fall convention apply.','Moderate in 2007.','[REV13-P009] [REV13-P033]'),
('REV13-E08','measurement/calibration','The stellar IMF has a Salpeter-like high-mass tail and turns over or flattens below roughly a solar mass.','Unresolved binaries, age, tracks, extinction, cluster dynamics, and functional form affect normalization/turnover.','High for Milky-Way populations.','[REV13-P004] [REV13-P005] [REV13-P006] [REV13-P024]'),
('REV13-E09','observation','Dense-core mass distributions resemble the IMF in shape but are shifted to higher mass, consistent with incomplete core-to-star conversion.','Dust opacity/temperature, completeness, boundedness, multiplicity, lifetime, and core definition prevent one-to-one mapping.','Moderate.','[REV13-P007] [REV13-P026] [REV13-P027] [REV13-P051]'),
('REV13-E10','simulation/analytic theory','Thermal physics, turbulent fragmentation, accretion, and dynamics can each produce IMF-like mass spectra under specific assumptions.','No 2007 model uniquely reproduced universality, binaries, and all environments.','Moderate.','[REV13-P015] [REV13-P041] [REV13-P047] [REV13-P048]'),
('REV13-E11','observation/review synthesis','Most stars form in groups or clusters embedded in molecular clouds, so interactions and a shared gas reservoir may affect outcomes.','Cluster membership and embedded-lifetime completeness; does not imply competitive accretion dominates every region.','High for clustered occurrence.','[REV13-P008] [REV13-P015]'),
('REV13-E12','analytic theory','Low-mass protostellar accretion, disks, winds, and outflows jointly solve mass, angular-momentum, and efficiency constraints.','Idealized collapse/accretion histories and MHD wind coupling; episodicity and nonideal disk physics remain.','High for necessity; model-dependent rates.','[REV13-P038] [REV13-P039] [REV13-P051]'),
('REV13-E13','analytic theory/simulation','Massive stars can grow by accretion despite radiation pressure when geometry, disks, cavities, or multidimensional instabilities redirect radiation and flow.','High-pressure cores/cluster environments; opacity, luminosity, resolution, and feedback treatment apply.','Moderate-to-high by 2007.','[REV13-P016] [REV13-P020] [REV13-P023] [REV13-P050]'),
('REV13-E14','review synthesis','Low-mass isolated-core, clustered, and massive-star formation are related but not safely represented by one scale-free pathway.','Core, clump, GMC, cluster, and galactic regimes require separate density, time, and efficiency definitions.','High.','[REV13-R00] [REV13-P001] [REV13-P012] [REV13-P016] [REV13-P017]'),
]
D=[
('REV13-D01','Cloud lifetimes','Long-lived magnetically regulated clouds versus rapid assembly and star formation in one or a few crossing times.','Age statistics, cloud definition, molecular tracer onset, destruction, and selection permit competing interpretations.','[REV13-P014] [REV13-P049]'),
('REV13-D02','Primary regulator','Strong-field ambipolar-diffusion control versus turbulence-regulated local collapse in supercritical clouds.','Zeeman projection and simulation initial conditions do not uniquely establish population-wide dominance.','[REV13-P010] [REV13-P011] [REV13-P043] [REV13-P046] [REV13-P049]'),
('REV13-D03','Turbulence driving','Feedback, galactic shear/gravity, accretion, or inherited cloud-assembly motions maintain observed linewidths.','Decay is demonstrated, but energy injection scale, coupling efficiency, and cloud boundaries remained uncertain.','[REV13-P042] [REV13-P044] [REV13-P045]'),
('REV13-D04','Virial interpretation','Observed virial parameters indicate quasi-equilibrium versus transient, pressure-confined, collapsing, or selection-biased structures.','Mass, radius, geometry, surface pressure, magnetic energy, and tracer definitions are uncertain.','[REV13-P013] [REV13-P018] [REV13-P046]'),
('REV13-D05','IMF characteristic mass','Thermal Jeans transition, turbulent fragmentation, accretion/dynamics, or outflow-regulated efficiency sets the IMF peak.','Multiple models produce similar spectra with environment-dependent hidden parameters.','[REV13-P015] [REV13-P041] [REV13-P047] [REV13-P048] [REV13-P051]'),
('REV13-D06','CMF-to-IMF mapping','A shifted core mass function directly seeds the IMF versus cores fragment, merge, accrete, and form multiples.','Core catalogs are tracer- and resolution-dependent; boundedness and lifetimes are uncertain.','[REV13-P007] [REV13-P026] [REV13-P027] [REV13-P047]'),
('REV13-D07','Massive-star pathway','Monolithic turbulent-core accretion versus competitive accretion/cluster-mediated growth.','Both require dense clustered conditions and differ in initial bounded cores, reservoir ownership, and dynamics.','[REV13-P016] [REV13-P017] [REV13-P023] [REV13-P050]'),
('REV13-D08','Radiation barrier','Spherical radiation pressure halts growth versus multidimensional accretion bypasses it.','Dust opacity, cavities, disks, instability resolution, and additional ionizing/outflow feedback set results.','[REV13-P012] [REV13-P020] [REV13-P023]'),
('REV13-D09','Universal star-formation law','One turbulence/free-fall law across clouds and galaxies versus distinct molecular, orbital, threshold, and environment regimes.','Tracer averaging, conversion factors, density PDFs, and timescale definitions differ across many orders of magnitude.','[REV13-P003] [REV13-P009] [REV13-P030] [REV13-P034]'),
]
N=[
('REV13-N01','t_ff = sqrt(3 pi / (32 G rho))','time','Uniform-density free-fall time using volume mass density rho.','Geometry and density choice matter; not a measured lifetime.','[REV13-R00]'),
('REV13-N02','t_cross = L / sigma','time','Flow crossing time for adopted scale L and one-dimensional velocity dispersion sigma.','Radius/diameter and 1D/3D conventions must be stated.','[REV13-P014] [REV13-P044] [REV13-P045]'),
('REV13-N03','alpha_vir = 5 sigma^2 R / (G M)','dimensionless','Virial parameter for a uniform, nonmagnetic sphere using 1D sigma.','Density profile, surface pressure, magnetic field, rotation, and geometry change coefficient/meaning.','[REV13-R00] [REV13-P013]'),
('REV13-N04','(M/Phi)_crit approximately 1 / (2 pi sqrt(G))','mass per magnetic flux','Critical value for an idealized magnetized sheet; normalized lambda=(M/Phi)/(M/Phi)_crit.','Geometry changes coefficient; Zeeman projection and flux assignment dominate observations.','[REV13-P022] [REV13-P046]'),
('REV13-N05','lambda_J = c_s sqrt(pi/(G rho)); M_J proportional to c_s^3 rho^-1/2 G^-3/2','length; mass','Thermal Jeans instability for uniform isothermal gas.','Numerical coefficient depends on Jeans-mass convention; turbulence/magnetic fields are not included.','[REV13-R00] [REV13-P048]'),
('REV13-N06','sigma_v approximately 0.72 (R/pc)^0.5 km s^-1','km s^-1','Representative Galactic CO GMC linewidth-size fit.','Cloud segmentation, distance, tracer opacity, environment, and fit form apply; not universal.','[REV13-P013]'),
('REV13-N07','Sigma_SFR approximately 2.5e-4 (Sigma_gas / (1 M_sun pc^-2))^1.4 M_sun yr^-1 kpc^-2','surface SFR','Disk-averaged global Schmidt-law calibration spanning normal disks and starbursts.','IMF/SFR calibration, X_CO, area averaging, and threshold/sample definitions apply.','[REV13-P003]'),
('REV13-N08','epsilon_ff approximately 0.01 (order of magnitude for virialized supersonic clouds)','dimensionless per free-fall time','Turbulence-regulated analytic model integrates a lognormal density PDF above a collapse threshold.','Depends on alpha_vir, Mach number, forcing, magnetic field, and free-fall weighting.','[REV13-P009]'),
('REV13-N09','dN/dlog m proportional to m^-1.35 at high mass','number per logarithmic mass','Salpeter high-mass IMF slope.','Original luminosity/evolution inference and mass range apply; equivalent dN/dm slope is -2.35.','[REV13-P004]'),
('REV13-N10','core-to-star efficiency roughly 0.3; individual low-mass core model range 0.25-0.70','dimensionless','CMF-to-IMF offset and outflow-regulated analytic core efficiencies.','Core definition, multiplicity, geometry, wind collimation, and massive-star feedback bound transfer.','[REV13-P007] [REV13-P051]'),
]
U=[
('REV13-U01','Origin and maintenance scale of molecular-cloud turbulence.','Sets cloud lifetime, density statistics, and collapse fraction.','Resolved multi-phase galactic simulations plus cloud kinematics and energy-source accounting.','[REV13-P042] [REV13-P044] [REV13-P045]'),
('REV13-U02','Population distribution of three-dimensional magnetic criticality and its evolution from cloud to core.','Discriminates strong-field regulation from turbulent supercritical collapse.','Large multi-tracer Zeeman/polarization samples with geometry and density tomography.','[REV13-P043] [REV13-P046] [REV13-P049]'),
('REV13-U03','True cloud assembly, star-forming, and dispersal lifetimes.','Determines whether clouds evolve over one crossing time or many.','Time-resolved population sequences in the Milky Way and resolved external galaxies with consistent cloud definitions.','[REV13-P014] [REV13-P049]'),
('REV13-U04','Physical origin and environmental invariance of the IMF peak, slope, and multiplicity.','Links thermal/turbulent cloud physics to stellar populations across galaxies.','Complete resolved IMFs and CMFs across metallicity/pressure plus radiation-MHD simulations resolving binaries.','[REV13-P005] [REV13-P006] [REV13-P041] [REV13-P048]'),
('REV13-U05','Whether dense cores map causally to stars and systems.','Controls interpretation of the CMF resemblance and efficiency.','Kinematic boundedness, lifetime tracking, fragmentation, accretion, and multiplicity from core to finished systems.','[REV13-P007] [REV13-P026] [REV13-P027] [REV13-P047]'),
('REV13-U06','Dominant route to the most massive stars under full feedback.','Sets upper-mass growth, cluster dynamics, and ionizing feedback.','Three-dimensional radiation-MHD including ionization, outflows, disks, and cluster-scale reservoirs with matched observations.','[REV13-P016] [REV13-P017] [REV13-P020] [REV13-P050]'),
('REV13-U07','A scale-consistent star-formation law from dense cores through galaxies.','Required to connect local efficiencies to cosmic galaxy evolution without definition transfer.','Matched gas-density PDFs, tracer timescales, SFR histories, and simulations across core/GMC/disk scales.','[REV13-P003] [REV13-P009] [REV13-P030] [REV13-P034]'),
]
L=['# Review Base 13 — McKee & Ostriker (2007): Theory of Star Formation','','Status: READY_FOR_HWAO_REVIEW — canonical advisory packet; raw custody preserved and independently reconciled.','',f"Raw custody SHA-256: `{hashlib.sha256(RAW.read_bytes()).hexdigest()}`",'','## 1. Review Identity and Scope Map','',t(['Field','Value'],[('Review key','[REV13-R00]'),('Authors','Christopher F. McKee; Eve C. Ostriker'),('Year / journal','2007, Annual Review of Astronomy and Astrophysics 45, 565-687'),('DOI','10.1146/annurev.astro.45.051806.110602'),('arXiv','0707.3514'),('ADS','2007ARA&A..45..565M'),('Authorized scope','Star formation from galactic disks and GMCs through clumps, cores, protostars, disks, winds, and low-/high-mass pathways; turbulence, fields, self-gravity, SFR, and IMF.'),('Explicit exclusions','Post-2007 work, uncited browsing spillover, transferring efficiencies/times across scales, virial-equals-equilibrium claims, universal CMF-to-IMF mapping, and simulation results without setup boundaries.')]),'','## 2. Established Findings','',t(['ID','Epistemic type','Bounded finding','Scale / boundary','Confidence','Sources'],E),'','## 3. Open Debates and Tensions','',t(['ID','Topic','Competing positions','Why unresolved / boundary','Sources'],D),'','## 4. Key Measurements and Model Calibrations','',t(['ID','Value / equation','Units','Definitions and regime','Status / caveat','Sources'],N),'','## 5. What Remained Unknown in 2007','',t(['ID','Gap','Why it matters','Needed test','Sources'],U),'','## 6. Primary-Citation Harvest','']
for s in p:L.append(f"[{s['key']}] {s['authors']} ({s['year']}, {s['journal']}) | title={s['title']} | DOI:{s['doi'] or 'none'}; arXiv:{s['arxiv'] or 'none'}; ADS:{s['ads_bibcode']} | role={s['role']} | review_locator={s['review_locator']} | {s['boundary']} | source_status=PASS_ADS_AND_REVIEW_MEMBERSHIP")
L+=['','### Supporting reviews','']
for s in sr:L.append(f"[{s['key']}] {s['authors']} ({s['year']}, {s['journal']}) | title={s['title']} | DOI:{s['doi'] or 'none'}; arXiv:{s['arxiv'] or 'none'}; ADS:{s['ads_bibcode']} | role=supporting_review | review_locator={s['review_locator']} | {s['boundary']} | source_status=PASS_ADS_AND_REVIEW_MEMBERSHIP")
L+=['','## 7. DO_NOT_USE_UNVERIFIED','']
for s in q:L.append(f"UNCITED_NOT_USABLE | [{s['key']}] {s['title']} | DOI:{s['doi'] or 'none'}; arXiv:{s['arxiv'] or 'none'}; ADS:{s['ads_bibcode'] or 'none'} | {s['quarantine_reason']}")
L+=['UNCITED_NOT_USABLE | virial parameter means equilibrium | none | virial balance is not a lifetime or equilibrium measurement.','UNCITED_NOT_USABLE | one efficiency or free-fall time transfers among galaxies, GMCs, clumps, cores, and protostars | none | scale-definition mismatch.','UNCITED_NOT_USABLE | CMF maps one-to-one onto the single-star IMF | none | fragmentation, multiplicity, accretion, lifetime, and completeness intervene.','UNCITED_NOT_USABLE | turbulence, magnetic fields, or one massive-star pathway is universally dominant | none | unresolved model-selection claim.','UNCITED_NOT_USABLE | post-2007 browsing results | none | outside temporal boundary.','','## 8. Composite Source Identity Ledger','','[REV13-R00] McKee CF; Ostriker EC (2007, Annual Review of Astronomy and Astrophysics) | title=Theory of Star Formation | DOI:10.1146/annurev.astro.45.051806.110602; arXiv:0707.3514; ADS:2007ARA&A..45..565M | role=review_synthesis | source_status=PASS_ADS_CROSSREF_ARXIV','']
for s in p+sr:L.append(f"[{s['key']}] {s['authors']} ({s['year']}, {s['journal']}) | title={s['title']} | DOI:{s['doi'] or 'none'}; arXiv:{s['arxiv'] or 'none'}; ADS:{s['ads_bibcode']} | role={s['role']} | boundary={s['boundary']} | source_status=PASS_ADS_AND_REVIEW_MEMBERSHIP")
L+=['','REVIEW_BASE_13_DR_COMPLETE_REFERENCE_ONLY',''];OUT.write_text('\n'.join(L));print(json.dumps({'packet':str(OUT),'primary':len(p),'supporting':len(sr),'quarantined':len(q),'sha256':hashlib.sha256(OUT.read_bytes()).hexdigest()},sort_keys=True))
