import json,re
from pathlib import Path
A=Path('/Users/duhokim/NebulaMind/NebulaMind/.hermes/handoffs/galaxy-evolution/wiki-expansion-20260715');I=A/'scratch/review_base12_ads_identities.json';O=A/'area_review_12_blanton_moustakas_2009_CURATED_SOURCE_REGISTRY.json';rows=json.loads(I.read_text())['sources'];ov={
'P014':('calibration','quantitative morphology','Supervised artificial-neural-network galaxy typing in SDSS; not interchangeable with visual Hubble types.'),
'P015':('measurement','groups and low-density environments','SDSS/2dFGRS group and low-density population trends; environment metric and survey selection apply.'),
'P016':('measurement','post-starburst/H-delta-strong galaxies','Near-IR properties of SDSS H-delta-strong galaxies; not a general Halpha-environment calibration.'),
'P020':('measurement','disk mass models and velocity fields','Two-dimensional spiral-galaxy velocity maps constrain baryonic/dark mass models; not a bar pattern-speed measurement.'),
'P022':('measurement','interaction-triggered star formation','Close-pair comparison designed to isolate triggered star formation; does not alone set the global pair fraction.'),
'P025':('measurement','gas-rich low-mass galaxies','Baryonic Tully-Fisher relation for extremely low-mass gas-rich galaxies; not a full atomic-gas mass function.'),
'P032':('simulation','bar evolution under tidal encounters','Numerical fly-by encounters can regenerate stellar bars; does not calibrate nuclear-ring occurrence.'),
'P034':('measurement','brightest cluster galaxies','BCG luminosities, sizes, and dispersions compared with ordinary early types; photometry and selection apply.'),
'P035':('measurement','early-type galaxy evolution and environment','Early-type population evolution/environment study; not specifically a local BCG scaling calibration.'),
'P040':('analytic_theory','elliptical rotation and anisotropy','Revisits rotation versus anisotropy support in galaxies; not a Solar-cylinder kinematic data set.'),
'P045':('measurement','scales of galaxy environment','Tests which measured environmental scales correlate with galaxy properties; correlation does not prove a unique driver.'),
}
sources=[];corrected=[]
for x in rows:
 a=x['ads_direct'];assert a['status']=='PASS';role=x['role'];loc=x['review_locator'];bd=x['boundary'];
 if x['key'] in ov:role,loc,bd=ov[x['key']]
 z={'key':'REV12-'+x['key'],'authors':'; '.join(a['authors']),'year':int(a['bibcode'][:4]),'journal':a['publication'],'title':a['title'],'doi':a['doi'],'arxiv':a['arxiv'],'ads_bibcode':a['bibcode'],'role':role,'review_locator':loc,'boundary':bd,'source_status':'PASS','identity_verification':{'status':'PASS_ADS_DIRECT','ads_url':a['url'],'review_membership':'PASS_AR5IV_AUTHOR_YEAR_JOURNAL_PAGE'}};sources.append(z)
 n=lambda v:re.sub(r'[^a-z0-9]','',(v or '').casefold());diff=[f for f,rv,av in [('title',x.get('raw_title'),a['title']),('doi',x.get('raw_doi'),a['doi']),('arxiv',x.get('raw_arxiv'),a['arxiv']),('bibcode',x.get('bibcode'),a['bibcode'])] if n(rv)!=n(av)]
 if diff:corrected.append({'key':'REV12-'+x['key'],'fields':diff})
sources.append({'key':'REV12-P052','authors':'Zwaan, M. A.; Meyer, M. J.; Staveley-Smith, L.; Webster, R. L.','year':2005,'journal':'Monthly Notices of the Royal Astronomical Society','title':'The HIPASS catalogue: ΩHI and environmental effects on the HI mass function of galaxies','doi':'10.1111/j.1745-3933.2005.00029.x','arxiv':'astro-ph/0502257','ads_bibcode':'2005MNRAS.359L..30Z','role':'measurement','review_locator':'atomic-gas mass function','boundary':'HIPASS blind 21-cm sample; h conventions, completeness, sky coverage, and environment estimator apply.','source_status':'PASS','identity_verification':{'status':'PASS_ADS_DIRECT','ads_url':'https://ui.adsabs.harvard.edu/abs/2005MNRAS.359L..30Z/abstract','review_membership':'PASS_AR5IV_AUTHOR_YEAR_JOURNAL_PAGE'}})
qs=[('P046',"Abdurro'uf et al. 2022 MaNGA DR17",2022,None,'POST_2009_UNCITED_NOT_USABLE'),('P047','Emsellem et al. 2011 ATLAS3D',2011,None,'POST_2009_UNCITED_NOT_USABLE'),('P048','Jones et al. 2018 ALFALFA final HIMF',2018,None,'POST_2009_UNCITED_NOT_USABLE'),('P049','Bouche et al. 2010 baryon-cycle model',2010,None,'POST_2009_UNCITED_NOT_USABLE'),('P050','Chowdhury et al. 2024 HI stacking',2024,None,'POST_2009_UNCITED_NOT_USABLE'),('P051','Ponomareva et al. 2023 high-z HIMF',2023,None,'POST_2009_UNCITED_NOT_USABLE')]
for key,title,year,ar,reason in qs:sources.append({'key':'REV12-'+key,'authors':'unverified browsing candidate','year':year,'journal':None,'title':title,'doi':None,'arxiv':ar,'ads_bibcode':None,'role':'quarantined_candidate','review_locator':'raw browsing spillover','boundary':'not usable','source_status':'QUARANTINED','identity_verification':{'status':'QUARANTINED','review_membership':'FAIL_OUTSIDE_2009_REVIEW_SOURCE_BASE'},'quarantine_reason':reason})
primary=[s for s in sources if s['source_status']=='PASS' and s['role']!='supporting_review'];support=[s for s in sources if s['source_status']=='PASS' and s['role']=='supporting_review'];q=[s for s in sources if s['source_status']!='PASS'];assert(len(primary),len(support),len(q))==(44,2,6);assert all(s['year']<=2009 for s in primary+support)
r={'status':'PASS_WITH_RAW_IDENTITIES_CORRECTED','mission_id':'GALAXY_REVIEW_BASE_DR_20260715','queue_item':12,'review':{'key':'REV12-R00','authors':'Blanton MR; Moustakas J','year':2009,'title':'Physical Properties and Environments of Nearby Galaxies','journal':'Annual Review of Astronomy and Astrophysics','doi':'10.1146/annurev-astro-082708-101734','arxiv':'0908.3017','ads_bibcode':'2009ARA&A..47..159B','identity_status':'PASS_ADS_CROSSREF_ARXIV'},'review_bibliography_basis':{'source':'https://ar5iv.labs.arxiv.org/html/0908.3017','status':'PASS_COMPLETE_REVIEW_TEXT_AND_REFERENCE_LIST_WEB_ONLY','ads_verification':'PASS_DIRECT_FULL_PAGES_FOR_46_USABLE_ROWS','local_raw_source_extraction_used':False},'raw_response_reconciliation':{'raw_source_rows':45,'raw_rows_not_found_in_review':0,'raw_identity_tuples_corrected':len(corrected),'supplemented_review_cited_primary_rows':1,'raw_packet_preserved':True,'corrections':corrected},'counts':{'raw_source_rows':45,'total_registry_rows':52,'usable_primary_sources':44,'usable_supporting_reviews':2,'quarantined_sources':6,'usable_sources_verified_by_ads':46},'sources':sources};O.write_text(json.dumps(r,indent=2,ensure_ascii=False)+'\n');print(json.dumps({'counts':r['counts'],'corrected':len(corrected)},sort_keys=True))
