import json,re
from pathlib import Path
A=Path('/Users/duhokim/NebulaMind/NebulaMind/.hermes/handoffs/galaxy-evolution/wiki-expansion-20260715');D=json.loads((A/'scratch/review_base14_ads_identities.json').read_text())['sources'];O=A/'area_review_14_kewley_nicholls_sutherland_2019_CURATED_SOURCE_REGISTRY.json';qraw={'P001':'NO_COMPOSITE_IDENTITY_SUBMITTED_2019','P023':'RAW_ROW_NOT_IN_REVIEW_BIBLIOGRAPHY','P024':'RAW_ROW_NOT_IN_REVIEW_BIBLIOGRAPHY','P025':'RAW_ROW_NOT_IN_REVIEW_BIBLIOGRAPHY','P030':'RAW_ROW_NOT_IN_REVIEW_BIBLIOGRAPHY','P037':'RAW_ROW_NOT_IN_REVIEW_BIBLIOGRAPHY','P039':'RAW_ROW_NOT_IN_REVIEW_BIBLIOGRAPHY'}
manual={'P006':{'title':'Physics of Thermal Gaseous Nebulae','authors':['Aller, Lawrence H.'],'publication':'Book','doi':None,'arxiv':None,'bibcode':'1984ptgn.book.....A','url':'https://ui.adsabs.harvard.edu/abs/1984ptgn.book.....A/abstract'}}
roles={'Measurements':'measurement','Shock simulations':'simulation','Photoionization simulations':'simulation','Model grids':'simulation','Analytic/calibration':'calibration','Analytic/atomic':'calibration','Supporting reviews':'supporting_review'}
sources=[];corrected=[]
for x in D:
 key=x['key'];a=manual.get(key,x['ads_direct'])
 if key in qraw:
  sources.append({'key':'REV14-'+key,'authors':x['raw_citation'],'year':int(re.search(r'\b(\d{4})\b',x['raw_citation']).group(1)),'journal':None,'title':x['raw_citation'],'doi':x['raw_doi'],'arxiv':x['raw_arxiv'],'ads_bibcode':x['bibcode'],'role':'quarantined_candidate','review_locator':'raw source harvest','boundary':'not usable','source_status':'QUARANTINED','identity_verification':{'status':'QUARANTINED','review_membership':'FAIL_COMPOSITE_IDENTITY_OR_AR5IV_BIBLIOGRAPHY'},'quarantine_reason':qraw[key]});continue
 assert a.get('title') and a.get('bibcode'),key;role='supporting_review' if key=='P006' else roles[x['raw_role']]
 sources.append({'key':'REV14-'+key,'authors':'; '.join(a['authors']),'year':int(a['bibcode'][:4]),'journal':a['publication'],'title':a['title'],'doi':a.get('doi'),'arxiv':a.get('arxiv'),'ads_bibcode':a['bibcode'],'role':role,'review_locator':'emission-line '+x['raw_role'].casefold(),'boundary':x['boundary'],'source_status':'PASS','identity_verification':{'status':'PASS_ADS_DIRECT_OR_ADS_BOOK_COMPOSITE','ads_url':a['url'],'review_membership':'PASS_AR5IV_AUTHOR_YEAR_JOURNAL_PAGE'}})
 n=lambda v:re.sub(r'[^a-z0-9]','',(v or '').casefold());diff=[f for f,rv,av in [('doi',x.get('raw_doi'),a.get('doi')),('arxiv',x.get('raw_arxiv'),a.get('arxiv')),('bibcode',x.get('bibcode'),a['bibcode'])] if n(rv)!=n(av)]
 if diff:corrected.append({'key':'REV14-'+key,'fields':diff})
extra=[
('P046',['Kewley, Lisa J.','Groves, Brent','Kauffmann, Guinevere','Heckman, Tim'],2006,'Monthly Notices of the Royal Astronomical Society','The host galaxies and classification of active galactic nuclei','10.1111/j.1365-2966.2006.10859.x','astro-ph/0605681','2006MNRAS.372..961K','calibration','optical excitation classification','Empirical SDSS Seyfert/LINER separation and host correlations; aperture, line-S/N, and low-ionization source mixing apply.'),
('P047',['Steidel, Charles C.','Rudie, Gwen C.','Strom, Allison L.','Pettini, Max','Reddy, Naveen A.','Shapley, Alice E.','Trainor, Ryan F.','Erb, Dawn K.'],2014,'The Astrophysical Journal','Strong Nebular Line Ratios in the Spectra of z ~ 2-3 Star Forming Galaxies: First Results from KBSS-MOSFIRE','10.1088/0004-637X/795/2/165','1405.5473','2014ApJ...795..165S','measurement','high-redshift diagnostic sequences','KBSS-MOSFIRE z~2.3 selection; photoionization interpretation is model-dependent and local BPT boundaries do not transfer unchanged.'),
('P048',['Curti, M.','Cresci, G.','Mannucci, F.','Marconi, A.','Maiolino, R.','Esposito, S.'],2017,'Monthly Notices of the Royal Astronomical Society','New fully empirical calibrations of strong-line metallicity indicators in star-forming galaxies','10.1093/mnras/stw2766','1610.06939','2017MNRAS.465.1384C','calibration','empirical strong-line metallicity','SDSS stacks on a consistent Te scale; stacking, DIG, calibration range, and auroral-line selection apply.'),
('P049',['Zhang, Kai','Yan, Renbin','Bundy, Kevin','Bershady, Matthew','Haffner, L. Matthew','Walterbos, René','Maiolino, Roberto'],2017,'Monthly Notices of the Royal Astronomical Society','SDSS-IV MaNGA: the impact of diffuse ionized gas on emission-line ratios, interpretation of diagnostic diagrams and gas metallicity measurements','10.1093/mnras/stw3308','1612.02000','2017MNRAS.466.3217Z','measurement','diffuse ionized gas contamination','MaNGA low-Sigma_Halpha spaxels; DIG source mixture and strong-line biases are diagnostic- and resolution-dependent.')]
for key,au,yr,j,t,doi,ar,bib,role,loc,bd in extra:sources.append({'key':'REV14-'+key,'authors':'; '.join(au),'year':yr,'journal':j,'title':t,'doi':doi,'arxiv':ar,'ads_bibcode':bib,'role':role,'review_locator':loc,'boundary':bd,'source_status':'PASS','identity_verification':{'status':'PASS_ADS_DIRECT','ads_url':'https://ui.adsabs.harvard.edu/abs/'+bib.replace('&','%26')+'/abstract','review_membership':'PASS_AR5IV_AUTHOR_YEAR_JOURNAL_PAGE'}})
spill=[('P050','Curti et al. 2020/2023',2023),('P051','Katz et al. 2023 JWST',2023),('P052','Arellano-Cordova et al. 2022',2022),('P053','Mendez-Delgado et al. 2022',2022),('P054','Cameron et al. 2021',2021),('P055','unspecified JWST/CEERS/NIRSpec result',2024)]
for key,title,year in spill:sources.append({'key':'REV14-'+key,'authors':'unverified browsing candidate','year':year,'journal':None,'title':title,'doi':None,'arxiv':None,'ads_bibcode':None,'role':'quarantined_candidate','review_locator':'raw browsing spillover','boundary':'not usable','source_status':'QUARANTINED','identity_verification':{'status':'QUARANTINED','review_membership':'FAIL_POST_2019_OR_OUTSIDE_REVIEW'},'quarantine_reason':'POST_2019_UNCITED_NOT_USABLE'})
primary=[s for s in sources if s['source_status']=='PASS' and s['role']!='supporting_review'];support=[s for s in sources if s['source_status']=='PASS' and s['role']=='supporting_review'];q=[s for s in sources if s['source_status']!='PASS'];assert(len(primary),len(support),len(q))==(40,2,13),(len(primary),len(support),len(q));assert all(s['year']<=2019 for s in primary+support)
r={'status':'PASS_WITH_RAW_IDENTITIES_AND_MEMBERSHIP_CORRECTED','mission_id':'GALAXY_REVIEW_BASE_DR_20260715','queue_item':14,'review':{'key':'REV14-R00','authors':'Kewley LJ; Nicholls DC; Sutherland RS','year':2019,'title':'Understanding Galaxy Evolution Through Emission Lines','journal':'Annual Review of Astronomy and Astrophysics','doi':'10.1146/annurev-astro-081817-051832','arxiv':'1910.09730','ads_bibcode':'2019ARA&A..57..511K','identity_status':'PASS_ADS_CROSSREF_ARXIV'},'review_bibliography_basis':{'source':'https://ar5iv.labs.arxiv.org/html/1910.09730','status':'PASS_COMPLETE_REVIEW_TEXT_AND_442_ENTRY_REFERENCE_LIST_WEB_ONLY','ads_verification':'PASS_DIRECT_OR_COMPOSITE_FOR_42_USABLE_ROWS','local_raw_source_extraction_used':False},'raw_response_reconciliation':{'raw_source_rows':45,'raw_rows_not_found_or_not_identifiable':7,'raw_identifier_tuples_corrected':len(corrected),'supplemented_review_cited_primary_rows':4,'raw_packet_preserved':True,'corrections':corrected},'counts':{'raw_source_rows':45,'total_registry_rows':55,'usable_primary_sources':40,'usable_supporting_reviews':2,'quarantined_sources':13,'usable_sources_verified_by_ads':42},'sources':sources};O.write_text(json.dumps(r,indent=2,ensure_ascii=False)+'\n');print(json.dumps({'counts':r['counts'],'corrected':len(corrected)},sort_keys=True))
