import json
from pathlib import Path
A=Path("/Users/duhokim/NebulaMind/NebulaMind/.hermes/handoffs/galaxy-evolution/wiki-expansion-20260715");I=A/'scratch/review_base10_ads_identities.json';O=A/'area_review_10_conroy_2013_CURATED_SOURCE_REGISTRY.json';rows=json.loads(I.read_text())['sources'];sources=[]
for x in rows:
 a=x['ads_direct'];assert a['status']=='PASS',x['key'];year=int(a['bibcode'][:4]);authors='; '.join(a['authors']);membership='PASS_AR5IV_THOMAS_2003B_REFERENCE' if x['key']=='P039' else 'PASS_AR5IV_AUTHOR_YEAR_JOURNAL_PAGE'
 sources.append({'key':'REV10-'+x['key'],'authors':authors,'year':year,'journal':a['publication'],'title':a['title'],'doi':a['doi'],'arxiv':a['arxiv'],'ads_bibcode':a['bibcode'],'role':x['role'],'review_locator':x['review_locator'],'boundary':x['boundary'],'source_status':'PASS','identity_verification':{'status':'PASS_ADS_DIRECT','ads_url':a['url'],'review_membership':membership},'recovery_basis':'selected from Conroy 2013 ar5iv bibliography after raw response under-harvested the required source base'})
qs=[
('P044','Chameleon Gravity Dynamics',2014,None,'1407.6044',None,'POST_REVIEW_AND_OUT_OF_SCOPE_NOT_USABLE'),
('P045','GalaxyCoin Cryptocurrency',2026,None,'2603.29340',None,'POST_REVIEW_NONSCIENTIFIC_OUT_OF_SCOPE_NOT_USABLE'),
('P046','Ultra-Diffuse Galaxy Kinematics',2021,None,'2112.00017',None,'POST_REVIEW_DYNAMICS_OUT_OF_SCOPE_NOT_USABLE'),
('P047','Lunar and Asteroid Regolith',2021,None,None,None,'POST_REVIEW_PLANETARY_SCIENCE_OUT_OF_SCOPE_NOT_USABLE'),
('P048','Cosmological Age Constraints thesis',2026,None,None,None,'POST_REVIEW_EXTERNAL_THESIS_NOT_USABLE')]
for k,title,year,doi,ar,bib,reason in qs:sources.append({'key':'REV10-'+k,'authors':'unverified candidate','year':year,'journal':None,'title':title,'doi':doi,'arxiv':ar,'ads_bibcode':bib,'role':'quarantined_candidate','review_locator':'raw Deep Research browsing spillover','boundary':'not usable','source_status':'QUARANTINED','identity_verification':{'status':'QUARANTINED','review_membership':'FAIL_OUTSIDE_2013_REVIEW_SOURCE_BASE'},'quarantine_reason':reason})
primary=[s for s in sources if s['source_status']=='PASS' and s['role']!='supporting_review'];support=[s for s in sources if s['source_status']=='PASS' and s['role']=='supporting_review'];q=[s for s in sources if s['source_status']!='PASS'];assert(len(primary),len(support),len(q))==(40,3,5);assert all(s['year']<=2013 for s in primary+support)
r={'status':'PASS_RECOVERED_FROM_COMPLETE_REVIEW_BIBLIOGRAPHY','mission_id':'GALAXY_REVIEW_BASE_DR_20260715','queue_item':10,'review':{'key':'REV10-R00','authors':'Conroy C','year':2013,'title':'Modeling the Panchromatic Spectral Energy Distributions of Galaxies','journal':'Annual Review of Astronomy and Astrophysics','doi':'10.1146/annurev-astro-082812-141017','arxiv':'1301.7095','ads_bibcode':'2013ARA&A..51..393C','identity_status':'PASS_ADS_CROSSREF_ARXIV'},'review_bibliography_basis':{'source':'https://ar5iv.labs.arxiv.org/html/1301.7095','status':'PASS_COMPLETE_REVIEW_TEXT_AND_REFERENCE_LIST_WEB_ONLY','local_raw_source_extraction_used':False,'ads_verification':'PASS_DIRECT_FULL_PAGES_FOR_43_USABLE_SOURCES'},'raw_response_recovery':{'raw_named_reference_rows':11,'raw_required_shape_pass':False,'action':'rebuilt atomic packet and 40-primary harvest from complete review bibliography','raw_packet_preserved':True},'counts':{'raw_named_reference_rows':11,'total_registry_rows':48,'usable_primary_sources':40,'usable_supporting_reviews':3,'quarantined_sources':5,'usable_sources_verified_by_ads':43},'sources':sources};O.write_text(json.dumps(r,indent=2,ensure_ascii=False)+'\n');print(json.dumps(r['counts'],sort_keys=True))
