import json,re
from pathlib import Path
A=Path('/Users/duhokim/NebulaMind/NebulaMind/.hermes/handoffs/galaxy-evolution/wiki-expansion-20260715');D=json.loads((A/'scratch/review_base13_ads_identities.json').read_text())['sources'];O=A/'area_review_13_mckee_ostriker_2007_CURATED_SOURCE_REGISTRY.json';quarantine={'P019':'RAW_ROW_NOT_IN_REVIEW_BIBLIOGRAPHY','P025':'RAW_ROW_NOT_IN_REVIEW_BIBLIOGRAPHY','P031':'RAW_ROW_NOT_IN_REVIEW_BIBLIOGRAPHY','P032':'RAW_ROW_NOT_IN_REVIEW_BIBLIOGRAPHY','P035':'RAW_ROW_NOT_IN_REVIEW_BIBLIOGRAPHY','P037':'RAW_ROW_NOT_IN_REVIEW_BIBLIOGRAPHY'}
manual={
'P001':{'title':'Star Formation in Molecular Clouds: Observation and Theory','authors':['Shu, Frank H.','Adams, Fred C.','Lizano, Susana'],'publication':'Annual Review of Astronomy and Astrophysics','doi':'10.1146/annurev.aa.25.090187.000323','arxiv':None,'bibcode':'1987ARA&A..25...23S','url':'https://ui.adsabs.harvard.edu/abs/1987ARA%26A..25...23S/abstract'},
'P014':{'title':'Star Formation in a Crossing Time','authors':['Elmegreen, Bruce G.'],'publication':'The Astrophysical Journal','doi':'10.1086/308361','arxiv':'astro-ph/9911172','bibcode':'2000ApJ...530..277E','url':'https://ui.adsabs.harvard.edu/abs/2000ApJ...530..277E/abstract'},
'P017':{'title':'Competitive accretion in embedded stellar clusters','authors':['Bonnell, I. A.','Bate, M. R.','Clarke, C. J.','Pringle, J. E.'],'publication':'Monthly Notices of the Royal Astronomical Society','doi':'10.1046/j.1365-8711.2001.04270.x','arxiv':'astro-ph/0101511','bibcode':'2001MNRAS.323..785B','url':'https://ui.adsabs.harvard.edu/abs/2001MNRAS.323..785B/abstract'}}
ov={'P014':('analytic_theory','cloud timescale','Observational-timescale argument for completion in one or a few crossing times; not a 1993 H2-transition paper.'),'P017':('analytic_theory','massive-star/cluster formation','Competitive accretion model; depends on shared cluster potential and gas reservoir.'),'P020':('simulation','massive-star radiation feedback','Three-dimensional radiation-hydrodynamic setup and resolution bound the radiation-instability result.')}
sources=[];corrected=[]
for x in D:
 key=x['key'];a=manual.get(key,x['ads_direct']);
 if key in quarantine:
  sources.append({'key':'REV13-'+key,'authors':x['raw_authors'],'year':int(x['raw_year']),'journal':x['raw_journal'],'title':x['raw_title'],'doi':x['raw_doi'],'arxiv':x['raw_arxiv'],'ads_bibcode':x['bibcode'],'role':'quarantined_candidate','review_locator':x['review_locator'],'boundary':'not usable','source_status':'QUARANTINED','identity_verification':{'status':'ADS_IDENTITY_NOT_SUFFICIENT','review_membership':'FAIL_AR5IV_COMPLETE_BIBLIOGRAPHY'},'quarantine_reason':quarantine[key]});continue
 assert a.get('title') and a.get('bibcode'),key;role=x['role'];loc=x['review_locator'];bd=x['boundary'];
 if key in ov:role,loc,bd=ov[key]
 sources.append({'key':'REV13-'+key,'authors':'; '.join(a['authors']),'year':int(a['bibcode'][:4]),'journal':a['publication'],'title':a['title'],'doi':a.get('doi'),'arxiv':a.get('arxiv'),'ads_bibcode':a['bibcode'],'role':role,'review_locator':loc,'boundary':bd,'source_status':'PASS','identity_verification':{'status':'PASS_ADS_DIRECT_OR_ADS_CROSSREF_COMPOSITE','ads_url':a['url'],'review_membership':'PASS_AR5IV_AUTHOR_YEAR_JOURNAL_PAGE'}})
 n=lambda v:re.sub(r'[^a-z0-9]','',(v or '').casefold());diff=[f for f,rv,av in [('title',x.get('raw_title'),a['title']),('doi',x.get('raw_doi'),a.get('doi')),('arxiv',x.get('raw_arxiv'),a.get('arxiv')),('bibcode',x.get('bibcode'),a['bibcode'])] if n(rv)!=n(av)]
 if diff:corrected.append({'key':'REV13-'+key,'fields':diff})
extra=[
('P041',['Padoan, Paolo','Nordlund, Åke'],2002,'The Astrophysical Journal','The Stellar Initial Mass Function from Turbulent Fragmentation','10.1086/341790','astro-ph/0011465','2002ApJ...576..870P','analytic_theory','turbulent fragmentation and IMF','Derives a core-mass spectrum from an isothermal turbulent density field; power spectrum, MHD jump, and collapse assumptions apply.'),
('P042',['Ostriker, Eve C.','Gammie, Charles F.','Stone, James M.'],1999,'The Astrophysical Journal','Kinetic and Structural Evolution of Self-gravitating, Magnetized Clouds: 2.5-dimensional Simulations of Decaying Turbulence','10.1086/306842','astro-ph/9810321','1999ApJ...513..259O','simulation','magnetic support and turbulent decay','2.5-D isothermal periodic simulations; collapse and decay times depend on magnetization, Jeans number, and setup.'),
('P043',['Li, P. S.','Norman, Michael L.','Mac Low, Mordecai-Mark','Heitsch, Fabian'],2004,'The Astrophysical Journal','The Formation of Self-Gravitating Cores in Turbulent Magnetized Clouds','10.1086/382652','astro-ph/0312622','2004ApJ...605..800L','simulation','magnetized core formation','Super-Alfvénic isothermal ZEUS-MP simulations; core statistics and collapse rates are resolution/initial-condition dependent.'),
('P044',['Stone, James M.','Ostriker, Eve C.','Gammie, Charles F.'],1998,'The Astrophysical Journal','Dissipation in Compressible Magnetohydrodynamic Turbulence','10.1086/311718','astro-ph/9809357','1998ApJ...508L..99S','simulation','turbulent decay','Forced/decaying periodic MHD simulations show crossing-time-scale dissipation; no direct cloud-lifetime measurement.'),
('P045',['Mac Low, Mordecai-Mark','Klessen, Ralf S.','Burkert, Andreas','Smith, Michael D.'],1998,'Physical Review Letters','Kinetic Energy Decay Rates of Supersonic and Super-Alfvénic Turbulence in Star-Forming Clouds','10.1103/PhysRevLett.80.2754','astro-ph/9712013','1998PhRvL..80.2754M','simulation','turbulent decay','Isothermal decaying-turbulence simulations; driving requirement follows from model decay, not an observed driver identity.'),
('P046',['Crutcher, Richard M.'],1999,'The Astrophysical Journal','Magnetic Fields in Molecular Clouds: Observations Confront Theory','10.1086/307483',None,'1999ApJ...520..706C','measurement','Zeeman magnetic fields','Compilation of 27 sensitive Zeeman measurements; projection, tracer, nondetections, and geometry bound mass-to-flux inference.'),
('P047',['Klessen, Ralf S.'],2001,'The Astrophysical Journal','The Formation of Stellar Clusters: Mass Spectra from Turbulent Molecular Cloud Fragmentation','10.1086/321626','astro-ph/0104127','2001ApJ...556..837K','simulation','cluster formation and core spectra','Hydrodynamic self-gravitating models vary driving scale; simulated core spectra are not a one-to-one IMF prediction.'),
('P048',['Larson, Richard B.'],2005,'Monthly Notices of the Royal Astronomical Society','Thermal physics, cloud geometry and the stellar initial mass function','10.1111/j.1365-2966.2005.08881.x','astro-ph/0412357','2005MNRAS.359..211L','analytic_theory','thermal fragmentation and IMF','Links characteristic mass to gas-dust thermal transition and geometry; metallicity/background assumptions apply.'),
('P049',['Mouschovias, Telemachos Ch.','Tassis, Konstantinos','Kunz, Matthew W.'],2006,'The Astrophysical Journal','Observational Constraints on the Ages of Molecular Clouds and the Star Formation Timescale: Ambipolar-Diffusion-controlled or Turbulence-induced Star Formation?','10.1086/500125','astro-ph/0512043','2006ApJ...646.1043M','analytic_theory','cloud lifetime debate','Reinterprets age and linewidth data in an ambipolar-diffusion framework; contested model comparison, not consensus measurement.'),
('P050',['Bonnell, Ian A.','Bate, Matthew R.','Zinnecker, Hans'],1998,'Monthly Notices of the Royal Astronomical Society','On the formation of massive stars','10.1046/j.1365-8711.1998.01590.x','astro-ph/9802332','1998MNRAS.298...93B','analytic_theory','massive-star formation','Cluster-mediated accretion/merger argument under dense-environment assumptions; not universal massive-star pathway.'),
('P051',['Matzner, Christopher D.','McKee, Christopher F.'],2000,'The Astrophysical Journal','Efficiencies of Low-Mass Star and Star Cluster Formation','10.1086/317785','astro-ph/0007383','2000ApJ...545..364M','analytic_theory','outflow-regulated efficiency','Analytic protostellar-outflow model predicts core/clump efficiencies; massive-star destructive feedback is excluded.')]
for key,au,yr,j,t,doi,ar,bib,role,loc,bd in extra:sources.append({'key':'REV13-'+key,'authors':'; '.join(au),'year':yr,'journal':j,'title':t,'doi':doi,'arxiv':ar,'ads_bibcode':bib,'role':role,'review_locator':loc,'boundary':bd,'source_status':'PASS','identity_verification':{'status':'PASS_ADS_DIRECT','ads_url':'https://ui.adsabs.harvard.edu/abs/'+bib.replace('&','%26')+'/abstract','review_membership':'PASS_AR5IV_AUTHOR_YEAR_JOURNAL_PAGE'}})
spill=[('P052','Krumholz 2014 Physics Reports',2014),('P053','Federrath & Klessen 2012 ApJ',2012),('P054','Padoan et al. 2014 Protostars and Planets VI',2014),('P055','Breen et al. 2013 MNRAS',2013),('P056','Krumholz, Dekel & McKee 2012 ApJ',2012),('P057','Herschel surveys 2010-2015',2015),('P058','Krumholz & McKee 2008 Nature',2008)]
for key,title,year in spill:sources.append({'key':'REV13-'+key,'authors':'unverified browsing candidate','year':year,'journal':None,'title':title,'doi':None,'arxiv':None,'ads_bibcode':None,'role':'quarantined_candidate','review_locator':'raw browsing spillover','boundary':'not usable','source_status':'QUARANTINED','identity_verification':{'status':'QUARANTINED','review_membership':'FAIL_POST_2007_OR_OUTSIDE_REVIEW'},'quarantine_reason':'POST_2007_UNCITED_NOT_USABLE'})
primary=[s for s in sources if s['source_status']=='PASS' and s['role']!='supporting_review'];support=[s for s in sources if s['source_status']=='PASS' and s['role']=='supporting_review'];q=[s for s in sources if s['source_status']!='PASS'];assert(len(primary),len(support),len(q))==(40,5,13),(len(primary),len(support),len(q));assert all(s['year']<=2007 for s in primary+support)
r={'status':'PASS_WITH_RAW_IDENTITIES_AND_MEMBERSHIP_CORRECTED','mission_id':'GALAXY_REVIEW_BASE_DR_20260715','queue_item':13,'review':{'key':'REV13-R00','authors':'McKee CF; Ostriker EC','year':2007,'title':'Theory of Star Formation','journal':'Annual Review of Astronomy and Astrophysics','doi':'10.1146/annurev.astro.45.051806.110602','arxiv':'0707.3514','ads_bibcode':'2007ARA&A..45..565M','identity_status':'PASS_ADS_CROSSREF_ARXIV'},'review_bibliography_basis':{'source':'https://ar5iv.labs.arxiv.org/html/0707.3514','status':'PASS_COMPLETE_REVIEW_TEXT_AND_801_ENTRY_REFERENCE_LIST_WEB_ONLY','ads_verification':'PASS_DIRECT_OR_COMPOSITE_FOR_45_USABLE_ROWS','local_raw_source_extraction_used':False},'raw_response_reconciliation':{'raw_source_rows':40,'raw_rows_not_found_in_review':6,'raw_identity_tuples_corrected':len(corrected),'supplemented_review_cited_primary_rows':11,'raw_packet_preserved':True,'corrections':corrected},'counts':{'raw_source_rows':40,'total_registry_rows':58,'usable_primary_sources':40,'usable_supporting_reviews':5,'quarantined_sources':13,'usable_sources_verified_by_ads':45},'sources':sources};O.write_text(json.dumps(r,indent=2,ensure_ascii=False)+'\n');print(json.dumps({'counts':r['counts'],'corrected':len(corrected)},sort_keys=True))
