import json,re
from pathlib import Path
A=Path('/Users/duhokim/NebulaMind/NebulaMind/.hermes/handoffs/galaxy-evolution/wiki-expansion-20260715');D=json.loads((A/'scratch/review_base15_ads_identities.json').read_text())['sources'];O=A/'area_review_15_veilleux_cecil_bland_hawthorn_2005_CURATED_SOURCE_REGISTRY.json';qraw={'P023':'RAW_ROW_NOT_IN_REVIEW_BIBLIOGRAPHY','P044':'RAW_ROW_NOT_IN_REVIEW_BIBLIOGRAPHY','P045':'RAW_ROW_NOT_IN_REVIEW_BIBLIOGRAPHY'}
manual={
'P023':{'title':'Metal Enrichment of the Intergalactic Medium in Cosmological Simulations','authors':['Aguirre, Anthony','Hernquist, Lars','Schaye, Joop','Katz, Neal','Weinberg, David H.','Gardner, Jeffrey'],'publication':'The Astrophysical Journal','doi':'10.1086/323370','arxiv':'astro-ph/0105184','bibcode':'2001ApJ...561..521A','url':'https://ui.adsabs.harvard.edu/abs/2001ApJ...561..521A/abstract'},
'P030':{'title':'Starbursts and Star Clusters in the Ultraviolet','authors':['Meurer, G. R.','Heckman, T. M.','Leitherer, C.','Kinney, A.','Robert, C.','Garnett, D. R.'],'publication':'The Astronomical Journal','doi':'10.1086/117721','arxiv':'astro-ph/9509038','bibcode':'1995AJ....110.2665M','url':'https://ui.adsabs.harvard.edu/abs/1995AJ....110.2665M/abstract'},
'P042':{'title':'Mass flow from stellar systems-I. Radial flow from spherical systems','authors':['Burke, J. Anthony'],'publication':'Monthly Notices of the Royal Astronomical Society','doi':'10.1093/mnras/140.2.241','arxiv':None,'bibcode':'1968MNRAS.140..241B','url':'https://ui.adsabs.harvard.edu/abs/1968MNRAS.140..241B/abstract'}}
roles={'Measurement':'measurement','Analytic':'analytic_model','Calibration':'calibration','Simulation':'simulation'};sources=[];corrected=[]
for x in D:
 key=x['key'];a=manual.get(key,x['ads_direct']);assert a.get('title') and a.get('bibcode'),key;status='QUARANTINED' if key in qraw else 'PASS';role='quarantined_candidate' if status!='PASS' else roles[x['raw_role']]
 sources.append({'key':'REV15-'+key,'authors':'; '.join(a['authors']),'year':int(a['bibcode'][:4]),'journal':a['publication'],'title':a['title'],'doi':a.get('doi'),'arxiv':a.get('arxiv'),'ads_bibcode':a['bibcode'],'role':role,'review_locator':x['review_locator'],'boundary':x['boundary'] if status=='PASS' else 'not usable','source_status':status,'identity_verification':{'status':'QUARANTINED' if status!='PASS' else ('PASS_ADS_DIRECT' if key not in manual else 'PASS_ADS_CROSSREF_OR_AUTHORITATIVE_COMPOSITE'),'ads_url':a['url'],'review_membership':'FAIL_AR5IV_BIBLIOGRAPHY' if status!='PASS' else 'PASS_AR5IV_AUTHOR_YEAR_JOURNAL_PAGE'},**({'quarantine_reason':qraw[key]} if status!='PASS' else {})})
 n=lambda v:re.sub(r'[^a-z0-9]','',(v or '').casefold());diff=[f for f,rv,av in [('doi',x.get('raw_doi'),a.get('doi')),('arxiv',x.get('raw_arxiv'),a.get('arxiv')),('bibcode',x.get('bibcode'),a['bibcode'])] if n(rv)!=n(av)]
 if diff:corrected.append({'key':'REV15-'+key,'fields':diff})
spill=[('P046','Tumlinson et al. COS-Halos Survey',2011),('P047','Borthakur et al. Impact of Starbursts on the CGM',2013),('P048','Hopkins et al. FIRE simulations',2014),('P049','Fielding et al. idealized high-resolution wind simulations',2017),('P050','Cicone et al. molecular outflows/ALMA',2016),('P051','Roberts-Borsani et al. high-redshift outflows',2020),('P052','Weldon et al. / Carniani et al. JWST measurements',2024),('P053','Lopez et al. Chandra M82 analysis',2020),('P054','Naab & Ostriker galaxy-formation review',2017),('P055','Heckman & Thompson galactic-wind review',2017),('P056','Rupke galactic-wind review',2018),('P057','Zhang hot-galactic-wind review',2018),('P058','Fabian AGN-feedback review',2012),('P059','Madau & Dickinson cosmic-SFH review',2014)]
for key,title,year in spill:sources.append({'key':'REV15-'+key,'authors':'unverified browsing candidate','year':year,'journal':None,'title':title,'doi':None,'arxiv':None,'ads_bibcode':None,'role':'quarantined_candidate','review_locator':'raw browsing spillover','boundary':'not usable','source_status':'QUARANTINED','identity_verification':{'status':'QUARANTINED','review_membership':'FAIL_POST_2005_OR_OUTSIDE_REVIEW'},'quarantine_reason':'POST_2005_UNCITED_NOT_USABLE'})
primary=[s for s in sources if s['source_status']=='PASS'];q=[s for s in sources if s['source_status']!='PASS'];assert(len(primary),len(q))==(42,17),(len(primary),len(q));assert all(s['year']<=2005 for s in primary)
r={'status':'PASS_WITH_RAW_IDENTITIES_AND_MEMBERSHIP_CORRECTED','mission_id':'GALAXY_REVIEW_BASE_DR_20260715','queue_item':15,'review':{'key':'REV15-R00','authors':'Veilleux, Sylvain; Cecil, Gerald; Bland-Hawthorn, Joss','year':2005,'title':'Galactic Winds','journal':'Annual Review of Astronomy and Astrophysics','doi':'10.1146/annurev.astro.43.072103.150610','arxiv':'astro-ph/0504435','ads_bibcode':'2005ARA&A..43..769V','identity_status':'PASS_ADS_CROSSREF_ARXIV'},'review_bibliography_basis':{'source':'https://ar5iv.labs.arxiv.org/html/astro-ph/0504435','status':'PASS_COMPLETE_REVIEW_TEXT_AND_488_ENTRY_REFERENCE_LIST_WEB_ONLY','ads_verification':'PASS_DIRECT_OR_COMPOSITE_FOR_42_USABLE_ROWS','local_raw_source_extraction_used':False},'raw_response_reconciliation':{'raw_source_rows':45,'raw_rows_absent_from_review':3,'raw_identifier_tuples_corrected':len(corrected),'supplemented_review_cited_primary_rows':0,'raw_packet_preserved':True,'corrections':corrected},'counts':{'raw_source_rows':45,'total_registry_rows':59,'usable_primary_sources':42,'usable_supporting_reviews':0,'quarantined_sources':17,'usable_sources_verified_by_ads':42},'sources':sources};O.write_text(json.dumps(r,indent=2,ensure_ascii=False)+'\n');print(json.dumps({'counts':r['counts'],'corrected':len(corrected)},sort_keys=True))
