import json,re
from pathlib import Path
A=Path('/Users/duhokim/NebulaMind/NebulaMind/.hermes/handoffs/galaxy-evolution/wiki-expansion-20260715');D=json.loads((A/'scratch/review_base17_ads_identities.json').read_text())['sources']
absent={'P018','P021','P024','P030','P033','P040'}; support={'P020'}
R=[]
for x in D:
 q=x['key'] in absent; bib=x['resolved_bibcode'] or x['raw_ads']; title=x['resolved_title'] if x['identity_page_pass'] else x['raw_title']; doi=x['resolved_doi'] or (None if x['raw_doi']=='none' else x['raw_doi']); ar=x['resolved_arxiv'] or (None if x['raw_arxiv']=='none' else x['raw_arxiv'])
 R.append({'key':x['key'],'authors_year':x['raw_authors_year'],'title':title,'doi':doi,'arxiv':ar,'ads_bibcode':bib,'role':'supporting_review' if x['key'] in support else 'primary','review_locator':x['raw_locator'],'scientific_boundary':x['raw_boundary'],'identity_status':'QUARANTINED' if q else 'PASS_ADS_COMPOSITE','review_membership':'FAIL_NOT_IN_COMPLETE_515_REFERENCE_BIBLIOGRAPHY' if q else 'PASS_COMPLETE_REVIEW_BIBLIOGRAPHY','status':'UNCITED_NOT_USABLE' if q else 'USABLE','verification_source':'ADS abstract + ar5iv complete review bibliography' if x['identity_page_pass'] else 'ADS bibcode/direct result + raw composite identifiers + ar5iv complete review bibliography'})
supp=[
('P046','McMillan, P. J. (2011)','Mass models of the Milky Way','10.1111/j.1365-2966.2011.18564.x','1102.4340','2011MNRAS.414.2446M','Integrated mass model','Bayesian multi-component mass model and Galactic constants; model-dependent, not a frame-free truth.'),
('P047','Schönrich, R., Binney, J., & Dehnen, W. (2010)','Local kinematics and the local standard of rest','10.1111/j.1365-2966.2010.16253.x','0912.3693','2010MNRAS.403.1829S','Solar motion / LSR','Revised solar peculiar velocity from local stellar kinematics; depends on population/asymmetric-drift treatment.'),
('P048','Kafle, P. R., Sharma, S., Lewis, G. F., & Bland-Hawthorn, J. (2012)','Kinematics of the Stellar Halo and the Mass Distribution of the Milky Way Using Blue Horizontal Branch Stars','10.1088/0004-637X/761/2/98','1210.7527','2012ApJ...761...98K','Halo mass and anisotropy','BHB Jeans analysis to about 60 kpc; equilibrium and anisotropy assumptions bound the inferred halo mass.')]
for k,a,t,d,ar,bib,loc,bnd in supp:R.append({'key':k,'authors_year':a,'title':t,'doi':d,'arxiv':ar,'ads_bibcode':bib,'role':'primary','review_locator':loc,'scientific_boundary':bnd,'identity_status':'PASS_ADS_COMPOSITE','review_membership':'PASS_COMPLETE_REVIEW_BIBLIOGRAPHY','status':'USABLE','verification_source':'ADS abstract/web result + ar5iv complete review bibliography'})
spill=[('P049','Gaia Collaboration (2018), Data Release 2 kinematics','POST_2016'),('P050','Eilers et al. (2019), Milky Way circular-velocity curve','POST_2016'),('P051','Posti & Helmi (2018), globular-cluster halo mass','POST_2016'),('P052','Monari et al. (2017), slower-bar models','POST_2016'),('P053','Bovy et al. (2019), stellar bar kinematics','POST_2016'),('P054','Xiang & Rix (2022), subgiant star-formation history','POST_2016'),('P055','Ou et al. (2024), low virial-mass estimate','POST_2016')]
for k,c,reason in spill:R.append({'key':k,'candidate':c,'doi':None,'arxiv':None,'ads_bibcode':None,'role':'quarantined','identity_status':'QUARANTINED','review_membership':'FAIL_OUT_OF_SCOPE','status':'UNCITED_NOT_USABLE','reason':reason})
usable=[x for x in R if x['status']=='USABLE'];q=[x for x in R if x['status']=='UNCITED_NOT_USABLE'];assert len(usable)==42 and sum(x['role']=='primary' for x in usable)==41 and sum(x['role']=='supporting_review' for x in usable)==1 and len(q)==13
out={'review':{'title':'The Galaxy in Context: Structural, Kinematic, and Integrated Properties','doi':'10.1146/annurev-astro-081915-023441','arxiv':'1602.07702','ads_bibcode':'2016ARA&A..54..529B','identity_status':'PASS_ADS_CROSSREF_ARXIV'},'verification_summary':{'raw_rows':45,'raw_rows_absent_from_review':6,'review_cited_primary_rows_supplemented':3,'usable_primary':41,'supporting_reviews':1,'quarantined':13,'usable_sources_ads_verified':42},'sources':R}
(A/'area_review_17_bland_hawthorn_gerhard_2016_CURATED_SOURCE_REGISTRY.json').write_text(json.dumps(out,indent=2,ensure_ascii=False)+'\n');print(out['verification_summary'])
