import json,re
from pathlib import Path
A=Path('/Users/duhokim/NebulaMind/NebulaMind/.hermes/handoffs/galaxy-evolution/wiki-expansion-20260715');D=json.loads((A/'scratch/review_base16_ads_identities.json').read_text())['sources'];O=A/'area_review_16_carilli_walter_2013_CURATED_SOURCE_REGISTRY.json';qraw={'P029':'RAW_ROW_NOT_IN_REVIEW_BIBLIOGRAPHY','P035':'RAW_ROW_NOT_IN_REVIEW_BIBLIOGRAPHY'}
manual={
'P007':{'title':'Evidence of strong quasar feedback in the early Universe','authors':['Maiolino, R.','Gallerani, S.','Neri, R.','Cicone, C.','Ferrara, A.','Genzel, R.','Lutz, D.','Sturm, E.','Tacconi, L. J.','Walter, F.'],'publication':'Monthly Notices of the Royal Astronomical Society','doi':'10.1111/j.1745-3933.2012.01303.x','arxiv':'1204.2904','bibcode':'2012MNRAS.425L..66M','url':'https://ui.adsabs.harvard.edu/abs/2012MNRAS.425L..66M/abstract'},
'P014':{'title':'Ionized Nitrogen at High Redshift','authors':['Decarli, R.','Walter, F.','Neri, R.','Bertoldi, F.','Carilli, C. L.','Cox, P.','Kneib, J.-P.','Lestrade, J.-F.','Maiolino, R.','Omont, A.','Richard, J.','Riechers, D. A.','Thanjavur, K.','Weiß, A.'],'publication':'The Astrophysical Journal','doi':'10.1088/0004-637x/752/1/2','arxiv':'1203.6852','bibcode':'2012ApJ...752....2D','url':'https://ui.adsabs.harvard.edu/abs/2012ApJ...752....2D/abstract'},
'P021':{'title':'Strong [CII] emission at high redshift','authors':['Maiolino, R.','Caselli, P.','Nagao, T.','Walmsley, M.','De Breuck, C.','Meneghetti, M.'],'publication':'Astronomy and Astrophysics','doi':'10.1051/0004-6361/200912265','arxiv':'0904.3793','bibcode':'2009A&A...500L...1M','url':'https://ui.adsabs.harvard.edu/abs/2009A%26A...500L...1M/abstract'},
'P028':{'title':'Evidence for CO Shock Excitation in NGC 6240 from Herschel SPIRE Spectroscopy','authors':['Meijerink, R.','Kristensen, L. E.','Weiß, A.','van der Werf, P. P.','Walter, F.','Spaans, M.'],'publication':'The Astrophysical Journal','doi':'10.1088/2041-8205/762/2/L16','arxiv':'1211.6659','bibcode':'2013ApJ...762L..16M','url':'https://ui.adsabs.harvard.edu/abs/2013ApJ...762L..16M/abstract'}}
roles={'Measurement':'measurement','Calibration':'calibration','Synthesis':'calibration','Model':'analytic_model','Simulation':'simulation','Methodological':'supporting_review','Review':'supporting_review'};sources=[];corrected=[]
for x in D:
 key=x['key'];a=manual.get(key,x['ads_direct']);status='QUARANTINED' if key in qraw else 'PASS'
 if status=='PASS':assert a and a.get('title') and a.get('bibcode'),key
 if status!='PASS':
  a=a or {};sources.append({'key':'REV16-'+key,'authors':x['raw_citation'],'year':int(re.search(r'\b(\d{4})\b',x['raw_citation']).group(1)),'journal':a.get('publication'),'title':a.get('title') or x['raw_citation'],'doi':a.get('doi') or x['raw_doi'],'arxiv':a.get('arxiv') or x['raw_arxiv'],'ads_bibcode':a.get('bibcode') or x['bibcode'],'role':'quarantined_candidate','review_locator':'raw primary harvest','boundary':'not usable','source_status':'QUARANTINED','identity_verification':{'status':'QUARANTINED','review_membership':'FAIL_AR5IV_BIBLIOGRAPHY'},'quarantine_reason':qraw[key]});continue
 role=roles[x['raw_role']];sources.append({'key':'REV16-'+key,'authors':'; '.join(a['authors']),'year':int(a['bibcode'][:4]),'journal':a['publication'],'title':a['title'],'doi':a.get('doi'),'arxiv':a.get('arxiv'),'ads_bibcode':a['bibcode'],'role':role,'review_locator':'cool-gas '+x['raw_role'].casefold(),'boundary':x['boundary'],'source_status':'PASS','identity_verification':{'status':'PASS_ADS_DIRECT_OR_AUTHORITATIVE_COMPOSITE','ads_url':a['url'],'review_membership':'PASS_AR5IV_AUTHOR_YEAR_JOURNAL_PAGE_OR_EXACT_ARXIV'}})
 n=lambda v:re.sub(r'[^a-z0-9]','',(v or '').casefold());diff=[f for f,rv,av in [('doi',x.get('raw_doi'),a.get('doi')),('arxiv',x.get('raw_arxiv'),a.get('arxiv')),('bibcode',x.get('bibcode'),a['bibcode'])] if n(rv)!=n(av)]
 if diff:corrected.append({'key':'REV16-'+key,'fields':diff})
extra={'key':'REV16-P046','authors':'Kennicutt, Robert C., Jr.','year':1998,'journal':'The Astrophysical Journal','title':'The Global Schmidt Law in Star-forming Galaxies','doi':'10.1086/305588','arxiv':'astro-ph/9712213','ads_bibcode':'1998ApJ...498..541K','role':'calibration','review_locator':'global star-formation law','boundary':'Disk-averaged local spiral plus infrared-starburst relation; CO conversion, helium, SFR IMF, area averaging, and regression range apply.','source_status':'PASS','identity_verification':{'status':'PASS_ADS_DIRECT','ads_url':'https://ui.adsabs.harvard.edu/abs/1998ApJ...498..541K/abstract','review_membership':'PASS_AR5IV_AUTHOR_YEAR_JOURNAL_PAGE'}};sources.append(extra)
spill=[('P047','Capak et al. post-2013 ALMA [CII]',2015),('P048','Finkelstein et al. specific reionization candidate',2013),('P049','Fisher et al. post-2013',2014),('P050','Riechers et al. post-2013 ALMA deep fields',2020),('P051','Umehata et al. post-2013',2020),('P052',"D'Eugenio et al. post-2013 JWST/ALMA",2024),('P053','Oteo et al. / Zavala et al. post-2013',2018),('P054','Belli/Williams/Woodrum quiescent-gas studies',2022),('P055','soccer/name-collision entities for da Cunha',2024)]
for key,title,year in spill:sources.append({'key':'REV16-'+key,'authors':'unverified browsing candidate','year':year,'journal':None,'title':title,'doi':None,'arxiv':None,'ads_bibcode':None,'role':'quarantined_candidate','review_locator':'raw browsing spillover','boundary':'not usable','source_status':'QUARANTINED','identity_verification':{'status':'QUARANTINED','review_membership':'FAIL_POST_2013_OR_OUTSIDE_REVIEW'},'quarantine_reason':'POST_2013_OR_UNCITED_NOT_USABLE'})
primary=[s for s in sources if s['source_status']=='PASS' and s['role']!='supporting_review'];support=[s for s in sources if s['source_status']=='PASS' and s['role']=='supporting_review'];q=[s for s in sources if s['source_status']!='PASS'];assert(len(primary),len(support),len(q))==(40,4,11),(len(primary),len(support),len(q));assert all(s['year']<=2013 for s in primary+support)
r={'status':'PASS_WITH_RAW_IDENTITIES_AND_MEMBERSHIP_CORRECTED','mission_id':'GALAXY_REVIEW_BASE_DR_20260715','queue_item':16,'review':{'key':'REV16-R00','authors':'Carilli, C. L.; Walter, F.','year':2013,'title':'Cool Gas in High-Redshift Galaxies','journal':'Annual Review of Astronomy and Astrophysics','doi':'10.1146/annurev-astro-082812-140953','arxiv':'1301.0371','ads_bibcode':'2013ARA&A..51..105C','identity_status':'PASS_ADS_CROSSREF_ARXIV'},'review_bibliography_basis':{'source':'https://ar5iv.labs.arxiv.org/html/1301.0371','status':'PASS_COMPLETE_REVIEW_TEXT_AND_401_ENTRY_REFERENCE_LIST_WEB_ONLY','ads_verification':'PASS_DIRECT_OR_COMPOSITE_FOR_44_USABLE_ROWS','local_raw_source_extraction_used':False},'raw_response_reconciliation':{'raw_source_rows':45,'raw_rows_absent_from_review':2,'raw_identifier_tuples_corrected':len(corrected),'raw_identifier_hybrids_corrected':['REV16-P007','REV16-P021','REV16-P028'],'supplemented_review_cited_primary_rows':1,'raw_packet_preserved':True,'corrections':corrected},'counts':{'raw_source_rows':45,'total_registry_rows':55,'usable_primary_sources':40,'usable_supporting_reviews':4,'quarantined_sources':11,'usable_sources_verified_by_ads':44},'sources':sources};O.write_text(json.dumps(r,indent=2,ensure_ascii=False)+'\n');print(json.dumps({'counts':r['counts'],'corrected':len(corrected)},sort_keys=True))
