import json
from pathlib import Path
A=Path('/Users/duhokim/NebulaMind/NebulaMind/.hermes/handoffs/galaxy-evolution/wiki-expansion-20260715');D=json.loads((A/'scratch/review_base20_ads_identities.json').read_text())['sources'];absent={'P007','P013','P020','P023','P025','P028','P032','P033'};S=[]
for x in D:
 ok=x['key'] not in absent;S.append({'key':x['key'],'status':'USABLE' if ok else 'UNCITED_NOT_USABLE','role':'primary' if ok else 'quarantine','title':x.get('resolved_title') or x['raw_citation'],'raw_citation':x['raw_citation'],'doi':x.get('resolved_doi') if ok else None,'arxiv':x.get('resolved_arxiv') if ok else None,'ads_bibcode':x['raw_ads'] if ok else None,'review_membership':'PASS_AR5IV_COMPLETE_REFERENCE_LIST' if ok else 'FAIL_COMPLETE_REFERENCE_LIST','review_locator':'Renzini 2006 complete reference list' if ok else None,'scientific_boundary':x['raw_boundary'] if ok else None,'reason':None if ok else 'ADS-valid browsing candidate absent from complete review bibliography'})
for x in S:
    if x['key']=='P020': x.update(review_membership='FAIL_INVALID_COMPOSITE_IDENTITY',reason='raw hybrid: 1990 citation paired with a 1992 title and non-resolving 18-character bibcode')
    if x['key']=='P021': x.update(title='The Cosmic Baryon Budget',doi='10.1086/306025',arxiv='astro-ph/9712020',ads_bibcode='1998ApJ...503..518F',identity_source='arXiv journal reference plus DOI cross-link')
    if x['key']=='P027': x.update(title='Origin of the colour-magnitude relation of elliptical galaxies',doi=None,arxiv='astro-ph/9609160',ads_bibcode='1997A&A...320...41K',identity_source='arXiv journal reference plus ADS bibliography record')
    if x['key']=='P045': x.update(title='Galactic Bulges from HST-NICMOS Observations: Ages and Dust',doi=None,arxiv='astro-ph/9910153',ads_bibcode='1999MNRAS.310..703P',identity_source='arXiv journal reference plus ADS bibliography record')
extra=[('P046','Trager et al. 2000','The Stellar Population Histories of Early-Type Galaxies. II. Controlling Parameters of the Stellar Populations','10.1086/301442','astro-ph/0004095','2000AJ....120..165T','central SSP-equivalent ages, [Z/H] and enhancement ratios for 50 local ellipticals; young frosting bias retained'),('P047','Treu et al. 2005','The Assembly History of Field Spheroidals: Evolution of Mass-to-Light Ratios and Signatures of Recent Star Formation','10.1086/444585','astro-ph/0503164','2005ApJ...633..174T','morphologically selected GOODS-N field spheroidals at 0.2<z<1.2; FP selection and recent-star-formation sensitivity retained'),('P070','Treu et al. 2005','Keck Spectroscopy of Distant GOODS Spheroidal Galaxies: Downsizing in a Hierarchical Universe','10.1086/429374','astro-ph/0502028','2005ApJ...622L...5T','morphologically selected 0.2<z<1.2 field spheroidals; luminosity-weighted downsizing and selection limits retained')]
for k,a,t,d,ar,b,bound in extra:S.append({'key':k,'status':'USABLE','role':'primary','title':t,'authors_year':a,'doi':d,'arxiv':ar,'ads_bibcode':b,'review_membership':'PASS_AR5IV_COMPLETE_REFERENCE_LIST','review_locator':'Renzini 2006 complete reference list','scientific_boundary':bound,'identity_source':'ADS abstract page verified'})
names=['Choi et al. 2014','Gallazzi et al. 2014','Siudek et al. 2015','Fritz et al. 2014','Pozzetti et al. 2010','Moresco et al. 2011','Belli et al. 2014','Belli et al. 2015','Zanella et al. 2016','Carollo et al. 2013','Poggianti et al. 2013','Fagioli et al. 2016','Patel et al. 2013','Huang et al. 2013','Beifiori et al. 2014','Masters et al. 2011','Maraston et al. 2013','Thomas et al. 2013','Gargiulo et al. 2017','Saracco et al. 2010','Popesso et al. 2023','Smith 2020']
for i,c in enumerate(names,48):S.append({'key':f'P{i:03d}','status':'UNCITED_NOT_USABLE','role':'quarantine','candidate':c,'doi':None,'arxiv':None,'ads_bibcode':None,'review_membership':'FAIL_POST_2006','reason':'post-2006 retrospective source'})
out={'review':{'doi':'10.1146/annurev.astro.44.051905.092450','arxiv':'astro-ph/0603479','ads_bibcode':'2006ARA&A..44..141R','status':'PASS_ADS_CROSSREF_ARXIV'},'sources':S,'counts':{'raw_rows':45,'usable_primary':40,'supporting_reviews':0,'quarantined':30,'raw_rows_absent_from_review_or_invalid_identity':8,'supplemented_review_cited_primaries':3}}
(A/'area_review_20_renzini_2006_CURATED_SOURCE_REGISTRY.json').write_text(json.dumps(out,indent=2,ensure_ascii=False)+'\n');print(out['counts'])
