import json,re
from pathlib import Path
A=Path('/Users/duhokim/NebulaMind/NebulaMind/.hermes/handoffs/galaxy-evolution/wiki-expansion-20260715');D=json.loads((A/'scratch/review_base18_ads_identities.json').read_text())['sources'];S=[]
for x in D:
 doi=x.get('resolved_doi') or (None if x['raw_doi']=='none' else x['raw_doi']);ar=x.get('resolved_arxiv') or (None if x['raw_arxiv']=='none' else x['raw_arxiv']);bib=x.get('resolved_bibcode') or x['raw_ads'];title=x.get('resolved_title') or x['raw_citation'];role='supporting_review' if int(x['key'][1:])>=36 else 'primary'
 S.append({'key':x['key'],'status':'USABLE','role':role,'title':title,'raw_citation':x['raw_citation'],'doi':doi,'arxiv':ar,'ads_bibcode':bib,'review_membership':'PASS_AR5IV_COMPLETE_REFERENCE_LIST','review_locator':'Freeman & Bland-Hawthorn 2002 complete reference list','scientific_boundary':x['raw_boundary'],'identity_source':'ADS abstract page or direct ADS bibcode resolution'})
extra=[
('P041','Prochaska et al. 2000','The Galactic Thick Disk Stellar Abundances','10.1086/316818','astro-ph/0008075','2000AJ....120.2513P','thick-disk abundance sample; 1D-LTE and kinematic-selection boundary'),
('P042','Gilmore, Wyse & Jones 1995','A Determination of the Thick Disk Chemical Abundance Distribution: Implications for Galaxy Evolution','10.1086/117344','astro-ph/9411116','1995AJ....109.1095G','in-situ F/G-star metallicity distribution 0.5-3 kpc above plane'),
('P043','Unavane, Wyse & Gilmore 1996','The merging history of the Milky Way','10.1093/mnras/278.3.727','astro-ph/9509030','1996MNRAS.278..727U','turnoff-colour limits on recent accretion of Carina/Fornax-like satellites'),
('P044','Ryan, Norris & Beers 1996','Extremely Metal-poor Stars. II. Elemental Abundances and the Early Chemical Enrichment of the Galaxy','10.1086/177967',None,'1996ApJ...471..254R','high-resolution abundances of stars below [Fe/H]=-2.5; atmosphere and non-LTE systematics retained'),
('P045','Norris & Ryan 1989','Population Studies: Evidence for Accretion of the Galactic Halo','10.1086/185351',None,'1989ApJ...336L..17N','kinematically selected retrograde dwarf-star evidence; selection boundary retained')]
for k,a,t,d,ar,b,bound in extra:S.append({'key':k,'status':'USABLE','role':'primary','title':t,'authors_year':a,'doi':d,'arxiv':ar,'ads_bibcode':b,'review_membership':'PASS_AR5IV_COMPLETE_REFERENCE_LIST','review_locator':'Freeman & Bland-Hawthorn 2002 complete reference list','scientific_boundary':bound,'identity_source':'ADS abstract page verified'})
q=[('P046','Gaia/APOGEE/GALAH/LAMOST/DESI/RAVE results','Post-2002 survey products'),('P047','Gaia-Sausage-Enceladus/Splash/Kraken/Sequoia/C-19','Post-2002 substructure discoveries'),('P048','FIRE/EAGLE/IllustrisTNG','Post-2002 hydrodynamic simulations'),('P049','Modern machine-learning clustering','Post-2002 methods'),('P050','Modern radial-migration consensus','Post-2002 synthesis; only contemporaneous 2002 limits allowed')]
for k,c,reason in q:S.append({'key':k,'status':'UNCITED_NOT_USABLE','role':'quarantine','candidate':c,'doi':None,'arxiv':None,'ads_bibcode':None,'review_membership':'FAIL_ERA_OR_SOURCE_BASE','reason':reason})
out={'review':{'doi':'10.1146/annurev.astro.40.060401.093840','arxiv':'astro-ph/0208106','ads_bibcode':'2002ARA&A..40..487F','status':'PASS_ADS_CROSSREF_ARXIV'},'sources':S,'counts':{'raw_rows':40,'usable_primary':40,'supporting_reviews':5,'quarantined':5,'supplemented_review_cited_primaries':5}}
(A/'area_review_18_freeman_bland_hawthorn_2002_CURATED_SOURCE_REGISTRY.json').write_text(json.dumps(out,indent=2,ensure_ascii=False)+'\n');print(out['counts'])
