import json
from pathlib import Path
A=Path("/Users/duhokim/NebulaMind/NebulaMind/.hermes/handoffs/galaxy-evolution/wiki-expansion-20260715")
seeds=[
("P001","2003MNRAS.344.1000B","calibration","SPS models","BC03 evolutionary population synthesis; model-dependent stellar tracks, libraries, IMF, and SFH."),
("P002","2005MNRAS.362..799M","calibration","TP-AGB/SPS","Fuel-consumption SPS with strong intermediate-age TP-AGB contribution."),
("P003","2009ApJ...699..486C","calibration","SPS uncertainties","FSPS framework varying uncertain stellar-evolution phases."),
("P004","2010ApJ...712..833C","calibration","SPS validation","FSPS calibration and comparison against star clusters and galaxy colors."),
("P005","2010MNRAS.404.1639V","calibration","spectral synthesis","MILES-based SSP spectral models; optical empirical-library coverage."),
("P006","1997A&A...326..950F","calibration","panchromatic SPS","PEGASE evolutionary synthesis from UV through FIR."),
("P007","2000A&AS..141..371G","calibration","stellar isochrones","Padova stellar tracks/isochrones over age and metallicity grids."),
("P008","2008A&A...482..883M","calibration","stellar isochrones","Isochrones including updated TP-AGB evolution and circumstellar dust."),
("P009","2004ApJ...612..168P","calibration","stellar isochrones","BaSTI stellar-evolution database; scaled-solar grids and mass loss assumptions."),
("P010","2006ApJS..162..375V","calibration","stellar isochrones","Victoria-Regina isochrones; old/intermediate populations and abundance assumptions."),
("P011","1998PASP..110..863P","calibration","stellar spectra","Empirical stellar spectral flux library; finite parameter and abundance coverage."),
("P012","2003A&A...402..433L","calibration","stellar spectra","STELIB empirical stellar library used in population synthesis."),
("P013","2006MNRAS.371..703S","calibration","stellar spectra","MILES empirical stellar library and atmospheric-parameter coverage."),
("P014","2005A&A...443..735C","calibration","stellar spectra","Theoretical high-resolution stellar library with abundance/model-atmosphere limits."),
("P015","1955ApJ...121..161S","analytic_theory","IMF","Original single-slope stellar initial mass function over its calibrated mass range."),
("P016","2001MNRAS.322..231K","calibration","IMF","Multi-part Galactic-field IMF; low-mass normalization affects stellar mass-to-light ratios."),
("P017","2003PASP..115..763C","calibration","IMF","Lognormal/power-law Galactic IMF calibration."),
("P018","2010Natur.468..940V","measurement","IMF-sensitive spectra","Gravity-sensitive absorption in massive ellipticals; abundance-response degeneracy applies."),
("P019","2012ApJ...760...70V","measurement","IMF-sensitive spectra","Expanded IMF-sensitive spectral analysis of early-type galaxies."),
("P020","2012Natur.484..485C","measurement","dynamical IMF","ATLAS3D dynamical mass-to-light ratios interpreted as systematic IMF variation."),
("P021","2010ApJ...709.1195T","measurement","lensing IMF","Strong-lensing plus dynamics constraints on early-type galaxy IMF normalization."),
("P022","1989ApJ...345..245C","calibration","dust extinction","Parameterized Milky Way extinction law and R_V dependence; screen extinction, not universal attenuation."),
("P023","2001PASP..113.1449C","supporting_review","dust attenuation","Review of empirical starburst attenuation and UV-through-IR diagnostics."),
("P024","2000ApJ...539..718C","analytic_theory","dust attenuation","Two-component birth-cloud plus diffuse-ISM attenuation model."),
("P025","1984ApJ...285...89D","analytic_theory","dust grains","Graphite/silicate grain optical properties used in extinction and emission models."),
("P026","2007ApJ...657..810D","calibration","dust emission","PAH and starlight-intensity dust-emission templates."),
("P027","2008MNRAS.388.1595D","calibration","energy-balance SED fitting","MAGPHYS UV-optical attenuation plus IR energy-balance framework."),
("P028","1998ARA&A..36..189K","supporting_review","SFR calibration","Review of star-formation diagnostics and IMF/timescale dependencies."),
("P029","2003ApJS..149..289B","measurement","stellar masses","Color-mass-to-light relations and stellar masses for local galaxies."),
("P030","2003MNRAS.341...33K","measurement","stellar masses/ages","SDSS spectral indices and Bayesian stellar population inference."),
("P031","2004MNRAS.351.1151B","measurement","SFR inference","SDSS star-formation rates with aperture, dust, and emission-line modeling assumptions."),
("P032","2007ApJS..173..267S","measurement","UV SFR/SED fitting","GALEX-SDSS UV-optical SED fits for star formation and dust."),
("P033","2009MNRAS.400.1181Z","calibration","resolved mass maps","Optical/NIR color-to-M/L prescriptions and TP-AGB sensitivity."),
("P034","2010ApJ...722L..64K","measurement","TP-AGB tests","Post-starburst galaxy spectra testing TP-AGB-heavy SPS predictions."),
("P035","2006MNRAS.365...46O","calibration","nonparametric SFH","STECKMAP full-spectrum recovery with regularization and degeneracies."),
("P036","2007MNRAS.381.1252T","calibration","nonparametric SFH","VESPA recovery of star-formation and metallicity histories from spectra."),
("P037","2005MNRAS.358..363C","calibration","full-spectrum fitting","STARLIGHT spectral synthesis for composite populations."),
("P038","1994ApJS...95..107W","calibration","age-metallicity degeneracy","SSP colors and indices establishing the optical age-metallicity degeneracy."),
("P039","2003MNRAS.339..897T","calibration","abundance-sensitive indices","SSP absorption-line models with variable alpha/Fe."),
("P040","2007ApJS..171..146S","calibration","spectral indices","Optical population models with abundance-sensitive Lick indices."),
("P041","1999ApJ...521...64M","measurement","IRX-beta","UV slope versus infrared excess for starbursts; not universal for all galaxies."),
("P042","2001MNRAS.323..887C","calibration","nebular emission","Coupled stellar-population and photoionization models for galaxy emission lines."),
]
(A/'scratch/review_base10_source_seeds.json').write_text(json.dumps([{'key':k,'bibcode':b,'role':r,'review_locator':loc,'boundary':bd} for k,b,r,loc,bd in seeds],indent=2)+"\n")
print(json.dumps({'seeds':len(seeds),'primary':sum(r!='supporting_review' for _,_,r,_,_ in seeds),'supporting':sum(r=='supporting_review' for _,_,r,_,_ in seeds)}))
