import hashlib,json,re
from pathlib import Path
A=Path("/Users/duhokim/NebulaMind/NebulaMind/.hermes/handoffs/galaxy-evolution/wiki-expansion-20260715"); P=A/"area_review_08_tumlinson_peeples_werk_2017_DR_PACKET.md"; R=A/"area_review_08_tumlinson_peeples_werk_2017_DR_RAW_PACKET.md"; G=A/"area_review_08_tumlinson_peeples_werk_2017_CURATED_SOURCE_REGISTRY.json"; O=A/"area_review_08_tumlinson_peeples_werk_2017_VALIDATION.json"
s=P.read_text();g=json.loads(G.read_text());f=[]
def ck(n,x,d):
 if not x:f.append({"check":n,"detail":d})
c=g["counts"];ck("registry_status",g["status"]=="PASS_COMPOSITE_IDS_AND_REVIEW_MEMBERSHIP",g["status"]);ck("source_counts",(c["usable_primary_sources"],c["usable_supporting_reviews"],c["quarantined_sources"])==(67,1,5),c)
actual=(len(re.findall(r"\| REV08-E\d{2} \|",s)),len(re.findall(r"\| REV08-D\d{2} \|",s)),len(re.findall(r"\| REV08-N\d{2} \|",s)),len(re.findall(r"\| REV08-U\d{2} \|",s)));ck("claim_counts",actual==(14,8,8,6),actual)
claim=s[s.index("## 2."):s.index("## 6.")];refs=set(re.findall(r"\[(REV08-P\d{3})\]",claim));usable={x["key"] for x in g["sources"] if x["source_status"]=="PASS"};q={x["key"] for x in g["sources"] if x["source_status"]!="PASS"};ck("claim_refs_resolve",refs<=usable,sorted(refs-usable));ck("quarantine_not_load_bearing",not refs&q,sorted(refs&q))
h=s[s.index("## 6."):s.index("## 7.")];l=s[s.index("## 8."):];ck("harvest_primary",len(re.findall(r"^\[REV08-P\d{3}\].*role=(?!supporting_review)",h,re.M))==67,"primary rows");ck("harvest_supporting",len(re.findall(r"^\[REV08-P\d{3}\].*role=supporting_review",h,re.M))==1,"support rows");ck("ledger_rows",len(re.findall(r"^\[REV08-(?:R00|P\d{3})\]",l,re.M))==69,"review plus 68 usable");ck("ledger_complete",all(f"[{k}]" in l for k in usable),"usable absent");ck("identity",all(x in s for x in ["10.1146/annurev-astro-091916-055240","1709.09180","2017ARA&A..55..389T"]),"review IDs");ck("raw_hash",hashlib.sha256(R.read_bytes()).hexdigest() in s,"raw hash");ck("terminal",s.rstrip().endswith("REVIEW_BASE_08_DR_COMPLETE_REFERENCE_ONLY"),"marker");ck("temporal",all(x["year"]<=2017 for x in g["sources"] if x["source_status"]=="PASS"),"post-2017 usable");ck("dnu","UNCITED_NOT_USABLE" in s and all(f"[{k}]" in s[s.index("## 7."):s.index("## 8.")] for k in q),"quarantine coverage")
status="PASS" if not f else "FAIL";o={"status":status,"failed_checks":f,"packet_sha256":hashlib.sha256(P.read_bytes()).hexdigest(),"raw_packet_sha256":hashlib.sha256(R.read_bytes()).hexdigest(),"registry_sha256":hashlib.sha256(G.read_bytes()).hexdigest(),"counts":{"established":14,"debates":8,"measurements":8,"unknowns":6,"usable_primary":67,"supporting_reviews":1,"quarantined":5,"claim_source_keys":len(refs),"ledger_rows":69}};O.write_text(json.dumps(o,indent=2,sort_keys=True)+"\n");print(json.dumps(o,sort_keys=True));raise SystemExit(0 if status=="PASS" else 1)
