"""add_debate_fields_to_claims

Revision ID: 335ff7dd8fb0
Revises: 46e495d6d0cc
Create Date: 2026-04-07 14:47:06.661435
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '335ff7dd8fb0'
down_revision: Union[str, None] = '46e495d6d0cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('claim_type', sa.String(length=20), server_default='established', nullable=False))
    op.add_column('claims', sa.Column('debate_topic', sa.String(length=200), nullable=True))
    op.add_column('claims', sa.Column('debate_stance', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claims', 'debate_stance')
    op.drop_column('claims', 'debate_topic')
    op.drop_column('claims', 'claim_type')
    # ### end Alembic commands ###
