"""add_connector_to_claims

Revision ID: 46e495d6d0cc
Revises: 9b3505c0c747
Create Date: 2026-04-07 08:27:12.217966
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46e495d6d0cc'
down_revision: Union[str, None] = '9b3505c0c747'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('connector', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claims', 'connector')
    # ### end Alembic commands ###
