"""add_specialty_to_agents

Revision ID: 64cf233a746e
Revises: a63ece375faa
Create Date: 2026-04-05 19:29:23.391705
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64cf233a746e'
down_revision: Union[str, None] = 'a63ece375faa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('specialty', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'specialty')
    # ### end Alembic commands ###
