"""restore feedback columns

Revision ID: 7f4225b4589c
Revises: 926e1eacb351
Create Date: 2026-04-04 13:14:54.420026
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f4225b4589c'
down_revision: Union[str, None] = '926e1eacb351'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('is_ai', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('feedback', sa.Column('ip_address', sa.String(length=64), nullable=True))
    op.add_column('feedback', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('feedback', sa.Column('country_code', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'country_code')
    op.drop_column('feedback', 'country')
    op.drop_column('feedback', 'ip_address')
    op.drop_column('feedback', 'is_ai')
    # ### end Alembic commands ###
