"""add_hero_fields_to_wiki_pages

Revision ID: 82b87ab5e7b0
Revises: 0507d2ffed2b
Create Date: 2026-04-06 23:41:10.099492
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82b87ab5e7b0'
down_revision: Union[str, None] = '0507d2ffed2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wiki_pages', sa.Column('hero_tagline', sa.Text(), nullable=True))
    op.add_column('wiki_pages', sa.Column('hero_facts', sa.Text(), nullable=True))
    op.add_column('wiki_pages', sa.Column('did_you_know', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wiki_pages', 'did_you_know')
    op.drop_column('wiki_pages', 'hero_facts')
    op.drop_column('wiki_pages', 'hero_tagline')
    # ### end Alembic commands ###
