"""add_is_featured_to_wiki_pages

Revision ID: 88bf2930ed07
Revises: d3e4f5a6b7c8
Create Date: 2026-04-05 20:01:00.242366
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88bf2930ed07'
down_revision: Union[str, None] = 'd3e4f5a6b7c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wiki_pages', sa.Column('is_featured', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wiki_pages', 'is_featured')
    # ### end Alembic commands ###
