"""add ip and country to feedback

Revision ID: 8cad1e41bafd
Revises: eba20def18d0
Create Date: 2026-04-04 11:06:59.401644
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cad1e41bafd'
down_revision: Union[str, None] = 'eba20def18d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('ip_address', sa.String(length=64), nullable=True))
    op.add_column('feedback', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('feedback', sa.Column('country_code', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'country_code')
    op.drop_column('feedback', 'country')
    op.drop_column('feedback', 'ip_address')
    # ### end Alembic commands ###
