"""add_cards_metadata_fields

Revision ID: 90dbee74b13f
Revises: 88bf2930ed07
Create Date: 2026-04-06 17:44:54.020592
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90dbee74b13f'
down_revision: Union[str, None] = '88bf2930ed07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wiki_pages', sa.Column('category', sa.String(length=30), nullable=True))
    op.add_column('wiki_pages', sa.Column('difficulty', sa.String(length=20), nullable=True))
    op.add_column('wiki_pages', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('wiki_pages', sa.Column('thumbnail_emoji', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wiki_pages', 'thumbnail_emoji')
    op.drop_column('wiki_pages', 'summary')
    op.drop_column('wiki_pages', 'difficulty')
    op.drop_column('wiki_pages', 'category')
    # ### end Alembic commands ###
