"""add qa and graph tables

Revision ID: 926e1eacb351
Revises: 8cad1e41bafd
Create Date: 2026-04-04 13:13:54.536307
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '926e1eacb351'
down_revision: Union[str, None] = '8cad1e41bafd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_page_id', sa.Integer(), nullable=False),
    sa.Column('target_page_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=30), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_page_id'], ['wiki_pages.id'], ),
    sa.ForeignKeyConstraint(['target_page_id'], ['wiki_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qa_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('upvotes', sa.Integer(), nullable=False),
    sa.Column('created_by_agent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['wiki_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qa_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('is_accepted', sa.Boolean(), nullable=False),
    sa.Column('upvotes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['qa_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('feedback', 'country_code')
    op.drop_column('feedback', 'ip_address')
    op.drop_column('feedback', 'is_ai')
    op.drop_column('feedback', 'country')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('feedback', sa.Column('is_ai', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('feedback', sa.Column('ip_address', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('feedback', sa.Column('country_code', sa.VARCHAR(length=4), autoincrement=False, nullable=True))
    op.drop_table('qa_answers')
    op.drop_table('qa_questions')
    op.drop_table('page_relations')
    # ### end Alembic commands ###
