"""add claim_edit_proposals

Revision ID: 9b3505c0c747
Revises: 82b87ab5e7b0
Create Date: 2026-04-07 08:20:24.687208
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b3505c0c747'
down_revision: Union[str, None] = '82b87ab5e7b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_edit_proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('new_text', sa.Text(), nullable=False),
    sa.Column('arxiv_evidence', sa.String(length=50), nullable=False),
    sa.Column('evidence_summary', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('votes_approve', sa.Integer(), nullable=False),
    sa.Column('votes_reject', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_edit_proposals_claim_id'), 'claim_edit_proposals', ['claim_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claim_edit_proposals_claim_id'), table_name='claim_edit_proposals')
    op.drop_table('claim_edit_proposals')
    # ### end Alembic commands ###
