"""add is_ai to feedback

Revision ID: eba20def18d0
Revises: 394dc3ce2da0
Create Date: 2026-04-04 10:25:37.576255
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eba20def18d0'
down_revision: Union[str, None] = '394dc3ce2da0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('is_ai', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'is_ai')
    # ### end Alembic commands ###
