import re

with open('/Users/duhokim/NebulaMind/NebulaMind/.hermes/handoffs/weekend-video-sextet-20260808T0136K/prereg/_successor_build_20260824/gates/SECTION6_DRAFT_AGY_R8B.md', 'r') as f:
    content = f.read()

# 1. Heading
content = content.replace(
    '# §6 DRAFT — AGY SEAT, EIGHTH PASS REPAIR B (R8B), 2026-08-27',
    '# §6 DRAFT — AGY SEAT, NINTH PASS (R9), 2026-08-27'
)

# 2. Status
old_status = 'Status: DRAFT FOR REFEREE. Written under `BRIEF_DRAFT_SECTION6_R8B.md`, performing a targeted repair pass to make the route-(b) prose decidable and fix the temporally false BS-5f claim. BS-2a findings remain UNRESOLVED.'
new_status = "Status: DRAFT FOR REFEREE. Written under `BRIEF_DRAFT_SECTION6_R9.md`. Normatively, only Row P's operational threshold handling and calibration applicability rules changed; the remaining diffs are the R9 metadata and explanatory updates. BS-2a findings remain UNRESOLVED."
content = content.replace(old_status, new_status)

# 3. Row P
old_row_p = """| P | **Verdict path** | **post-unblinding only**: reads the real χ vector via a **pinned post-unblinding exact-parent join** against the independently fixed attempt set governed by the BS-2a design digest, using `brickid` and `objid` as fixed join keys. **Silent inner-join loss is forbidden.** Row P assigns exactly one fixed consequence to every attempt in a closed set of states, applied in this precedence order: (1) zero records (emits `INCONCLUSIVE-BY-MISSING-RECORD`), (2) duplicate records — more than one measurement for a parent is unconditional refusal (`INCONCLUSIVE-BY-DUPLICATE`), (3) extra records (`INCONCLUSIVE-BY-ORPHAN`), (4) malformed records (`INCONCLUSIVE-BY-MALFORMED`), (5) absent measurement (dropped; `EXCLUDED-BY-ABSENCE`), (6) non-finite measurement (dropped; `EXCLUDED-BY-NONFINITE`), (7) low confidence (dropped; `EXCLUDED-BY-CONFIDENCE`), (8) accepted-finite. **No discretionary retry.** This exact set-equality closure produces the canonical **post-unblinding adequacy receipt**, binding the parent-set digest, old BS-2f mask digest, complete terminal-state partition, final-mask digest, calibration applicability, Stage-C inputs/result, protocol digest, and verifier result. Any post-unblinding removal deterministically forces re-evaluation of locked adequacy predicates: if a removal takes out an allocated committee member, it unconditionally emits `INCONCLUSIVE-BY-CALIBRATION` (frozen recalculation is forbidden). Other predicates: calibration fails if any per-bin accuracy lower bound `a_LB_b < 0.85` (`../PREREG_SUCCESSOR_DRAFT_V15_20260827.md` lines 566–567, `../ref/successor_ref_v9.py` line 81) (`INCONCLUSIVE-BY-CALIBRATION`); power fails if the re-run Stage C yields fewer than 962 passing trials out of 1,000 (`../ref/successor_ref_v9.py` lines 77–78) (`INCONCLUSIVE-BY-POWER`). If post-unblinding attrition means the 962/1,000 criterion cannot be applied as written (e.g., because the trial structure differs), this is a stated gap requiring a defined post-attrition threshold rather than a substituted number. | P8, after unblinding | the unblinding receipt and a verified BS-L | the **post-unblinding adequacy receipt**, then BS-7f, then BS-V | any execution before unblinding; any verdict produced outside this symbol; missing/duplicate/extra/malformed records; **silent inner-join loss; discretionary retry** |"""

new_row_p = """| P | **Verdict path** | **post-unblinding only**: reads the real χ vector via a **pinned post-unblinding exact-parent join** against the independently fixed attempt set governed by the BS-2a design digest, using `brickid` and `objid` as fixed join keys. **Silent inner-join loss is forbidden.** Row P assigns exactly one fixed consequence to every attempt in a closed set of states, applied in this precedence order: (1) zero records (emits `INCONCLUSIVE-BY-MISSING-RECORD`), (2) duplicate records — more than one measurement for a parent is unconditional refusal (`INCONCLUSIVE-BY-DUPLICATE`), (3) extra records (`INCONCLUSIVE-BY-ORPHAN`), (4) malformed records (`INCONCLUSIVE-BY-MALFORMED`), (5) absent measurement (dropped; `EXCLUDED-BY-ABSENCE`), (6) non-finite measurement (dropped; `EXCLUDED-BY-NONFINITE`), (7) low confidence (dropped; `EXCLUDED-BY-CONFIDENCE`), (8) accepted-finite. **No discretionary retry.** This exact set-equality closure produces the canonical **post-unblinding adequacy receipt**, binding the parent-set digest, old BS-2f mask digest, complete terminal-state partition, final-mask digest, calibration applicability, Stage-C inputs/result, protocol digest, and verifier result. Any post-unblinding removal deterministically forces re-evaluation of locked adequacy predicates: if a removal takes out an allocated committee member, it unconditionally emits `INCONCLUSIVE-BY-CALIBRATION` (frozen recalculation is forbidden). Other predicates: calibration fails if any per-bin accuracy lower bound `a_LB_b < 0.85` (`../PREREG_SUCCESSOR_DRAFT_V15_20260827.md` lines 566–567, `../ref/successor_ref_v9.py` line 81) (`INCONCLUSIVE-BY-CALIBRATION`); for non-committee attrition, calibration applicability must be established by a frozen predicate, and because this predicate does not exist in the frozen record, any non-committee attrition fails closed to `INCONCLUSIVE-BY-CALIBRATION`. Power fails if the re-run Stage C yields fewer than 962 passing trials out of 1,000 (`../ref/successor_ref_v9.py` lines 77–78) (`INCONCLUSIVE-BY-POWER`). If post-unblinding attrition means the exact 962/1,000 criterion cannot be applied as written (e.g., because the trial structure differs), the run emits `INCONCLUSIVE-BY-POWER`. This consequence is fixed before any real χ is read, citing V15 lines 570–573 which void any post-first-real-χ change to a decision threshold. | P8, after unblinding | the unblinding receipt and a verified BS-L | the **post-unblinding adequacy receipt**, then BS-7f, then BS-V | any execution before unblinding; any verdict produced outside this symbol; missing/duplicate/extra/malformed records; **silent inner-join loss; discretionary retry** |"""
content = content.replace(old_row_p, new_row_p)

# 4. Part 2, Item 4
old_item_4 = """4. **Verdict Path (Row P) Post-Unblinding Consequence:** Define the deterministic rule: Row P must execute an exact set-equality join against the pinned attempt-set identity governed by the BS-2a design digest, using `brickid` and `objid` as fixed join keys, and produce the canonical post-unblinding adequacy receipt. This process assigns explicit precedence states to every attempt: zero records, duplicate records, extra records, or malformed records trigger an unconditional refusal; absent, non-finite, and low-confidence measurements are dropped; all others are accepted-finite. If any removal alters the mask, Row P deterministically re-evaluates calibration (including a strict block on removing any allocated committee member) and Stage-C power under locked predicates, issuing the post-unblinding adequacy receipt or emitting a defined `INCONCLUSIVE-BY-*` refusal."""

new_item_4 = """4. **Verdict Path (Row P) Post-Unblinding Consequence:** Define the deterministic rule: Row P must execute an exact set-equality join against the pinned attempt-set identity governed by the BS-2a design digest, using `brickid` and `objid` as fixed join keys, and produce the canonical post-unblinding adequacy receipt. This process assigns explicit precedence states to every attempt: zero records, duplicate records, extra records, or malformed records trigger an unconditional refusal; absent, non-finite, and low-confidence measurements are dropped; all others are accepted-finite. If any removal alters the mask, Row P deterministically re-evaluates calibration (including a strict block on removing any allocated committee member, and failing closed to `INCONCLUSIVE-BY-CALIBRATION` for any non-committee attrition due to the lack of a frozen applicability predicate) and Stage-C power under locked predicates, issuing the post-unblinding adequacy receipt or emitting a defined `INCONCLUSIVE-BY-*` refusal. If the exact frozen 962/1,000 power criterion cannot be applied, it deterministically emits `INCONCLUSIVE-BY-POWER`."""
content = content.replace(old_item_4, new_item_4)

# 5. Part 3, C2
old_c2 = """- **C2 — Carrying fixed thresholds from the frozen record.** Rather than composing numeric thresholds for post-unblinding adequacy gates, we recorded the exact values inherited from the frozen record. The calibration failure threshold (any `a_LB_b < 0.85`) is carried from `../PREREG_SUCCESSOR_DRAFT_V15_20260827.md` lines 566–567 and `../ref/successor_ref_v9.py` line 81. The Stage C power failure threshold (< 962 passing trials out of 1,000) is carried from `../ref/successor_ref_v9.py` lines 77–78. Alternative: Invent decision thresholds for the missing gaps (like post-attrition Stage C power). We chose to cite the frozen record and state explicit gaps where they exist, because inventing numbers renames a finding."""

new_c2 = """- **C2 — Carrying fixed thresholds and failing closed from the frozen record.** Rather than composing numeric thresholds for post-unblinding adequacy gates, we recorded the exact values inherited from the frozen record. The calibration failure threshold (any `a_LB_b < 0.85`) is carried from `../PREREG_SUCCESSOR_DRAFT_V15_20260827.md` lines 566–567 and `../ref/successor_ref_v9.py` line 81. For non-committee attrition, calibration applicability fails closed because the needed applicability predicate is missing from the frozen record. The Stage C power failure threshold (< 962 passing trials out of 1,000) is carried from `../ref/successor_ref_v9.py` lines 77–78. Alternative: Invent decision thresholds for the missing gaps (like post-attrition Stage C power or calibration applicability). We chose to cite the frozen record and assign fail-closed terminal consequences (`INCONCLUSIVE-BY-POWER` and `INCONCLUSIVE-BY-CALIBRATION`) where the frozen criteria cannot be applied, because V15 lines 570–573 void any post-first-real-χ change to a decision threshold, and inventing numbers renames a finding."""
content = content.replace(old_c2, new_c2)

# 6. Part 5, new findings
new_findings = """
8. **R9 Defect 1 — The stated post-attrition power "gap" has no terminal consequence.** REPAIR. Row P now deterministically emits `INCONCLUSIVE-BY-POWER` if the exact frozen 962/1,000 criterion cannot be applied. The text explicitly cites V15 lines 570–573 to explain that this consequence must be fixed before any real χ is read.
9. **R9 Defect 2 — `calibration applicability` is undefined for non-committee attrition.** REPAIR. Row P now explicitly states that calibration applicability for non-committee attrition relies on a frozen predicate, and because this predicate is missing from the frozen record, any non-committee attrition fails closed to `INCONCLUSIVE-BY-CALIBRATION`.
10. **R9 Defect 3 — A false claim about your own diff.** REPAIR. The status line and explanatory prose have been updated to accurately reflect that only threshold handling and calibration applicability changed normatively in this pass, while the remaining diffs are metadata and explanatory prose updates."""

content += new_findings + '\n'

with open('/Users/duhokim/NebulaMind/NebulaMind/.hermes/handoffs/weekend-video-sextet-20260808T0136K/prereg/_successor_build_20260824/gates/SECTION6_DRAFT_AGY_R9.md', 'w') as f:
    f.write(content)
