# -*- coding: utf-8 -*-
import re

with open('SECTION6_DRAFT_AGY_R10B.md', 'r', encoding='utf-8') as f:
    content = f.read()

# 1. Update title/status
content = content.replace('# §6 DRAFT — AGY SEAT, TENTH PASS (R10), 2026-08-27', '# §6 DRAFT — AGY SEAT, ELEVENTH PASS (R11), 2026-08-27')
content = content.replace('Written under `BRIEF_DRAFT_SECTION6_R10B.md`', 'Written under `BRIEF_DRAFT_SECTION6_R11.md`')
content = content.replace('and the Stage C power inapplicability branch was deleted, replacing it with a strict `VOID` for any deviation from the 1,000-trial protocol.', 'and the Stage C power branch was deleted from Row P, keeping the `< 962/1,000 → INCONCLUSIVE-BY-POWER` decision pre-unblinding in Row J.')

# 2. Row J modifications:
old_row_j = '| J | **Stage-C runner** | reads the sealed BS-2f mask (χ-free) and the BS-8f aggregates; injects synthetic signs only — **never reads a real χ**. BS-5f certifies **only** the locked pre-attrition BS-2f population and is **insufficient** for a changed final mask. (Post-unblinding attrition requires a separately named post-unblinding adequacy receipt under Row P.) → writes the Stage-C receipt | P5, before BS-L | BS-2f and BS-8f | BS-5f | reading any real χ; continuing the run after a Stage-C FAIL |'

new_row_j = '| J | **Stage-C runner** | reads the sealed BS-2f mask (χ-free) and the BS-8f aggregates; injects synthetic signs only — **never reads a real χ**. BS-5f certifies **only** the locked pre-attrition BS-2f population and is **insufficient** for a changed final mask. (Post-unblinding attrition requires a separately named post-unblinding adequacy receipt under Row P.) **If the locked Stage C yields fewer than 962 passing trials out of 1,000 (`../ref/successor_ref_v9.py` lines 77–78), it emits `INCONCLUSIVE-BY-POWER` and halts the run.** → writes the Stage-C receipt | P5, before BS-L | BS-2f and BS-8f | BS-5f | reading any real χ; continuing the run after a Stage-C FAIL |'
content = content.replace(old_row_j, new_row_j)


# 3. Row P modifications:
old_row_p = '| P | **Verdict path** | **post-unblinding only**: reads the real χ vector via a **pinned post-unblinding exact-parent join** against the independently fixed attempt set governed by the BS-2a design digest, using `brickid` and `objid` as fixed join keys. **Silent inner-join loss is forbidden.** Row P assigns exactly one fixed consequence to every attempt in a closed set of states, applied in this precedence order: (1) zero records (emits `INCONCLUSIVE-BY-MISSING-RECORD`), (2) duplicate records — more than one measurement for a parent is unconditional refusal (`INCONCLUSIVE-BY-DUPLICATE`), (3) extra records (`INCONCLUSIVE-BY-ORPHAN`), (4) malformed records (`INCONCLUSIVE-BY-MALFORMED`), (5) absent measurement (dropped; `EXCLUDED-BY-ABSENCE`), (6) non-finite measurement (dropped; `EXCLUDED-BY-NONFINITE`), (7) low confidence (dropped; `EXCLUDED-BY-CONFIDENCE`), (8) accepted-finite. **No discretionary retry.** This exact set-equality closure produces the canonical **post-unblinding adequacy receipt**, binding the parent-set digest, old BS-2f mask digest, complete terminal-state partition, final-mask digest, calibration applicability, Stage-C inputs/result, protocol digest, and verifier result. **Adequacy decisions follow an ordered tree:** First, calibration applicability: any post-unblinding removal immediately emits `INCONCLUSIVE-BY-CALIBRATION` and **no Stage-C rerun is performed**. Second, calibration accuracy: if the per-bin accuracy lower bound `a_LB_b < 0.85` (`../PREREG_SUCCESSOR_DRAFT_V15_20260827.md` lines 566–567, `../ref/successor_ref_v9.py` line 81), the run emits `INCONCLUSIVE-BY-CALIBRATION`. Third, Stage C power: if the locked Stage C yields fewer than 962 passing trials out of 1,000 (`../ref/successor_ref_v9.py` lines 77–78), it emits `INCONCLUSIVE-BY-POWER`. Any deviation from the pinned 1,000-trial protocol or the frozen Stage-C implementation terminates `VOID`. These consequences are fixed before any real χ is read, citing V15 lines 570–573 which void any post-first-real-χ change to a decision threshold. | P8, after unblinding | the unblinding receipt and a verified BS-L | the **post-unblinding adequacy receipt**, then BS-7f, then BS-V | any execution before unblinding; any verdict produced outside this symbol; **silent inner-join loss; discretionary retry; any deviation from the pinned 1,000-trial protocol or the frozen Stage-C implementation** |'

new_row_p = '| P | **Verdict path** | **post-unblinding only**: reads the real χ vector via a **pinned post-unblinding exact-parent join** against the independently fixed attempt set governed by the BS-2a design digest, using `brickid` and `objid` as fixed join keys. **Silent inner-join loss is forbidden.** Row P assigns exactly one fixed consequence to every attempt in a closed set of states, applied in this precedence order: (1) zero records (emits `INCONCLUSIVE-BY-MISSING-RECORD`), (2) duplicate records — more than one measurement for a parent is unconditional refusal (`INCONCLUSIVE-BY-DUPLICATE`), (3) extra records (`INCONCLUSIVE-BY-ORPHAN`), (4) malformed records (`INCONCLUSIVE-BY-MALFORMED`), (5) absent measurement (dropped; `EXCLUDED-BY-ABSENCE`), (6) non-finite measurement (dropped; `EXCLUDED-BY-NONFINITE`), (7) low confidence (dropped; `EXCLUDED-BY-CONFIDENCE`), (8) accepted-finite. **No discretionary retry.** This exact set-equality closure produces the canonical **post-unblinding adequacy receipt**, binding the parent-set digest, old BS-2f mask digest, complete terminal-state partition, final-mask digest, calibration applicability, the already-verified locked Stage-C PASS, protocol digest, and verifier result. (The adequacy receipt must not branch on a Stage-C FAIL that BS-L excludes.) **Adequacy decisions follow an ordered tree:** First, calibration applicability: any post-unblinding removal immediately emits `INCONCLUSIVE-BY-CALIBRATION` and **no Stage-C rerun is performed**. Second, calibration accuracy: if the per-bin accuracy lower bound `a_LB_b < 0.85` (`../PREREG_SUCCESSOR_DRAFT_V15_20260827.md` lines 566–567, `../ref/successor_ref_v9.py` line 81), the run emits `INCONCLUSIVE-BY-CALIBRATION`. These consequences are fixed before any real χ is read, citing V15 lines 570–573 which void any post-first-real-χ change to a decision threshold. | P8, after unblinding | the unblinding receipt and a verified BS-L | the **post-unblinding adequacy receipt**, then BS-7f, then BS-V | any execution before unblinding; any verdict produced outside this symbol; **silent inner-join loss; discretionary retry** |'
content = content.replace(old_row_p, new_row_p)

# 4. Part 2 Item 4:
old_p2_item4 = '4. **Verdict Path (Row P) Post-Unblinding Consequence:** Define the deterministic rule: Row P must execute an exact set-equality join against the pinned attempt-set identity governed by the BS-2a design digest, using `brickid` and `objid` as fixed join keys, and produce the canonical post-unblinding adequacy receipt. This process assigns explicit precedence states to every attempt: zero records, duplicate records, extra records, or malformed records trigger an unconditional refusal; absent, non-finite, and low-confidence measurements are dropped; all others are accepted-finite. Adequacy decisions follow an ordered tree: First, calibration applicability: any post-unblinding removal immediately emits `INCONCLUSIVE-BY-CALIBRATION` and **no Stage-C rerun is performed**. Second, calibration accuracy: failure of the per-bin accuracy lower bound (`a_LB_b < 0.85`) emits `INCONCLUSIVE-BY-CALIBRATION`. Third, Stage C power: yielding fewer than 962/1,000 passing trials emits `INCONCLUSIVE-BY-POWER`. Any deviation from the pinned 1,000-trial protocol or the frozen Stage-C implementation terminates `VOID`.'

new_p2_item4 = '4. **Verdict Path (Row P) Post-Unblinding Consequence:** Define the deterministic rule: Row P must execute an exact set-equality join against the pinned attempt-set identity governed by the BS-2a design digest, using `brickid` and `objid` as fixed join keys, and produce the canonical post-unblinding adequacy receipt. This process assigns explicit precedence states to every attempt: zero records, duplicate records, extra records, or malformed records trigger an unconditional refusal; absent, non-finite, and low-confidence measurements are dropped; all others are accepted-finite. Adequacy decisions follow an ordered tree: First, calibration applicability: any post-unblinding removal immediately emits `INCONCLUSIVE-BY-CALIBRATION` and **no Stage-C rerun is performed**. Second, calibration accuracy: failure of the per-bin accuracy lower bound (`a_LB_b < 0.85`) emits `INCONCLUSIVE-BY-CALIBRATION`.'
content = content.replace(old_p2_item4, new_p2_item4)

# 5. Part 3 C1:
old_p3_c1 = '- **C1 — Refusing to build a pre-lock execution supervisor for reason (c).** The brief allowed either building a mechanically sound execution supervisor for instrument presence/finiteness, or refusing/deferring reason (c) entirely. Alternative: Build the execution supervisor. We chose to REFUSE reason (c) pre-lock because building a sealed supervisor transaction is a massive expansion of scope and mechanism. The cost is that we lock a mask that may contain objects whose instrument outputs are non-finite, relying on the post-unblinding confidence cut consequence (recomputing power and potentially failing the verdict) instead of structurally excluding them early.'

new_p3_c1 = '- **C1 — Refusing to build a pre-lock execution supervisor for reason (c).** The brief allowed either building a mechanically sound execution supervisor for instrument presence/finiteness, or refusing/deferring reason (c) entirely. Alternative: Build the execution supervisor. We chose to REFUSE reason (c) pre-lock because building a sealed supervisor transaction is a massive expansion of scope and mechanism. The cost is that we lock a mask that may contain objects whose instrument outputs are non-finite, relying on the post-unblinding confidence cut consequence (any post-unblinding removal emits `INCONCLUSIVE-BY-CALIBRATION` **without rerunning Stage C**) instead of structurally excluding them early.'
content = content.replace(old_p3_c1, new_p3_c1)


# Part 3 C2
old_p3_c2 = 'The Stage C power failure threshold (< 962 passing trials out of 1,000) is carried from `../ref/successor_ref_v9.py` lines 77–78. Alternative: Maintain an `INCONCLUSIVE-BY-POWER` branch for cases where the power criterion is inapplicable (e.g. if the trial count changes). We chose to delete the inapplicability branch entirely and apply the pinned `< 962` rule alone, because lines 1275–1277 of the frozen code only admit a trial count exactly equal to `N_TRIALS = 1000`. No lawful state exists where the count differs without a protocol breach. Any deviation from the pinned 1,000-trial protocol or the frozen Stage-C implementation is a departure from the frozen protocol, and V15 lines 570–573 make any post-first-real-χ deviation from a binding rule `VOID`, not inconclusive. Emitting a softer terminal state for a protocol breach would be the document excusing its own violation. For calibration applicability, we cite the frozen record and assign `INCONCLUSIVE-BY-CALIBRATION` where the frozen criteria cannot be applied, because inventing numbers renames a finding.'
new_p3_c2 = 'The Stage C power failure threshold (< 962 passing trials out of 1,000) is carried from `../ref/successor_ref_v9.py` lines 77–78, but evaluated pre-unblinding in Row J / BS-5f. Alternative: Maintain an `INCONCLUSIVE-BY-POWER` branch in Row P\'s post-unblinding adequacy tree for cases where the power criterion is inapplicable (e.g. if the trial count changes). We chose to delete the Stage-C power branch from Row P entirely and keep the decision strictly pre-unblinding in Row J, because Row P requires a verified BS-L, which requires BS-5f\'s PASS. Row J forbids continuing after a Stage-C FAIL, so a Row-P invocation can only ever inherit a locked Stage-C PASS. Therefore, any post-unblinding branch on a Stage-C FAIL is unreachable dead code. For calibration applicability, we cite the frozen record and assign `INCONCLUSIVE-BY-CALIBRATION` where the frozen criteria cannot be applied, because inventing numbers renames a finding.'
content = content.replace(old_p3_c2, new_p3_c2)

# 6. Part 5 finding 5:
old_p5_f5 = '5. **Defect 4 — The post-unblinding consequence of reason (c) and confidence cut.** REPAIR. Row I fails the run before BS-8f if any allocated object lacks a finite output. Row P executes an exact set-equality join against a pinned attempt set, assigns exact explicit terminal states with defined precedence, and produces a canonical post-unblinding adequacy receipt bound to the final parent accounting, terminal-state partition, re-evaluated Stage-C result, and final-mask digest. This formally replaces the temporally false claim about BS-5f and resolves the receipt seam.'
new_p5_f5 = '5. **Defect 4 — The post-unblinding consequence of reason (c) and confidence cut.** REPAIR. Row I fails the run before BS-8f if any allocated object lacks a finite output. Row P executes an exact set-equality join against a pinned attempt set, assigns exact explicit terminal states with defined precedence, and produces a canonical post-unblinding adequacy receipt bound to the final parent accounting, terminal-state partition, the **locked BS-5f Stage-C inputs/result**, and final-mask digest. This formally replaces the temporally false claim about BS-5f and resolves the receipt seam.'
content = content.replace(old_p5_f5, new_p5_f5)

# Append new findings
new_finding_17 = '\n17. **R11 Defect 1 — The Stage-C power branch in Row P is unreachable.** REPAIR. Deleted the Stage-C power branch from Row P\'s post-unblinding adequacy tree and Part 2 item 4. Kept the `< 962/1,000 → INCONCLUSIVE-BY-POWER` decision where it executes: pre-unblinding in Row J / BS-5f. The post-unblinding adequacy receipt now binds the already-verified locked PASS and protocol digest without branching on a FAIL that BS-L excludes.'
new_finding_18 = '\n18. **R11 Defect 2 — Two passages still assert the behaviour you removed.** REPAIR. Conformed Part 3 C1 to state that any post-unblinding removal emits `INCONCLUSIVE-BY-CALIBRATION` without rerunning Stage C. Conformed Part 5 finding 5 to state that the adequacy receipt binds the locked BS-5f Stage-C inputs/result.'
content = content + new_finding_17 + new_finding_18

with open('SECTION6_DRAFT_AGY_R11.md', 'w', encoding='utf-8') as f:
    f.write(content)

print("Modification complete.")
