import re

with open("SECTION6_DRAFT_AGY_R13.md", "r") as f:
    content = f.read()

# Replace Row J
old_j = r"\| J \| \*\*Stage-C runner\*\* \| reads the sealed BS-2f mask \(χ-free\) and the BS-8f aggregates; injects synthetic signs only — \*\*never reads a real χ\*\*\. \*\*Row J must verify exactly `N_TRIALS = 1_000` and the frozen Stage-C implementation/protocol digest \*before\* running or issuing BS-5f\.\*\* BS-5f binds that verification and certifies \*\*only\*\* the locked pre-attrition BS-2f population and is \*\*insufficient\*\* for a changed final mask\. \(Post-unblinding attrition requires a separately named post-unblinding adequacy receipt under Row P\.\) \*\*Any locked Stage-C FAIL emits `INCONCLUSIVE-BY-POWER` and halts the run, explicitly including \(a\) fewer than 962 of 1,000 passing trials \(`\.\./ref/successor_ref_v9\.py` lines 77–78\) and \(b\) the self-verification `refuted` or `nonconservative` fail-closed return at reference lines 1275–1276\. The complementary PASS branch is the sole route to BS-5f → BS-L\.\*\* → writes the Stage-C receipt \| P5, before BS-L \| BS-2f and BS-8f \| BS-5f \| reading any real χ; continuing the run after a Stage-C FAIL; \*\*any deviation from the pinned 1,000-trial protocol or the frozen Stage-C implementation\*\* \|"
new_j = "| J | **Stage-C runner** | reads the sealed BS-2f mask (χ-free) and the BS-8f aggregates; injects synthetic signs only — **never reads a real χ**. **Before running Stage C, Row J evaluates the calibration accuracy lower bound `a_LB_b < 0.85` from the BS-8f aggregate (V15 lines 566–567). If `a_LB_b < 0.85`, it emits `INCONCLUSIVE-BY-CALIBRATION` and halts the run pre-unblinding. On PASS, Row J must then verify exactly `N_TRIALS = 1_000` and the frozen Stage-C implementation/protocol digest *before* running or issuing BS-5f.** BS-5f binds that calibration PASS and verification, and certifies **only** the locked pre-attrition BS-2f population and is **insufficient** for a changed final mask. (Post-unblinding attrition requires a separately named post-unblinding adequacy receipt under Row P.) **Any locked Stage-C FAIL emits `INCONCLUSIVE-BY-POWER` and halts the run, explicitly including (a) fewer than 962 of 1,000 passing trials (`../ref/successor_ref_v9.py` lines 77–78) and (b) the self-verification `refuted` or `nonconservative` fail-closed return at reference lines 1275–1277. The complementary PASS branches are the sole route to BS-5f → BS-L.** → writes the Stage-C receipt | P5, before BS-L | BS-2f and BS-8f | BS-5f | reading any real χ; continuing the run after a calibration or Stage-C FAIL; **any deviation from the pinned 1,000-trial protocol or the frozen Stage-C implementation** |"

content = re.sub(old_j, new_j, content)

# Replace Row P
old_p = r"\| P \| \*\*Verdict path\*\* \| \*\*post-unblinding only\*\*: reads the real χ vector via a \*\*pinned post-unblinding exact-parent join\*\* against the independently fixed attempt set governed by the BS-2a design digest, using `brickid` and `objid` as fixed join keys\. \*\*Silent inner-join loss is forbidden\.\*\* Row P assigns exactly one fixed consequence to every attempt in a closed set of states, applied in this precedence order: \(1\) zero records \(emits `INCONCLUSIVE-BY-MISSING-RECORD`\), \(2\) duplicate records — more than one measurement for a parent is unconditional refusal \(`INCONCLUSIVE-BY-DUPLICATE`\), \(3\) extra records \(`INCONCLUSIVE-BY-ORPHAN`\), \(4\) malformed records \(`INCONCLUSIVE-BY-MALFORMED`\), \(5\) absent measurement \(dropped; `EXCLUDED-BY-ABSENCE`\), \(6\) non-finite measurement \(dropped; `EXCLUDED-BY-NONFINITE`\), \(7\) low confidence \(dropped; `EXCLUDED-BY-CONFIDENCE`\), \(8\) accepted-finite\. \*\*No discretionary retry\.\*\* This exact set-equality closure produces the canonical \*\*post-unblinding adequacy receipt\*\*, binding the parent-set digest, old BS-2f mask digest, complete terminal-state partition, final-mask digest, calibration applicability, the already-verified locked Stage-C PASS, protocol digest, and verifier result\. \(The adequacy receipt must not branch on a Stage-C FAIL that BS-L excludes\.\) \*\*Adequacy decisions follow an ordered tree:\*\* First, calibration applicability: any post-unblinding removal immediately emits `INCONCLUSIVE-BY-CALIBRATION` and \*\*no Stage-C rerun is performed\*\*\. Second, calibration accuracy: if the per-bin accuracy lower bound `a_LB_b < 0\.85` \(`\.\./PREREG_SUCCESSOR_DRAFT_V15_20260827\.md` lines 566–567, `\.\./ref/successor_ref_v9\.py` line 81\), the run emits `INCONCLUSIVE-BY-CALIBRATION`\. These consequences are fixed before any real χ is read, citing V15 lines 570–573 which void any post-first-real-χ change to a decision threshold\. \| P8, after unblinding \| the unblinding receipt and a verified BS-L \| the \*\*post-unblinding adequacy receipt\*\*, then BS-7f, then BS-V \| any execution before unblinding; any verdict produced outside this symbol; \*\*silent inner-join loss; discretionary retry\*\* \|"
new_p = "| P | **Verdict path** | **post-unblinding only**: reads the real χ vector via a **pinned post-unblinding exact-parent join** against the independently fixed attempt set governed by the BS-2a design digest, using `brickid` and `objid` as fixed join keys. **Silent inner-join loss is forbidden.** Row P assigns exactly one fixed consequence to every attempt in a closed set of states, applied in this precedence order: (1) zero records (emits `INCONCLUSIVE-BY-MISSING-RECORD`), (2) duplicate records — more than one measurement for a parent is unconditional refusal (`INCONCLUSIVE-BY-DUPLICATE`), (3) extra records (`INCONCLUSIVE-BY-ORPHAN`), (4) malformed records (`INCONCLUSIVE-BY-MALFORMED`), (5) absent measurement (dropped; `EXCLUDED-BY-ABSENCE`), (6) non-finite measurement (dropped; `EXCLUDED-BY-NONFINITE`), (7) low confidence (dropped; `EXCLUDED-BY-CONFIDENCE`), (8) accepted-finite. **No discretionary retry.** This exact set-equality closure produces the canonical **post-unblinding adequacy receipt**, binding the parent-set digest, old BS-2f mask digest, complete terminal-state partition, final-mask digest, calibration applicability, the already-verified pre-unblinding calibration PASS, locked Stage-C PASS, protocol digest, and verifier result. (The adequacy receipt must not branch on a Stage-C or calibration FAIL that BS-L excludes.) **Adequacy decisions follow an ordered tree:** First, calibration applicability: any post-unblinding removal immediately emits `INCONCLUSIVE-BY-CALIBRATION` and **no Stage-C rerun is performed**. Second, Row P binds the already-verified pre-unblinding calibration PASS (`a_LB_b >= 0.85`), relying on the locked BS-5f and BS-L verification rather than re-evaluating the threshold. These consequences are fixed before any real χ is read, citing V15 lines 570–573 which void any post-first-real-χ change to a decision threshold. | P8, after unblinding | the unblinding receipt and a verified BS-L | the **post-unblinding adequacy receipt**, then BS-7f, then BS-V | any execution before unblinding; any verdict produced outside this symbol; **silent inner-join loss; discretionary retry** |"
content = re.sub(old_p, new_p, content)

# Replace Clause 3c
old_3c = r"\(c\) \*Sequence, producers and verification\.\* The sequence BS-5f → BS-L → unblinding → BS-7f → BS-V is recorded through named producers\. The pinned verifier `verify_lock\(\)` checks schema completeness, every digest binding, BS-5f's PASS, the manifest of freeze completeness \(verifying those bound bytes rather than re-resolving filenames\), the lock checkpoint's extension of BS-2f, and the archive seal-state transition \(Clause 7\)\. \*\*Failure refuses unblinding and refuses the verdict path\.\*\*"
new_3c = "(c) *Sequence, producers and verification.* The sequence BS-5f → BS-L → unblinding → BS-7f → BS-V is recorded through named producers. The pinned verifier `verify_lock()` checks schema completeness, every digest binding, BS-5f's complementary calibration PASS and Stage-C PASS, the manifest of freeze completeness (verifying those bound bytes rather than re-resolving filenames), the lock checkpoint's extension of BS-2f, and the archive seal-state transition (Clause 7). **Failure refuses unblinding and refuses the verdict path.**"
content = re.sub(old_3c, new_3c, content)


# Replace Part 3 C2
old_c2 = r"- \*\*C2 — Carrying fixed thresholds and failing closed from the frozen record\.\*\* Rather than composing numeric thresholds for post-unblinding adequacy gates, we recorded the exact values inherited from the frozen record\. The calibration failure threshold \(any `a_LB_b < 0\.85`\) is carried from `\.\./PREREG_SUCCESSOR_DRAFT_V15_20260827\.md` lines 566–567 and `\.\./ref/successor_ref_v9\.py` line 81\. For non-committee attrition, calibration applicability fails closed because the needed applicability predicate is missing from the frozen record, which means any attrition emits `INCONCLUSIVE-BY-CALIBRATION`\. The Stage-C PASS/FAIL partition — including both the power failure threshold \(< 962 passing trials out of 1,000, `\.\./ref/successor_ref_v9\.py` lines 77–78\) and the self-verification `refuted` or `nonconservative` fail-closed return \(lines 1275–1276\) — is evaluated pre-unblinding in Row J / BS-5f\. Alternative: Maintain an `INCONCLUSIVE-BY-POWER` branch in Row P's post-unblinding adequacy tree for cases where the power criterion is inapplicable \(e\.g\. if the trial count changes\)\. We chose to delete the Stage-C power branch from Row P entirely and keep the decision strictly pre-unblinding in Row J, because Row P requires a verified BS-L, which requires BS-5f's PASS\. Row J forbids continuing after a Stage-C FAIL, so a Row-P invocation can only ever inherit a locked Stage-C PASS\. Therefore, any post-unblinding branch on a Stage-C FAIL is unreachable dead code\. For calibration applicability, we cite the frozen record and assign `INCONCLUSIVE-BY-CALIBRATION` where the frozen criteria cannot be applied, because inventing numbers renames a finding\."
new_c2 = "- **C2 — Carrying fixed thresholds and failing closed from the frozen record.** Rather than composing numeric thresholds for post-unblinding adequacy gates, we recorded the exact values inherited from the frozen record. The calibration failure threshold (any `a_LB_b < 0.85`) is carried from `../PREREG_SUCCESSOR_DRAFT_V15_20260827.md` lines 566–567 and `../ref/successor_ref_v9.py` line 81, and evaluated pre-unblinding in Row J before Stage C. For non-committee attrition, calibration applicability fails closed because the needed applicability predicate is missing from the frozen record, which means any attrition emits `INCONCLUSIVE-BY-CALIBRATION`. The Stage-C PASS/FAIL partition — including both the power failure threshold (< 962 passing trials out of 1,000, `../ref/successor_ref_v9.py` lines 77–78) and the self-verification `refuted` or `nonconservative` fail-closed return and count-return partition (lines 1275–1277) — is evaluated pre-unblinding in Row J / BS-5f. Alternative: Maintain an `INCONCLUSIVE-BY-POWER` branch in Row P's post-unblinding adequacy tree for cases where the power criterion is inapplicable (e.g. if the trial count changes). We chose to delete the Stage-C power branch and the calibration accuracy branch from Row P entirely and keep the decisions strictly pre-unblinding in Row J, because Row P requires a verified BS-L, which requires BS-5f's PASS. Row J forbids continuing after a FAIL, so a Row-P invocation can only ever inherit a locked PASS. Therefore, any post-unblinding branch on a Stage-C or calibration accuracy FAIL is unreachable dead code. For calibration applicability, we cite the frozen record and assign `INCONCLUSIVE-BY-CALIBRATION` where the frozen criteria cannot be applied, because inventing numbers renames a finding."
content = re.sub(old_c2, new_c2, content)


# Replace Part 5 Item 16
old_16 = r"16\. \*\*R10B Defect 1 — The inapplicability branch downgrades a void to inconclusive\.\*\* REPAIR\. The ordinary Stage-C PASS/FAIL decision executes at Row J; a verified PASS is required for BS-L and is therefore inherited by Row P; protocol or frozen-implementation deviation terminates `VOID` at Row J before an acceptable BS-5f exists\. \(The frozen code at lines 1275-1276 admits no lawful state where the count differs without a breach\.\)"
new_16 = "16. **R10B Defect 1 — The inapplicability branch downgrades a void to inconclusive.** REPAIR. The ordinary Stage-C PASS/FAIL decision executes at Row J; a verified PASS is required for BS-L and is therefore inherited by Row P; protocol or frozen-implementation deviation terminates `VOID` at Row J before an acceptable BS-5f exists. Row J enforces the no-deviation rule as a new pre-run verification. (The frozen code at lines 1275–1277 only implements the self-verification `refuted` or `nonconservative` fail-closed return and the count-return partition returning `None` when `n_trials != N_TRIALS`.)"
content = re.sub(old_16, new_16, content)

# Check for R11 Defect 1 and Part 5 Item 17 as it references lines 1275-1276
old_17 = r"17\. \*\*R11 Defect 1 — The Stage-C power branch in Row P is unreachable\.\*\* REPAIR\. Deleted the Stage-C power branch from Row P's post-unblinding adequacy tree and Part 2 item 4\. Kept the complete Stage-C PASS/FAIL partition — explicitly including fewer than 962 of 1,000 passing trials and the self-verification `refuted` or `nonconservative` fail-closed return \(lines 1275–1276\) — where it executes: pre-unblinding in Row J / BS-5f\. The post-unblinding adequacy receipt now binds the already-verified locked PASS and protocol digest without branching on a FAIL that BS-L excludes\."
new_17 = "17. **R11 Defect 1 — The Stage-C power branch in Row P is unreachable.** REPAIR. Deleted the Stage-C power branch from Row P's post-unblinding adequacy tree and Part 2 item 4. Kept the complete Stage-C PASS/FAIL partition — explicitly including fewer than 962 of 1,000 passing trials and the self-verification `refuted` or `nonconservative` fail-closed return and count-return partition (lines 1275–1277) — where it executes: pre-unblinding in Row J / BS-5f. The post-unblinding adequacy receipt now binds the already-verified locked PASS and protocol digest without branching on a FAIL that BS-L excludes."
content = re.sub(old_17, new_17, content)

with open("SECTION6_DRAFT_AGY_R13.md", "w") as f:
    f.write(content)
