# Recognized physical observable keywords for the research ideas quality gate (§5.2).
# Extend this set when adding new page types (e.g. exoplanet-atmospheres).
OBSERVABLE_KEYWORDS: set[str] = {
    "stellar mass",
    "sfr",
    "ssfr",
    "specific star formation rate",
    "star formation rate",
    "sérsic index",
    "sersic index",
    "velocity dispersion",
    "[oii] flux",
    "hα flux",
    "ha flux",
    "fir luminosity",
    "hi mass",
    "x-ray luminosity",
    "agn luminosity",
    "quenching fraction",
    "metallicity",
    "dust obscuration",
    "dust attenuation",
    "gas fraction",
    "color gradient",
    "effective radius",
    "half-light radius",
    "co luminosity",
    "[cii] flux",
    "lyman-alpha",
    "lya flux",
    "rest-frame uv",
    "uv slope",
    "balmer break",
    "mass function",
    "luminosity function",
    "merger rate",
    "pair fraction",
    "morphology",
    "bulge fraction",
    "disk fraction",
    "kinematic",
    "rotation curve",
    "velocity field",
}
