#!/usr/bin/env python3
"""Re-point the Gemini burn_plan entry in model_usage_status.json at real numbers.

model_usage_status.json is regenerated by external ccusage tooling, so this patch
is idempotent and safe to re-run after every regeneration:

  python3 tools/gemini_burn_plan_patch.py --check   # exit 1 if it needs patching
  python3 tools/gemini_burn_plan_patch.py

The authoritative, always-fresh copy of this advice is written by
live_provider_usage_monitor.py into provider_usage_monitor.gemini_app_burn_advice.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from gemini_app_usage import (  # noqa: E402
    PROVIDER,
    ReadingError,
    burn_advice,
    load_reading,
)

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_STATUS = ROOT / 'frontend/public/agent-reports/model_usage_status.json'


def status_path() -> Path:
    override = os.environ.get('NM_MODEL_USAGE_STATUS_JSON')
    return Path(override) if override else DEFAULT_STATUS


def gemini_entry(advice: dict) -> dict:
    known = advice['lane'] != 'unknown'
    headroom = advice['headroom_pct']
    return {
        'provider': 'Gemini',
        'priority': 'broad/cheap long-context lane',
        'good_burn_tasks': list(advice['good_burn_tasks']),
        'reserve_rule': (
            f'{advice["reserve_rule"]} The Antigravity agent-request pool and the consumer app '
            'compute meter are billed separately: spending one does not draw down the other, so '
            'check both gauges before routing.'
        ),
        'when_to_burn': (
            (
                f'App lane is "{advice["lane"]}" at {headroom:.0f}% headroom. {advice["rationale"]}'
                if known
                else f'App-lane headroom is unknown. {advice["rationale"]}'
            )
            + ' Live value: provider_usage_monitor.gemini_app_burn_advice; gauge: '
            + f'"{PROVIDER}".'
        ),
        'app_lane': {
            'source': 'https://gemini.google.com/usage (no API; operator-confirmed capture)',
            'lane': advice['lane'],
            'headroom_pct': headroom,
            'minutes_to_reset': advice.get('minutes_to_reset'),
        },
    }


def patch(document: dict, advice: dict) -> dict:
    plan = list(document.get('burn_plan') or [])
    entry = gemini_entry(advice)
    for i, item in enumerate(plan):
        if str(item.get('provider', '')).strip().lower().startswith('gemini'):
            plan[i] = entry
            break
    else:
        plan.append(entry)
    document['burn_plan'] = plan

    notes = [n for n in (document.get('notes') or []) if 'assume 250 requests/day' not in n]
    note = (
        'Gemini has four separate quota pools (Antigravity agent requests, Gemini CLI OAuth, the '
        'consumer app compute meter at gemini.google.com/usage, and the generativelanguage API key). '
        'They do not share a budget. The app meter has no API and is only as fresh as the last '
        'operator capture.'
    )
    if note not in notes:
        notes.append(note)
    document['notes'] = notes
    return document


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--check', action='store_true', help='exit 1 if the file would change; write nothing')
    ap.add_argument('--path', type=Path, default=None)
    args = ap.parse_args()

    target = args.path or status_path()
    if not target.exists():
        print(f'{target} not found; nothing to patch.', file=sys.stderr)
        return 1

    try:
        reading = load_reading()
    except ReadingError as exc:
        print(f'ignoring untrustworthy capture: {exc}', file=sys.stderr)
        reading = None

    before = target.read_text()
    document = json.loads(before)
    after = json.dumps(
        patch(document, burn_advice(reading, datetime.now(timezone.utc))),
        ensure_ascii=False,
        indent=2,
        sort_keys=True,
    ) + '\n'

    if json.loads(before) == json.loads(after):
        print(f'{target} already current.')
        return 0
    if args.check:
        print(f'{target} needs patching (re-run without --check).')
        return 1

    tmp = target.with_name(target.name + '.tmp')
    tmp.write_text(after)
    os.replace(tmp, target)
    print(f'Patched Gemini burn_plan in {target}.')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
